/* 
 * OptinHTMLFormInputsPanel.java
 *
 * Created on December 30, 2003, 2:28 PM
 */
package com.trinity.ea.design.optin.inputs;

import com.trinity.ea.design.optin.EADesignerOptinPanel;
import com.trinity.ea.design.optin.provider.OptinWizard;
import com.trinity.ea.design.common.panel.EAPanel;
import com.trinity.ea.design.common.file.ProjectManager;
import com.trinity.ea.design.rules.builder.DesignerRuleBuilder;
import java.awt.Color;
import java.awt.Font;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Insets;
import java.awt.BorderLayout;
import javax.swing.JPanel;
import javax.swing.JLabel;
import javax.swing.JButton;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.border.TitledBorder;
import javax.swing.border.EtchedBorder;
import javax.swing.JTable;

/**
 *
 * @author  aaronsc Trinity Software
 * Copyright ©2003-2004 Trinity Software. All rights reserved.
 */
public class OptinHTMLFormInputsPanel extends EAPanel {

    private Color backgroundColor = new java.awt.Color(140, 160, 210);
    private Color borderColor1 = new java.awt.Color(198, 226, 253);
    private Color borderColor2 = new java.awt.Color(96, 110, 145);
    private Color rowColor = new java.awt.Color(220, 225, 240);
    private Color rowBorderColor = new java.awt.Color(255, 255, 255);
    private Color mouseOverWebLinkColor = new Color(39, 63, 109);
    private Color webLinkTextColor = new Color(255, 255, 255);
    private int rowHeight = 25;  
    
    /** Creates new form OptinHTMLFormInputsPanel */
    public OptinHTMLFormInputsPanel() {
        initComponents();
 	setProjectData();       
    }

   public synchronized void getDataUpdate()
   {
	try
	{
		// Optin Support Functionality Checkbox Enabled/Disabled
		// Privacy Policy Checkbox Enabled/Disabled
            if(cbEnablePrivacyPolicy.isSelected()==true)
            {
		    ProjectManager.putTempNoFileWrite("optinPrivacyPolicyEnabled", "true");
            }
            else
            {
		    ProjectManager.putTempNoFileWrite("optinPrivacyPolicyEnabled", "false");
            }
		
		ProjectManager.putTempNoFileWrite("optinFormActionURL", tfEMailOptinFormActionURL.getText());

            if(optinRadioPostRequestMethod.isSelected()==true)
            {
			ProjectManager.putTempNoFileWrite("optinFormRequestMethod", "POST");
		}
		else
		{
			ProjectManager.putTempNoFileWrite("optinFormRequestMethod", "GET");
		}
		ProjectManager.saveTempNow();
		//TheContentPanelReference.getDataUpdate();
	}
	catch(Exception e)
	{
		e.printStackTrace();
	}
  }   

    public synchronized void setProjectData()
    {
        try
        {
		// Optin Support Functionality Checkbox Enabled/Disabled   
		// Privacy Policy Checkbox Enabled/Disabled
            if(ProjectManager.get("optinPrivacyPolicyEnabled").equalsIgnoreCase("true")==true)
            {
		    cbEnablePrivacyPolicy.setSelected(true);
            }
            else
            {
		    cbEnablePrivacyPolicy.setSelected(false);
            }
            if(ProjectManager.get("optinFormRequestMethod").equalsIgnoreCase("POST")==true)
            {
			optinRadioPostRequestMethod.setSelected(true);
			optinRadioGetRequestMethod.setSelected(false);
		}
		else
		{
			optinRadioGetRequestMethod.setSelected(true);
			optinRadioPostRequestMethod.setSelected(false);
		}
		tfEMailOptinFormActionURL.setOpaque(true);
		tfEMailOptinFormActionURL.setText(ProjectManager.get("optinFormActionURL"));
		tfEMailOptinFormActionURL.setCaretPosition(0);
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }

    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        OptinCentralContentPanel = new javax.swing.JPanel();
        OptinContentPanel = new javax.swing.JPanel();
        OptinSettingsPanelItem10 = new javax.swing.JPanel();
        OptinContentPanelItem2 = new javax.swing.JPanel();
        OptinSettingsPanelItem3 = new javax.swing.JPanel();
        OptinTitlePanel2 = new javax.swing.JPanel();
        lFiller3 = new javax.swing.JLabel();
        lEMailOptinFormActionURL = new javax.swing.JLabel();
        lFiller2 = new javax.swing.JLabel();
        tfEMailOptinFormActionURL = new javax.swing.JTextField();
        OptinTitleRightPanel2 = new javax.swing.JPanel();
        OptinSettingsPanelItem4 = new javax.swing.JPanel();
        OptinTitlePanel3 = new javax.swing.JPanel();
        optinRequestMethodLabel = new javax.swing.JLabel();
        optinRadioGetRequestMethod = new javax.swing.JRadioButton();
        optinRadioPostRequestMethod = new javax.swing.JRadioButton();
        OptinPrivacyPolicyPanel = new javax.swing.JPanel();
        OptinSettingsPanelItem5 = new javax.swing.JPanel();
        OptinTitlePanel4 = new javax.swing.JPanel();
        cbEnablePrivacyPolicy = new javax.swing.JCheckBox();
        OptinPrivacyPolicyPanel1 = new javax.swing.JPanel();
        OptinContentPanelItem1 = new javax.swing.JPanel();
        EMailOptinSettingsPanelItem1 = new javax.swing.JPanel();
        FindProviderPanel = new javax.swing.JPanel();
        FindProviderWebLink = new javax.swing.JLabel();
        LearnMorePanel = new javax.swing.JPanel();
        LearnMoreLabel = new javax.swing.JLabel();
        OptinSettingsPanelItem7 = new javax.swing.JPanel();
        OptinSettingsPanelItem9 = new javax.swing.JPanel();
        OptinContentPanelItem5 = new javax.swing.JPanel();
        taStatus = new javax.swing.JTextArea();
        OptinCentralContentLeftMarginPanel = new javax.swing.JPanel();
        OptinCentralContentRightMarginPanel = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        setBackground(backgroundColor);
        OptinCentralContentPanel.setLayout(new java.awt.BorderLayout());

        OptinCentralContentPanel.setBackground(backgroundColor);
        OptinCentralContentPanel.setMaximumSize(new java.awt.Dimension(2147483647, 120));
        OptinContentPanel.setLayout(new javax.swing.BoxLayout(OptinContentPanel, javax.swing.BoxLayout.Y_AXIS));

        OptinContentPanel.setBackground(backgroundColor);
        OptinContentPanel.setMaximumSize(new java.awt.Dimension(2147483647, 120));
        OptinContentPanel.setMinimumSize(new java.awt.Dimension(448, 0));
        OptinContentPanel.setPreferredSize(new java.awt.Dimension(600, 120));
        OptinSettingsPanelItem10.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        OptinSettingsPanelItem10.setBackground(backgroundColor);
        OptinSettingsPanelItem10.setMaximumSize(new java.awt.Dimension(32767, 10));
        OptinContentPanel.add(OptinSettingsPanelItem10);

        OptinContentPanelItem2.setLayout(new javax.swing.BoxLayout(OptinContentPanelItem2, javax.swing.BoxLayout.Y_AXIS));

        OptinContentPanelItem2.setBackground(backgroundColor);
        OptinContentPanelItem2.setMaximumSize(new java.awt.Dimension(1400, 100));
        OptinContentPanelItem2.setMinimumSize(new java.awt.Dimension(60, 100));
        OptinContentPanelItem2.setPreferredSize(new java.awt.Dimension(600, 100));
        OptinSettingsPanelItem3.setLayout(new java.awt.BorderLayout(5, 0));

        OptinSettingsPanelItem3.setBackground(backgroundColor);
        OptinSettingsPanelItem3.setMaximumSize(new java.awt.Dimension(32767, 33));
        OptinTitlePanel2.setLayout(new javax.swing.BoxLayout(OptinTitlePanel2, javax.swing.BoxLayout.X_AXIS));

        OptinTitlePanel2.setBackground(backgroundColor);
        OptinTitlePanel2.setMaximumSize(new java.awt.Dimension(100, 2147483647));
        OptinTitlePanel2.setMinimumSize(new java.awt.Dimension(131, 20));
        OptinTitlePanel2.setPreferredSize(new java.awt.Dimension(220, 20));
        lFiller3.setBackground(backgroundColor);
        lFiller3.setMaximumSize(new java.awt.Dimension(300, 15));
        lFiller3.setMinimumSize(new java.awt.Dimension(5, 15));
        lFiller3.setPreferredSize(new java.awt.Dimension(5, 15));
        OptinTitlePanel2.add(lFiller3);

        lEMailOptinFormActionURL.setBackground(backgroundColor);
        lEMailOptinFormActionURL.setFont(new java.awt.Font("Arial", 0, 12));
        lEMailOptinFormActionURL.setText("HTML Form Action URL:");
        lEMailOptinFormActionURL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lEMailOptinFormActionURLMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lEMailOptinFormActionURLMouseExited(evt);
            }
        });

        OptinTitlePanel2.add(lEMailOptinFormActionURL);

        lFiller2.setText("   ");
        lFiller2.setMaximumSize(new java.awt.Dimension(300, 15));
        OptinTitlePanel2.add(lFiller2);

        tfEMailOptinFormActionURL.setText("http://...");
        tfEMailOptinFormActionURL.setMinimumSize(new java.awt.Dimension(6, 20));
        tfEMailOptinFormActionURL.setPreferredSize(new java.awt.Dimension(300, 20));
        tfEMailOptinFormActionURL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tfEMailOptinFormActionURLMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tfEMailOptinFormActionURLMouseExited(evt);
            }
        });

        OptinTitlePanel2.add(tfEMailOptinFormActionURL);

        OptinSettingsPanelItem3.add(OptinTitlePanel2, java.awt.BorderLayout.NORTH);

        OptinTitleRightPanel2.setLayout(new javax.swing.BoxLayout(OptinTitleRightPanel2, javax.swing.BoxLayout.Y_AXIS));

        OptinTitleRightPanel2.setBackground(backgroundColor);
        OptinSettingsPanelItem3.add(OptinTitleRightPanel2, java.awt.BorderLayout.EAST);

        OptinContentPanelItem2.add(OptinSettingsPanelItem3);

        OptinSettingsPanelItem4.setLayout(new java.awt.BorderLayout());

        OptinSettingsPanelItem4.setBackground(backgroundColor);
        OptinSettingsPanelItem4.setMaximumSize(new java.awt.Dimension(32767, 33));
        OptinTitlePanel3.setBackground(backgroundColor);
        OptinTitlePanel3.setMaximumSize(new java.awt.Dimension(100, 2147483647));
        optinRequestMethodLabel.setBackground(backgroundColor);
        optinRequestMethodLabel.setFont(new java.awt.Font("Arial", 0, 12));
        optinRequestMethodLabel.setText("HTTP Request Method:");
        optinRequestMethodLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                optinRequestMethodLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                optinRequestMethodLabelMouseExited(evt);
            }
        });

        OptinTitlePanel3.add(optinRequestMethodLabel);

        optinRadioGetRequestMethod.setBackground(backgroundColor);
        optinRadioGetRequestMethod.setFont(new java.awt.Font("Arial", 1, 12));
        optinRadioGetRequestMethod.setText("GET");
        optinRadioGetRequestMethod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optinRadioGetRequestMethodActionPerformed(evt);
            }
        });
        optinRadioGetRequestMethod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                optinRadioGetRequestMethodMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                optinRadioGetRequestMethodMouseExited(evt);
            }
        });

        OptinTitlePanel3.add(optinRadioGetRequestMethod);

        optinRadioPostRequestMethod.setBackground(backgroundColor);
        optinRadioPostRequestMethod.setFont(new java.awt.Font("Arial", 1, 12));
        optinRadioPostRequestMethod.setSelected(true);
        optinRadioPostRequestMethod.setText("POST");
        optinRadioPostRequestMethod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optinRadioPostRequestMethodActionPerformed(evt);
            }
        });
        optinRadioPostRequestMethod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                optinRadioPostRequestMethodMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                optinRadioPostRequestMethodMouseExited(evt);
            }
        });

        OptinTitlePanel3.add(optinRadioPostRequestMethod);

        OptinSettingsPanelItem4.add(OptinTitlePanel3, java.awt.BorderLayout.WEST);

        OptinPrivacyPolicyPanel.setBackground(backgroundColor);
        OptinPrivacyPolicyPanel.setMaximumSize(new java.awt.Dimension(100, 2147483647));
        OptinSettingsPanelItem4.add(OptinPrivacyPolicyPanel, java.awt.BorderLayout.CENTER);

        OptinContentPanelItem2.add(OptinSettingsPanelItem4);

        OptinSettingsPanelItem5.setLayout(new java.awt.BorderLayout());

        OptinSettingsPanelItem5.setBackground(backgroundColor);
        OptinSettingsPanelItem5.setMaximumSize(new java.awt.Dimension(32767, 33));
        OptinTitlePanel4.setBackground(backgroundColor);
        OptinTitlePanel4.setMaximumSize(new java.awt.Dimension(100, 2147483647));
        cbEnablePrivacyPolicy.setBackground(backgroundColor);
        cbEnablePrivacyPolicy.setFont(new java.awt.Font("Arial", 0, 12));
        cbEnablePrivacyPolicy.setSelected(true);
        cbEnablePrivacyPolicy.setText("Enable Privacy Policy Support ");
        cbEnablePrivacyPolicy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEnablePrivacyPolicyActionPerformed(evt);
            }
        });
        cbEnablePrivacyPolicy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cbEnablePrivacyPolicyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cbEnablePrivacyPolicyMouseExited(evt);
            }
        });

        OptinTitlePanel4.add(cbEnablePrivacyPolicy);

        OptinSettingsPanelItem5.add(OptinTitlePanel4, java.awt.BorderLayout.WEST);

        OptinPrivacyPolicyPanel1.setBackground(backgroundColor);
        OptinPrivacyPolicyPanel1.setMaximumSize(new java.awt.Dimension(100, 2147483647));
        OptinSettingsPanelItem5.add(OptinPrivacyPolicyPanel1, java.awt.BorderLayout.CENTER);

        OptinContentPanelItem2.add(OptinSettingsPanelItem5);

        OptinContentPanel.add(OptinContentPanelItem2);

        OptinContentPanelItem1.setLayout(new java.awt.BorderLayout());

        OptinContentPanelItem1.setBackground(backgroundColor);
        OptinContentPanelItem1.setMaximumSize(new java.awt.Dimension(2147483647, 60));
        OptinContentPanelItem1.setMinimumSize(new java.awt.Dimension(425, 40));
        OptinContentPanelItem1.setPreferredSize(new java.awt.Dimension(500, 60));
        EMailOptinSettingsPanelItem1.setLayout(new java.awt.BorderLayout());

        EMailOptinSettingsPanelItem1.setBackground(backgroundColor);
        EMailOptinSettingsPanelItem1.setMinimumSize(new java.awt.Dimension(425, 40));
        EMailOptinSettingsPanelItem1.setPreferredSize(new java.awt.Dimension(425, 60));
        FindProviderPanel.setLayout(new java.awt.BorderLayout());

        FindProviderPanel.setBackground(backgroundColor);
        FindProviderPanel.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        FindProviderPanel.setMinimumSize(new java.awt.Dimension(175, 20));
        FindProviderPanel.setPreferredSize(new java.awt.Dimension(250, 20));
        FindProviderWebLink.setBackground(backgroundColor);
        FindProviderWebLink.setFont(new java.awt.Font("Arial", 1, 12));
        FindProviderWebLink.setForeground(new java.awt.Color(255, 255, 255));
        FindProviderWebLink.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        FindProviderWebLink.setText("Find a Provider");
        FindProviderWebLink.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        FindProviderWebLink.setMaximumSize(new java.awt.Dimension(175, 20));
        FindProviderWebLink.setMinimumSize(new java.awt.Dimension(175, 20));
        FindProviderWebLink.setPreferredSize(new java.awt.Dimension(175, 20));
        FindProviderWebLink.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        FindProviderWebLink.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        FindProviderWebLink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FindProviderWebLinkMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                FindProviderWebLinkMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                FindProviderWebLinkMouseExited(evt);
            }
        });

        FindProviderPanel.add(FindProviderWebLink, java.awt.BorderLayout.WEST);

        EMailOptinSettingsPanelItem1.add(FindProviderPanel, java.awt.BorderLayout.WEST);

        LearnMorePanel.setLayout(new java.awt.BorderLayout(5, 0));

        LearnMorePanel.setBackground(backgroundColor);
        LearnMorePanel.setMinimumSize(new java.awt.Dimension(250, 20));
        LearnMorePanel.setPreferredSize(new java.awt.Dimension(250, 20));
        LearnMoreLabel.setBackground(backgroundColor);
        LearnMoreLabel.setFont(new java.awt.Font("Arial", 1, 12));
        LearnMoreLabel.setForeground(new java.awt.Color(255, 255, 255));
        LearnMoreLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LearnMoreLabel.setText("Learn more about E-mail Opt-Ins");
        LearnMoreLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        LearnMoreLabel.setMaximumSize(new java.awt.Dimension(250, 20));
        LearnMoreLabel.setMinimumSize(new java.awt.Dimension(250, 20));
        LearnMoreLabel.setPreferredSize(new java.awt.Dimension(250, 20));
        LearnMoreLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        LearnMoreLabel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        LearnMoreLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LearnMoreLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LearnMoreLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LearnMoreLabelMouseExited(evt);
            }
        });

        LearnMorePanel.add(LearnMoreLabel, java.awt.BorderLayout.WEST);

        EMailOptinSettingsPanelItem1.add(LearnMorePanel, java.awt.BorderLayout.NORTH);

        OptinContentPanelItem1.add(EMailOptinSettingsPanelItem1, java.awt.BorderLayout.WEST);

        OptinSettingsPanelItem7.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        OptinSettingsPanelItem7.setBackground(backgroundColor);
        OptinContentPanelItem1.add(OptinSettingsPanelItem7, java.awt.BorderLayout.NORTH);

        OptinContentPanel.add(OptinContentPanelItem1);

        OptinSettingsPanelItem9.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        OptinSettingsPanelItem9.setBackground(backgroundColor);
        OptinSettingsPanelItem9.setMaximumSize(new java.awt.Dimension(32767, 10));
        OptinContentPanel.add(OptinSettingsPanelItem9);

        OptinContentPanelItem5.setLayout(new java.awt.BorderLayout());

        OptinContentPanelItem5.setBackground(backgroundColor);
        OptinContentPanelItem5.setMaximumSize(new java.awt.Dimension(2147483647, 30));
        OptinContentPanelItem5.setMinimumSize(new java.awt.Dimension(400, 30));
        OptinContentPanelItem5.setPreferredSize(new java.awt.Dimension(400, 30));
        taStatus.setBackground(backgroundColor);
        taStatus.setFont(new java.awt.Font("Arial", 0, 12));
        taStatus.setLineWrap(true);
        taStatus.setWrapStyleWord(true);
        OptinContentPanelItem5.add(taStatus, java.awt.BorderLayout.SOUTH);

        OptinContentPanel.add(OptinContentPanelItem5);

        OptinCentralContentPanel.add(OptinContentPanel, java.awt.BorderLayout.CENTER);

        OptinCentralContentLeftMarginPanel.setBackground(backgroundColor);
        OptinCentralContentPanel.add(OptinCentralContentLeftMarginPanel, java.awt.BorderLayout.WEST);

        OptinCentralContentRightMarginPanel.setBackground(backgroundColor);
        OptinCentralContentPanel.add(OptinCentralContentRightMarginPanel, java.awt.BorderLayout.EAST);

        add(OptinCentralContentPanel, java.awt.BorderLayout.CENTER);

    }//GEN-END:initComponents

    private void optinRadioGetRequestMethodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optinRadioGetRequestMethodActionPerformed
        optinRadioPostRequestMethod.setSelected(false);
        optinRadioGetRequestMethod.setSelected(true);
    }//GEN-LAST:event_optinRadioGetRequestMethodActionPerformed

    private void optinRadioPostRequestMethodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optinRadioPostRequestMethodActionPerformed
        optinRadioGetRequestMethod.setSelected(false);
        optinRadioPostRequestMethod.setSelected(true);
    }//GEN-LAST:event_optinRadioPostRequestMethodActionPerformed

    private void LearnMoreLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LearnMoreLabelMouseExited
	LearnMoreLabel.setForeground(webLinkTextColor);
    }//GEN-LAST:event_LearnMoreLabelMouseExited

    private void LearnMoreLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LearnMoreLabelMouseEntered
	LearnMoreLabel.setForeground(mouseOverWebLinkColor);
    }//GEN-LAST:event_LearnMoreLabelMouseEntered

    private void LearnMoreLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LearnMoreLabelMouseClicked
	try
	{   
                 if(DesignerRuleBuilder.get("optinLearnMoreAction")!=null)
                    {
                        try
                        {
                            Class.forName(DesignerRuleBuilder.get("optinLearnMoreAction")).newInstance();
                        }
                        catch(InstantiationException e)
                        {
                            //System.out.println(e);
                        }   
                        catch(IllegalAccessException e)
                        {
                            //System.out.println(e);
                        }                      
                        catch(ClassNotFoundException e)
                        {
                            //System.out.println(e);
                        }       
                    }
	}
	catch(Exception e)
	{
		e.printStackTrace();
	}
    }//GEN-LAST:event_LearnMoreLabelMouseClicked

    private void FindProviderWebLinkMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FindProviderWebLinkMouseExited
        FindProviderWebLink.setForeground(webLinkTextColor);
    }//GEN-LAST:event_FindProviderWebLinkMouseExited

    private void FindProviderWebLinkMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FindProviderWebLinkMouseEntered
        FindProviderWebLink.setForeground(mouseOverWebLinkColor);
    }//GEN-LAST:event_FindProviderWebLinkMouseEntered

    private void FindProviderWebLinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FindProviderWebLinkMouseClicked
	try
	{   
		OptinWizard findWiz = new OptinWizard(1);
		findWiz.setMasterControlPanel(parentObj);
		findWiz.hideDesigner();
	}
	catch(Exception e)
	{
		e.printStackTrace();
	}

    }//GEN-LAST:event_FindProviderWebLinkMouseClicked

    private void cbEnablePrivacyPolicyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbEnablePrivacyPolicyMouseExited
        // Add your handling code here:
    }//GEN-LAST:event_cbEnablePrivacyPolicyMouseExited

    private void cbEnablePrivacyPolicyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbEnablePrivacyPolicyMouseEntered
        // Add your handling code here:
    }//GEN-LAST:event_cbEnablePrivacyPolicyMouseEntered

    private void cbEnablePrivacyPolicyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEnablePrivacyPolicyActionPerformed
        // Add your handling code here:
    }//GEN-LAST:event_cbEnablePrivacyPolicyActionPerformed

    private void optinRadioPostRequestMethodMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_optinRadioPostRequestMethodMouseExited
        // Add your handling code here:
    }//GEN-LAST:event_optinRadioPostRequestMethodMouseExited

    private void optinRadioPostRequestMethodMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_optinRadioPostRequestMethodMouseEntered
        // Add your handling code here:
    }//GEN-LAST:event_optinRadioPostRequestMethodMouseEntered

    private void optinRadioGetRequestMethodMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_optinRadioGetRequestMethodMouseExited
        // Add your handling code here:
    }//GEN-LAST:event_optinRadioGetRequestMethodMouseExited

    private void optinRadioGetRequestMethodMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_optinRadioGetRequestMethodMouseEntered
        // Add your handling code here:
    }//GEN-LAST:event_optinRadioGetRequestMethodMouseEntered

    private void optinRequestMethodLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_optinRequestMethodLabelMouseExited
        // Add your handling code here:
    }//GEN-LAST:event_optinRequestMethodLabelMouseExited

    private void optinRequestMethodLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_optinRequestMethodLabelMouseEntered
        // Add your handling code here:
    }//GEN-LAST:event_optinRequestMethodLabelMouseEntered

    private void lEMailOptinFormActionURLMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lEMailOptinFormActionURLMouseExited
        // Add your handling code here:
    }//GEN-LAST:event_lEMailOptinFormActionURLMouseExited

    private void lEMailOptinFormActionURLMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lEMailOptinFormActionURLMouseEntered
        // Add your handling code here:
    }//GEN-LAST:event_lEMailOptinFormActionURLMouseEntered

    private void tfEMailOptinFormActionURLMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfEMailOptinFormActionURLMouseExited
        // Add your handling code here:
    }//GEN-LAST:event_tfEMailOptinFormActionURLMouseExited

    private void tfEMailOptinFormActionURLMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfEMailOptinFormActionURLMouseEntered
        // Add your handling code here:
    }//GEN-LAST:event_tfEMailOptinFormActionURLMouseEntered
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel EMailOptinSettingsPanelItem1;
    private javax.swing.JPanel FindProviderPanel;
    private javax.swing.JLabel FindProviderWebLink;
    private javax.swing.JLabel LearnMoreLabel;
    private javax.swing.JPanel LearnMorePanel;
    private javax.swing.JPanel OptinCentralContentLeftMarginPanel;
    private javax.swing.JPanel OptinCentralContentPanel;
    private javax.swing.JPanel OptinCentralContentRightMarginPanel;
    private javax.swing.JPanel OptinContentPanel;
    private javax.swing.JPanel OptinContentPanelItem1;
    private javax.swing.JPanel OptinContentPanelItem2;
    private javax.swing.JPanel OptinContentPanelItem5;
    private javax.swing.JPanel OptinPrivacyPolicyPanel;
    private javax.swing.JPanel OptinPrivacyPolicyPanel1;
    private javax.swing.JPanel OptinSettingsPanelItem10;
    private javax.swing.JPanel OptinSettingsPanelItem3;
    private javax.swing.JPanel OptinSettingsPanelItem4;
    private javax.swing.JPanel OptinSettingsPanelItem5;
    private javax.swing.JPanel OptinSettingsPanelItem7;
    private javax.swing.JPanel OptinSettingsPanelItem9;
    private javax.swing.JPanel OptinTitlePanel2;
    private javax.swing.JPanel OptinTitlePanel3;
    private javax.swing.JPanel OptinTitlePanel4;
    private javax.swing.JPanel OptinTitleRightPanel2;
    private javax.swing.JCheckBox cbEnablePrivacyPolicy;
    private javax.swing.JLabel lEMailOptinFormActionURL;
    private javax.swing.JLabel lFiller2;
    private javax.swing.JLabel lFiller3;
    private javax.swing.JRadioButton optinRadioGetRequestMethod;
    private javax.swing.JRadioButton optinRadioPostRequestMethod;
    private javax.swing.JLabel optinRequestMethodLabel;
    private javax.swing.JTextArea taStatus;
    private javax.swing.JTextField tfEMailOptinFormActionURL;
    // End of variables declaration//GEN-END:variables

    EADesignerOptinPanel parentObj = null;
    public void setMasterStatusController(EADesignerOptinPanel parentObject)
    {
        parentObj = (EADesignerOptinPanel)parentObject;
    }
}
