/*
 * ProductInformationPanel.java
 *
 * Created on November 20, 2004, 12:05 PM
 */

package com.trinity.ea.design.common.project;

import com.trinity.ea.design.common.file.ProjectManager;
import com.trinity.ea.design.rules.builder.DesignerRuleBuilder;
import com.trinity.ea.design.common.panel.EAPanel;
import com.trinity.ea.design.common.project.NewProject;
import java.io.File;
import java.net.URL;
import java.net.MalformedURLException;
import java.util.ArrayList;
import javax.swing.*;
import java.awt.*;

/**
 *
 * @author  aaronsc Trinity Software, LLC
 * Copyright ©2004 Trinity Software, LLC. All rights reserved.
 */
public class ProductInformationPanel extends EAPanel {
    
    /** Creates new ProductInformationPanel */
    public ProductInformationPanel() 
    {
        initComponents();
        try
        {
            setProjectData();    
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }        
    }
    
    public synchronized void setProjectData()
    {
        try
        {
            CopyrightTextField.setText(ProjectManager.get("product_copyright"));
            // Start Set the Product Version Info...
            Object[] versionArray = getStringArraysFromString(ProjectManager.get("product_version"));
            VersionBox1TextField.setText((String)versionArray[0]);
            VersionBox2TextField.setText((String)versionArray[1]);
            VersionBox3TextField.setText((String)versionArray[2]);
            VersionBox4TextField.setText((String)versionArray[3]);
            // End Set the Product Version Info...          
            VendorNameTextField.setText(ProjectManager.get("product_vendor_name"));
            ProductNameTextField.setText(ProjectManager.get("product_name"));    
            ProductInformationTextField.setText(ProjectManager.get("product_info_url"));
            ProductURLTextField.setText(ProjectManager.get("product_url"));
                      
            CopyrightTextField.setCaretPosition(0);
            ProductNameTextField.setCaretPosition(0);
            VendorNameTextField.setCaretPosition(0);
            VersionBox1TextField.setCaretPosition(0);
            VersionBox2TextField.setCaretPosition(0);
            VersionBox3TextField.setCaretPosition(0);
            VersionBox4TextField.setCaretPosition(0);
            ProductInformationTextField.setCaretPosition(0);
            ProductURLTextField.setCaretPosition(0);
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }

    /* Updates the project data properties changes */
    public void getDataUpdate()
    {
        try
        {
            ProjectManager.put("product_vendor_name", VendorNameTextField.getText());
            ProjectManager.put("product_name", ProductNameTextField.getText());    
            ProjectManager.put("product_version", VersionBox1TextField.getText() + "," + VersionBox2TextField.getText() + "," + VersionBox3TextField.getText() + "," + VersionBox4TextField.getText());
            ProjectManager.put("product_copyright", CopyrightTextField.getText());  
            ProjectManager.put("product_info_url", ProductInformationTextField.getText());
            ProjectManager.put("product_url", ProductURLTextField.getText());
            ProjectManager.saveTempNow();         
            // project_last_built is set by the Build Panel, once a build is complete.
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }    
            
     /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        VendorNamePanel = new javax.swing.JPanel();
        VendorNameLabel = new javax.swing.JLabel();
        VendorNameTextField = new javax.swing.JTextField();
        Filler007 = new javax.swing.JLabel();
        ProductNamePanel = new javax.swing.JPanel();
        ProductNameLabel = new javax.swing.JLabel();
        ProductNameTextField = new javax.swing.JTextField();
        Filler006 = new javax.swing.JLabel();
        VersionCopyrightPanel = new javax.swing.JPanel();
        VersionLabel = new javax.swing.JLabel();
        VersionBox1TextField = new javax.swing.JTextField();
        Filler001 = new javax.swing.JLabel();
        VersionBox2TextField = new javax.swing.JTextField();
        Filler002 = new javax.swing.JLabel();
        VersionBox3TextField = new javax.swing.JTextField();
        Filler003 = new javax.swing.JLabel();
        VersionBox4TextField = new javax.swing.JTextField();
        Filler004 = new javax.swing.JLabel();
        CopyrightLabel = new javax.swing.JLabel();
        Filler005 = new javax.swing.JLabel();
        CopyrightTextField = new javax.swing.JTextField();
        Filler008 = new javax.swing.JLabel();
        ProductURLPanel = new javax.swing.JPanel();
        ProductURLLabel = new javax.swing.JLabel();
        ProductURLTextField = new javax.swing.JTextField();
        Filler009 = new javax.swing.JLabel();
        ProductInformationURLPanel = new javax.swing.JPanel();
        ProductInformationLabel = new javax.swing.JLabel();
        ProductInformationTextField = new javax.swing.JTextField();
        Filler010 = new javax.swing.JLabel();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        VendorNamePanel.setLayout(new javax.swing.BoxLayout(VendorNamePanel, javax.swing.BoxLayout.X_AXIS));

        VendorNamePanel.setMaximumSize(new java.awt.Dimension(370, 29));
        VendorNamePanel.setMinimumSize(new java.awt.Dimension(370, 29));
        VendorNamePanel.setPreferredSize(new java.awt.Dimension(370, 29));
        //VendorNamePanel.setRequestFocusEnabled(false);
        VendorNamePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                VendorNamePanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                VendorNamePanelMouseExited(evt);
            }
        });

        VendorNameLabel.setFont(new java.awt.Font("Dialog", 0, 12));
        VendorNameLabel.setText("Vendor Name:");
        VendorNameLabel.setMaximumSize(new java.awt.Dimension(103, 16));
        VendorNameLabel.setMinimumSize(new java.awt.Dimension(103, 16));
        VendorNameLabel.setPreferredSize(new java.awt.Dimension(103, 16));
        VendorNamePanel.add(VendorNameLabel);

        VendorNameTextField.setText("Vendor_Name");
        VendorNameTextField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        VendorNameTextField.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        VendorNameTextField.setMargin(new java.awt.Insets(0, 10, 0, 5));
        VendorNameTextField.setMaximumSize(new java.awt.Dimension(2147483647, 22));
        VendorNameTextField.setMinimumSize(new java.awt.Dimension(165, 22));
        VendorNameTextField.setPreferredSize(new java.awt.Dimension(235, 22));
        VendorNameTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                VendorNameTextFieldMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                VendorNameTextFieldMouseExited(evt);
            }
        });

        VendorNamePanel.add(VendorNameTextField);

        Filler007.setMaximumSize(new java.awt.Dimension(10, 10));
        Filler007.setMinimumSize(new java.awt.Dimension(10, 10));
        Filler007.setPreferredSize(new java.awt.Dimension(10, 10));
        VendorNamePanel.add(Filler007);

        add(VendorNamePanel);

        ProductNamePanel.setLayout(new javax.swing.BoxLayout(ProductNamePanel, javax.swing.BoxLayout.X_AXIS));

        ProductNamePanel.setMaximumSize(new java.awt.Dimension(370, 29));
        ProductNamePanel.setMinimumSize(new java.awt.Dimension(370, 29));
        ProductNamePanel.setPreferredSize(new java.awt.Dimension(370, 29));
        ProductNamePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ProductNamePanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ProductNamePanelMouseExited(evt);
            }
        });

        ProductNameLabel.setFont(new java.awt.Font("Dialog", 0, 12));
        ProductNameLabel.setText("Product Name:");
        ProductNameLabel.setMaximumSize(new java.awt.Dimension(103, 16));
        ProductNameLabel.setMinimumSize(new java.awt.Dimension(103, 16));
        ProductNameLabel.setPreferredSize(new java.awt.Dimension(103, 16));
        ProductNamePanel.add(ProductNameLabel);

        ProductNameTextField.setText("My_Product");
        ProductNameTextField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        ProductNameTextField.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        ProductNameTextField.setMargin(new java.awt.Insets(0, 10, 0, 5));
        ProductNameTextField.setMaximumSize(new java.awt.Dimension(2147483647, 22));
        ProductNameTextField.setMinimumSize(new java.awt.Dimension(165, 22));
        ProductNameTextField.setPreferredSize(new java.awt.Dimension(235, 22));
        ProductNameTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ProductNameTextFieldMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ProductNameTextFieldMouseExited(evt);
            }
        });

        ProductNamePanel.add(ProductNameTextField);

        Filler006.setMaximumSize(new java.awt.Dimension(10, 10));
        Filler006.setMinimumSize(new java.awt.Dimension(10, 10));
        Filler006.setPreferredSize(new java.awt.Dimension(10, 10));
        ProductNamePanel.add(Filler006);

        add(ProductNamePanel);

        VersionCopyrightPanel.setLayout(new javax.swing.BoxLayout(VersionCopyrightPanel, javax.swing.BoxLayout.X_AXIS));

        VersionCopyrightPanel.setMaximumSize(new java.awt.Dimension(370, 29));
        VersionCopyrightPanel.setMinimumSize(new java.awt.Dimension(370, 29));
        VersionCopyrightPanel.setPreferredSize(new java.awt.Dimension(370, 29));
        VersionCopyrightPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                VersionCopyrightPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                VersionCopyrightPanelMouseExited(evt);
            }
        });

        VersionLabel.setFont(new java.awt.Font("Dialog", 0, 12));
        VersionLabel.setText("Version:");
        VersionLabel.setMaximumSize(new java.awt.Dimension(103, 16));
        VersionLabel.setMinimumSize(new java.awt.Dimension(103, 16));
        VersionLabel.setPreferredSize(new java.awt.Dimension(103, 16));
        VersionCopyrightPanel.add(VersionLabel);

        VersionBox1TextField.setText("1");
        VersionBox1TextField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        VersionBox1TextField.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        VersionBox1TextField.setMargin(new java.awt.Insets(0, 10, 0, 5));
        VersionBox1TextField.setMaximumSize(new java.awt.Dimension(2147483647, 22));
        VersionBox1TextField.setMinimumSize(new java.awt.Dimension(20, 22));
        VersionBox1TextField.setPreferredSize(new java.awt.Dimension(20, 22));
        //VersionBox1TextField.setRequestFocusEnabled(false);
        VersionBox1TextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                VersionBox1TextFieldMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                VersionBox1TextFieldMouseExited(evt);
            }
        });

        VersionCopyrightPanel.add(VersionBox1TextField);

        Filler001.setMaximumSize(new java.awt.Dimension(10, 10));
        Filler001.setMinimumSize(new java.awt.Dimension(10, 10));
        Filler001.setPreferredSize(new java.awt.Dimension(10, 10));
        VersionCopyrightPanel.add(Filler001);

        VersionBox2TextField.setText("0");
        VersionBox2TextField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        VersionBox2TextField.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        VersionBox2TextField.setMargin(new java.awt.Insets(0, 10, 0, 5));
        VersionBox2TextField.setMaximumSize(new java.awt.Dimension(2147483647, 22));
        VersionBox2TextField.setMinimumSize(new java.awt.Dimension(20, 22));
        VersionBox2TextField.setPreferredSize(new java.awt.Dimension(20, 22));
        //VersionBox2TextField.setRequestFocusEnabled(false);
        VersionBox2TextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                VersionBox2TextFieldMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                VersionBox2TextFieldMouseExited(evt);
            }
        });

        VersionCopyrightPanel.add(VersionBox2TextField);

        Filler002.setMaximumSize(new java.awt.Dimension(10, 10));
        Filler002.setMinimumSize(new java.awt.Dimension(10, 10));
        Filler002.setPreferredSize(new java.awt.Dimension(10, 10));
        VersionCopyrightPanel.add(Filler002);

        VersionBox3TextField.setText("0");
        VersionBox3TextField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        VersionBox3TextField.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        VersionBox3TextField.setMargin(new java.awt.Insets(0, 10, 0, 5));
        VersionBox3TextField.setMaximumSize(new java.awt.Dimension(2147483647, 22));
        VersionBox3TextField.setMinimumSize(new java.awt.Dimension(20, 22));
        VersionBox3TextField.setPreferredSize(new java.awt.Dimension(20, 22));
        //VersionBox3TextField.setRequestFocusEnabled(false);
        VersionBox3TextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                VersionBox3TextFieldMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                VersionBox3TextFieldMouseExited(evt);
            }
        });

        VersionCopyrightPanel.add(VersionBox3TextField);

        Filler003.setMaximumSize(new java.awt.Dimension(10, 10));
        Filler003.setMinimumSize(new java.awt.Dimension(10, 10));
        Filler003.setPreferredSize(new java.awt.Dimension(10, 10));
        VersionCopyrightPanel.add(Filler003);

        VersionBox4TextField.setText("0");
        VersionBox4TextField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        VersionBox4TextField.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        VersionBox4TextField.setMargin(new java.awt.Insets(0, 10, 0, 5));
        VersionBox4TextField.setMaximumSize(new java.awt.Dimension(2147483647, 22));
        VersionBox4TextField.setMinimumSize(new java.awt.Dimension(20, 22));
        VersionBox4TextField.setPreferredSize(new java.awt.Dimension(20, 22));
        //VersionBox4TextField.setRequestFocusEnabled(false);
        VersionBox4TextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                VersionBox4TextFieldMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                VersionBox4TextFieldMouseExited(evt);
            }
        });

        VersionCopyrightPanel.add(VersionBox4TextField);

        Filler004.setMaximumSize(new java.awt.Dimension(10, 10));
        Filler004.setMinimumSize(new java.awt.Dimension(10, 10));
        Filler004.setPreferredSize(new java.awt.Dimension(10, 10));
        VersionCopyrightPanel.add(Filler004);

        CopyrightLabel.setFont(new java.awt.Font("Dialog", 0, 12));
        CopyrightLabel.setText("Copyright:");
        VersionCopyrightPanel.add(CopyrightLabel);

        Filler005.setMaximumSize(new java.awt.Dimension(10, 10));
        Filler005.setMinimumSize(new java.awt.Dimension(10, 10));
        Filler005.setPreferredSize(new java.awt.Dimension(10, 10));
        VersionCopyrightPanel.add(Filler005);

        CopyrightTextField.setText("2004");
        CopyrightTextField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        CopyrightTextField.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        CopyrightTextField.setMargin(new java.awt.Insets(0, 10, 0, 5));
        CopyrightTextField.setMaximumSize(new java.awt.Dimension(2147483647, 22));
        CopyrightTextField.setMinimumSize(new java.awt.Dimension(50, 22));
        CopyrightTextField.setPreferredSize(new java.awt.Dimension(100, 22));
        //CopyrightTextField.setRequestFocusEnabled(false);
        CopyrightTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CopyrightTextFieldMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CopyrightTextFieldMouseExited(evt);
            }
        });

        VersionCopyrightPanel.add(CopyrightTextField);

        Filler008.setMaximumSize(new java.awt.Dimension(10, 10));
        Filler008.setMinimumSize(new java.awt.Dimension(10, 10));
        Filler008.setPreferredSize(new java.awt.Dimension(10, 10));
        VersionCopyrightPanel.add(Filler008);

        add(VersionCopyrightPanel);

        ProductURLPanel.setLayout(new javax.swing.BoxLayout(ProductURLPanel, javax.swing.BoxLayout.X_AXIS));

        ProductURLPanel.setMaximumSize(new java.awt.Dimension(370, 29));
        ProductURLPanel.setMinimumSize(new java.awt.Dimension(370, 29));
        ProductURLPanel.setPreferredSize(new java.awt.Dimension(370, 29));
        ProductURLPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ProductURLPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ProductURLPanelMouseExited(evt);
            }
        });

        ProductURLLabel.setFont(new java.awt.Font("Dialog", 0, 12));
        ProductURLLabel.setText("Product URL:");
        ProductURLLabel.setMaximumSize(new java.awt.Dimension(103, 16));
        ProductURLLabel.setMinimumSize(new java.awt.Dimension(103, 16));
        ProductURLLabel.setPreferredSize(new java.awt.Dimension(103, 16));
        ProductURLPanel.add(ProductURLLabel);

        ProductURLTextField.setText("http://www.evaluateanywhere.com");
        ProductURLTextField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        ProductURLTextField.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        ProductURLTextField.setMargin(new java.awt.Insets(0, 10, 0, 5));
        ProductURLTextField.setMaximumSize(new java.awt.Dimension(2147483647, 22));
        ProductURLTextField.setMinimumSize(new java.awt.Dimension(165, 22));
        ProductURLTextField.setPreferredSize(new java.awt.Dimension(235, 22));
        ProductURLTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ProductURLTextFieldMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ProductURLTextFieldMouseExited(evt);
            }
        });

        ProductURLPanel.add(ProductURLTextField);

        Filler009.setMaximumSize(new java.awt.Dimension(10, 10));
        Filler009.setMinimumSize(new java.awt.Dimension(10, 10));
        Filler009.setPreferredSize(new java.awt.Dimension(10, 10));
        ProductURLPanel.add(Filler009);

        add(ProductURLPanel);

        ProductInformationURLPanel.setLayout(new javax.swing.BoxLayout(ProductInformationURLPanel, javax.swing.BoxLayout.X_AXIS));

        ProductInformationURLPanel.setMaximumSize(new java.awt.Dimension(370, 29));
        ProductInformationURLPanel.setMinimumSize(new java.awt.Dimension(370, 29));
        ProductInformationURLPanel.setPreferredSize(new java.awt.Dimension(370, 29));
        ProductInformationURLPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ProductInformationURLPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ProductInformationURLPanelMouseExited(evt);
            }
        });

        ProductInformationLabel.setFont(new java.awt.Font("Dialog", 0, 12));
        ProductInformationLabel.setText("Product Info URL:");
        ProductInformationLabel.setMaximumSize(new java.awt.Dimension(103, 16));
        ProductInformationLabel.setMinimumSize(new java.awt.Dimension(103, 16));
        ProductInformationLabel.setPreferredSize(new java.awt.Dimension(103, 16));
        ProductInformationURLPanel.add(ProductInformationLabel);

        ProductInformationTextField.setText("http://www.evaluateanywhere.com/info");
        ProductInformationTextField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        ProductInformationTextField.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        ProductInformationTextField.setMargin(new java.awt.Insets(0, 10, 0, 5));
        ProductInformationTextField.setMaximumSize(new java.awt.Dimension(2147483647, 22));
        ProductInformationTextField.setMinimumSize(new java.awt.Dimension(165, 22));
        ProductInformationTextField.setPreferredSize(new java.awt.Dimension(235, 22));
        ProductInformationTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ProductInformationTextFieldMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ProductInformationTextFieldMouseExited(evt);
            }
        });

        ProductInformationURLPanel.add(ProductInformationTextField);

        Filler010.setMaximumSize(new java.awt.Dimension(10, 10));
        Filler010.setMinimumSize(new java.awt.Dimension(10, 10));
        Filler010.setPreferredSize(new java.awt.Dimension(10, 10));
        ProductInformationURLPanel.add(Filler010);

        add(ProductInformationURLPanel);

    }//GEN-END:initComponents

    private void ProductInformationURLPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProductInformationURLPanelMouseExited
        ((NewProject)getParentComponent()).setStatus("");
    }//GEN-LAST:event_ProductInformationURLPanelMouseExited

    private void ProductInformationURLPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProductInformationURLPanelMouseEntered
        ((NewProject)getParentComponent()).setStatus("Specify the product information URL (web page address starting http://).");
    }//GEN-LAST:event_ProductInformationURLPanelMouseEntered

    private void ProductURLPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProductURLPanelMouseExited
        ((NewProject)getParentComponent()).setStatus("");
    }//GEN-LAST:event_ProductURLPanelMouseExited

    private void ProductURLPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProductURLPanelMouseEntered
        ((NewProject)getParentComponent()).setStatus("Specify the product URL (web page address starting http://).");
    }//GEN-LAST:event_ProductURLPanelMouseEntered

    private void VersionCopyrightPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VersionCopyrightPanelMouseExited
        ((NewProject)getParentComponent()).setStatus("");
    }//GEN-LAST:event_VersionCopyrightPanelMouseExited

    private void VersionCopyrightPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VersionCopyrightPanelMouseEntered
        ((NewProject)getParentComponent()).setStatus("Specify the software product release version, and copyright date.");
    }//GEN-LAST:event_VersionCopyrightPanelMouseEntered

    private void ProductNamePanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProductNamePanelMouseExited
        ((NewProject)getParentComponent()).setStatus("");
    }//GEN-LAST:event_ProductNamePanelMouseExited

    private void ProductNamePanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProductNamePanelMouseEntered
        ((NewProject)getParentComponent()).setStatus("Specify the product name (software title).");
    }//GEN-LAST:event_ProductNamePanelMouseEntered

    private void VendorNamePanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VendorNamePanelMouseExited
        ((NewProject)getParentComponent()).setStatus("");
    }//GEN-LAST:event_VendorNamePanelMouseExited

    private void VendorNamePanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VendorNamePanelMouseEntered
        ((NewProject)getParentComponent()).setStatus("Specify the vendor name (company, organization, or developer name).");
    }//GEN-LAST:event_VendorNamePanelMouseEntered

    private void VersionBox4TextFieldMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VersionBox4TextFieldMouseExited
        ((NewProject)getParentComponent()).setStatus("");
    }//GEN-LAST:event_VersionBox4TextFieldMouseExited

    private void VersionBox4TextFieldMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VersionBox4TextFieldMouseEntered
        ((NewProject)getParentComponent()).setStatus("Specify the software product release version.");
    }//GEN-LAST:event_VersionBox4TextFieldMouseEntered

    private void VersionBox3TextFieldMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VersionBox3TextFieldMouseExited
        ((NewProject)getParentComponent()).setStatus("");
    }//GEN-LAST:event_VersionBox3TextFieldMouseExited

    private void VersionBox3TextFieldMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VersionBox3TextFieldMouseEntered
        ((NewProject)getParentComponent()).setStatus("Specify the software product release version.");
    }//GEN-LAST:event_VersionBox3TextFieldMouseEntered

    private void VersionBox2TextFieldMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VersionBox2TextFieldMouseExited
        ((NewProject)getParentComponent()).setStatus("");
    }//GEN-LAST:event_VersionBox2TextFieldMouseExited

    private void VersionBox2TextFieldMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VersionBox2TextFieldMouseEntered
        ((NewProject)getParentComponent()).setStatus("Specify the software product release version.");
    }//GEN-LAST:event_VersionBox2TextFieldMouseEntered

    private void VersionBox1TextFieldMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VersionBox1TextFieldMouseExited
        ((NewProject)getParentComponent()).setStatus("");
    }//GEN-LAST:event_VersionBox1TextFieldMouseExited

    private void VersionBox1TextFieldMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VersionBox1TextFieldMouseEntered
        ((NewProject)getParentComponent()).setStatus("Specify the software product release version.");
    }//GEN-LAST:event_VersionBox1TextFieldMouseEntered

    private void CopyrightTextFieldMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CopyrightTextFieldMouseExited
        ((NewProject)getParentComponent()).setStatus("");
    }//GEN-LAST:event_CopyrightTextFieldMouseExited

    private void CopyrightTextFieldMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CopyrightTextFieldMouseEntered
        ((NewProject)getParentComponent()).setStatus("Specify the software product copyright date.");
    }//GEN-LAST:event_CopyrightTextFieldMouseEntered

    private void ProductInformationTextFieldMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProductInformationTextFieldMouseExited
        ((NewProject)getParentComponent()).setStatus("");
    }//GEN-LAST:event_ProductInformationTextFieldMouseExited

    private void ProductInformationTextFieldMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProductInformationTextFieldMouseEntered
    ((NewProject)getParentComponent()).setStatus("Specify the product information URL (web page address starting http://).");
    
    }//GEN-LAST:event_ProductInformationTextFieldMouseEntered

    private void ProductURLTextFieldMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProductURLTextFieldMouseExited
        ((NewProject)getParentComponent()).setStatus("");
    }//GEN-LAST:event_ProductURLTextFieldMouseExited

    private void ProductURLTextFieldMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProductURLTextFieldMouseEntered
        ((NewProject)getParentComponent()).setStatus("Specify the product URL (web page address starting http://).");
    }//GEN-LAST:event_ProductURLTextFieldMouseEntered

    private void ProductNameTextFieldMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProductNameTextFieldMouseExited
        ((NewProject)getParentComponent()).setStatus("");
    }//GEN-LAST:event_ProductNameTextFieldMouseExited

    private void ProductNameTextFieldMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProductNameTextFieldMouseEntered
        ((NewProject)getParentComponent()).setStatus("Specify the product name (software title).");
    }//GEN-LAST:event_ProductNameTextFieldMouseEntered

    private void VendorNameTextFieldMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VendorNameTextFieldMouseExited
        ((NewProject)getParentComponent()).setStatus("");
    }//GEN-LAST:event_VendorNameTextFieldMouseExited

    private void VendorNameTextFieldMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VendorNameTextFieldMouseEntered
        ((NewProject)getParentComponent()).setStatus("Specify the vendor name (company, organization, or developer name).");
    }//GEN-LAST:event_VendorNameTextFieldMouseEntered
    
    private static synchronized Object[] getStringArraysFromString(String textArrayString)
    {
        ArrayList aryList = new ArrayList();
        String tempString = "";
        while(textArrayString.indexOf(",")!=-1)
        {
            tempString = textArrayString.substring(0,textArrayString.indexOf(","));
            textArrayString = textArrayString.substring(textArrayString.indexOf(",") + 1);
            aryList.add(tempString);
        }
        aryList.add(textArrayString);
        return aryList.toArray();
    }        

    /** Return true on all data entry fields contain text data, false otherwise. */
    public boolean getDataEntryIsComplete()
    {
        try
        {
            if(CopyrightTextField.getText().equalsIgnoreCase("")==true)
            {
                return false;
            }
            else if(ProductNameTextField.getText().equalsIgnoreCase("")==true)
            {
                return false;
            }
            else if(VendorNameTextField.getText().equalsIgnoreCase("")==true)
            {
                return false;
            }            
            else if(ProductInformationTextField.getText().equalsIgnoreCase("")==true)
            {
                return false;
            }
            else if(ProductURLTextField.getText().equalsIgnoreCase("")==true)
            {
                return false;
            }            
            else if(VersionBox1TextField.getText().equalsIgnoreCase("")==true)
            {
                return false;
            }            
        }
        catch(Exception e)
        {
            return false;
        }
        return true;
    }
    
    /** If getDataEntryIsComplete()==false, call this method to retrieve the first incomplete data field entry String. Return "" on unknown. */
    public String getIncompleteDataEntryString()
    {
        try
        {
            if(VendorNameTextField.getText().equalsIgnoreCase("")==true)
            {
                return "Please enter the vendor name (company, organization, or developer name).";
            }                
            else if(ProductNameTextField.getText().equalsIgnoreCase("")==true)
            {
                return "Please enter the product name (software title).";
            }
            else if(VersionBox1TextField.getText().equalsIgnoreCase("")==true)
            {
                return "Please enter the version (release version).";
            }          
            else if(CopyrightTextField.getText().equalsIgnoreCase("")==true)
            {
                return "Please enter the software product copyright date.";
            }             
            else if(ProductURLTextField.getText().equalsIgnoreCase("")==true)
            {
                return "Please enter the product URL (product web page address starting http://).";
            }       
            else if(ProductInformationTextField.getText().equalsIgnoreCase("")==true)
            {
                return "Please enter the product information URL (product information web page address starting http://).";
            }            
        }
        catch(Exception e)
        {
            return "";
        }
        return "";
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CopyrightLabel;
    private javax.swing.JTextField CopyrightTextField;
    private javax.swing.JLabel Filler001;
    private javax.swing.JLabel Filler002;
    private javax.swing.JLabel Filler003;
    private javax.swing.JLabel Filler004;
    private javax.swing.JLabel Filler005;
    private javax.swing.JLabel Filler006;
    private javax.swing.JLabel Filler007;
    private javax.swing.JLabel Filler008;
    private javax.swing.JLabel Filler009;
    private javax.swing.JLabel Filler010;
    private javax.swing.JLabel ProductInformationLabel;
    private javax.swing.JTextField ProductInformationTextField;
    private javax.swing.JPanel ProductInformationURLPanel;
    private javax.swing.JLabel ProductNameLabel;
    private javax.swing.JPanel ProductNamePanel;
    private javax.swing.JTextField ProductNameTextField;
    private javax.swing.JLabel ProductURLLabel;
    private javax.swing.JPanel ProductURLPanel;
    private javax.swing.JTextField ProductURLTextField;
    private javax.swing.JLabel VendorNameLabel;
    private javax.swing.JPanel VendorNamePanel;
    private javax.swing.JTextField VendorNameTextField;
    private javax.swing.JTextField VersionBox1TextField;
    private javax.swing.JTextField VersionBox2TextField;
    private javax.swing.JTextField VersionBox3TextField;
    private javax.swing.JTextField VersionBox4TextField;
    private javax.swing.JPanel VersionCopyrightPanel;
    private javax.swing.JLabel VersionLabel;
    // End of variables declaration//GEN-END:variables
    
}
