/*
 * SaveDialog.java
 *
 * Created on March 20, 2004, 12:32 AM
 */

package com.trinity.ea.design.common.project;
import javax.swing.*;
import java.awt.*;
import javax.swing.ImageIcon;

/** 
 *
 * @author  aaronsc Trinity Software
 * Copyright ©2005 Trinity Software. All rights reserved.
 */
public class ProjectNotFoundDialog extends javax.swing.JDialog {
    private static int retCode = 0;
    private Icon theInfoIcon = new javax.swing.ImageIcon(getClass().getResource("/images/lgpl/filetypes.png"));

  public static int showDialog(Frame parent, String title, String filename) 
  {
    ProjectNotFoundDialog dialog = new ProjectNotFoundDialog(parent, true, filename);
    dialog.dispose();
    return retCode;
  }    
    
    /** Creates new form SaveDialog */
    public ProjectNotFoundDialog(java.awt.Frame parent, boolean modal, String filename) {
        super(parent, modal);
        initComponents(filename);
        // Get the size of the screen
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        // Determine the new location of the window
	  setSize(403, 207);
        int w = getSize().width;
        int h = getSize().height;
        int x = (dim.width-w)/2;
        int y = (dim.height-h)/2;
        // Move the window
        setLocation(x, y);  
        show();
    }
    
    public int getMethod()
    {
        return retCode;
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents(String filename) {//GEN-BEGIN:initComponents
        NorthPanel = new javax.swing.JPanel();
        NorthLeftPanel = new javax.swing.JPanel();
        ImageLabel = new javax.swing.JLabel();
        NorthRightPanel = new javax.swing.JPanel();
        HeaderPanel = new javax.swing.JPanel();
        HeaderLabel = new javax.swing.JLabel();
        SouthPanel = new javax.swing.JPanel();
        SouthRightPanel = new javax.swing.JPanel();
        OKButton = new javax.swing.JButton();
        RemoveButton = new javax.swing.JButton();

        setTitle("EvaluateAnywhere Project");
        setModal(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        NorthPanel.setLayout(new java.awt.BorderLayout());

        NorthPanel.setMaximumSize(new java.awt.Dimension(2147483647, 90));
        NorthPanel.setMinimumSize(new java.awt.Dimension(370, 90));
        NorthPanel.setPreferredSize(new java.awt.Dimension(370, 90));
        NorthLeftPanel.setLayout(new java.awt.BorderLayout(20, 0));

        NorthLeftPanel.setMinimumSize(new java.awt.Dimension(64, 50));
        NorthLeftPanel.setPreferredSize(new java.awt.Dimension(64, 50));
        ImageLabel.setBackground(new java.awt.Color(102, 102, 102));
        ImageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ImageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/lgpl/file_broken.png")));
        ImageLabel.setText("<html></html>");
        ImageLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        ImageLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ImageLabel.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        NorthLeftPanel.add(ImageLabel, java.awt.BorderLayout.CENTER);

        NorthPanel.add(NorthLeftPanel, java.awt.BorderLayout.WEST);

        NorthRightPanel.setLayout(new javax.swing.BoxLayout(NorthRightPanel, javax.swing.BoxLayout.Y_AXIS));

        NorthRightPanel.setMinimumSize(new java.awt.Dimension(300, 40));
        NorthRightPanel.setPreferredSize(new java.awt.Dimension(300, 40));
        HeaderPanel.setLayout(new java.awt.BorderLayout());

        HeaderPanel.setMinimumSize(new java.awt.Dimension(300, 20));
        HeaderPanel.setPreferredSize(new java.awt.Dimension(300, 20));
        HeaderLabel.setBackground(new java.awt.Color(102, 102, 102));
        HeaderLabel.setFont(new java.awt.Font("Arial", 0, 11));
        HeaderLabel.setText("<html><br>The project file name or path is not valid. Try these suggestions:<br>* Check the file permissions for the project file or drive.<br>* Use the open project dialog box to locate the project file.<br>" + filename + "<br><br>Click the \"Remove\" button to remove the project file from the recent project files list.</html>");
        HeaderLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        HeaderLabel.setMaximumSize(new java.awt.Dimension(300, 20));
        HeaderLabel.setMinimumSize(new java.awt.Dimension(300, 20));
        HeaderLabel.setPreferredSize(new java.awt.Dimension(300, 20));
        HeaderLabel.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        HeaderPanel.add(HeaderLabel, java.awt.BorderLayout.CENTER);

        NorthRightPanel.add(HeaderPanel);

        NorthPanel.add(NorthRightPanel, java.awt.BorderLayout.CENTER);

        getContentPane().add(NorthPanel, java.awt.BorderLayout.CENTER);

        SouthPanel.setLayout(new javax.swing.BoxLayout(SouthPanel, javax.swing.BoxLayout.X_AXIS));

        SouthRightPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 10));

        OKButton.setFont(new java.awt.Font("Arial", 0, 12));
        OKButton.setMnemonic('O');
        OKButton.setText("OK");
        OKButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKButtonActionPerformed(evt);
            }
        });

        SouthRightPanel.add(OKButton);

        RemoveButton.setFont(new java.awt.Font("Arial", 0, 12));
        RemoveButton.setMnemonic('R');
        RemoveButton.setText("Remove");
        RemoveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveButtonActionPerformed(evt);
            }
        });

        SouthRightPanel.add(RemoveButton);

        SouthPanel.add(SouthRightPanel);

        getContentPane().add(SouthPanel, java.awt.BorderLayout.SOUTH);

    }//GEN-END:initComponents

    private void RemoveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveButtonActionPerformed
        retCode=1;
        setVisible(false);
    }//GEN-LAST:event_RemoveButtonActionPerformed

    private void OKButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKButtonActionPerformed
        retCode=0;
        setVisible(false);        
    }//GEN-LAST:event_OKButtonActionPerformed
    
    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        retCode=0;        
    }//GEN-LAST:event_closeDialog
    
     // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel HeaderLabel;
    private javax.swing.JPanel HeaderPanel;
    private javax.swing.JLabel ImageLabel;
    private javax.swing.JPanel NorthLeftPanel;
    private javax.swing.JPanel NorthPanel;
    private javax.swing.JPanel NorthRightPanel;
    private javax.swing.JButton OKButton;
    private javax.swing.JButton RemoveButton;
    private javax.swing.JPanel SouthPanel;
    private javax.swing.JPanel SouthRightPanel;
    // End of variables declaration//GEN-END:variables
    
}
