/*
 * dlgEMailOptin.java
 *
 * Created on November 15, 2003, 7:25 PM
 */

package com.trinity.ea.forms.optin;
import com.trinity.ea.rules.reader.EncryptedRuleReader;
import javax.swing.JDialog;
import javax.swing.JFrame;
import java.awt.Toolkit;
import java.awt.Dimension;
import java.awt.BorderLayout;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.ComponentOrientation;
import java.awt.Graphics2D;
import java.awt.Graphics;
import java.awt.RenderingHints;  
import javax.swing.UIManager;

/**
 *
 * @author  aaronsc Trinity Software
 * Copyright ©2003-2005 Trinity Software. All rights reserved.
 */
public class dlgEMailOptin extends javax.swing.JDialog {
    private int btnHeight = -1;
    /** Creates new form dlgEMailOptin
     * @param parent
     * @param modal
     */
    public dlgEMailOptin(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
	  if(btnHeight!=-1)
	  {
        	setSize(322 + getHorizontalInsetAdjustment(this.getInsets().left, this.getInsets().right), (135 + btnHeight) + getVerticalInsetAdjustment(this.getInsets().top, this.getInsets().bottom));
	  }
	  else
	  {
        	setSize(322 + getHorizontalInsetAdjustment(this.getInsets().left, this.getInsets().right), 159 + getVerticalInsetAdjustment(this.getInsets().top, this.getInsets().bottom));
	  }
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        int w = getSize().width;
        int h = getSize().height;
        int x = (dim.width-w)/2;
        int y = (dim.height-h)/2;
        setLocation(x, y);   
        try
        {
            setTitle(EncryptedRuleReader.getLocaleString("registerSoftwareTitle"));
        }
        catch(Exception e){}
	try
	{
	  	  applyComponentOrientation(ComponentOrientation.getOrientation(EncryptedRuleReader.getLocale()));
	}
	catch(Exception e)
	{
		e.printStackTrace();
	}
    }

private int getVerticalInsetAdjustment(int actualTopInset, int actualBottomInset)
{
	try
	{
		int sum = actualTopInset + actualBottomInset;
		if(sum!=25)
		{
			if(sum<25)
			{
		    		return 0 - (25 - sum);
			}
			else if(sum>25)
			{
		     		return 0 + (sum - 25);
			}
		}
		else
		{
			return 0;
		}
	}
	catch(Exception e)
	{
		return 0;
	}
	return 0;
}

private int getHorizontalInsetAdjustment(int actualLeftInset, int actualRightInset)
{
	try
	{
		int sum = actualLeftInset + actualRightInset;
		if(sum!=6)
		{
			if(sum<6)
			{
		    		return 0 - (6 - sum);
			}
			else if(sum>6)
			{
		     		return 0 + (sum - 6);
			}
		}
		else
		{
			return 0;
		}
	}
	catch(Exception e)
	{
		return 0;
	}
	return 0;
}
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        emailOptin1 = new emailOptin();
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });
		
setResizable(false);
        getContentPane().add(emailOptin1, java.awt.BorderLayout.CENTER);
try
{
	  if(EncryptedRuleReader.get("btnBarImgButtonsEnabled")!=null)
	  {
	  	if(EncryptedRuleReader.get("btnBarImgButtonsEnabled").equalsIgnoreCase("true")==true)
	  	{
	  if(EncryptedRuleReader.get("registrationImgButtonHeight")!=null)
	  {
	  	if(EncryptedRuleReader.get("registrationImgButtonHeight").equalsIgnoreCase("")==false)
	  	{
			try
			{
				btnHeight = new Integer(EncryptedRuleReader.get("registrationImgButtonHeight")).intValue();
			}
			catch(Exception eee)
			{
				eee.printStackTrace();
				btnHeight = 24;
			}
		}
		else
		{
			btnHeight = 24;
		}
	  }
	  else
	  {
		btnHeight = 24;
	  }	
	}
   }
}
catch(Exception e)
{
	e.printStackTrace();
} 
       pack();
    }//GEN-END:initComponents
    
    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog
    
    public void paint(Graphics g)
    {
	Graphics2D g2 = (Graphics2D) g;
	g2.setRenderingHint(RenderingHints.KEY_TEXT_ANTIALIASING,RenderingHints.VALUE_TEXT_ANTIALIAS_ON);
	super.paint(g);
    } 

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        new dlgEMailOptin(new javax.swing.JFrame(), true).show();
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private emailOptin emailOptin1;
    // End of variables declaration//GEN-END:variables
    
}
