/*
 * PaymentsEnabledControl.java
 *
 * Created on April 9, 2004, 9:24 PM
 */

package com.trinity.ea.design.payments;

import com.trinity.ea.design.common.panel.EAPanel;
import com.trinity.ea.design.common.file.ProjectManager;
import java.awt.Color;
import java.awt.BorderLayout;
import javax.swing.JCheckBox;
import javax.swing.JPanel;

/** 
 *
 * @author  aaronsc Trinity Software
 * Copyright ©2003-2004 Trinity Software. All rights reserved.
 */
public class PaymentsEnabledControl extends EAPanel {
    private Color backgroundColor = new java.awt.Color(100, 120, 170);
    private Color txtColor = new java.awt.Color(0, 0, 0);    
    
    /** Creates new form PaymentsEnabledControl */
    public PaymentsEnabledControl() {
        initComponents();
        setProjectData();
    }
  
    public synchronized void getDataUpdate()
    {
	try
	{
		// Registration Support Functionality Checkbox Enabled/Disabled
            if(cbPaymentProcessingEnabled.isSelected()==true)
            {
		    ProjectManager.putTempNoFileWrite("paymentProcessingSupportEnabled", "true");
 		    ProjectManager.putTempNoFileWrite("project_payment_processing_support_is_enabled", "true");                            
            }
            else
            {
		    ProjectManager.putTempNoFileWrite("paymentProcessingSupportEnabled", "false");
		    ProjectManager.putTempNoFileWrite("project_payment_processing_support_is_enabled", "false");               
            }
            ProjectManager.saveTempNow();
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }
 
    public synchronized void setProjectData()
    {
        try
        {
		// Optin Support Functionality Checkbox Enabled/Disabled   
            if(ProjectManager.get("project_payment_processing_support_is_enabled").equalsIgnoreCase("true")==true)
            {
                cbPaymentProcessingEnabled.setSelected(true);              
            }
            else
            {
                cbPaymentProcessingEnabled.setSelected(false);               
            }
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }

    public void setText(String cbText)
    {
        try
        {
            cbPaymentProcessingEnabled.setText(cbText);
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }
    
    public String getText()
    {
        try
        {
            return cbPaymentProcessingEnabled.getText();
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
        return null;
    }
    
    public void setBackgroundColor(Color BGColor)
    {
        try
        {
            backgroundColor = BGColor;
            cbPaymentProcessingEnabled.setBackground(BGColor);
            DescriptorPanel.setBackground(BGColor);
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }      
    }
    
    public Color getBackgroundColor()
    {
        return backgroundColor;
    }
    
    public void setTextColor(Color textColor)
    {
        try
        {
            txtColor = textColor;
            cbPaymentProcessingEnabled.setForeground(textColor);  
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }
    
    public Color getTextColor()
    {
        return cbPaymentProcessingEnabled.getForeground(); 
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        DescriptorPanel = new javax.swing.JPanel();
        cbPaymentProcessingEnabled = new javax.swing.JCheckBox();

        setLayout(new java.awt.BorderLayout());

        setBackground(new java.awt.Color(100, 120, 170));
        DescriptorPanel.setLayout(new java.awt.BorderLayout());

        DescriptorPanel.setBackground(new java.awt.Color(100, 120, 170));
        cbPaymentProcessingEnabled.setBackground(new java.awt.Color(100, 120, 170));
        cbPaymentProcessingEnabled.setFont(new java.awt.Font("Arial", 1, 12));
        cbPaymentProcessingEnabled.setSelected(true);
        cbPaymentProcessingEnabled.setText("Enable Payment Processing Support");
        cbPaymentProcessingEnabled.setMnemonic('n');
        DescriptorPanel.add(cbPaymentProcessingEnabled, java.awt.BorderLayout.CENTER);

        add(DescriptorPanel, java.awt.BorderLayout.CENTER);

    }//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DescriptorPanel;
    private javax.swing.JCheckBox cbPaymentProcessingEnabled;
    // End of variables declaration//GEN-END:variables
    
}
