/*
 * AllowURLChangesControl.java
 *
 * Created on April 9, 2004, 9:24 PM
 */

package com.trinity.ea.design.messaging.config;

import com.trinity.ea.design.common.panel.EAPanel;
import com.trinity.ea.design.common.file.ProjectManager;
import java.awt.Color;
import java.awt.BorderLayout;
import javax.swing.JCheckBox;
import javax.swing.JPanel;

/** 
 *
 * @author  aaronsc Trinity Software
 * Copyright ©2004 Trinity Software. All rights reserved.
 */
public class AllowURLChangesControl extends EAPanel {
    private Color backgroundColor = new java.awt.Color(100, 120, 170);
    private Color txtColor = new java.awt.Color(0, 0, 0);    
    
    /** Creates new form AllowURLChangesControl */
    public AllowURLChangesControl() {
        initComponents();
        setProjectData();
    }

    public synchronized void setProjectData()
    {
        try
        {
		// Auto Update Support Functionality Checkbox Enabled/Disabled   
            if(ProjectManager.get("msgBaseURLChangesAllowed").equalsIgnoreCase("true")==true)
            {
                cbAllowURLChangesEnabled.setSelected(true);              
            }
            else
            {
                cbAllowURLChangesEnabled.setSelected(false);               
            }
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }
  
    public synchronized void getDataUpdate()
    {
	try
	{
		// Auto Update Support Functionality Checkbox Enabled/Disabled
            if(cbAllowURLChangesEnabled.isSelected()==true)
            {
		    ProjectManager.putTempNoFileWrite("msgBaseURLChangesAllowed", "true");
            }
            else
            {
		    ProjectManager.putTempNoFileWrite("msgBaseURLChangesAllowed", "false");
            }
            ProjectManager.saveTempNow();
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }
 
    public void setText(String cbText)
    {
        try
        {
            cbAllowURLChangesEnabled.setText(cbText);
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }
    
    public String getText()
    {
        try
        {
            return cbAllowURLChangesEnabled.getText();
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
        return null;
    }
    
    public void setBackgroundColor(Color BGColor)
    {
        try
        {
            backgroundColor = BGColor;
            cbAllowURLChangesEnabled.setBackground(BGColor);
            DescriptorPanel.setBackground(BGColor);
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }      
    }
    
    public Color getBackgroundColor()
    {
        return backgroundColor;
    }
    
    public void setTextColor(Color textColor)
    {
        try
        {
            txtColor = textColor;
            cbAllowURLChangesEnabled.setForeground(textColor);  
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }
    
    public Color getTextColor()
    {
        return cbAllowURLChangesEnabled.getForeground(); 
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        DescriptorPanel = new javax.swing.JPanel();
        cbAllowURLChangesEnabled = new javax.swing.JCheckBox();

        setLayout(new java.awt.BorderLayout());

        setBackground(new java.awt.Color(100, 120, 170));
        DescriptorPanel.setLayout(new java.awt.BorderLayout());

        DescriptorPanel.setBackground(new java.awt.Color(100, 120, 170));
        cbAllowURLChangesEnabled.setBackground(new java.awt.Color(100, 120, 170));
        cbAllowURLChangesEnabled.setFont(new java.awt.Font("Arial", 1, 12));
        cbAllowURLChangesEnabled.setSelected(true);
        cbAllowURLChangesEnabled.setText("Allow Message URL changes");
        cbAllowURLChangesEnabled.setMnemonic('l');
        DescriptorPanel.add(cbAllowURLChangesEnabled, java.awt.BorderLayout.CENTER);

        add(DescriptorPanel, java.awt.BorderLayout.CENTER);

    }//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DescriptorPanel;
    private javax.swing.JCheckBox cbAllowURLChangesEnabled;
    // End of variables declaration//GEN-END:variables
    
}
