/*
 * ProjectLookAndFeelPanel.java
 *
 * Created on December 16, 2003, 4:55 PM
 */

package com.trinity.ea.design.project.lookandfeel;
import com.trinity.ea.design.common.panel.EAPanel;
import com.trinity.ea.design.project.lookandfeel.general.*;
import com.trinity.ea.design.project.lookandfeel.images.*;
import com.trinity.ea.design.project.lookandfeel.bgimages.*;
import com.trinity.ea.design.project.lookandfeel.buttons.*;
import com.trinity.ea.design.project.lookandfeel.colors.*;
import com.trinity.ea.design.project.lookandfeel.error.*;
import com.trinity.ea.design.project.lookandfeel.information.*;
import com.trinity.ea.design.project.lookandfeel.fonts.*;
import com.trinity.ea.design.project.lookandfeel.text.*;
import com.trinity.ea.design.project.lookandfeel.other.*;
import com.trinity.ea.design.project.lookandfeel.scrollbars.*;
import javax.swing.*;
import java.awt.*;
import javax.swing.UIManager;
import javax.swing.plaf.ColorUIResource;
import javax.swing.plaf.InsetsUIResource;
import javax.swing.plaf.BorderUIResource;

/**
 *
 * @author  aaronsc Trinity Software
 * Copyright ©2003-2004 Trinity Software. All rights reserved.
 */
public class ProjectLookAndFeelPanel extends EAPanel {

    /** Creates new form ProjectLookAndFeelPanel */
    public ProjectLookAndFeelPanel() {
        UIManager uiM = new UIManager();
        UIDefaults uid = uiM.getDefaults();

        //set to your main Panel bg color
        uid.put("TabbedPane.tabAreaInsets", new InsetsUIResource(1, 1, 1, 1));
        uid.put("TabbedPane.contentBorderInsets", new InsetsUIResource(1, 1, 1, 1));
        uid.put("TabbedPane.selectedTabPadInsets", new InsetsUIResource(2, 2, 2, 2));
        uid.put("TabbedPane.selectHighlight", new ColorUIResource(Color.white));
	  UIManager.put("TabbedPane.tabAreaBackground", new java.awt.Color(140, 160, 210));
	  UIManager.put("TabbedPane.background", new java.awt.Color(140, 160, 210));
	  UIManager.put("TabbedPane.foreground", new ColorUIResource(Color.black));
	  UIManager.put("TabbedPane.selected", new java.awt.Color(140, 160, 210));
	  UIManager.put("TabbedPane.border", new BorderUIResource(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0)));
        initComponents();
	  setProjectData();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        ProjectLookAndFeelContentContainer = new javax.swing.JPanel();
        ProjectLookAndFeelLeftMargin = new javax.swing.JPanel();
        ProjectLookAndFeelContent = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        ProjectLookAndFeelRightMargin = new javax.swing.JPanel();
        ProjectLookAndFeelBottomMargin = new javax.swing.JPanel();
        ProjectLookAndFeelTopMarginContainer = new javax.swing.JPanel();
	  generalPanel = new GeneralLookAndFeelPanel();
    	  imagesPanel = new MainImagesPanel();
	  scrollbarPanel = new ScrollbarPanel();
    	  imagesPanel.setParentComp(getParentComp());
    	  //errorPanel = new ErrorPanel();
    	  //errorPanel.setParentComp(getParentComp());
    	  //informationPanel = new InformationPanel();
    	  //informationPanel.setParentComp(getParentComp());
    	  bgImagesPanel = new BGImagesPanel();
    	  bgImagesPanel.setParentComp(getParentComp());
	  buttonPanel = new MainButtonsPanel();
	  buttonPanel.setParentComp(getParentComp());
	  colorsPanel = new MainColorPanel();
	  fontsPanel = new MainFontPanel();
	  fontsPanel.setParentComp(getParentComp());
	  textPanel = new MainTextPanel();
	  textPanel.setParentComp(getParentComp());
	  otherPanel = new OtherPanel();
	  otherPanel.setParentComp(getParentComp());
	  scrollbarPanel.setParentComp(getParentComp());
        setLayout(new java.awt.BorderLayout());

        setBackground(new java.awt.Color(140, 160, 210));
        ProjectLookAndFeelContentContainer.setLayout(new java.awt.BorderLayout());

        ProjectLookAndFeelContentContainer.setBackground(new java.awt.Color(140, 160, 210));
        ProjectLookAndFeelLeftMargin.setBackground(new java.awt.Color(140, 160, 210));
        ProjectLookAndFeelContentContainer.add(ProjectLookAndFeelLeftMargin, java.awt.BorderLayout.WEST);

        ProjectLookAndFeelContent.setLayout(new java.awt.BorderLayout());

        ProjectLookAndFeelContent.setBackground(new java.awt.Color(140, 160, 210));
        jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jTabbedPane1.addTab("General UI", generalPanel);

        jTabbedPane1.addTab("Images", imagesPanel);

        jTabbedPane1.addTab("Background Images", bgImagesPanel);

        jTabbedPane1.addTab("Buttons", buttonPanel);

        jTabbedPane1.addTab("Colors", colorsPanel);
        jTabbedPane1.addTab("Fonts", fontsPanel);

        jTabbedPane1.addTab("Text", textPanel);
        jTabbedPane1.addTab("Scrollbars", scrollbarPanel);
        jTabbedPane1.addTab("Other", otherPanel);
	  try
	  {
	  ((javax.swing.JViewport)jTabbedPane1.getComponents()[0]).getView().setBackground(new java.awt.Color(140, 160, 210));
	  }
	  catch(Exception e){}

        //jTabbedPane1.addTab("Information Dialog", informationPanel);

        //jTabbedPane1.addTab("Error Dialog", errorPanel);

        ProjectLookAndFeelContent.add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        ProjectLookAndFeelContentContainer.add(ProjectLookAndFeelContent, java.awt.BorderLayout.CENTER);

        ProjectLookAndFeelRightMargin.setBackground(new java.awt.Color(140, 160, 210));
        ProjectLookAndFeelContentContainer.add(ProjectLookAndFeelRightMargin, java.awt.BorderLayout.EAST);

        ProjectLookAndFeelBottomMargin.setBackground(new java.awt.Color(140, 160, 210));
        ProjectLookAndFeelBottomMargin.setMaximumSize(new java.awt.Dimension(32767, 10));
        ProjectLookAndFeelContentContainer.add(ProjectLookAndFeelBottomMargin, java.awt.BorderLayout.SOUTH);

        add(ProjectLookAndFeelContentContainer, java.awt.BorderLayout.CENTER);

        ProjectLookAndFeelTopMarginContainer.setLayout(new java.awt.BorderLayout());

        ProjectLookAndFeelTopMarginContainer.setBackground(new java.awt.Color(140, 160, 210));
        add(ProjectLookAndFeelTopMarginContainer, java.awt.BorderLayout.NORTH);

    }//GEN-END:initComponents

    public synchronized void getDataUpdate()
    {
        try
        {
            generalPanel.getDataUpdate();
		imagesPanel.getDataUpdate();
		bgImagesPanel.getDataUpdate();
		buttonPanel.getDataUpdate();
		colorsPanel.getDataUpdate();
		fontsPanel.getDataUpdate();
		textPanel.getDataUpdate();
		scrollbarPanel.getDataUpdate();
		otherPanel.getDataUpdate();
		//informationPanel.getDataUpdate();
		//errorPanel.getDataUpdate();
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }
    
    public synchronized void setProjectData()
    {
        try
        {
            generalPanel.setProjectData();
            generalPanel.setParentComponent(this);
		imagesPanel.setProjectData();
		imagesPanel.setParentComponent(this);
		imagesPanel.setParentComp(getParentComp());
		bgImagesPanel.setProjectData();
		bgImagesPanel.setParentComponent(this);
		bgImagesPanel.setParentComp(getParentComp());
		generalPanel.setParentComponent(this);
		buttonPanel.setProjectData();
		buttonPanel.setParentComponent(this);
		buttonPanel.setParentComp(getParentComp());
		colorsPanel.setProjectData();
		colorsPanel.setParentComponent(this);
		fontsPanel.setProjectData();
		fontsPanel.setParentComponent(this);
		fontsPanel.setParentComp(getParentComp());
		textPanel.setProjectData();
		textPanel.setParentComponent(this);
		textPanel.setParentComp(getParentComp());
		scrollbarPanel.setProjectData();
		scrollbarPanel.setParentComponent(this);
		scrollbarPanel.setParentComp(getParentComp());
		otherPanel.setProjectData();
		otherPanel.setParentComponent(this);
		otherPanel.setParentComp(getParentComp());
		//informationPanel.setProjectData();
		//informationPanel.setParentComponent(this);
		//errorPanel.setProjectData();
		//errorPanel.setParentComponent(this);
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }        
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ProjectLookAndFeelBottomMargin;
    private javax.swing.JPanel ProjectLookAndFeelContent;
    private javax.swing.JPanel ProjectLookAndFeelContentContainer;
    private javax.swing.JPanel ProjectLookAndFeelLeftMargin;
    private javax.swing.JPanel ProjectLookAndFeelRightMargin;
    private javax.swing.JPanel ProjectLookAndFeelTopMarginContainer;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private GeneralLookAndFeelPanel generalPanel;
    private MainImagesPanel imagesPanel;
    //private ErrorPanel errorPanel;
    //private InformationPanel informationPanel;
    private BGImagesPanel bgImagesPanel;
    private MainButtonsPanel buttonPanel;
    private MainColorPanel colorsPanel;
    private MainFontPanel fontsPanel;
    private MainTextPanel textPanel;
    private ScrollbarPanel scrollbarPanel;
    private OtherPanel otherPanel;
    // End of variables declaration//GEN-END:variables
    
}
