/*
 * GetRespOptinProvider.java
 *
 * Created on April 23, 2004, 10:16 PM
 */

package com.trinity.ea.design.optin.provider.panels;
import com.trinity.ea.design.optin.provider.panels.GetRespProviderMainPanel;
import  com.trinity.ea.design.common.project.CreateGRAccount;
import com.trinity.ea.design.common.file.ProjectManager;
import javax.swing.ImageIcon;
import javax.swing.JSpinner;
import javax.swing.SpinnerNumberModel;
import java.util.HashMap;
import java.util.ArrayList;
import java.awt.Font;
import javax.swing.ButtonGroup;
import javax.swing.JPanel;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.JRadioButton;
import javax.swing.BoxLayout;
import java.awt.Dimension;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import java.text.ParseException;
import javax.swing.JFormattedTextField;
import javax.swing.SpinnerNumberModel;

/** 
 *
 * @author  aaronsc Trinity Software
 * Copyright ©2003-2004 Trinity Software. All rights reserved.
 */
public class GetRespOptinProvider extends javax.swing.JPanel 
{
private final ImageIcon topLeftBranchIcon = new javax.swing.ImageIcon(getClass().getResource("/images/tree/topleftbranch.png"));   
private final ImageIcon middleLeftBranchIcon = new javax.swing.ImageIcon(getClass().getResource("/images/tree/leftcenterbranch.png"));   
private final ImageIcon bottomLeftBranchIcon = new javax.swing.ImageIcon(getClass().getResource("/images/tree/bottomleftbranch.png"));   
private final ImageIcon middleLeftStraightLineBranchIcon = new javax.swing.ImageIcon(getClass().getResource("/images/tree/leftstraightlinebranch_gray.png"));   
private final ImageIcon middleLeftExpandedBranchIcon = new javax.swing.ImageIcon(getClass().getResource("/images/tree/leftcenterbranchminus_gray.png"));   
private final ImageIcon middleLeftCollapsedBranchIcon = new javax.swing.ImageIcon(getClass().getResource("/images/tree/leftcenterbranchplus_gray.png"));   
private final ImageIcon bottomLeftExpandedBranchIcon = new javax.swing.ImageIcon(getClass().getResource("/images/tree/bottomleftbranchminus_gray.png"));   
private final ImageIcon bottomLeftCollapsedBranchIcon = new javax.swing.ImageIcon(getClass().getResource("/images/tree/bottomleftbranchplus_gray.png"));   
 
 
 /** Creates new form GetRespOptinProvider */
    public GetRespOptinProvider() {
        initComponents();
        setProjectData();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        adTrackingButtonGroup = new javax.swing.ButtonGroup();
        followUpMessagesButtonGroup = new javax.swing.ButtonGroup();
        ListNamePanel = new javax.swing.JPanel();
        lFiller15 = new javax.swing.JLabel();
        lFiller18 = new javax.swing.JLabel();
        lVendorName1 = new javax.swing.JLabel();
        lFiller16 = new javax.swing.JLabel();
        tfAutoResponderListName = new javax.swing.JTextField();
        lFiller17 = new javax.swing.JLabel();
        AdTrackerPanel = new javax.swing.JPanel();
        AdTrackingYesNoPanel = new javax.swing.JPanel();
        AdTrackerBranchImage = new javax.swing.JLabel();
        lFiller19 = new javax.swing.JLabel();
        lSoftwareTitle1 = new javax.swing.JLabel();
        radioAdTrackingYes = new javax.swing.JRadioButton();
        radioAdTrackingNo = new javax.swing.JRadioButton();
        lFiller13 = new javax.swing.JLabel();
        lFiller14 = new javax.swing.JLabel();
        AdTrackerIdentificationPanel = new javax.swing.JPanel();
        lFiller22 = new javax.swing.JLabel();
        lFiller27 = new javax.swing.JLabel();
        lFiller21 = new javax.swing.JLabel();
        lProductInfoURL1 = new javax.swing.JLabel();
        spinMessageNumber = new javax.swing.JSpinner();
        lFiller7 = new javax.swing.JLabel();
        lFiller6 = new javax.swing.JLabel();
        AutoResponsePanel = new javax.swing.JPanel();
        AutoResponseYesNoPanel = new javax.swing.JPanel();
        AutoResponseBranchImage = new javax.swing.JLabel();
        lFiller23 = new javax.swing.JLabel();
        lProductInfoURL = new javax.swing.JLabel();
        radioFollowUpMessagesYes = new javax.swing.JRadioButton();
        radioFollowUpMessagesNo = new javax.swing.JRadioButton();
        lFiller2 = new javax.swing.JLabel();
        lFiller4 = new javax.swing.JLabel();
        AutoResponseMessageNumber = new javax.swing.JPanel();
        lFiller24 = new javax.swing.JLabel();
        lFiller28 = new javax.swing.JLabel();
        lFiller25 = new javax.swing.JLabel();
        lProductInfoURL2 = new javax.swing.JLabel();
        tfAdCatagory = new javax.swing.JTextField();
        lFiller9 = new javax.swing.JLabel();
        NewAccountButtonPanel = new javax.swing.JPanel();
        btnNewAccount = new javax.swing.JButton();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        ListNamePanel.setLayout(new javax.swing.BoxLayout(ListNamePanel, javax.swing.BoxLayout.X_AXIS));

        ListNamePanel.setMaximumSize(new java.awt.Dimension(2147483647, 26));
        ListNamePanel.setMinimumSize(new java.awt.Dimension(600, 26));
        ListNamePanel.setPreferredSize(new java.awt.Dimension(800, 26));
        lFiller15.setIcon(topLeftBranchIcon);
        lFiller15.setText("   ");
        lFiller15.setMaximumSize(new java.awt.Dimension(20, 25));
        lFiller15.setMinimumSize(new java.awt.Dimension(20, 25));
        lFiller15.setPreferredSize(new java.awt.Dimension(20, 25));
        ListNamePanel.add(lFiller15);

        lFiller18.setMaximumSize(new java.awt.Dimension(5, 15));
        lFiller18.setMinimumSize(new java.awt.Dimension(5, 16));
        lFiller18.setPreferredSize(new java.awt.Dimension(5, 16));
        ListNamePanel.add(lFiller18);

        lVendorName1.setFont(new java.awt.Font("Arial", 0, 12));
        lVendorName1.setText("Smart Responder name:");
        lVendorName1.setMaximumSize(new java.awt.Dimension(200, 15));
        lVendorName1.setMinimumSize(new java.awt.Dimension(200, 15));
        lVendorName1.setPreferredSize(new java.awt.Dimension(200, 15));
        lVendorName1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lVendorName1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lVendorName1MouseExited(evt);
            }
        });

        ListNamePanel.add(lVendorName1);

        lFiller16.setText("   ");
        lFiller16.setMaximumSize(new java.awt.Dimension(10, 15));
        lFiller16.setMinimumSize(new java.awt.Dimension(10, 16));
        lFiller16.setPreferredSize(new java.awt.Dimension(10, 16));
        ListNamePanel.add(lFiller16);

        tfAutoResponderListName.setFont(new java.awt.Font("Arial", 0, 12));
        tfAutoResponderListName.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tfAutoResponderListName.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        tfAutoResponderListName.setText("responder_name");
        tfAutoResponderListName.setMaximumSize(new java.awt.Dimension(160, 20));
        tfAutoResponderListName.setMinimumSize(new java.awt.Dimension(160, 20));
        tfAutoResponderListName.setPreferredSize(new java.awt.Dimension(160, 20));
        tfAutoResponderListName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tfAutoResponderListNameMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tfAutoResponderListNameMouseExited(evt);
            }
        });

        ListNamePanel.add(tfAutoResponderListName);

        lFiller17.setText("   ");
        lFiller17.setMaximumSize(new java.awt.Dimension(15, 15));
        lFiller17.setMinimumSize(new java.awt.Dimension(15, 16));
        lFiller17.setPreferredSize(new java.awt.Dimension(15, 16));
        ListNamePanel.add(lFiller17);

        add(ListNamePanel);

        AdTrackerPanel.setLayout(new javax.swing.BoxLayout(AdTrackerPanel, javax.swing.BoxLayout.Y_AXIS));

        AdTrackerPanel.setMaximumSize(new java.awt.Dimension(2147483647, 52));
        AdTrackerPanel.setMinimumSize(new java.awt.Dimension(600, 52));
        AdTrackerPanel.setPreferredSize(new java.awt.Dimension(800, 52));
        AdTrackingYesNoPanel.setLayout(new javax.swing.BoxLayout(AdTrackingYesNoPanel, javax.swing.BoxLayout.X_AXIS));

        AdTrackingYesNoPanel.setMaximumSize(new java.awt.Dimension(2147483647, 26));
        AdTrackingYesNoPanel.setMinimumSize(new java.awt.Dimension(600, 26));
        AdTrackingYesNoPanel.setPreferredSize(new java.awt.Dimension(800, 26));
        AdTrackerBranchImage.setIcon(middleLeftExpandedBranchIcon);
        AdTrackerBranchImage.setText("   ");
        AdTrackerBranchImage.setMaximumSize(new java.awt.Dimension(20, 25));
        AdTrackerBranchImage.setMinimumSize(new java.awt.Dimension(20, 25));
        AdTrackerBranchImage.setPreferredSize(new java.awt.Dimension(20, 25));
        AdTrackerBranchImage.setOpaque(true);
        AdTrackerBranchImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AdTrackerBranchImageMouseClicked(evt);
            }
        });

        AdTrackingYesNoPanel.add(AdTrackerBranchImage);

        lFiller19.setMaximumSize(new java.awt.Dimension(5, 15));
        lFiller19.setMinimumSize(new java.awt.Dimension(5, 16));
        lFiller19.setPreferredSize(new java.awt.Dimension(5, 16));
        lFiller19.setOpaque(true);
        AdTrackingYesNoPanel.add(lFiller19);

        lSoftwareTitle1.setFont(new java.awt.Font("Arial", 0, 12));
        lSoftwareTitle1.setText("Incorporate the Prospect Tracking feature?");
        lSoftwareTitle1.setMaximumSize(new java.awt.Dimension(290, 15));
        lSoftwareTitle1.setMinimumSize(new java.awt.Dimension(290, 15));
        lSoftwareTitle1.setPreferredSize(new java.awt.Dimension(290, 15));
        lSoftwareTitle1.setOpaque(true);
        lSoftwareTitle1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lSoftwareTitle1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lSoftwareTitle1MouseExited(evt);
            }
        });

        AdTrackingYesNoPanel.add(lSoftwareTitle1);

        radioAdTrackingYes.setFont(new java.awt.Font("Arial", 1, 12));
        radioAdTrackingYes.setText("Yes");
        adTrackingButtonGroup.add(radioAdTrackingYes);
        radioAdTrackingYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioAdTrackingYesActionPerformed(evt);
            }
        });
        radioAdTrackingYes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                radioAdTrackingYesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                radioAdTrackingYesMouseExited(evt);
            }
        });

        AdTrackingYesNoPanel.add(radioAdTrackingYes);

        radioAdTrackingNo.setFont(new java.awt.Font("Arial", 1, 12));
        radioAdTrackingNo.setSelected(true);
        radioAdTrackingNo.setText("No");
        adTrackingButtonGroup.add(radioAdTrackingNo);
        radioAdTrackingNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioAdTrackingNoActionPerformed(evt);
            }
        });
        radioAdTrackingNo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                radioAdTrackingNoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                radioAdTrackingNoMouseExited(evt);
            }
        });

        AdTrackingYesNoPanel.add(radioAdTrackingNo);

        lFiller13.setText("   ");
        lFiller13.setMaximumSize(new java.awt.Dimension(300, 15));
        lFiller13.setMinimumSize(new java.awt.Dimension(10, 16));
        lFiller13.setPreferredSize(new java.awt.Dimension(10, 16));
        lFiller13.setOpaque(true);
        AdTrackingYesNoPanel.add(lFiller13);

        lFiller14.setText("   ");
        lFiller14.setMaximumSize(new java.awt.Dimension(15, 15));
        lFiller14.setMinimumSize(new java.awt.Dimension(15, 16));
        lFiller14.setPreferredSize(new java.awt.Dimension(15, 16));
        lFiller14.setOpaque(true);
        AdTrackingYesNoPanel.add(lFiller14);

        AdTrackerPanel.add(AdTrackingYesNoPanel);

        AdTrackerIdentificationPanel.setLayout(new javax.swing.BoxLayout(AdTrackerIdentificationPanel, javax.swing.BoxLayout.X_AXIS));

        AdTrackerIdentificationPanel.setMaximumSize(new java.awt.Dimension(2147483647, 26));
        AdTrackerIdentificationPanel.setMinimumSize(new java.awt.Dimension(600, 26));
        AdTrackerIdentificationPanel.setPreferredSize(new java.awt.Dimension(800, 26));
        lFiller22.setIcon(middleLeftStraightLineBranchIcon);
        lFiller22.setText("   ");
        lFiller22.setMaximumSize(new java.awt.Dimension(20, 25));
        lFiller22.setMinimumSize(new java.awt.Dimension(20, 25));
        lFiller22.setPreferredSize(new java.awt.Dimension(20, 25));
        lFiller22.setOpaque(true);
        AdTrackerIdentificationPanel.add(lFiller22);

        lFiller27.setIcon(bottomLeftBranchIcon);
        lFiller27.setText("   ");
        lFiller27.setMaximumSize(new java.awt.Dimension(20, 25));
        lFiller27.setMinimumSize(new java.awt.Dimension(20, 25));
        lFiller27.setPreferredSize(new java.awt.Dimension(20, 25));
        lFiller27.setOpaque(true);
        AdTrackerIdentificationPanel.add(lFiller27);

        lFiller21.setMaximumSize(new java.awt.Dimension(5, 15));
        lFiller21.setMinimumSize(new java.awt.Dimension(5, 16));
        lFiller21.setPreferredSize(new java.awt.Dimension(5, 16));
        lFiller21.setOpaque(true);
        AdTrackerIdentificationPanel.add(lFiller21);

        lProductInfoURL1.setFont(new java.awt.Font("Arial", 0, 12));
        lProductInfoURL1.setText("Tracking Number (0 to 999): ");
        lProductInfoURL1.setMaximumSize(new java.awt.Dimension(190, 15));
        lProductInfoURL1.setMinimumSize(new java.awt.Dimension(190, 15));
        lProductInfoURL1.setPreferredSize(new java.awt.Dimension(190, 15));
        lProductInfoURL1.setOpaque(true);
        lProductInfoURL1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lProductInfoURL1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lProductInfoURL1MouseExited(evt);
            }
        });

        AdTrackerIdentificationPanel.add(lProductInfoURL1);

        spinMessageNumber.setMaximumSize(new java.awt.Dimension(40, 20));
        spinMessageNumber.setMinimumSize(new java.awt.Dimension(40, 20));
        spinMessageNumber.setPreferredSize(new java.awt.Dimension(40, 20));
        spinMessageNumber.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                spinMessageNumberMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                spinMessageNumberMouseExited(evt);
            }
        });

        AdTrackerIdentificationPanel.add(spinMessageNumber);

        lFiller7.setText("   ");
        lFiller7.setMaximumSize(new java.awt.Dimension(15, 15));
        lFiller7.setMinimumSize(new java.awt.Dimension(15, 16));
        lFiller7.setPreferredSize(new java.awt.Dimension(15, 16));
        lFiller7.setOpaque(true);
        AdTrackerIdentificationPanel.add(lFiller7);

        lFiller6.setText("   ");
        lFiller6.setMaximumSize(new java.awt.Dimension(41, 16));
        lFiller6.setMinimumSize(new java.awt.Dimension(41, 16));
        lFiller6.setPreferredSize(new java.awt.Dimension(41, 16));
        lFiller6.setOpaque(true);
        AdTrackerIdentificationPanel.add(lFiller6);

        AdTrackerPanel.add(AdTrackerIdentificationPanel);

        add(AdTrackerPanel);

        AutoResponsePanel.setLayout(new javax.swing.BoxLayout(AutoResponsePanel, javax.swing.BoxLayout.Y_AXIS));

        AutoResponseYesNoPanel.setLayout(new javax.swing.BoxLayout(AutoResponseYesNoPanel, javax.swing.BoxLayout.X_AXIS));

        AutoResponseYesNoPanel.setMaximumSize(new java.awt.Dimension(2147483647, 26));
        AutoResponseYesNoPanel.setMinimumSize(new java.awt.Dimension(600, 26));
        AutoResponseYesNoPanel.setPreferredSize(new java.awt.Dimension(800, 26));
        AutoResponseBranchImage.setIcon(bottomLeftExpandedBranchIcon);
        AutoResponseBranchImage.setText("   ");
        AutoResponseBranchImage.setMaximumSize(new java.awt.Dimension(20, 25));
        AutoResponseBranchImage.setMinimumSize(new java.awt.Dimension(20, 25));
        AutoResponseBranchImage.setPreferredSize(new java.awt.Dimension(20, 25));
        AutoResponseBranchImage.setOpaque(true);
        AutoResponseBranchImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AutoResponseBranchImageMouseClicked(evt);
            }
        });

        AutoResponseYesNoPanel.add(AutoResponseBranchImage);

        lFiller23.setMaximumSize(new java.awt.Dimension(5, 15));
        lFiller23.setMinimumSize(new java.awt.Dimension(5, 16));
        lFiller23.setPreferredSize(new java.awt.Dimension(5, 16));
        AutoResponseYesNoPanel.add(lFiller23);

        lProductInfoURL.setFont(new java.awt.Font("Arial", 0, 12));
        lProductInfoURL.setText("Would you like to add a \"misc\" value? ");
        lProductInfoURL.setMaximumSize(new java.awt.Dimension(290, 15));
        lProductInfoURL.setMinimumSize(new java.awt.Dimension(290, 15));
        lProductInfoURL.setPreferredSize(new java.awt.Dimension(290, 15));
        lProductInfoURL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lProductInfoURLMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lProductInfoURLMouseExited(evt);
            }
        });

        AutoResponseYesNoPanel.add(lProductInfoURL);

        radioFollowUpMessagesYes.setFont(new java.awt.Font("Arial", 1, 12));
        radioFollowUpMessagesYes.setText("Yes");
        followUpMessagesButtonGroup.add(radioFollowUpMessagesYes);
        radioFollowUpMessagesYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioFollowUpMessagesYesActionPerformed(evt);
            }
        });
        radioFollowUpMessagesYes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                radioFollowUpMessagesYesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                radioFollowUpMessagesYesMouseExited(evt);
            }
        });

        AutoResponseYesNoPanel.add(radioFollowUpMessagesYes);

        radioFollowUpMessagesNo.setFont(new java.awt.Font("Arial", 1, 12));
        radioFollowUpMessagesNo.setSelected(true);
        radioFollowUpMessagesNo.setText("No");
        followUpMessagesButtonGroup.add(radioFollowUpMessagesNo);
        radioFollowUpMessagesNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioFollowUpMessagesNoActionPerformed(evt);
            }
        });
        radioFollowUpMessagesNo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                radioFollowUpMessagesNoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                radioFollowUpMessagesNoMouseExited(evt);
            }
        });

        AutoResponseYesNoPanel.add(radioFollowUpMessagesNo);

        lFiller2.setText("   ");
        lFiller2.setMaximumSize(new java.awt.Dimension(300, 15));
        lFiller2.setMinimumSize(new java.awt.Dimension(10, 16));
        lFiller2.setPreferredSize(new java.awt.Dimension(10, 16));
        AutoResponseYesNoPanel.add(lFiller2);

        lFiller4.setText("   ");
        lFiller4.setMaximumSize(new java.awt.Dimension(15, 15));
        lFiller4.setMinimumSize(new java.awt.Dimension(15, 16));
        lFiller4.setPreferredSize(new java.awt.Dimension(15, 16));
        AutoResponseYesNoPanel.add(lFiller4);

        AutoResponsePanel.add(AutoResponseYesNoPanel);

        AutoResponseMessageNumber.setLayout(new javax.swing.BoxLayout(AutoResponseMessageNumber, javax.swing.BoxLayout.X_AXIS));

        AutoResponseMessageNumber.setMaximumSize(new java.awt.Dimension(2147483647, 26));
        AutoResponseMessageNumber.setMinimumSize(new java.awt.Dimension(600, 26));
        AutoResponseMessageNumber.setPreferredSize(new java.awt.Dimension(800, 26));
        lFiller24.setText("   ");
        lFiller24.setMaximumSize(new java.awt.Dimension(20, 25));
        lFiller24.setMinimumSize(new java.awt.Dimension(20, 25));
        lFiller24.setPreferredSize(new java.awt.Dimension(20, 25));
        lFiller24.setOpaque(true);
        AutoResponseMessageNumber.add(lFiller24);

        lFiller28.setIcon(bottomLeftBranchIcon);
        lFiller28.setText("   ");
        lFiller28.setMaximumSize(new java.awt.Dimension(20, 25));
        lFiller28.setMinimumSize(new java.awt.Dimension(20, 25));
        lFiller28.setPreferredSize(new java.awt.Dimension(20, 25));
        lFiller28.setOpaque(true);
        AutoResponseMessageNumber.add(lFiller28);

        lFiller25.setMaximumSize(new java.awt.Dimension(5, 15));
        lFiller25.setMinimumSize(new java.awt.Dimension(5, 16));
        lFiller25.setPreferredSize(new java.awt.Dimension(5, 16));
        lFiller25.setOpaque(true);
        AutoResponseMessageNumber.add(lFiller25);

        lProductInfoURL2.setFont(new java.awt.Font("Arial", 0, 12));
        lProductInfoURL2.setText("\"misc\" value:");
        lProductInfoURL2.setMaximumSize(new java.awt.Dimension(190, 15));
        lProductInfoURL2.setMinimumSize(new java.awt.Dimension(190, 15));
        lProductInfoURL2.setPreferredSize(new java.awt.Dimension(190, 15));
        lProductInfoURL2.setOpaque(true);
        lProductInfoURL2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lProductInfoURL2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lProductInfoURL2MouseExited(evt);
            }
        });

        AutoResponseMessageNumber.add(lProductInfoURL2);

        tfAdCatagory.setFont(new java.awt.Font("Arial", 0, 12));
        tfAdCatagory.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tfAdCatagory.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        tfAdCatagory.setText("misc_info");
        tfAdCatagory.setMaximumSize(new java.awt.Dimension(160, 20));
        tfAdCatagory.setMinimumSize(new java.awt.Dimension(160, 20));
        tfAdCatagory.setPreferredSize(new java.awt.Dimension(160, 20));
        tfAdCatagory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tfAdCatagoryMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tfAdCatagoryMouseExited(evt);
            }
        });

        AutoResponseMessageNumber.add(tfAdCatagory);

        lFiller9.setText("   ");
        lFiller9.setMaximumSize(new java.awt.Dimension(300, 15));
        lFiller9.setMinimumSize(new java.awt.Dimension(10, 16));
        lFiller9.setPreferredSize(new java.awt.Dimension(10, 16));
        lFiller9.setOpaque(true);
        AutoResponseMessageNumber.add(lFiller9);

        AutoResponsePanel.add(AutoResponseMessageNumber);

        add(AutoResponsePanel);
        NewAccountButtonPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 13, 2));

        btnNewAccount.setText("Create New Account");
        btnNewAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewAccountActionPerformed(evt);
            }
        });
        btnNewAccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNewAccountMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNewAccountMouseExited(evt);
            }
        });
	  btnNewAccount.setMnemonic('C');
        NewAccountButtonPanel.add(btnNewAccount);

        add(NewAccountButtonPanel);

    }//GEN-END:initComponents

    private void btnNewAccountMouseExited(java.awt.event.MouseEvent evt) {
        setStatus("");
    }

    private void btnNewAccountMouseEntered(java.awt.event.MouseEvent evt) {
        setStatus("Create a free GetResponse account.");
    }

    private void btnNewAccountActionPerformed(java.awt.event.ActionEvent evt) {
        try
	  {
		String strLoginID = CreateGRAccount.showDialog(null);
		if(strLoginID!=null)
		{
			tfAutoResponderListName.setText(strLoginID);
		}
	  }
	  catch(Exception e)
	  {
		//e.printStackTrace();
	  }
    }

    private void tfAutoResponderListNameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfAutoResponderListNameMouseEntered
        // Add your handling code here:
    }//GEN-LAST:event_tfAutoResponderListNameMouseEntered

    private void tfAutoResponderListNameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfAutoResponderListNameMouseExited
        // Add your handling code here:
    }//GEN-LAST:event_tfAutoResponderListNameMouseExited

    private void lProductInfoURL2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lProductInfoURL2MouseExited
        setStatus("");
    }//GEN-LAST:event_lProductInfoURL2MouseExited

    private void lProductInfoURL2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lProductInfoURL2MouseEntered
        setStatus("Change the \"" + "tracking number" + "\" value to any tracking value you would like (20 char max).");
    }//GEN-LAST:event_lProductInfoURL2MouseEntered

    private void lProductInfoURLMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lProductInfoURLMouseExited
        setStatus("");
    }//GEN-LAST:event_lProductInfoURLMouseExited

    private void lProductInfoURLMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lProductInfoURLMouseEntered
        setStatus("Select Yes to add a \"misc\" value.");
    }//GEN-LAST:event_lProductInfoURLMouseEntered

    private void lProductInfoURL1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lProductInfoURL1MouseExited
        setStatus("");
    }//GEN-LAST:event_lProductInfoURL1MouseExited

    private void lProductInfoURL1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lProductInfoURL1MouseEntered
        setStatus("Change the \"" + tfAdCatagory.getText() + "\" value to any tracking value you specify (20 char max).");
    }//GEN-LAST:event_lProductInfoURL1MouseEntered

    private void lSoftwareTitle1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lSoftwareTitle1MouseExited
        setStatus("");
    }//GEN-LAST:event_lSoftwareTitle1MouseExited

    private void lSoftwareTitle1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lSoftwareTitle1MouseEntered
        setStatus("Select Yes to incorporate the prospect tracking feature.");
    }//GEN-LAST:event_lSoftwareTitle1MouseEntered

    private void lVendorName1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lVendorName1MouseExited
        setStatus("");
    }//GEN-LAST:event_lVendorName1MouseExited

    private void lVendorName1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lVendorName1MouseEntered
        setStatus("Specify the GetResponse Smart Autoresponder name.");
    }//GEN-LAST:event_lVendorName1MouseEntered

    private void spinMessageNumberMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_spinMessageNumberMouseExited
        setStatus("");
    }//GEN-LAST:event_spinMessageNumberMouseExited

    private void spinMessageNumberMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_spinMessageNumberMouseEntered
        setStatus("Specify the Prospect Tracking reference number.");
    }//GEN-LAST:event_spinMessageNumberMouseEntered

    private void radioFollowUpMessagesNoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radioFollowUpMessagesNoMouseExited
        setStatus("");
    }//GEN-LAST:event_radioFollowUpMessagesNoMouseExited

    private void radioFollowUpMessagesNoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radioFollowUpMessagesNoMouseEntered
        setStatus("Select No if a \"misc\" value is not configured.");
    }//GEN-LAST:event_radioFollowUpMessagesNoMouseEntered

    private void radioFollowUpMessagesYesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radioFollowUpMessagesYesMouseExited
        setStatus("");
    }//GEN-LAST:event_radioFollowUpMessagesYesMouseExited

    private void radioFollowUpMessagesYesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radioFollowUpMessagesYesMouseEntered
        setStatus("Select Yes to configure a \"misc\" value.");
    }//GEN-LAST:event_radioFollowUpMessagesYesMouseEntered

    private void radioAdTrackingYesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radioAdTrackingYesMouseExited
        setStatus(""); 
    }//GEN-LAST:event_radioAdTrackingYesMouseExited

    private void radioAdTrackingYesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radioAdTrackingYesMouseEntered
        setStatus("Select Yes to incorporate the prospect tracking feature.");
    }//GEN-LAST:event_radioAdTrackingYesMouseEntered

    private void radioAdTrackingNoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radioAdTrackingNoMouseExited
        setStatus("");
    }//GEN-LAST:event_radioAdTrackingNoMouseExited

    private void radioAdTrackingNoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radioAdTrackingNoMouseEntered
        setStatus("Select No to disable the prospect tracking feature.");
    }//GEN-LAST:event_radioAdTrackingNoMouseEntered

    private void tfAdCatagoryMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfAdCatagoryMouseExited
        setStatus("");
    }//GEN-LAST:event_tfAdCatagoryMouseExited

    private void tfAdCatagoryMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfAdCatagoryMouseEntered
        setStatus("Change the \"" + tfAdCatagory.getText() + "\" value to any tracking value you would like (20 char max).");
    }//GEN-LAST:event_tfAdCatagoryMouseEntered

    private void AutoResponderListNameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AutoResponderListNameMouseExited
        setStatus("");
    }//GEN-LAST:event_AutoResponderListNameMouseExited
 
    private void AutoResponderListNameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AutoResponderListNameMouseEntered
	setStatus("Specify the GetResponse Smart Autoresponder name.");
    }//GEN-LAST:event_AutoResponderListNameMouseEntered

    private void AutoResponseBranchImageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AutoResponseBranchImageMouseClicked
        if(autoResponseBranchIsExpanded==1)
        {
            collapseAutoResponse();
        }
        else if(autoResponseBranchIsExpanded==2)
        {
            expandAutoResponse();
        }
    }//GEN-LAST:event_AutoResponseBranchImageMouseClicked

    private void radioFollowUpMessagesNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioFollowUpMessagesNoActionPerformed
                   radioFollowUpMessagesYes.setSelected(false); 
                   radioFollowUpMessagesNo.setSelected(true); 
                   getDataUpdate();
                   setProjectData();
    }//GEN-LAST:event_radioFollowUpMessagesNoActionPerformed

    private void radioFollowUpMessagesYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioFollowUpMessagesYesActionPerformed
                   radioFollowUpMessagesYes.setSelected(true);  
                   radioFollowUpMessagesNo.setSelected(false); 
                   getDataUpdate();     
                   setProjectData();
    }//GEN-LAST:event_radioFollowUpMessagesYesActionPerformed

    private void radioAdTrackingNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioAdTrackingNoActionPerformed
               radioAdTrackingYes.setSelected(false);  
               radioAdTrackingNo.setSelected(true);   
               getDataUpdate();      
               setProjectData();
    }//GEN-LAST:event_radioAdTrackingNoActionPerformed

    private void radioAdTrackingYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioAdTrackingYesActionPerformed
               radioAdTrackingYes.setSelected(true);  
               radioAdTrackingNo.setSelected(false);
               getDataUpdate();  
               setProjectData();               
    }//GEN-LAST:event_radioAdTrackingYesActionPerformed

    private void AdTrackerBranchImageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdTrackerBranchImageMouseClicked
        if(adTrackingBranchIsExpanded==1)
        {
            collapseAdTracking();
        }
        else if(adTrackingBranchIsExpanded==2)
        {
            expandAdTracking();
        }
    }//GEN-LAST:event_AdTrackerBranchImageMouseClicked
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AdTrackerBranchImage;
    private javax.swing.JPanel AdTrackerIdentificationPanel;
    private javax.swing.JPanel AdTrackerPanel;
    private javax.swing.JPanel AdTrackingYesNoPanel;
    private javax.swing.JLabel AutoResponseBranchImage;
    private javax.swing.JPanel AutoResponseMessageNumber;
    private javax.swing.JPanel AutoResponsePanel;
    private javax.swing.JPanel AutoResponseYesNoPanel;
    private javax.swing.JPanel ListNamePanel;
    private javax.swing.ButtonGroup adTrackingButtonGroup;
    private javax.swing.ButtonGroup followUpMessagesButtonGroup;
    private javax.swing.JLabel lFiller13;
    private javax.swing.JLabel lFiller14;
    private javax.swing.JLabel lFiller15;
    private javax.swing.JLabel lFiller16;
    private javax.swing.JLabel lFiller17;
    private javax.swing.JLabel lFiller18;
    private javax.swing.JLabel lFiller19;
    private javax.swing.JLabel lFiller2;
    private javax.swing.JLabel lFiller21;
    private javax.swing.JLabel lFiller22;
    private javax.swing.JLabel lFiller23;
    private javax.swing.JLabel lFiller24;
    private javax.swing.JLabel lFiller25;
    private javax.swing.JLabel lFiller27;
    private javax.swing.JLabel lFiller28;
    private javax.swing.JLabel lFiller4;
    private javax.swing.JLabel lFiller6;
    private javax.swing.JLabel lFiller7;
    private javax.swing.JLabel lFiller9;
    private javax.swing.JLabel lProductInfoURL;
    private javax.swing.JLabel lProductInfoURL1;
    private javax.swing.JLabel lProductInfoURL2;
    private javax.swing.JLabel lSoftwareTitle1;
    private javax.swing.JLabel lVendorName1;
    private javax.swing.JRadioButton radioAdTrackingNo;
    private javax.swing.JRadioButton radioAdTrackingYes;
    private javax.swing.JRadioButton radioFollowUpMessagesNo;
    private javax.swing.JRadioButton radioFollowUpMessagesYes;
    private javax.swing.JSpinner spinMessageNumber;
    private javax.swing.JTextField tfAdCatagory;
    private javax.swing.JTextField tfAutoResponderListName;
    private javax.swing.JButton btnNewAccount;
    private javax.swing.JPanel NewAccountButtonPanel;

    // End of variables declaration//GEN-END:variables

    public void getDataUpdate()
    {
        try
        {
            ProjectManager.putTempNoFileWrite("optinFormActionURL", "http://www.getresponse.com/cgi-bin/add.cgi");
            ProjectManager.putTempNoFileWrite("optinFormRequestMethod", "POST");
            ProjectManager.putTempNoFileWrite("optinInputFullName", "category2");
            ProjectManager.putTempNoFileWrite("optinInputEMailAddress", "category3"); 
            //::: represents a comma in the Rules Properties File
            String getresptracking = "777";
		String miscInfo = "misc_info";
		SpinnerNumberModel sm = (SpinnerNumberModel)spinMessageNumber.getModel();
            getresptracking = String.valueOf(sm.getNumber().intValue());
            if(radioFollowUpMessagesYes.isSelected()==true)
            {
			miscInfo = tfAdCatagory.getText();
            }
		else if(radioFollowUpMessagesNo.isSelected()==true)
		{
			miscInfo = "misc_info";
		}
            if(radioAdTrackingNo.isSelected()==false)
            {
                ProjectManager.putTempNoFileWrite("optinInputHiddenNames", "category1,confirmation,error_page,misc,ref");
                ProjectManager.putTempNoFileWrite("optinInputHiddenValues",tfAutoResponderListName.getText() + ",,," + miscInfo + "," + getresptracking);                
            }        
            else if(radioAdTrackingNo.isSelected()==true)
            {
                ProjectManager.putTempNoFileWrite("optinInputHiddenNames", "category1,confirmation,error_page,misc,ref");
                ProjectManager.putTempNoFileWrite("optinInputHiddenValues",tfAutoResponderListName.getText() + ",,," + miscInfo + ",777");
            }
            ProjectManager.saveTempNow();
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }

    public void setProjectData()
    {
        Object[] inputNames = getStringArraysFromString(ProjectManager.get("optinInputHiddenNames"));
        Object[] inputValues = getStringArraysFromString(ProjectManager.get("optinInputHiddenValues"));
        HashMap theTempMap = new HashMap(inputNames.length);
        for(int i = 0;i<inputNames.length;i++)
        {
            theTempMap.put((String)inputNames[i], new Integer(i));
        }
        try
        {
           int intCategory1 = -1;
           int intConfirmation = -1;
           int intErrorPage = -1;
           int intMisc = -1;
           int intTracking = -1;
           boolean boolAdTracking = false;
           String strTrackerNumber = "1";
           if(theTempMap.get("category1")!=null)
           {
                intCategory1 = ((Integer)theTempMap.get("category1")).intValue();
           }
           if(theTempMap.get("confirmation")!=null)
           {
                intConfirmation = ((Integer)theTempMap.get("confirmation")).intValue();
           }
           if(theTempMap.get("error_page")!=null)
           {
                intErrorPage = ((Integer)theTempMap.get("error_page")).intValue();              
           } 
           if(theTempMap.get("misc")!=null)
           {
                intMisc = ((Integer)theTempMap.get("misc")).intValue();              
           } 
           if(theTempMap.get("ref")!=null)
           {
                intTracking = ((Integer)theTempMap.get("ref")).intValue();
           }
               if(intTracking != -1)
               {
                   String theRefString = (String)inputValues[intTracking];
                   if(theRefString.startsWith("00")==true)
                   {
                      theRefString = theRefString.substring(2,2);
                   }
                   else if(theRefString.startsWith("0")==true)
                   {
                      theRefString = theRefString.substring(1,2);                       
                   }                
                   
                   if(theRefString.equalsIgnoreCase("777")==true)
                   {
                    try
                    {
				if(radioAdTrackingYes.isSelected()==true)
				{
                       		radioAdTrackingYes.setSelected(true);
		       		spinMessageNumber.setModel(new SpinnerNumberModel(new Integer(777),new Integer(1),new Integer(999),new Integer(1)));
                       		radioAdTrackingNo.setSelected(false);                  
                       		expandAdTracking();
				}
				else if(radioAdTrackingNo.isSelected()==true)
				{
                       		radioAdTrackingYes.setSelected(false);
		       		spinMessageNumber.setModel(new SpinnerNumberModel(new Integer(777),new Integer(1),new Integer(999),new Integer(1)));
                       		radioAdTrackingNo.setSelected(true);                  
                       		collapseAdTracking();
				}
				else
				{
                       		radioAdTrackingYes.setSelected(false);
		       		spinMessageNumber.setModel(new SpinnerNumberModel(new Integer(777),new Integer(1),new Integer(999),new Integer(1)));
                       		radioAdTrackingNo.setSelected(true);                  
                       		collapseAdTracking();
			      }           
             	  }          
                    catch(Exception e)
                    {
                        e.printStackTrace();
                    } 
                   }
                   else
                   {
                        if(Integer.valueOf(theRefString).intValue() < 1000)
                        {		     	  
                                spinMessageNumber.setModel(new SpinnerNumberModel(Integer.valueOf(theRefString),new Integer(1),new Integer(999),new Integer(1)));
                        }
                        else
                        {
                                spinMessageNumber.setModel(new SpinnerNumberModel(Integer.valueOf(theRefString),new Integer(1),Integer.valueOf(strTrackerNumber),new Integer(1)));
                        }
                       radioAdTrackingYes.setSelected(true); 
                       radioAdTrackingNo.setSelected(false);                   
                       expandAdTracking();
                   }

               if(intCategory1!=-1)
               {
                    tfAutoResponderListName.setText((String)inputValues[intCategory1]);
               }
               if(intMisc != -1)
               {
                    tfAdCatagory.setText((String)inputValues[intMisc]);
               }
           }
           else
           {
               spinMessageNumber.setModel(new SpinnerNumberModel(new Integer(777),new Integer(1),new Integer(999),new Integer(1)));
               radioAdTrackingYes.setSelected(false);
               radioAdTrackingNo.setSelected(true);                      
               collapseAdTracking();                  
               if(intCategory1 != -1)
               {
                   tfAutoResponderListName.setText((String)inputValues[intCategory1]);
               }
            }
            if(intMisc != -1)
            {
			if(((String)inputValues[intMisc]).equalsIgnoreCase("misc_info")==true)
			{
                    try
                    {
				if(radioFollowUpMessagesYes.isSelected()==true)
				{
                       		radioFollowUpMessagesYes.setSelected(true); 
                       		radioFollowUpMessagesNo.setSelected(false);                    
                       		expandAutoResponse();
				}
				else if(radioFollowUpMessagesNo.isSelected()==true)
				{
                       		radioFollowUpMessagesYes.setSelected(false); 
                       		radioFollowUpMessagesNo.setSelected(true);                    
                       		collapseAutoResponse();
				}
				else
				{
                       		radioFollowUpMessagesYes.setSelected(false); 
                       		radioFollowUpMessagesNo.setSelected(true);                    
                       		collapseAutoResponse();
				}
            	    }          
                    catch(Exception e)
                    {
                        e.printStackTrace();
                    }
			}
			else
			{
                       radioFollowUpMessagesYes.setSelected(true); 
                       radioFollowUpMessagesNo.setSelected(false);                    
                       expandAutoResponse();
			}

			
			tfAdCatagory.setText((String)inputValues[intMisc]);
			  
            }
            else
            {
                    try
                    {
				if(radioFollowUpMessagesYes.isSelected()==true)
				{
                       		radioFollowUpMessagesYes.setSelected(true); 
                       		radioFollowUpMessagesNo.setSelected(false);                    
                       		expandAutoResponse();
                       		tfAdCatagory.setText("misc_info");
				}
				else if(radioFollowUpMessagesNo.isSelected()==true)
				{
                       		radioFollowUpMessagesYes.setSelected(false); 
                       		radioFollowUpMessagesNo.setSelected(true);                    
                       		collapseAutoResponse();
                       		tfAdCatagory.setText("misc_info");
				}
				else
				{
                       		radioFollowUpMessagesYes.setSelected(false); 
                       		radioFollowUpMessagesNo.setSelected(true);                    
                       		collapseAutoResponse();
                       		tfAdCatagory.setText("misc_info");
				}
            	    }          
                    catch(Exception e)
                    {
                        e.printStackTrace();
                    }
        	}
	  }
        catch(Exception e)
        {
             e.printStackTrace();
        }
    }
    
    private int autoResponseBranchIsExpanded = 0;
    private int adTrackingBranchIsExpanded = 0;   
    
    private void defaultBranchAutoResponse()
    {
        autoResponseBranchIsExpanded = 0;
        AutoResponsePanel.setMaximumSize(new java.awt.Dimension(2147483647, 26));
        AutoResponsePanel.setMinimumSize(new java.awt.Dimension(600, 26));
        AutoResponsePanel.setPreferredSize(new java.awt.Dimension(800, 26));
        AutoResponseBranchImage.setIcon(bottomLeftBranchIcon);
        AutoResponsePanel.removeAll();
        AutoResponsePanel.add(AutoResponseYesNoPanel);       
    }
    
    private void collapseAutoResponse()
    {
        autoResponseBranchIsExpanded = 2;
        AutoResponsePanel.setMaximumSize(new java.awt.Dimension(2147483647, 26));
        AutoResponsePanel.setMinimumSize(new java.awt.Dimension(600, 26));
        AutoResponsePanel.setPreferredSize(new java.awt.Dimension(800, 26));
        AutoResponseBranchImage.setIcon(bottomLeftCollapsedBranchIcon);
        AutoResponsePanel.removeAll();
        AutoResponsePanel.add(AutoResponseYesNoPanel);
    }
    
    private void expandAutoResponse()
    {
        autoResponseBranchIsExpanded = 1;
        AutoResponsePanel.setMaximumSize(new java.awt.Dimension(2147483647, 52));
        AutoResponsePanel.setMinimumSize(new java.awt.Dimension(600, 52));
        AutoResponsePanel.setPreferredSize(new java.awt.Dimension(800, 52));  
        AutoResponseBranchImage.setIcon(bottomLeftExpandedBranchIcon);
        AutoResponsePanel.removeAll();
        AutoResponsePanel.add(AutoResponseYesNoPanel);        
        AutoResponsePanel.add(AutoResponseMessageNumber);
    }   
    
    private void defaultBranchAdTracking()
    {
        adTrackingBranchIsExpanded = 0; 
        AdTrackerPanel.setMaximumSize(new java.awt.Dimension(2147483647, 26));
        AdTrackerPanel.setMinimumSize(new java.awt.Dimension(600, 26));
        AdTrackerPanel.setPreferredSize(new java.awt.Dimension(800, 26));  
        AdTrackerBranchImage.setIcon(middleLeftBranchIcon);    
        AdTrackerPanel.removeAll();
        AdTrackerPanel.add(AdTrackingYesNoPanel);
    }    
    
    private void collapseAdTracking()
    {
        adTrackingBranchIsExpanded = 2; 
        AdTrackerPanel.setMaximumSize(new java.awt.Dimension(2147483647, 26));
        AdTrackerPanel.setMinimumSize(new java.awt.Dimension(600, 26));
        AdTrackerPanel.setPreferredSize(new java.awt.Dimension(800, 26));  
        AdTrackerBranchImage.setIcon(middleLeftCollapsedBranchIcon); 
        AdTrackerPanel.removeAll();        
        AdTrackerPanel.add(AdTrackingYesNoPanel);
    }
    
    private void expandAdTracking()
    {
        adTrackingBranchIsExpanded = 1; 
        AdTrackerPanel.setMaximumSize(new java.awt.Dimension(2147483647, 52));
        AdTrackerPanel.setMinimumSize(new java.awt.Dimension(600, 52));
        AdTrackerPanel.setPreferredSize(new java.awt.Dimension(800, 52)); 
        AdTrackerBranchImage.setIcon(middleLeftExpandedBranchIcon); 
        AdTrackerPanel.removeAll();        
        AdTrackerPanel.add(AdTrackingYesNoPanel);
        AdTrackerPanel.add(AdTrackerIdentificationPanel);       
    } 
      
    private static Object[] getStringArraysFromString(String textArrayString)
    {
        ArrayList aryList = new ArrayList();
        String tempString = "";
        try
        {
            while(textArrayString.indexOf(",")!=-1)
            {
                tempString = textArrayString.substring(0,textArrayString.indexOf(","));
                textArrayString = textArrayString.substring(textArrayString.indexOf(",") + 1);
                aryList.add(tempString);
            }
            aryList.add(textArrayString);
            aryList.trimToSize();
        }
        catch(NullPointerException e)
        {
         
        }

        return aryList.toArray();
    }  
    
    private String getCommaSeparatedStringValues(String strToUpdate)
    {
	 return strToUpdate.replaceAll(":::",",");
    }   
    GetRespProviderMainPanel parentObj = null;
    public void setMasterStatusController(Object parentObject)
    {
        parentObj = (GetRespProviderMainPanel)parentObject;
    }
    private void setStatus(String statusMessage)
    {
        try
        {
            parentObj.setStatus(statusMessage);
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }
    
}
