/*
 * ProjectLocalesPanel.java
 *
 * Created on December 16, 2003, 4:55 PM
 */

package com.trinity.ea.design.project.locales;
import com.trinity.ea.design.common.panel.EAPanel;
import com.trinity.ea.design.common.panel.EAMasterControlPanel;
import com.trinity.ea.design.common.panel.EAPropertiesPanel;
import com.trinity.ea.design.common.panel.EAListItem;
import com.trinity.ea.design.common.panel.EAListItemContent;
import com.trinity.ea.design.common.file.ProjectManager;
import com.trinity.ea.design.rules.builder.DesignerRuleBuilder;
import com.trinity.ea.design.common.localechooser.LocaleSelector;
import com.trinity.ea.design.common.util.ZipBuilder;
import java.awt.event.ActionEvent;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.ArrayList;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JPanel;
import javax.swing.ImageIcon;
import javax.swing.Icon;
import javax.swing.BoxLayout;
import java.awt.FlowLayout;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Color;
import java.awt.Font;
import java.util.HashMap;
import java.io.File;
import java.net.URL;
import java.net.MalformedURLException;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.FileOutputStream;
import java.io.FileInputStream;

/**
 *
 * @author  aaronsc Trinity Software
 * Copyright ©2003-2004 Trinity Software. All rights reserved.
 */
public class ProjectLocalesPanel extends EAMasterControlPanel {
    private Color backgroundColor = new java.awt.Color(140, 160, 210);
    private Color borderColor1 = new java.awt.Color(140, 160, 210);
    private Color borderColor2 = new java.awt.Color(140, 160, 210);
    private Color rowColor = new java.awt.Color(220, 225, 240);
    private Color rowBorderColor = new java.awt.Color(255, 255, 255);
    private Color tabColor = new java.awt.Color(255, 255, 255);
    private Color tabBorderColor = new java.awt.Color(0, 0, 0);
    private Icon theActionRowIcon = new javax.swing.ImageIcon(getClass().getResource("/images/lgpl/locale.png"));
    private int rowHeight = 25;
    private int defActionLabelWidth = 260;
    private int defActionDataWidth = 125;
    private int defActionDataValueWidth = 150;    
    private static String strMessageFileName = "lib/locales/MessagesBundle.properties"; 

    /** Set the message filename. */
    public static void setFileName(String strFileName)
    {
        strMessageFileName = strFileName;
    }
    
    /** Return the Message File filename. Default Message filename is MessagesBundle.properties */
    public static String getFileName()
    {
        return strMessageFileName;
    }

    /** Creates new form ProjectLocalesPanel */
    public ProjectLocalesPanel() {
        initComponents();
	  setProjectData();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        ProjectLocalesCenterPanel = new javax.swing.JPanel();
        ProjectLocalesCenterPanelScrollPane = new javax.swing.JScrollPane();
        LocalesCenterPanelScrollPaneContentPanel = new javax.swing.JPanel();
        LocalesCenterPanelScrollPaneLanguageID = new javax.swing.JScrollPane();
        LocalesJTreeLanguages = new javax.swing.JTree();
        LocalesCenterPanelScrollPaneLanguageEnabled = new javax.swing.JScrollPane();
        LocalesEnablesLocalesCheckboxPanel = new javax.swing.JPanel();
        ProjectLocalesNorthPanel = new javax.swing.JPanel();
        ProjectLocalesNorthPanelTopPanel = new javax.swing.JPanel();
        ProjectLocalesNorthPanelBottomPanel = new javax.swing.JPanel();
        ProjectLocalesSouthPanel = new javax.swing.JPanel();
        //LocalesSelectAllButton = new javax.swing.JButton();
        //LocalesDeselectAllButton = new javax.swing.JButton();
        ProjectLocalesLeftPanel = new javax.swing.JPanel();
        ProjectLocalesRightPanel = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        setBackground(new java.awt.Color(140, 160, 210));
        ProjectLocalesCenterPanel.setLayout(new java.awt.BorderLayout());
//
theEAProperties = new EAPropertiesPanel(getActionsEAListItems(),rowColor, rowBorderColor, backgroundColor, rowHeight);
//
theEAProperties.setMasterControlPanel(this);
//	  
	try
	{
	  theEAProperties.setDescriptorPanelWidth(149);
	  //allowURLChangesPanel.setBackgroundColor(backgroundColor);
	  //allowURLChangesPanel.setText("Allow URL changes via messages");
	  theEAProperties.setHeaderText("Locale List");
	  theEAProperties.setDescriptorText("Configure Languages");
	  theEAProperties.setHeaderTextAndWidth("Locale List", 275, "Enabled", 110, "Pre-Translated", 150);
	  theEAProperties.setAddEALIOnAddEnabled(true);
	  theEAProperties.setAddButtonVisible(true);
	  theEAProperties.setEditButtonVisible(false);
	  theEAProperties.setRemoveButtonVisible(true);
		try
		{
             			if(DesignerRuleBuilder.get("prjLocalesEnabled")!=null)
             			{
                				if(DesignerRuleBuilder.get("prjLocalesEnabled").equalsIgnoreCase("true")==true)
                 				{
						}
						else
						{
	  theEAProperties.setAddButtonEnabled(false);
	  theEAProperties.setEditButtonEnabled(false);
	  theEAProperties.setRemoveButtonEnabled(false);
						}
					}
					else
					{
	  theEAProperties.setAddButtonEnabled(false);
	  theEAProperties.setEditButtonEnabled(false);
	  theEAProperties.setRemoveButtonEnabled(false);
					}
		}
		catch(Exception e)
		{
			e.printStackTrace();
		}
	  theEAProperties.setAddButtonText("Add Locale");
	  theEAProperties.setEditButtonText("Edit Locale");
	  theEAProperties.setRemoveButtonText("Remove Locale");
	  theEAProperties.setPreviewButtonVisible(false);
	  theEAProperties.setConfigurationWizardButtonVisible(false);
	  theEAProperties.setSelectedIndex(0);
	  theEAProperties.setLabelWidth(defActionLabelWidth);
	  theEAProperties.setDataWidth(defActionDataWidth);
	  theEAProperties.setDefaultRowIcon(theActionRowIcon);
	  theEAProperties.setBackgroundColor(backgroundColor);
	  theEAProperties.setTabColor(tabColor);
	  theEAProperties.setTabBorderColor(tabBorderColor);
	  theEAProperties.setParentComponent(this);
	  EAListItem eaListItemObj = theEAProperties.getSelectedEAListItem();
	  eaListItemObj.setSelectedMode();
	}
	catch(Exception e)
	{
		e.printStackTrace();
	}

        ProjectLocalesCenterPanel.setBackground(new java.awt.Color(220, 225, 240));
        ProjectLocalesCenterPanelScrollPane.setBackground(new java.awt.Color(220, 225, 240));
        ProjectLocalesCenterPanelScrollPane.setBorder(null);
        ProjectLocalesCenterPanelScrollPane.setHorizontalScrollBarPolicy(javax.swing.JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
        ProjectLocalesCenterPanelScrollPane.setVerticalScrollBarPolicy(javax.swing.JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);
        LocalesCenterPanelScrollPaneContentPanel.setLayout(new java.awt.BorderLayout());

        LocalesCenterPanelScrollPaneContentPanel.setBackground(new java.awt.Color(220, 225, 240));
        LocalesCenterPanelScrollPaneLanguageID.setBackground(new java.awt.Color(220, 225, 240));
        LocalesCenterPanelScrollPaneLanguageID.setBorder(null);
        LocalesCenterPanelScrollPaneLanguageID.setHorizontalScrollBarPolicy(javax.swing.JScrollPane.HORIZONTAL_SCROLLBAR_ALWAYS);
        LocalesCenterPanelScrollPaneLanguageID.setVerticalScrollBarPolicy(javax.swing.JScrollPane.VERTICAL_SCROLLBAR_NEVER);
        LocalesCenterPanelScrollPaneLanguageID.setFont(new java.awt.Font("Arial", 0, 12));
        LocalesCenterPanelScrollPaneLanguageID.setMinimumSize(new java.awt.Dimension(385, 22));
        LocalesCenterPanelScrollPaneLanguageID.setPreferredSize(new java.awt.Dimension(385, 3));
        LocalesJTreeLanguages.setBackground(new java.awt.Color(220, 225, 240));
        LocalesJTreeLanguages.setFont(new java.awt.Font("Arial", 0, 12));
        LocalesJTreeLanguages.setMaximumSize(new java.awt.Dimension(385, 32768));
        LocalesJTreeLanguages.setMinimumSize(new java.awt.Dimension(385, 0));
        LocalesJTreeLanguages.setPreferredSize(new java.awt.Dimension(385, 2000));
        LocalesJTreeLanguages.setRootVisible(false);
        LocalesJTreeLanguages.setRowHeight(20);
        LocalesJTreeLanguages.setVisibleRowCount(100);
        LocalesCenterPanelScrollPaneLanguageID.setViewportView(LocalesJTreeLanguages);

        LocalesCenterPanelScrollPaneContentPanel.add(LocalesCenterPanelScrollPaneLanguageID, java.awt.BorderLayout.WEST);

        LocalesCenterPanelScrollPaneLanguageEnabled.setBackground(new java.awt.Color(220, 225, 240));
        LocalesCenterPanelScrollPaneLanguageEnabled.setBorder(null);
        LocalesCenterPanelScrollPaneLanguageEnabled.setHorizontalScrollBarPolicy(javax.swing.JScrollPane.HORIZONTAL_SCROLLBAR_ALWAYS);
        LocalesCenterPanelScrollPaneLanguageEnabled.setVerticalScrollBarPolicy(javax.swing.JScrollPane.VERTICAL_SCROLLBAR_NEVER);
        LocalesEnablesLocalesCheckboxPanel.setBackground(new java.awt.Color(220, 225, 240));
        LocalesCenterPanelScrollPaneLanguageEnabled.setViewportView(LocalesEnablesLocalesCheckboxPanel);

        LocalesCenterPanelScrollPaneContentPanel.add(LocalesCenterPanelScrollPaneLanguageEnabled, java.awt.BorderLayout.CENTER);

        ProjectLocalesCenterPanelScrollPane.setViewportView(LocalesCenterPanelScrollPaneContentPanel);

        ProjectLocalesCenterPanel.add(ProjectLocalesCenterPanelScrollPane, java.awt.BorderLayout.CENTER);

        //add(ProjectLocalesCenterPanel, java.awt.BorderLayout.CENTER);
        add(theEAProperties, java.awt.BorderLayout.CENTER);

        ProjectLocalesNorthPanel.setLayout(new javax.swing.BoxLayout(ProjectLocalesNorthPanel, javax.swing.BoxLayout.Y_AXIS));

        ProjectLocalesNorthPanel.setBackground(new java.awt.Color(140, 160, 210));
        ProjectLocalesNorthPanelTopPanel.setBackground(new java.awt.Color(140, 160, 210));
        ProjectLocalesNorthPanel.add(ProjectLocalesNorthPanelTopPanel);

        ProjectLocalesNorthPanelBottomPanel.setBackground(new java.awt.Color(140, 160, 210));
        ProjectLocalesNorthPanel.add(ProjectLocalesNorthPanelBottomPanel);

        add(ProjectLocalesNorthPanel, java.awt.BorderLayout.NORTH);

        ProjectLocalesSouthPanel.setBackground(new java.awt.Color(140, 160, 210));
       // LocalesSelectAllButton.setFont(new java.awt.Font("Arial", 0, 12));
        //LocalesSelectAllButton.setText("Select All");
        //LocalesSelectAllButton.addActionListener(new java.awt.event.ActionListener() {
        //    public void actionPerformed(java.awt.event.ActionEvent evt) {
        //        LocalesSelectAllButtonActionPerformed(evt);
        //    }
        //});

        //ProjectLocalesSouthPanel.add(LocalesSelectAllButton);

        //LocalesDeselectAllButton.setFont(new java.awt.Font("Arial", 0, 12));
        //LocalesDeselectAllButton.setText("Deselect All");
        //LocalesDeselectAllButton.addActionListener(new java.awt.event.ActionListener() {
        //    public void actionPerformed(java.awt.event.ActionEvent evt) {
        //        LocalesDeselectAllButtonActionPerformed(evt);
        //    }
        //});

        //ProjectLocalesSouthPanel.add(LocalesDeselectAllButton);

        add(ProjectLocalesSouthPanel, java.awt.BorderLayout.SOUTH);

        ProjectLocalesLeftPanel.setBackground(new java.awt.Color(140, 160, 210));
        ProjectLocalesLeftPanel.setMaximumSize(new java.awt.Dimension(10, 32767));
        add(ProjectLocalesLeftPanel, java.awt.BorderLayout.WEST);

        ProjectLocalesRightPanel.setBackground(new java.awt.Color(140, 160, 210));
        ProjectLocalesRightPanel.setMaximumSize(new java.awt.Dimension(10, 32767));
        add(ProjectLocalesRightPanel, java.awt.BorderLayout.EAST);

    }//GEN-END:initComponents

   // private void LocalesDeselectAllButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LocalesDeselectAllButtonActionPerformed
        // Add your handling code here:
    //}//GEN-LAST:event_LocalesDeselectAllButtonActionPerformed

    //private void LocalesSelectAllButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LocalesSelectAllButtonActionPerformed
        // Add your handling code here:
  //  }//GEN-LAST:event_LocalesSelectAllButtonActionPerformed

public EAListItem[] getEAListItemURLArray()
{
	return getActionsEAListItems();
}

private int translatedLangs = 3;
EAListItem[] ActionsEAListItemArray = new EAListItem[4];
//private String[] strActionsArray = new String[4];
private EAListItem[] getActionsEAListItems()
{
	String strDefaultLanguage = "en";
        try
        {
		Object[] localArray = {"en"};
		ArrayList strArrayList1 = new ArrayList();
		ArrayList eaListItemArrayList1 = new ArrayList();
		if(ProjectManager.get("prjdefaultlocale")!=null)
		{
			if(ProjectManager.get("prjdefaultlocale").equalsIgnoreCase("")==false)
			{
				strDefaultLanguage = ProjectManager.get("prjdefaultlocale");
			}
		}
		
		if(ProjectManager.get("prjlocales")!=null)
		{
			if(ProjectManager.get("prjlocales").equalsIgnoreCase("")==false)
			{
				localArray = getStringArraysFromString(ProjectManager.get("prjlocales"));
				ActionsEAListItemArray = new EAListItem[localArray.length];
			}
		}
		try
		{
        		try
        		{
            		// Translated languages available value
            		if(ProjectManager.get("project_translated_lang_count")!=null)
            		{
            			if(ProjectManager.get("project_translated_lang_count").equalsIgnoreCase("")==false)
            			{
   		    				translatedLangs = Integer.valueOf(ProjectManager.get("project_translated_lang_count")).intValue();
 					}
					else
					{
						translatedLangs = 3;
					}
	           		}
				else
				{
					translatedLangs = 3;
				}
        		}
        		catch(Exception e)
        		{
            		translatedLangs = 3;
        		}
			int loopnum = 0;
			if(translatedLangs<=localArray.length)
			{
				loopnum=translatedLangs;
			}
			else
			{
				loopnum = localArray.length;
			}
			for(int i = 0;i<loopnum;i++)
			{
            		EAListItem eai2 = new EAListItem(theActionRowIcon,rowColor);
				EAListItemContent locales1 = new EAListItemContent(rowColor, defActionLabelWidth, defActionDataWidth, defActionDataValueWidth, true);
				HashMap locHM = getLocaleMap();
				if(localArray[i]!=null)
				{
             			if(DesignerRuleBuilder.get("prjLocalesEnabled")!=null)
             			{
                				if(DesignerRuleBuilder.get("prjLocalesEnabled").equalsIgnoreCase("true")==true)
                 				{
							try
							{
								Object[] theObj = (Object[])locHM.get((String)localArray[i]);
								locales1.setLabelText(((String)theObj[0]) + " - " + ((String)localArray[i]));
								locales1.setCheckBoxSelected(((Boolean)theObj[1]).booleanValue());
								locales1.setValueBoxEnabled(true);
								locales1.setInputTextColor(Color.black);
								locales1.setInputValueText("Yes");
								if(strDefaultLanguage.equalsIgnoreCase(((String)localArray[i]))==true)
								{
									locales1.setCheckBoxEnabled(false);
								}
							}
							catch(Exception e)
							{
								locales1.setLabelText((String)localArray[i]);
								locales1.setCheckBoxEnabled(false);
							}
						}
						else
						{
							try
							{
								Object[] theObj = (Object[])locHM.get((String)localArray[i]);
								locales1.setLabelText(((String)theObj[0]) + " - " + ((String)localArray[i]));
								locales1.setCheckBoxSelected(((Boolean)theObj[1]).booleanValue());
								if(ProjectManager.get("prjdefaultlocale")!=null)
								{
									locales1.setCheckBoxEnabled(false);
								}
								else
								{
									locales1.setCheckBoxEnabled(false);
								}
							}
							catch(Exception e)
							{
								locales1.setLabelText((String)localArray[i]);
							}
						}
					}
					else
					{
							try
							{
								Object[] theObj = (Object[])locHM.get((String)localArray[i]);
								locales1.setLabelText(((String)theObj[0]) + " - " + ((String)localArray[i]));
								locales1.setCheckBoxSelected(((Boolean)theObj[1]).booleanValue());
								if(ProjectManager.get("prjdefaultlocale")!=null)
								{
									locales1.setCheckBoxEnabled(false);
								}
								else
								{
									locales1.setCheckBoxEnabled(false);
								}
							}
							catch(Exception e)
							{
								locales1.setLabelText((String)localArray[i]);
							}
					}
				}
            		eai2.setRowDataPanel(locales1);
				// Always call setListItemIsRemovable(false) after the ContentPanel is added, like in setRowDataPanel(...)
				eai2.setListItemIsRemovable(false);
				eai2.setValueBoxEnabled(true);
				eai2.getJCheckBoxControl().addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                localeSelectedActionPerformed(evt);
            }
        });

				eaListItemArrayList1.add(eai2);
			}
			for(int i = (translatedLangs);i<localArray.length;i++)
			{
            		EAListItem eai2 = new EAListItem(theActionRowIcon,rowColor);
				EAListItemContent locales1 = new EAListItemContent(rowColor, defActionLabelWidth, defActionDataWidth,defActionDataValueWidth, true);
				HashMap locHM = getLocaleMap();
				if(localArray[i]!=null)
				{
             			if(DesignerRuleBuilder.get("prjLocalesEnabled")!=null)
             			{
                				if(DesignerRuleBuilder.get("prjLocalesEnabled").equalsIgnoreCase("true")==true)
                 				{
							try
							{
								Object[] theObj = (Object[])locHM.get((String)localArray[i]);
								locales1.setLabelText(((String)theObj[0]) + " - " + ((String)localArray[i]));
								locales1.setCheckBoxSelected(((Boolean)theObj[1]).booleanValue());
								locales1.setValueBoxEnabled(true);
								locales1.setInputTextColor(Color.black);
								locales1.setInputValueText("No");
								if(strDefaultLanguage.equalsIgnoreCase(((String)localArray[i]))==true)
								{
									locales1.setCheckBoxEnabled(false);
								}
							}
							catch(Exception e)
							{
								locales1.setLabelText((String)localArray[i]);
								locales1.setCheckBoxEnabled(false);
							}
						}
						else
						{
							try
							{
								Object[] theObj = (Object[])locHM.get((String)localArray[i]);
								locales1.setLabelText(((String)theObj[0]) + " - " + ((String)localArray[i]));
								locales1.setCheckBoxSelected(((Boolean)theObj[1]).booleanValue());
								if(ProjectManager.get("prjdefaultlocale")!=null)
								{
									locales1.setCheckBoxEnabled(false);
								}
								else
								{
									locales1.setCheckBoxEnabled(false);
								}
							}
							catch(Exception e)
							{
								locales1.setLabelText((String)localArray[i]);
							}
						}
					}
					else
					{
							try
							{
								Object[] theObj = (Object[])locHM.get((String)localArray[i]);
								locales1.setLabelText(((String)theObj[0]) + " - " + ((String)localArray[i]));
								locales1.setCheckBoxSelected(((Boolean)theObj[1]).booleanValue());
								if(ProjectManager.get("prjdefaultlocale")!=null)
								{
									locales1.setCheckBoxEnabled(false);
								}
								else
								{
									locales1.setCheckBoxEnabled(false);
								}
							}
							catch(Exception e)
							{
								locales1.setLabelText((String)localArray[i]);
							}
					}
				}
            		eai2.setRowDataPanel(locales1);
				// Always call setListItemIsRemovable(false) after the ContentPanel is added, like in setRowDataPanel(...)
				eai2.setListItemIsRemovable(true);
				eai2.setValueBoxEnabled(true);
				eai2.getJCheckBoxControl().addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                localeSelectedActionPerformed(evt);
            }
        });
				eaListItemArrayList1.add(eai2);
			}
		}
		catch(Exception e)
		{
			e.printStackTrace();
		}
		eaListItemArrayList1.trimToSize();
		Object[] theEAListItemObjArray = eaListItemArrayList1.toArray();
		ActionsEAListItemArray = new EAListItem[theEAListItemObjArray.length];
		for(int i = 0;i<theEAListItemObjArray.length;i++)
		{
			ActionsEAListItemArray[i] = (EAListItem)theEAListItemObjArray[i];
		}

		return ActionsEAListItemArray;
        }
        catch(Exception e)
        {
          e.printStackTrace();   
        }
	EAListItem[] tempLIArray2 = new EAListItem[0];
	return tempLIArray2;
}

private HashMap getLocaleMap()
{
	HashMap hm = new HashMap();
	try
	{
	if(ProjectManager.get("prjlocales")!=null)
	{
		if(ProjectManager.get("prjlocales").equalsIgnoreCase("")==false)
		{
			if(ProjectManager.get("prjlocalesnames")!=null)
			{
				if(ProjectManager.get("prjlocalesnames").equalsIgnoreCase("")==false)
				{
					if(ProjectManager.get("prjbuildlocales")!=null)
					{
						if(ProjectManager.get("prjbuildlocales").equalsIgnoreCase("")==false)
						{
							Object[] shorts = getStringArraysFromString(ProjectManager.get("prjlocales"));
							Object[] names = getStringArraysFromString(ProjectManager.get("prjlocalesnames"));
							Object[] enabled = getStringArraysFromString(ProjectManager.get("prjbuildlocales"));
							HashMap enabledMap = new HashMap();
							for(int i = 0;i<enabled.length;i++)
							{
								hm.put((String)enabled[i],(String)enabled[i]);
							}
							for(int i = 0;i<shorts.length;i++)
							{
									Object[] strArray = new Object[2];
									strArray[0] = (String)names[i];

								if(hm.get((String)shorts[i])!=null)
								{
									strArray[1] = new Boolean(true);
								}
								else
								{
									strArray[1] = new Boolean(false);
								}
								hm.put((String)shorts[i],strArray);
							}
							return hm;
						}
					}
				}	
			}
		}	
	}	
	}
	catch(Exception e)
	{
		e.printStackTrace();
	}
	return null;
}

    public EAListItemContent addEAListItem()
    {
	try
	{
        if(LocaleSelector.showLocaleSelectorDialog()!=-1)
        {
		 addLocale(LocaleSelector.getLocaleString(), LocaleSelector.getLocaleNameString());
	 	 EAListItemContent locales1 = new EAListItemContent(rowColor, defActionLabelWidth, defActionDataWidth,true);
		 try
		 {
			locales1.setLabelText(LocaleSelector.getLocaleNameString() + " - " + LocaleSelector.getLocaleString());
		 	locales1.setCheckBoxSelected(false);
			locales1.setValueBoxEnabled(true);
			locales1.setInputTextColor(Color.black);
			locales1.setInputValueText("No");
getMakeLocaleFile(LocaleSelector.getLocaleString());
		 }
		 catch(Exception e)
		 {
			e.printStackTrace();
		 }
		locales1.cbInputLabel.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                localeSelectedActionPerformed(evt);
            }
        });

		return locales1;
        }
        else
        {
         	return null;
        }

	}
	catch(Exception e)
	{
		e.printStackTrace();
         	return null;
	}
    } 


    public void removeListItem(int index)
    {
       try
       {
		Object[] prjLocales = getStringArraysFromString(ProjectManager.get("prjlocales"));
		removeLocale(((String)prjLocales[index]));
	}
	catch(Exception e)
	{
		e.printStackTrace();
	}
    } 

	private void addLocale(String strLocale, String strLocaleName)
	{
		try
		{
             	if(DesignerRuleBuilder.get("prjLocalesEnabled")!=null)
             	{
                		if(DesignerRuleBuilder.get("prjLocalesEnabled").equalsIgnoreCase("true")==true)
                 		{
					if(strLocale!=null)
					{
						if(strLocaleName!=null)	
						{
							ProjectManager.putTempNoFileWrite("prjlocales", ProjectManager.get("prjlocales") + "," + strLocale);
							ProjectManager.putTempNoFileWrite("prjlocalesnames", ProjectManager.get("prjlocalesnames") + "," + strLocaleName);
							ProjectManager.saveTempNow();
						}
					}
				}
			}
		}
		catch(Exception e)
		{
			e.printStackTrace();
		}
	}

	private void addBuildLocale(String strLocale)
	{
		try
		{
             	if(DesignerRuleBuilder.get("prjLocalesEnabled")!=null)
             	{
                		if(DesignerRuleBuilder.get("prjLocalesEnabled").equalsIgnoreCase("true")==true)
                 		{
					if(strLocale!=null)
					{
						ProjectManager.putTempNoFileWrite("prjbuildlocales", ProjectManager.get("prjbuildlocales") + "," + strLocale);
						ProjectManager.saveTempNow();
					}
				}
			}
		}
		catch(Exception e)
		{
			e.printStackTrace();
		}		
	}

	private void removeLocale(String strLocale)
	{
		try
		{
             	if(DesignerRuleBuilder.get("prjLocalesEnabled")!=null)
             	{
                		if(DesignerRuleBuilder.get("prjLocalesEnabled").equalsIgnoreCase("true")==true)
                 		{
					if(strLocale!=null)
					{
						removeBuildLocale(strLocale);
						Object[] prjLocales = getStringArraysFromString(ProjectManager.get("prjlocales"));
						Object[] prjLocaleNames = getStringArraysFromString(ProjectManager.get("prjlocalesnames"));
						String[] newPrjLocales = new String[prjLocales.length - 1];
						String[] newPrjLocaleNames = new String[prjLocales.length - 1];
						int j = 0;
						for(int i = 0;i<prjLocales.length;i++)
						{
							if(strLocale.equalsIgnoreCase((String)prjLocales[i])==false)
							{
								newPrjLocales[j] = (String)prjLocales[i];
								newPrjLocaleNames[j] = (String)prjLocaleNames[i];
								j++;
							}
						}
						String strNewPrjLocales = newPrjLocales[0];
						String strNewPrjLocaleNames = newPrjLocaleNames[0];
						for(int i = 1;i<newPrjLocales.length;i++)
						{
							strNewPrjLocales = strNewPrjLocales + "," + newPrjLocales[i];
							strNewPrjLocaleNames = strNewPrjLocaleNames + "," + newPrjLocaleNames[i];
						}						
						ProjectManager.putTempNoFileWrite("prjlocales", strNewPrjLocales);
						ProjectManager.putTempNoFileWrite("prjlocalesnames", strNewPrjLocaleNames);
						ProjectManager.saveTempNow();
					}
				}
			}
		}
		catch(Exception e)
		{
			e.printStackTrace();
		}		
	}

	private static void removeBuildLocale(String strLocale)
	{
		try
		{
             	if(DesignerRuleBuilder.get("prjLocalesEnabled")!=null)
             	{
                		if(DesignerRuleBuilder.get("prjLocalesEnabled").equalsIgnoreCase("true")==true)
                 		{
					if(strLocale!=null)
					{
						Object[] prjLocales = getStringArraysFromString(ProjectManager.get("prjbuildlocales"));
						String[] newPrjLocales = new String[prjLocales.length - 1];
						int j = 0;
						for(int i = 0;i<prjLocales.length;i++)
						{
							if(strLocale.equalsIgnoreCase((String)prjLocales[i])==false)
							{
								newPrjLocales[j] = (String)prjLocales[i];
								j++;
							}
						}
                                    if(0<newPrjLocales.length)
                                    {
                                        String strNewPrjLocales = newPrjLocales[0];
                                        for(int i = 1;i<newPrjLocales.length;i++)
                                        {
                                            strNewPrjLocales = strNewPrjLocales + "," + newPrjLocales[i];
                                        }						
                                        ProjectManager.putTempNoFileWrite("prjbuildlocales", strNewPrjLocales);
                                        ProjectManager.saveTempNow();
                                    }
					}
				}
			}
		}
		catch(Exception e)
		{
			e.printStackTrace();
		}
	}

    private void localeSelectedActionPerformed(java.awt.event.ItemEvent evt)
    {
	try
	{
	theEAProperties.setSelectedIndex(((EAListItem)((JCheckBox)evt.getItem()).getParent().getParent().getParent()).getComponentLocalizationID());
	Object[] prjLocales = getStringArraysFromString(ProjectManager.get("prjlocales"));
	Object[] prjLocaleNames = getStringArraysFromString(ProjectManager.get("prjlocalesnames"));
	//System.out.println("Checkbox Action performed. The selected index is: " + theEAProperties.getSelectedIndex() + ", The index locale is: " + ((String)prjLocales[theEAProperties.getSelectedIndex()]) + ", The Language is: " + ((String)prjLocaleNames[theEAProperties.getSelectedIndex()]));
	if(((JCheckBox)evt.getItem()).isSelected()==true)
	{
		addBuildLocale(((String)prjLocales[theEAProperties.getSelectedIndex()]));
		getMakeLocaleFile(((String)prjLocales[theEAProperties.getSelectedIndex()]));
	}
	else
	{
		removeBuildLocale(((String)prjLocales[theEAProperties.getSelectedIndex()]));
	}
	}
	catch(Exception e)
	{
		e.printStackTrace();
	}
    }

    public static void getMakeLocaleFile(String strLocale)
    {
        try
        {
		String strDefaultLanguage = "en";
		int result = -1;
		if(ProjectManager.get("prjdefaultlocale")!=null)
		{
			if(ProjectManager.get("prjdefaultlocale").equalsIgnoreCase("")==false)
			{
				strDefaultLanguage = ProjectManager.get("prjdefaultlocale");
			}
		}

		if(strLocale.equalsIgnoreCase(strDefaultLanguage)==true)
		{
			String newFile = getFileName().substring(getFileName().lastIndexOf("/"));
                    if(ProjectManager.get("i18nBundleName")!=null)
                    {
                        if(ProjectManager.get("i18nBundleName").equalsIgnoreCase("")==false)
                        {
					ZipBuilder.getFileFromZipEntry(new File(new URL(new File(System.getProperty("user.dir")).toURL().toString() + "/lib/locales.jar").getFile()), ProjectManager.get("i18nBundleName") + ".properties", new File(new URL(DesignerRuleBuilder.getTempProject()).getPath().substring(0, new URL(DesignerRuleBuilder.getTempProject()).getPath().lastIndexOf("/")) + "/locales/" + ProjectManager.get("i18nBundleName") + ".properties"),false);
				}
				else
				{
					ZipBuilder.getFileFromZipEntry(new File(new URL(new File(System.getProperty("user.dir")).toURL().toString() + "/lib/locales.jar").getFile()), "MessagesBundle" + ".properties", new File(new URL(DesignerRuleBuilder.getTempProject()).getPath().substring(0, new URL(DesignerRuleBuilder.getTempProject()).getPath().lastIndexOf("/")) + "/locales/" + "MessagesBundle" + ".properties"),false);
				}
	        	  }
	        	  else
	        	  {
		 	  	ZipBuilder.getFileFromZipEntry(new File(new URL(new File(System.getProperty("user.dir")).toURL().toString() + "/lib/locales.jar").getFile()), "MessagesBundle" + ".properties", new File(new URL(DesignerRuleBuilder.getTempProject()).getPath().substring(0, new URL(DesignerRuleBuilder.getTempProject()).getPath().lastIndexOf("/")) + "/locales/" + "MessagesBundle" + ".properties"),false);
	        	  }
			  //result = copyFile(getFileName(), new URL(DesignerRuleBuilder.getTempProject()).getPath().substring(0, new URL(DesignerRuleBuilder.getTempProject()).getPath().lastIndexOf("/")) + "/locales" + newFile, false);
		}
		else
		{
			//String newFile = getFileName().substring(getFileName().lastIndexOf("/"),getFileName().lastIndexOf(".")) + "_" + strLocale + ".properties";
			//File sourceFile = new File(getFileName().substring(0,getFileName().lastIndexOf("/")) + newFile);
//System.out.println(getFileName().substring(0,getFileName().lastIndexOf("/")) + newFile);
			//if(sourceFile.exists()==true)
			//{
			//	result = copyFile(sourceFile.getPath(), new URL(DesignerRuleBuilder.getTempProject()).getPath().substring(0, new URL(DesignerRuleBuilder.getTempProject()).getPath().lastIndexOf("/")) + "/locales" + newFile, false);
			//}
			//else
			//{
			//	result = copyFile(getFileName(), new URL(DesignerRuleBuilder.getTempProject()).getPath().substring(0, new URL(DesignerRuleBuilder.getTempProject()).getPath().lastIndexOf("/")) + "/locales" + newFile, false);
			//}

			boolean isTranslated = getLocaleIsTranslated(strLocale);
                    if(ProjectManager.get("i18nBundleName")!=null)
                    {
                        if(ProjectManager.get("i18nBundleName").equalsIgnoreCase("")==false)
                        {
					if(isTranslated==true)
					{
						ZipBuilder.getFileFromZipEntry(new File(new URL(new File(System.getProperty("user.dir")).toURL().toString() + "/lib/locales.jar").getFile()), ProjectManager.get("i18nBundleName") + "_" + strLocale + ".properties", new File(new URL(DesignerRuleBuilder.getTempProject()).getPath().substring(0, new URL(DesignerRuleBuilder.getTempProject()).getPath().lastIndexOf("/")) + "/locales/" + ProjectManager.get("i18nBundleName") + "_" + strLocale + ".properties"),false);
					}
					else
					{
						ZipBuilder.getFileFromZipEntry(new File(new URL(new File(System.getProperty("user.dir")).toURL().toString() + "/lib/locales.jar").getFile()), ProjectManager.get("i18nBundleName") + ".properties", new File(new URL(DesignerRuleBuilder.getTempProject()).getPath().substring(0, new URL(DesignerRuleBuilder.getTempProject()).getPath().lastIndexOf("/")) + "/locales/" + ProjectManager.get("i18nBundleName") + "_" + strLocale + ".properties"),false);
					}
				}
				else
				{
					if(isTranslated==true)
					{
						ZipBuilder.getFileFromZipEntry(new File(new URL(new File(System.getProperty("user.dir")).toURL().toString() + "/lib/locales.jar").getFile()), "MessagesBundle" + "_" + strLocale + ".properties", new File(new URL(DesignerRuleBuilder.getTempProject()).getPath().substring(0, new URL(DesignerRuleBuilder.getTempProject()).getPath().lastIndexOf("/")) + "/locales/" + "MessagesBundle" + "_" + strLocale + ".properties"),false);
					}
					else
					{
						ZipBuilder.getFileFromZipEntry(new File(new URL(new File(System.getProperty("user.dir")).toURL().toString() + "/lib/locales.jar").getFile()), "MessagesBundle" + ".properties", new File(new URL(DesignerRuleBuilder.getTempProject()).getPath().substring(0, new URL(DesignerRuleBuilder.getTempProject()).getPath().lastIndexOf("/")) + "/locales/" + "MessagesBundle" + "_" + strLocale + ".properties"),false);
					}
			  	}
	       	 }
	        	 else
	        	 {
				if(isTranslated==true)
				{
		 			ZipBuilder.getFileFromZipEntry(new File(new URL(new File(System.getProperty("user.dir")).toURL().toString() + "/lib/locales.jar").getFile()), "MessagesBundle" + "_" + strLocale + ".properties", new File(new URL(DesignerRuleBuilder.getTempProject()).getPath().substring(0, new URL(DesignerRuleBuilder.getTempProject()).getPath().lastIndexOf("/")) + "/locales/" + "MessagesBundle" + "_" + strLocale + ".properties"),false);
				}
				else
				{
		 			ZipBuilder.getFileFromZipEntry(new File(new URL(new File(System.getProperty("user.dir")).toURL().toString() + "/lib/locales.jar").getFile()), "MessagesBundle" + ".properties", new File(new URL(DesignerRuleBuilder.getTempProject()).getPath().substring(0, new URL(DesignerRuleBuilder.getTempProject()).getPath().lastIndexOf("/")) + "/locales/" + "MessagesBundle" + "_" + strLocale + ".properties"),false);
				}
	        	 }
		}


        }
	catch(Exception e)
	{
		e.printStackTrace();
	}
    }

    private static boolean getLocaleIsTranslated(String theAbbreviatedLocale)
    {
	int translatedLangs = 3;
	try
	{
		try
		{
			translatedLangs = Integer.valueOf(ProjectManager.get("project_translated_lang_count")).intValue();
		}
		catch(Exception e)
		{

		}
		String locales1 = ProjectManager.get("prjlocales");
            Object[] localesArray = getStringArraysFromString(locales1);
            	for(int i = 0;i<translatedLangs;i++)
            	{
				if(((String)localesArray[i]).equalsIgnoreCase(theAbbreviatedLocale)==true)
				{
					return true;
				}
			}
	}
	catch(Exception e)
	{

	}
	return false;
    }

    private static int copyFile(String sourceFile, String destinationFile, boolean boolOverwriteFile)
    {  
         return copyFile(new File(sourceFile), new File(destinationFile), boolOverwriteFile);
    }
    
    private static int copyFile(File theSourceFile, File theDestinationFile, boolean boolOverwriteFile)
    {
        try
        {
            if(theSourceFile.isDirectory()==true)
            {
                try
                {
                    //System.out.println("THe source file is a directory: " + theSourceFile.getPath());
                    // Move file to new directory
                    copyDirectory(theSourceFile, theDestinationFile);
                    return 0;
                }
                catch(Exception e)
                {
                    return 1;
                }    
            }
            else
            {
                // Destination directory
                if(theSourceFile.exists()==true)
                {
                        // if the source file exists, then continue.
                        if(theDestinationFile.exists()==true)
                        {
                            // 1. Check if the file can be overwriten. If not then return 0;
                            if(boolOverwriteFile==true)
                            {
                                // TODO 2/11/2004: Implement Rollback feature for manual Rollback on failed upgrades.
                                // The Destination File exists. Must overwrite. Backup may be necessary.
                                try
                                {
         //                           System.out.println("Deleting old update file to replace with new file.");
                                    theDestinationFile.delete();
         //                            System.out.println("Deleted Successfully");
                                    try
                                    {
                                        // Move file to new directory
                                        copy(theSourceFile, theDestinationFile);
                                        return 0;
                                    }
                                    catch(Exception e)
                                    {
                                        return 1;
                                    }    
                                }
                                catch(Exception e)
                                {

                                    e.printStackTrace();
                                    return 8;
                                }                           
                            }
                            else
                            {
                                return 0;
                            }
                        }
                        else 
                        {
                            // The destination file does not exist. Proceed by verifying directory exists. If not create the directory, and then attemp to create the file.
                              try
                              {
                                File theCopyToDirectory = new File(getDownloadDirFromFileString(theDestinationFile.toURL().getPath()));
                                if(theCopyToDirectory.exists()==true)
                                {
                                    //if the directory exists for the destination file, copy the file.
                                    try
                                    {
                                        // Move file to new directory
                                        copy(theSourceFile, theDestinationFile);
                                        return 0;
                                    }
                                    catch(Exception e)
                                    {
                                        return 1;
                                    }    
                                }
                                else
                                {
                                      //if the directory does not exist for the destination file, create the directory and then copy the file.                               
        //                              System.out.println("Making directory: " + theCopyToDirectory.getAbsolutePath());
                                      boolean isCreated = theCopyToDirectory.mkdirs();
        //                              System.out.println("Created Directory: " + isCreated);    
                                    try
                                    {
                                        // Move file to new directory
                                        copy(theSourceFile, theDestinationFile);
                                        return 0;
                                    }
                                    catch(Exception e)
                                    {
                                        return 1;
                                    }                                        
                                }
                              }
                              catch(Exception e)
                              {
                                  e.printStackTrace();
                                  return 8;
                              }

                        }

                }
                else
                {
                    // return code 9 is source file does not exist.
                    return 9;
                }

            }
        }
        catch(Exception e)
        {
            return 8;
        }       
    }         

    /* returns the install file path minus file and last slash for directory path */
    private static synchronized String getDownloadDirFromFileString(String strFilePath)
    {
        try
        {
            if(strFilePath.indexOf("/")!=-1)
            {
                if(strFilePath.indexOf("/")==0)
                {
                    if(strFilePath.lastIndexOf("/")==0)
                    {
                        return "/";
                    }
                    else
                    {
                        return strFilePath.substring(0,strFilePath.lastIndexOf("/"));
                    }
                }
                else
                {
                    /* If / is not the first character assume the first part of the dir path is the directory name followed by a / */
                    try
                    {
                        strFilePath=strFilePath.trim();
                        if(strFilePath.indexOf("/")==0)
                        {
                            if(strFilePath.lastIndexOf("/")==0)
                            {
                                return "/";
                            }
                            else
                            {
                                return strFilePath.substring(0,strFilePath.lastIndexOf("/"));
                            }
                        }
                        else
                        {
                            strFilePath = "/" + strFilePath;
                            return strFilePath.substring(0,strFilePath.lastIndexOf("/"));
                        }
                    }
                    catch(NullPointerException e)
                    {
                        return "/";
                    }
                    catch(Exception e)
                    {
                        return "/";                
                    }
                }
            }
            else
            {
                    return "/";                
            }
        }
        catch(NullPointerException e)
        {
            return "/";
        }
        catch(Exception e)
        {
            return "/";                
        }        
     }    

    // Copies src file to dst file.
    // If the dst file does not exist, it is created
    private static void copy(File src, File dst) throws IOException 
    {
        InputStream in = new FileInputStream(src);
        OutputStream out = new FileOutputStream(dst);
    
        // Transfer bytes from in to out
        byte[] buf = new byte[1024];
        int len;
        while ((len = in.read(buf)) > 0) 
        {
            out.write(buf, 0, len);
        }
        in.close();
        out.close();
        dst.setLastModified(src.lastModified());
    }   

     // Copies all files under srcDir to dstDir.
    // If dstDir does not exist, it will be created.
    public static void copyDirectory(File srcDir, File dstDir) throws IOException 
    {
        if (srcDir.isDirectory()) 
        {
            if (!dstDir.exists()) 
            {
                dstDir.mkdir();
            }
    
            String[] children = srcDir.list();
            for (int i=0; i<children.length; i++) 
            {
                copyDirectory(new File(srcDir, children[i]),new File(dstDir, children[i]));
            }
        } 
        else 
        {
            // This method is implemented in e1071 Copying a File
            copy(srcDir, dstDir);
        }
    }  

    public void setSelectedListItemEvent(int theLastSelectedIndex)
    {
		/*EAListItem eaListItemObj = theEAProperties.getSelectedEAListItem();
		EAListItemContent theContent = eaListItemObj.getRowDataPanel();
		if(theLastSelectedIndex!=-1)
		{
			try
			{
				theEAProperties.getSelectedEAListItem().getRowDataPanel().setInputText(ProjectManager.get(strActionsArray[theLastSelectedIndex]));
			}
			catch(Exception e)
			{
				e.printStackTrace();
			}
		}*/
    }

    private static Object[] getStringArraysFromString(String textArrayString)
    {
        ArrayList aryList = new ArrayList();
        String tempString = "";
        
        while(textArrayString.indexOf(",")!=-1)
        {
            tempString = textArrayString.substring(0,textArrayString.indexOf(","));
            textArrayString = textArrayString.substring(textArrayString.indexOf(",") + 1);
            aryList.add(tempString);
        }
        aryList.add(textArrayString);
        return aryList.toArray();
    }   

  public void getDataUpdate()
  {
	try
	{
		//System.out.println("Data Update not implemented in this Panel...");
	}
	catch(Exception e)
	{
		e.printStackTrace();
	}
  }       
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel LocalesCenterPanelScrollPaneContentPanel;
    private javax.swing.JScrollPane LocalesCenterPanelScrollPaneLanguageEnabled;
    private javax.swing.JScrollPane LocalesCenterPanelScrollPaneLanguageID;
   // private javax.swing.JButton LocalesDeselectAllButton;
    private javax.swing.JPanel LocalesEnablesLocalesCheckboxPanel;
    private javax.swing.JTree LocalesJTreeLanguages;
   // private javax.swing.JButton LocalesSelectAllButton;
    private javax.swing.JPanel ProjectLocalesCenterPanel;
    private javax.swing.JScrollPane ProjectLocalesCenterPanelScrollPane;
    private javax.swing.JPanel ProjectLocalesLeftPanel;
    private javax.swing.JPanel ProjectLocalesNorthPanel;
    private javax.swing.JPanel ProjectLocalesNorthPanelBottomPanel;
    private javax.swing.JPanel ProjectLocalesNorthPanelTopPanel;
    private javax.swing.JPanel ProjectLocalesRightPanel;
    private javax.swing.JPanel ProjectLocalesSouthPanel;
    private EAPropertiesPanel theEAProperties;
    // End of variables declaration//GEN-END:variables
    
}
