/*
 * MainButtonsPanel.java
 *
 * Created on October 11, 2004, 3:25 PM
 */

package com.trinity.ea.design.project.lookandfeel.buttons;
import com.trinity.ea.design.common.panel.EAPanel;
import com.trinity.ea.design.project.lookandfeel.buttons.GeneralButtonPanel;
import com.trinity.ea.design.project.lookandfeel.buttons.ButtonPanel;
import com.trinity.ea.design.project.lookandfeel.buttons.ImageButtonPanel;
import com.trinity.ea.design.project.lookandfeel.buttons.OKButtonPanel;
import javax.swing.*;

/**
 *
 * @author  aaronsc Trinity Software
 * Copyright ©2003-2004 Trinity Software. All rights reserved.
 */
public class MainButtonsPanel extends EAPanel {
    
    /** Creates new form MainColorPanel */
    public MainButtonsPanel() {
        initComponents();
    }

    public synchronized void getDataUpdate()
    {
	  try
        {
            //ProjectManager.saveTempNow(); 
		startupButtonPanel.getDataUpdate();
		okButtonPanel.getDataUpdate();
		generalButtonPanel.getDataUpdate();
		imageButtonPanel.getDataUpdate();
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }

    public synchronized void setProjectData()
    {
        try
        {
		startupButtonPanel.setProjectData();
		startupButtonPanel.setParentComponent(this);
		okButtonPanel.setProjectData();
		okButtonPanel.setParentComponent(this);
		generalButtonPanel.setProjectData();
		generalButtonPanel.setParentComponent(this);
		imageButtonPanel.setProjectData();
		imageButtonPanel.setParentComponent(this);
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }   
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        ColorsTabbedPane = new javax.swing.JTabbedPane();
        startupButtonPanel = new ButtonPanel();
        okButtonPanel = new OKButtonPanel();
        generalButtonPanel = new GeneralButtonPanel();
	  imageButtonPanel = new ImageButtonPanel();
        setLayout(new java.awt.BorderLayout());

        setBackground(new java.awt.Color(140, 160, 210));
        ColorsTabbedPane.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        ColorsTabbedPane.setBackground(new java.awt.Color(140, 160, 210));
        //ColorsTabbedPane.setForeground(new java.awt.Color(255, 255, 255));
try
{
	  ((javax.swing.JViewport)ColorsTabbedPane.getComponents()[0]).getView().setBackground(new java.awt.Color(140, 160, 210));
}
catch(Exception e){}         ColorsTabbedPane.setFont(new java.awt.Font("Arial", 0, 12));
        ColorsTabbedPane.addTab("General", generalButtonPanel);

        ColorsTabbedPane.addTab("Image Buttons", imageButtonPanel);

        ColorsTabbedPane.addTab("Startup Button Settings", startupButtonPanel);

        ColorsTabbedPane.addTab("OK Button Settings", okButtonPanel);

        ColorsTabbedPane.setTabPlacement(javax.swing.JTabbedPane.TOP);
        add(ColorsTabbedPane, java.awt.BorderLayout.CENTER);

    }//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane ColorsTabbedPane;
    private GeneralButtonPanel generalButtonPanel;
    private ButtonPanel startupButtonPanel;
    private OKButtonPanel okButtonPanel;
    private ImageButtonPanel imageButtonPanel;

    // End of variables declaration//GEN-END:variables
    
}
