/*
 * OKButtonPanel.java
 *
 * Created on June 13, 2004, 3:24 PM
 */

package com.trinity.ea.design.project.lookandfeel.buttons;
import com.trinity.ea.design.common.file.ProjectManager;
import com.trinity.ea.design.common.panel.EAPanel;
import com.trinity.ea.design.common.preview.actions.ErrorPreviewAction;
import java.util.ArrayList;
import java.io.File;
import java.io.IOException;
import java.net.URL;
import java.net.MalformedURLException;
import java.awt.*;
import javax.swing.*; 

/**
 *
 * @author  aaronsc Trinity Software
 * Copyright ©2003-2004 Trinity Software. All rights reserved.
 */
public class OKButtonPanel extends EAPanel {

    /** Creates new form ButtonPanel */
    public OKButtonPanel() 
    {
        initComponents();
        setProjectData();
    }

    public synchronized void getDataUpdate()
    {
	  try
	  {
// Button Text Strings
                ProjectManager.putTempNoFileWrite("errokbtn", tfUseEvaluationButtonText.getText());
                ProjectManager.putTempNoFileWrite("informationOKBtnText", tfUseEvaluationButtonText.getText());
                ProjectManager.putTempNoFileWrite("refundPolicyOKBtnText", tfUseEvaluationButtonText.getText());
                ProjectManager.putTempNoFileWrite("privacyPolicyOKBtnText", tfUseEvaluationButtonText.getText());
              
                ProjectManager.putTempNoFileWrite("errokbtnmnem", tfUseEvaluationButtonMnemonic.getText());
                ProjectManager.putTempNoFileWrite("informationOKBtnMnemonic", tfUseEvaluationButtonMnemonic.getText());
                ProjectManager.putTempNoFileWrite("refundOKBtnMnemonic", tfUseEvaluationButtonMnemonic.getText());
                ProjectManager.putTempNoFileWrite("privacyPolicyOKBtnMnemonic", tfUseEvaluationButtonMnemonic.getText());
               
            ProjectManager.saveTempNow(); 
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }
 
    public synchronized void setProjectData()
    {
        try
        {
// Button Text Strings
                if(ProjectManager.get("errokbtn")!=null)
                {
                    tfUseEvaluationButtonText.setText(ProjectManager.get("errokbtn"));
                }
                else
                {
                    tfUseEvaluationButtonText.setText("");
                }
                if(ProjectManager.get("errokbtnmnem")!=null)
                {
                    tfUseEvaluationButtonMnemonic.setText(ProjectManager.get("errokbtnmnem"));
                }
                else
                {
                    tfUseEvaluationButtonMnemonic.setText("");
                }  
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }    

    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        TryButtonPanel = new javax.swing.JPanel();
        ProjectLocationsCenterPanel1 = new javax.swing.JPanel();
        lFiller24 = new javax.swing.JLabel();
        lTryButtonText = new javax.swing.JLabel();
        tfUseEvaluationButtonText = new javax.swing.JTextField();
        lFiller27 = new javax.swing.JLabel();
        lTryButtonMnemonic = new javax.swing.JLabel();
        tfUseEvaluationButtonMnemonic = new javax.swing.JTextField();
        lFiller52 = new javax.swing.JLabel();
        SouthButtonPanelFiller = new javax.swing.JPanel();
        ImageDescriptionLabel3 = new javax.swing.JPanel();
        LeftUIFiller5 = new javax.swing.JLabel();
        ProjectLocationsCenterPanel4 = new javax.swing.JPanel();
        lFiller48 = new javax.swing.JLabel();
        PreviewButton = new javax.swing.JButton();
        lFiller45 = new javax.swing.JLabel();
        lFiller47 = new javax.swing.JLabel();
        UIChoicesBottomPanel4 = new javax.swing.JPanel();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        setBackground(new java.awt.Color(140, 160, 210));
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                formFocusLost(evt);
            }
        });

        TryButtonPanel.setLayout(new javax.swing.BoxLayout(TryButtonPanel, javax.swing.BoxLayout.Y_AXIS));

        TryButtonPanel.setBackground(new java.awt.Color(140, 160, 210));
        TryButtonPanel.setBorder(new javax.swing.border.TitledBorder(new javax.swing.border.EtchedBorder(new java.awt.Color(198, 226, 253), new java.awt.Color(96, 110, 145)), "OK Button", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12)));
        TryButtonPanel.setMaximumSize(new java.awt.Dimension(32767, 60));
        TryButtonPanel.setMinimumSize(new java.awt.Dimension(10, 60));
        TryButtonPanel.setPreferredSize(new java.awt.Dimension(10, 60));
        ProjectLocationsCenterPanel1.setLayout(new javax.swing.BoxLayout(ProjectLocationsCenterPanel1, javax.swing.BoxLayout.X_AXIS));

        ProjectLocationsCenterPanel1.setBackground(new java.awt.Color(140, 160, 210));
        ProjectLocationsCenterPanel1.setMaximumSize(new java.awt.Dimension(2147483647, 30));
        ProjectLocationsCenterPanel1.setMinimumSize(new java.awt.Dimension(600, 30));
        ProjectLocationsCenterPanel1.setPreferredSize(new java.awt.Dimension(800, 30));
        lFiller24.setBackground(new java.awt.Color(140, 160, 210));
        lFiller24.setText("   ");
        lFiller24.setMaximumSize(new java.awt.Dimension(10, 15));
        lFiller24.setMinimumSize(new java.awt.Dimension(10, 16));
        lFiller24.setPreferredSize(new java.awt.Dimension(10, 16));
        ProjectLocationsCenterPanel1.add(lFiller24);

        lTryButtonText.setBackground(new java.awt.Color(140, 160, 210));
        lTryButtonText.setFont(new java.awt.Font("Arial", 0, 12));
        lTryButtonText.setText("Button Text:");
        lTryButtonText.setMaximumSize(new java.awt.Dimension(80, 15));
        lTryButtonText.setMinimumSize(new java.awt.Dimension(80, 15));
        lTryButtonText.setPreferredSize(new java.awt.Dimension(80, 15));
        lTryButtonText.setRequestFocusEnabled(false);
        ProjectLocationsCenterPanel1.add(lTryButtonText);

        tfUseEvaluationButtonText.setFont(new java.awt.Font("Arial", 0, 12));
        tfUseEvaluationButtonText.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tfUseEvaluationButtonText.setText("OK");
        tfUseEvaluationButtonText.setMaximumSize(new java.awt.Dimension(120, 20));
        tfUseEvaluationButtonText.setMinimumSize(new java.awt.Dimension(120, 20));
        tfUseEvaluationButtonText.setPreferredSize(new java.awt.Dimension(120, 20));
        ProjectLocationsCenterPanel1.add(tfUseEvaluationButtonText);

        lFiller27.setBackground(new java.awt.Color(140, 160, 210));
        lFiller27.setText("   ");
        lFiller27.setMaximumSize(new java.awt.Dimension(10, 15));
        lFiller27.setMinimumSize(new java.awt.Dimension(10, 16));
        lFiller27.setPreferredSize(new java.awt.Dimension(10, 16));
        ProjectLocationsCenterPanel1.add(lFiller27);

        lTryButtonMnemonic.setBackground(new java.awt.Color(140, 160, 210));
        lTryButtonMnemonic.setFont(new java.awt.Font("Arial", 0, 12));
        lTryButtonMnemonic.setText("Button Mnemonic:");
        lTryButtonMnemonic.setMaximumSize(new java.awt.Dimension(110, 15));
        lTryButtonMnemonic.setMinimumSize(new java.awt.Dimension(110, 15));
        lTryButtonMnemonic.setPreferredSize(new java.awt.Dimension(110, 15));
        lTryButtonMnemonic.setRequestFocusEnabled(false);
        ProjectLocationsCenterPanel1.add(lTryButtonMnemonic);

        tfUseEvaluationButtonMnemonic.setFont(new java.awt.Font("Arial", 0, 12));
        tfUseEvaluationButtonMnemonic.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tfUseEvaluationButtonMnemonic.setText("O");
        tfUseEvaluationButtonMnemonic.setMaximumSize(new java.awt.Dimension(15, 20));
        tfUseEvaluationButtonMnemonic.setMinimumSize(new java.awt.Dimension(15, 20));
        tfUseEvaluationButtonMnemonic.setPreferredSize(new java.awt.Dimension(15, 20));
        ProjectLocationsCenterPanel1.add(tfUseEvaluationButtonMnemonic);

        lFiller52.setBackground(new java.awt.Color(140, 160, 210));
        lFiller52.setText("   ");
        lFiller52.setMaximumSize(new java.awt.Dimension(32767, 15));
        lFiller52.setMinimumSize(new java.awt.Dimension(15, 16));
        lFiller52.setPreferredSize(new java.awt.Dimension(15, 16));
        ProjectLocationsCenterPanel1.add(lFiller52);

        TryButtonPanel.add(ProjectLocationsCenterPanel1);

        add(TryButtonPanel);

        SouthButtonPanelFiller.setLayout(new javax.swing.BoxLayout(SouthButtonPanelFiller, javax.swing.BoxLayout.Y_AXIS));

        SouthButtonPanelFiller.setBackground(new java.awt.Color(140, 160, 210));
        SouthButtonPanelFiller.setMaximumSize(new java.awt.Dimension(32767, 75));
        SouthButtonPanelFiller.setMinimumSize(new java.awt.Dimension(10, 50));
        SouthButtonPanelFiller.setPreferredSize(new java.awt.Dimension(10, 60));
        ImageDescriptionLabel3.setLayout(new javax.swing.BoxLayout(ImageDescriptionLabel3, javax.swing.BoxLayout.X_AXIS));

        ImageDescriptionLabel3.setBackground(new java.awt.Color(140, 160, 210));
        LeftUIFiller5.setMaximumSize(new java.awt.Dimension(10, 10));
        LeftUIFiller5.setMinimumSize(new java.awt.Dimension(10, 10));
        LeftUIFiller5.setPreferredSize(new java.awt.Dimension(10, 10));
        ImageDescriptionLabel3.add(LeftUIFiller5);

        SouthButtonPanelFiller.add(ImageDescriptionLabel3);

        ProjectLocationsCenterPanel4.setLayout(new javax.swing.BoxLayout(ProjectLocationsCenterPanel4, javax.swing.BoxLayout.X_AXIS));

        ProjectLocationsCenterPanel4.setBackground(new java.awt.Color(140, 160, 210));
        ProjectLocationsCenterPanel4.setMaximumSize(new java.awt.Dimension(2147483647, 30));
        ProjectLocationsCenterPanel4.setMinimumSize(new java.awt.Dimension(600, 30));
        ProjectLocationsCenterPanel4.setPreferredSize(new java.awt.Dimension(800, 30));
        lFiller48.setBackground(new java.awt.Color(140, 160, 210));
        lFiller48.setText("   ");
        lFiller48.setMaximumSize(new java.awt.Dimension(32767, 15));
        lFiller48.setMinimumSize(new java.awt.Dimension(15, 16));
        lFiller48.setPreferredSize(new java.awt.Dimension(15, 16));
        ProjectLocationsCenterPanel4.add(lFiller48);

        PreviewButton.setFont(new java.awt.Font("Arial", 0, 12));
        PreviewButton.setLabel("Preview");
        PreviewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PreviewButtonActionPerformed(evt);
            }
        });

        ProjectLocationsCenterPanel4.add(PreviewButton);

        lFiller45.setBackground(new java.awt.Color(140, 160, 210));
        lFiller45.setText("   ");
        lFiller45.setMaximumSize(new java.awt.Dimension(15, 15));
        lFiller45.setMinimumSize(new java.awt.Dimension(15, 16));
        lFiller45.setPreferredSize(new java.awt.Dimension(15, 16));
        ProjectLocationsCenterPanel4.add(lFiller45);

        lFiller47.setBackground(new java.awt.Color(140, 160, 210));
        lFiller47.setText("   ");
        lFiller47.setMaximumSize(new java.awt.Dimension(15, 15));
        lFiller47.setMinimumSize(new java.awt.Dimension(15, 16));
        lFiller47.setPreferredSize(new java.awt.Dimension(15, 16));
        ProjectLocationsCenterPanel4.add(lFiller47);

        SouthButtonPanelFiller.add(ProjectLocationsCenterPanel4);

        UIChoicesBottomPanel4.setBackground(new java.awt.Color(140, 160, 210));
        UIChoicesBottomPanel4.setMinimumSize(new java.awt.Dimension(5, 5));
        UIChoicesBottomPanel4.setPreferredSize(new java.awt.Dimension(5, 5));
        SouthButtonPanelFiller.add(UIChoicesBottomPanel4);

        add(SouthButtonPanelFiller);

    }//GEN-END:initComponents

    private void formFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusLost
 
    }//GEN-LAST:event_formFocusLost

    private void PreviewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PreviewButtonActionPerformed
        try
        {
			EAPanel thePanel = (EAPanel)getParentComponent();
                ((EAPanel)thePanel.getParentComponent()).getDataUpdate(); 
                new ErrorPreviewAction();	
        }
        catch(Exception e)
        {
                e.printStackTrace();
        }
    }//GEN-LAST:event_PreviewButtonActionPerformed
 
    private static Object[] getStringArraysFromString(String textArrayString)
    {
        ArrayList aryList = new ArrayList();
        String tempString = "";
        
        while(textArrayString.indexOf(",")!=-1)
        {
            tempString = textArrayString.substring(0,textArrayString.indexOf(","));
            textArrayString = textArrayString.substring(textArrayString.indexOf(",") + 1);
            aryList.add(tempString);
        }
        aryList.add(textArrayString);
        return aryList.toArray();
    }   
     
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ImageDescriptionLabel3;
    private javax.swing.JLabel LeftUIFiller5;
    private javax.swing.JButton PreviewButton;
    private javax.swing.JPanel ProjectLocationsCenterPanel1;
    private javax.swing.JPanel ProjectLocationsCenterPanel4;
    private javax.swing.JPanel SouthButtonPanelFiller;
    private javax.swing.JPanel TryButtonPanel;
    private javax.swing.JPanel UIChoicesBottomPanel4;
    private javax.swing.JLabel lFiller24;
    private javax.swing.JLabel lFiller27;
    private javax.swing.JLabel lFiller45;
    private javax.swing.JLabel lFiller47;
    private javax.swing.JLabel lFiller48;
    private javax.swing.JLabel lFiller52;
    private javax.swing.JLabel lTryButtonMnemonic;
    private javax.swing.JLabel lTryButtonText;
    private javax.swing.JTextField tfUseEvaluationButtonMnemonic;
    private javax.swing.JTextField tfUseEvaluationButtonText;
    // End of variables declaration//GEN-END:variables
    
}
