/*
 * PaymentsHTMLFormInputsPanel.java
 *
 * Created on March 7, 2004, 5:33 PM
 */

package com.trinity.ea.design.payments.inputs;

import com.trinity.ea.design.common.panel.EAPanel;
import com.trinity.ea.design.payments.EADesignerPaymentsPanel;
import com.trinity.ea.design.common.sidebar.SBTab;
import com.trinity.ea.design.project.EADesignerProjectPanel;
import com.trinity.ea.design.common.sidebar.SBSpacer;
import com.trinity.ea.design.rules.builder.DesignerRuleBuilder;
import java.awt.Font;
import java.util.HashMap;
import java.util.Collections;
import java.util.Map;
import java.util.ArrayList;
import com.trinity.ea.design.common.borderline.ContentAreaHeaderPanel3;
import javax.swing.UIManager;
import javax.swing.plaf.ColorUIResource;
import javax.swing.plaf.InsetsUIResource;
import javax.swing.plaf.BorderUIResource;
import javax.swing.*;
import java.awt.*;


/**
 *
 * @author  aaronsc Trinity Software
 * Copyright ©2003-2004 Trinity Software. All rights reserved.
 */
public class PaymentsHTMLFormInputsPanel extends EAPanel {
    Map sbMap = Collections.synchronizedMap(new HashMap());  

    /** Creates new form PaymentsHTMLFormInputsPanel */
    public PaymentsHTMLFormInputsPanel() {
        initComponents();
	  initSidebar();
        setSelectedMenuItem(lPaymentMenuItem);
  	  setProjectData();   
    }

   private EAPanel TheContentPanelReference = new EAPanel();
   public void setContentPanel(EAPanel theContentPanel)
  {
    try
    {
	 getDataUpdate();
       TheContentPanelReference.setVisible(false);
       PaymentsSelectionContentPanel.remove(TheContentPanelReference);        
       TheContentPanelReference = theContentPanel;
       PaymentsSelectionContentPanel.add(TheContentPanelReference);     
       TheContentPanelReference.setVisible(true);

    }
    catch(Exception e)
    {
        System.out.println(e);
    }
  }   

  public synchronized void setProjectData()
  {
	try
	{
		TheContentPanelReference.setProjectData();
	}
	catch(Exception e)
	{
		e.printStackTrace();
	}
  }       
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents

        setLayout(new java.awt.BorderLayout());
        setBackground(new java.awt.Color(140, 160, 210));
 	  PaymentsMenuPanel = new javax.swing.JPanel();
	  PaymentsContentBottomPanel = new javax.swing.JPanel();
        LeftMenuPanelBottomPanel = new javax.swing.JPanel();
	  PaymentsUIMenuButtonPanel = new javax.swing.JPanel();
        PaymentsUIMenuButtonPanelTop = new SBTab(null,sbTabWidth, sbTabMenuTopSpaceFiller, sbTabLeftMargin, theCurrentMenuColor, theTextMenuColor, null, iconTextGap, theCurrentMenuColor, sbTabBottomBorderColor, sbTabRightInnerBorderColor, sbTabRightOuterBorderColor, sbTabIsOpaque);
        PaymentsUIMenuButtonPanelBottom = new SBSpacer(theCurrentMenuColor,sbTabTopBorderColor,theCurrentMenuColor,sbTabRightInnerBorderColor,sbTabRightOuterBorderColor,sbTabIsOpaque);
        PaymentsMenuLeftSpaceFiller = new javax.swing.JPanel();
	  PaymentsMenuContentPanel = new javax.swing.JPanel();
	  PaymentsSelectionContentPanel = new javax.swing.JPanel();

        PaymentsMenuPanel.setLayout(new java.awt.BorderLayout());
        PaymentsMenuPanel.setBackground(new java.awt.Color(140, 160, 210));
        PaymentsMenuPanel.setForeground(new java.awt.Color(255, 255, 255));
        PaymentsMenuPanel.setMaximumSize(new java.awt.Dimension(sbTabWidth, 32767));
        PaymentsMenuPanel.setMinimumSize(new java.awt.Dimension(sbTabWidth, 0));
        PaymentsMenuPanel.setPreferredSize(new java.awt.Dimension(sbTabWidth, 200));
        PaymentsUIMenuButtonPanel.setLayout(new javax.swing.BoxLayout(PaymentsUIMenuButtonPanel, javax.swing.BoxLayout.Y_AXIS));
        PaymentsUIMenuButtonPanel.setBackground(theCurrentMenuColor);
        PaymentsUIMenuButtonPanel.setForeground(theTextMenuColor);
        PaymentsUIMenuButtonPanel.setMaximumSize(new java.awt.Dimension(sbTabWidth, sbTabGroupHeight));
        PaymentsUIMenuButtonPanel.setMinimumSize(new java.awt.Dimension(sbTabWidth, sbTabGroupHeight));
        PaymentsUIMenuButtonPanel.setPreferredSize(new java.awt.Dimension(sbTabWidth, sbTabGroupHeight));

        LeftMenuPanelBottomPanel.setLayout(new java.awt.BorderLayout());
        LeftMenuPanelBottomPanel.setBackground(new java.awt.Color(140, 160, 210));
        LeftMenuPanelBottomPanel.setForeground(new java.awt.Color(255, 255, 255));
        LeftMenuPanelBottomPanel.setMaximumSize(new java.awt.Dimension(sbTabWidth, 100));
        LeftMenuPanelBottomPanel.setMinimumSize(new java.awt.Dimension(sbTabWidth, 100));
        LeftMenuPanelBottomPanel.setPreferredSize(new java.awt.Dimension(sbTabWidth, 100));

        PaymentsContentBottomPanel.setLayout(new java.awt.BorderLayout());
        PaymentsContentBottomPanel.setMaximumSize(new java.awt.Dimension(32767, 200));
        PaymentsContentBottomPanel.setMinimumSize(new java.awt.Dimension(0, 200));
        PaymentsContentBottomPanel.setPreferredSize(new java.awt.Dimension(500, 200));
        PaymentsContentBottomPanel.setBackground(new java.awt.Color(140, 160, 210));

        PaymentsSelectionContentPanel.setLayout(new java.awt.BorderLayout());
        PaymentsSelectionContentPanel.setBackground(new java.awt.Color(140, 160, 210));
        PaymentsSelectionContentPanel.setForeground(new java.awt.Color(255, 255, 255));

	  lPaymentMenuItem = new SBTab("Payment",sbTabWidth, sbTabHeight, sbTabLeftMargin, theCurrentMenuColor, theTextMenuColor, arrowIcon, iconTextGap, sbTabTopBorderColor, sbTabBottomBorderColor, sbTabRightInnerBorderColor, sbTabRightOuterBorderColor, sbTabIsOpaque);
    	  lResponseMenuItem = new SBTab("Response",sbTabWidth, sbTabHeight, sbTabLeftMargin, theCurrentMenuColor, theTextMenuColor, arrowIcon, iconTextGap, sbTabTopBorderColor, sbTabBottomBorderColor, sbTabRightInnerBorderColor, sbTabRightOuterBorderColor, sbTabIsOpaque);
	  lPaymentMenuItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lPaymentMenuItemMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lPaymentMenuItemMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lPaymentMenuItemMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lPaymentMenuItemMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lPaymentMenuItemMouseReleased(evt);
            }
        });

        PaymentsUIMenuButtonPanel.add(lPaymentMenuItem);

	  lResponseMenuItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lResponseMenuItemMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lResponseMenuItemMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lResponseMenuItemMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lResponseMenuItemMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lResponseMenuItemMouseReleased(evt);
            }
        });

        PaymentsUIMenuButtonPanel.add(lResponseMenuItem);

/**********************/

        LeftMenuPanelBottomPanel.add(PaymentsUIMenuButtonPanel, java.awt.BorderLayout.NORTH);
        LeftMenuPanelBottomPanel.add(PaymentsUIMenuButtonPanelBottom, java.awt.BorderLayout.CENTER);
        PaymentsMenuPanel.add(LeftMenuPanelBottomPanel, java.awt.BorderLayout.CENTER);
        PaymentsMenuPanel.add(PaymentsUIMenuButtonPanelTop, java.awt.BorderLayout.NORTH);
        PaymentsUIMenuButtonPanelBottom.setBackground(new java.awt.Color(140, 160, 210));
        PaymentsUIMenuButtonPanelBottom.setForeground(new java.awt.Color(255, 255, 255));
        PaymentsMenuLeftSpaceFiller.setBackground(new java.awt.Color(140, 160, 210));
        PaymentsMenuLeftSpaceFiller.setMinimumSize(new java.awt.Dimension(1, 10));
        PaymentsMenuLeftSpaceFiller.setPreferredSize(new java.awt.Dimension(1, 10));
        PaymentsMenuPanel.add(PaymentsMenuLeftSpaceFiller, java.awt.BorderLayout.WEST);
        PaymentsContentBottomPanel.add(PaymentsMenuPanel, java.awt.BorderLayout.WEST);
        PaymentsContentBottomPanel.add(PaymentsMenuPanel, java.awt.BorderLayout.WEST);
        PaymentsContentBottomPanel.add(PaymentsSelectionContentPanel, java.awt.BorderLayout.CENTER);
/**********************/
///////////////////////////
// add header here
	  contentPanel = new JPanel();
        contentPanel.setLayout(new java.awt.BorderLayout());
        contentPanel.add(PaymentsMenuPanel, java.awt.BorderLayout.WEST);
        contentPanel.add(PaymentsSelectionContentPanel, java.awt.BorderLayout.CENTER);
	  contentProjectPanel = new ContentAreaHeaderPanel3(contentPanel, sbTabWidth, theCurrentMenuColor, sbTabRightInnerBorderColor,sbTabRightOuterBorderColor,theSelectedMenuColor);
	add(contentProjectPanel, java.awt.BorderLayout.CENTER);

    }//GEN-END:initComponents

  public void getDataUpdate()
  {
	try
	{
		TheContentPanelReference.getDataUpdate();
	}
	catch(Exception e)
	{
		e.printStackTrace();
	}
  }       
 
    private void lPaymentMenuItemMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lPaymentMenuItemMouseReleased
	 setMouseReleasedMenuLabel(lPaymentMenuItem);
    }//GEN-LAST:event_lPaymentMenuItemMouseReleased

    private void lPaymentMenuItemMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lPaymentMenuItemMousePressed
        setMousePressedMenuLabel(lPaymentMenuItem);
    }//GEN-LAST:event_lPaymentMenuItemMousePressed

    private void lPaymentMenuItemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lPaymentMenuItemMouseExited
        setMouseExitedMenuLabel(lPaymentMenuItem);
    }//GEN-LAST:event_lPaymentMenuItemMouseExited

    private void lPaymentMenuItemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lPaymentMenuItemMouseEntered
        setMouseEnteredMenuLabel(lPaymentMenuItem);
    }//GEN-LAST:event_lPaymentMenuItemMouseEntered

    private void lPaymentMenuItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lPaymentMenuItemMouseClicked
	((EADesignerPaymentsPanel)getParentComponent()).setPaymentsHTMLFormInputsPropertyPanel();
 	setSelectedMenuItem(lPaymentMenuItem);
    }//GEN-LAST:event_lPaymentMenuItemMouseClicked

    private void lResponseMenuItemMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lResponseMenuItemMouseReleased
	 setMouseReleasedMenuLabel(lResponseMenuItem);
    }//GEN-LAST:event_lResponseMenuItemMouseReleased

    private void lResponseMenuItemMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lResponseMenuItemMousePressed
        setMousePressedMenuLabel(lResponseMenuItem);
    }//GEN-LAST:event_lResponseMenuItemMousePressed

    private void lResponseMenuItemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lResponseMenuItemMouseExited
        setMouseExitedMenuLabel(lResponseMenuItem);
    }//GEN-LAST:event_lResponseMenuItemMouseExited

    private void lResponseMenuItemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lResponseMenuItemMouseEntered
        setMouseEnteredMenuLabel(lResponseMenuItem);
    }//GEN-LAST:event_lResponseMenuItemMouseEntered

    private void lResponseMenuItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lResponseMenuItemMouseClicked
	((EADesignerPaymentsPanel)getParentComponent()).setPaymentResponseHTMLFormInputsPropertyPanel();
 	setSelectedMenuItem(lResponseMenuItem);
    }//GEN-LAST:event_lResponseMenuItemMouseClicked


 private Color theCurrentMenuColor = new Color(140,160,210);
 private Color theSelectedMenuColor = new Color(176, 191, 240);
 private Color theTextMenuColor = new Color(255, 255, 255);
 private boolean pressedSelected = false;
 private Icon arrowIcon = new javax.swing.ImageIcon(getClass().getResource("/images/arrow.gif"));
 private Icon arrowSelectedIcon = new javax.swing.ImageIcon(getClass().getResource("/images/arrow_selected.gif"));
 private Icon arrowMouseOverIcon = new javax.swing.ImageIcon(getClass().getResource("/images/arrow_mouseover.gif"));  
 private int iconTextGap = 5;
 private int sbTabMenuTopSpaceFiller = 15;
 private int sbTabLeftMargin = 5;
 private int sbTabWidth = 120;
 private int sbTabHeight = 25;
 private int sbTabGroupHeight = 50;
 private boolean sbTabIsOpaque=true;
 private Color sbTabTopBorderColor = new Color(198, 226, 253);
 private Color sbTabBottomBorderColor = new Color(100, 114, 149);
 private Color sbTabTopSelectedBorderColor = new Color(123,132,167);
 private Color sbTabBottomSelectedBorderColor = new Color(251, 255, 255);
 private Color sbTabRightInnerBorderColor = new java.awt.Color(84,94,118);
 private Color sbTabRightOuterBorderColor = new java.awt.Color(123,132,167);
 private Font sbTabFont = new java.awt.Font("Arial", 1, 12);
 private SBTab TheMenuLabelReference = new SBTab(null,sbTabWidth, sbTabHeight, sbTabLeftMargin, theCurrentMenuColor, theTextMenuColor, arrowIcon, iconTextGap, sbTabTopBorderColor, sbTabBottomBorderColor, sbTabRightInnerBorderColor, sbTabRightOuterBorderColor, sbTabIsOpaque);
 private SBTab thePressedLabelReference = null;
 private SBTab theEnteredLabelReference = null;

 private void setSelectedMenuItem(SBTab theMenuLabel)
  {
    try
    {
        TheMenuLabelReference.setBackgroundColor(theCurrentMenuColor);
	  TheMenuLabelReference.setTheTopBottomBorderColors(sbTabTopBorderColor, sbTabBottomBorderColor, sbTabRightInnerBorderColor, sbTabRightOuterBorderColor);
        TheMenuLabelReference.setTheIcon(arrowIcon);
        theMenuLabel.setBackgroundColor(theSelectedMenuColor);
        theMenuLabel.setTheIcon(arrowSelectedIcon);
	  theMenuLabel.setTheTopBottomBorderColors(sbTabTopSelectedBorderColor, sbTabBottomSelectedBorderColor, theSelectedMenuColor, theSelectedMenuColor);
        TheMenuLabelReference = theMenuLabel;
/*
                        try
                        {
                            setContentPanel((EAPanel)Class.forName(getSidebarComponentID(theMenuLabel.getComponentLocalizationID())).newInstance());
                        }
                        catch(InstantiationException e)
                        {
                            e.printStackTrace();
                        }   
                        catch(IllegalAccessException e)
                        {
                            e.printStackTrace();
                        }                      
                        catch(ClassNotFoundException e)
                        {
                            e.printStackTrace();
                        }   
*//*
	  theEAProperties.setSelectedIndex(0);
	  EAListItem eaListItemObj = theEAProperties.getSelectedEAListItem();
	  eaListItemObj.setSelectedMode();
*/ 
   }
    catch(Exception e)
    {
	e.printStackTrace();
    }
  }    
 
 boolean isEntered = false;
 private void setMouseEnteredMenuLabel(SBTab theEnteredLabel)
 {
    isEntered = true;
    try
    {
        theEnteredLabelReference = theEnteredLabel;
        if(theEnteredLabel.equals(TheMenuLabelReference)==false)
        {
            theEnteredLabel.setTheIcon(arrowMouseOverIcon);
            if(pressedSelected==true)
            {
                
                TheMenuLabelReference.setForegroundColor(theTextMenuColor);
            }
        }
        else
        {
            if(pressedSelected==true)
            {
                TheMenuLabelReference.setForegroundColor(theSelectedMenuColor);    
            }
        }
    }
    catch(Exception e)
    {
        System.out.println(e);
    }     
 }
 private void setMouseExitedMenuLabel(SBTab theExitedLabel)
 {
    isEntered = false;
    try
    {
        if(theExitedLabel.equals(TheMenuLabelReference)==false)
        {
            theExitedLabel.setTheIcon(arrowIcon);   
        }
        else
        {
            theEnteredLabelReference.setForegroundColor(theTextMenuColor);           
        }
    }
    catch(Exception e)
    {
        System.out.println(e);
    }  
 }

  private void setMousePressedMenuLabel(SBTab thePressedLabel)
 {
    try
    {
        thePressedLabelReference = thePressedLabel;
        if(thePressedLabel.equals(TheMenuLabelReference)==false)
        {
            thePressedLabel.setBackgroundColor(theSelectedMenuColor); 
	  	thePressedLabel.setTheTopBottomBorderColors(sbTabTopSelectedBorderColor, sbTabBottomSelectedBorderColor, theSelectedMenuColor, theSelectedMenuColor);
        }
        else
        {
            pressedSelected=true; 
            thePressedLabel.setForegroundColor(theSelectedMenuColor);
        }
    }
    catch(Exception e)
    {
        System.out.println(e);
    }  
 }
 
 
  private void setMouseReleasedMenuLabel(SBTab theReleasedLabel)
 {
    try
    {
        pressedSelected = false;
        if(theEnteredLabelReference.equals(thePressedLabelReference)==false || isEntered == false)
        {
            if(thePressedLabelReference.equals(TheMenuLabelReference)==false)
            {
                thePressedLabelReference.setBackgroundColor(theCurrentMenuColor);
		    thePressedLabelReference.setTheTopBottomBorderColors(sbTabTopBorderColor, sbTabBottomBorderColor, sbTabRightInnerBorderColor, sbTabRightOuterBorderColor);
            }
            if(thePressedLabelReference.equals(TheMenuLabelReference)==true)
            {           
                thePressedLabelReference.setForegroundColor(theTextMenuColor);
            }           
        }
        else
        {
            if(thePressedLabelReference.equals(TheMenuLabelReference)==true)
            {           
                thePressedLabelReference.setForegroundColor(theTextMenuColor);
            }
		else
		{
		    try
		    {
 		        TheMenuLabelReference.setBackgroundColor(theCurrentMenuColor);
			  TheMenuLabelReference.setTheTopBottomBorderColors(sbTabTopBorderColor, sbTabBottomBorderColor, sbTabRightInnerBorderColor, sbTabRightOuterBorderColor);
 		        TheMenuLabelReference.setTheIcon(arrowIcon);
 		        thePressedLabelReference.setTheIcon(arrowSelectedIcon);
 		        TheMenuLabelReference = thePressedLabelReference;
/*
                        try
                        {
                            setContentPanel((EAPanel)Class.forName(getSidebarComponentID(theReleasedLabel.getComponentLocalizationID())).newInstance());
                        }
                        catch(Exception e)
                        {
                            e.printStackTrace();
                        }   
*/
 		    }
		    catch(Exception e)
		    {
		        System.out.println(e);
		    }
		}
        }
        
    }
    catch(Exception e)
    {
        System.out.println(e);
    }  
 } 
    private static synchronized Object[] getStringArraysFromString(String textArrayString)
    {
        ArrayList aryList = new ArrayList();
        String tempString = "";
        try
        {
            while(textArrayString.indexOf(",")!=-1)
            {
                tempString = textArrayString.substring(0,textArrayString.indexOf(","));
                textArrayString = textArrayString.substring(textArrayString.indexOf(",") + 1);
                aryList.add(tempString);
            }
            aryList.add(textArrayString);
            aryList.trimToSize();
        }
        catch(NullPointerException e)
        {
         
        }

        return aryList.toArray();
    }  

private synchronized String getSidebarComponentID(String compRefID)
{
	try
	{
		return (String)sbMap.get(compRefID);
	}
	catch(Exception e)
	{
	e.printStackTrace();
	}
	return "";
}

private synchronized void initSidebar()
{
try
{
	Object[] sbUIStrings = getStringArraysFromString(DesignerRuleBuilder.get("sbPaymentsHTMLFormStrings"));
	Object[] sbUIActions = getStringArraysFromString(DesignerRuleBuilder.get("sbPaymentsHTMLFormActionPanels"));
//sbMap

                    for(int i = 0;i<sbUIStrings.length;i++)
                    {
                        try
				{
					sbMap.put((String)sbUIStrings[i],(String)sbUIActions[i]);
					//LeftMenuButtonPanel.add(new SBTab((String)sbUIStrings[i],sbTabWidth, sbTabHeight, sbTabLeftMargin, theCurrentMenuColor, theTextMenuColor, arrowIcon, iconTextGap, sbTabTopBorderColor, sbTabBottomBorderColor, sbTabRightInnerBorderColor, sbTabRightOuterBorderColor, sbTabIsOpaque));
				}
				catch(Exception e)
				{
					sbMap.put((String)sbUIStrings[i],"");
				} 
                    }
}
catch(Exception e)
{
	e.printStackTrace();
}
}
   
public void setPaymentSelected()
{
	setSelectedMenuItem(lPaymentMenuItem);
}
public void setResponseSelected()
{
	setSelectedMenuItem(lResponseMenuItem);
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private SBSpacer PaymentsUIMenuButtonPanelBottom;
    private SBTab PaymentsUIMenuButtonPanelTop;
    private SBTab lPaymentMenuItem;
    private SBTab lResponseMenuItem;
    private ContentAreaHeaderPanel3 contentProjectPanel;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JPanel PaymentsUIMenuButtonPanel;
    private javax.swing.JPanel PaymentsMenuContentPanel;
    private javax.swing.JPanel PaymentsMenuLeftSpaceFiller;
    private javax.swing.JPanel PaymentsMenuPanel;
    private javax.swing.JPanel PaymentsSelectionContentPanel;
    private javax.swing.JPanel LeftMenuPanelBottomPanel;
    private javax.swing.JPanel PaymentsContentBottomPanel;
/////////////////////////// 
   // End of variables declaration//GEN-END:variables
    
}
