/*
 * MainFontPanel.java
 *
 * Created on October 11, 2004, 3:25 PM
 */

package com.trinity.ea.design.project.lookandfeel.fonts;
import com.trinity.ea.design.common.panel.EAPanel;
import com.trinity.ea.design.project.lookandfeel.fonts.FontsPanel;
import com.trinity.ea.design.project.lookandfeel.fonts.RefundFontsPanel;
import com.trinity.ea.design.project.lookandfeel.fonts.PaymentsFontsPanel;
import com.trinity.ea.design.project.lookandfeel.fonts.RegistrationFontsPanel;
import com.trinity.ea.design.project.lookandfeel.fonts.OptinFontsPanel;
import com.trinity.ea.design.project.lookandfeel.fonts.PrivacyFontsPanel;
import com.trinity.ea.design.project.lookandfeel.fonts.ErrorFontsPanel;
import com.trinity.ea.design.project.lookandfeel.fonts.InformationFontsPanel;
import javax.swing.*;

/**
 *
 * @author  aaronsc Trinity Software
 * Copyright ©2003-2004 Trinity Software. All rights reserved.
 */
public class MainFontPanel extends EAPanel {
    
    /** Creates new form MainColorPanel */
    public MainFontPanel() {
        initComponents();
    }

    public synchronized void getDataUpdate()
    {
	  try
        {
            //ProjectManager.saveTempNow(); 
		startupWindowPanel.getDataUpdate();
		paymentsTab.getDataUpdate();
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }

    public synchronized void setProjectData()
    {
        try
        {
		startupWindowPanel.setProjectData();
		startupWindowPanel.setParentComponent(this);
		paymentsTab.setProjectData();
		paymentsTab.setParentComponent(this);
		refundPolicyTab.setProjectData();
		refundPolicyTab.setParentComponent(this);
		registrationPanel.setProjectData();
		registrationPanel.setParentComponent(this);
		optinPanel.setProjectData();
		optinPanel.setParentComponent(this);
		privacyPolicyPanel.setProjectData();
		privacyPolicyPanel.setParentComponent(this);
		errorPanel.setProjectData();
		errorPanel.setParentComponent(this);
		informationPanel.setProjectData();
		informationPanel.setParentComponent(this);
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }   
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        ColorsTabbedPane = new javax.swing.JTabbedPane();
        startupWindowPanel = new FontsPanel();
        paymentsTab = new PaymentsFontsPanel();
        refundPolicyTab = new RefundFontsPanel();
        registrationPanel = new RegistrationFontsPanel();
        optinPanel = new OptinFontsPanel();
        privacyPolicyPanel = new PrivacyFontsPanel();
        errorPanel = new ErrorFontsPanel();
        informationPanel = new InformationFontsPanel();

        setLayout(new java.awt.BorderLayout());

        setBackground(new java.awt.Color(140, 160, 210));
        ColorsTabbedPane.setBackground(new java.awt.Color(140, 160, 210));

        ColorsTabbedPane.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
try
{
	  ((javax.swing.JViewport)ColorsTabbedPane.getComponents()[0]).getView().setBackground(new java.awt.Color(140, 160, 210));
}
catch(Exception e){}         ColorsTabbedPane.setFont(new java.awt.Font("Arial", 0, 12));
        ColorsTabbedPane.addTab("Startup", startupWindowPanel);

        ColorsTabbedPane.addTab("Payment", paymentsTab);

        ColorsTabbedPane.addTab("Refund Policy", refundPolicyTab);

        ColorsTabbedPane.addTab("Registration", registrationPanel);

        ColorsTabbedPane.addTab("Opt-In", optinPanel);

        ColorsTabbedPane.addTab("Privacy Policy", privacyPolicyPanel);

        ColorsTabbedPane.addTab("Infomation Dialog", informationPanel);

        ColorsTabbedPane.addTab("Error Dialog", errorPanel);

        add(ColorsTabbedPane, java.awt.BorderLayout.CENTER);

    }//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane ColorsTabbedPane;
    private OptinFontsPanel optinPanel;
    private ErrorFontsPanel errorPanel;
    private InformationFontsPanel informationPanel;
    private PaymentsFontsPanel paymentsTab;
    private PrivacyFontsPanel privacyPolicyPanel;
    private RefundFontsPanel refundPolicyTab;
    private RegistrationFontsPanel registrationPanel;
    private FontsPanel startupWindowPanel;
    // End of variables declaration//GEN-END:variables
    
}
