/*
 * TopBottomPixelGroupPanel.java
 *
 * Created on March 15, 2004, 5:26 PM
 */

package com.trinity.ea.design.common.corners.upperleft;
import java.awt.Color;
import javax.swing.JPanel;
import java.awt.Dimension;
import javax.swing.BoxLayout;
import java.awt.BorderLayout;

/**
 *
 * @author  aaronsc Trinity Software
 * CopyBottom ©2003-2004 Trinity Software. All Bottoms reserved.
 */
public class TopBottomPixelGroupPanel extends javax.swing.JPanel {
    
    /** Creates new form BottomTopPixelGroupPanel */
    public TopBottomPixelGroupPanel(JPanel TopPanel, JPanel BottomPanel) {
        initComponents(TopPanel,BottomPanel);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents(JPanel TopPanel, JPanel BottomPanel) {//GEN-BEGIN:initComponents

        setLayout(new java.awt.BorderLayout());

        setMaximumSize(new java.awt.Dimension(4, 4));
        setMinimumSize(new java.awt.Dimension(4, 4));
        setPreferredSize(new java.awt.Dimension(4, 4));
        setOpaque(false);
        TopPanel.setMaximumSize(new java.awt.Dimension(4, 3));
        TopPanel.setMinimumSize(new java.awt.Dimension(4, 3));
        TopPanel.setPreferredSize(new java.awt.Dimension(4, 3));

        BottomPanel.setMaximumSize(new java.awt.Dimension(4, 1));
        BottomPanel.setMinimumSize(new java.awt.Dimension(4, 1));
        BottomPanel.setPreferredSize(new java.awt.Dimension(4, 1));


        add(TopPanel, java.awt.BorderLayout.CENTER);
        add(BottomPanel, java.awt.BorderLayout.SOUTH);

    }//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel TopPanel;
    private javax.swing.JPanel BottomPanel;
    // End of variables declaration//GEN-END:variables
    
}
