/*
 * dlgCustomerBillingResponsePanelFailure.java
 *
 * Created on October 30, 2003, 2:31 AM
 */

package com.trinity.ea.forms.payment;
import com.trinity.ea.forms.payment.PaymentFailureValidationHeaderPanel;
import com.trinity.ea.forms.payment.PaymentFailedCenterPanel;
import com.trinity.ea.forms.payment.PaymentFailureRightPanel;
import com.trinity.ea.forms.payment.BottomFillerPanelPaymentFailure;
import com.trinity.ea.forms.payment.LeftFillerPanelPaymentFailure;
import com.trinity.ea.rules.reader.EncryptedRuleReader;
import com.trinity.ea.forms.gui.swing.ImageBackgroundBorder;
import javax.swing.border.Border;
import javax.imageio.*;
import java.util.ArrayList;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.util.*;
import java.io.ByteArrayInputStream;

/**
 *
 * @author  aaronsc Trinity Software
 * Copyright ©2003-2005 Trinity Software. All rights reserved.
 */
public class dlgCustomerBillingResponsePanelFailure extends javax.swing.JDialog {
    private Map respMap = null;    
    /** Creates new form dlgCustomerBillingResponsePanelFailure */
    public dlgCustomerBillingResponsePanelFailure(Map responseMap, java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        respMap=responseMap;   
       initComponents();
        //setSize(484,302);
        // Get the size of the screen
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        setResizable(false);
        // Determine the new location of the window
        int w = getSize().width;
        int h = getSize().height;
        int x = (dim.width-w)/2;
        int y = (dim.height-h)/2;

        // Move the window
        setLocation(x, y);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        CenterPanel = new com.trinity.ea.forms.payment.PaymentFailedCenterPanel(respMap);
        RootPanel = new javax.swing.JPanel();
        TopPanel = new com.trinity.ea.forms.payment.PaymentFailureValidationHeaderPanel();
        BottomPanel = new javax.swing.JPanel();
        LowerBottomPanel = new com.trinity.ea.forms.payment.BottomFillerPanelPaymentFailure();
        LeftPanel = new com.trinity.ea.forms.payment.LeftFillerPanelPaymentFailure();
        RightPanel = new com.trinity.ea.forms.payment.PaymentFailureRightPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(EncryptedRuleReader.getLocaleString("paymentFailureResponsePanelTitle"));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });


        RootPanel.setLayout(new javax.swing.BoxLayout(RootPanel, javax.swing.BoxLayout.Y_AXIS));

        RootPanel.setMaximumSize(new java.awt.Dimension(476, 270));
        RootPanel.setMinimumSize(new java.awt.Dimension(476, 270));
        RootPanel.setPreferredSize(new java.awt.Dimension(476, 270));
        TopPanel.setMaximumSize(new java.awt.Dimension(476, 107));
        TopPanel.setMinimumSize(new java.awt.Dimension(476, 107));
        TopPanel.setPreferredSize(new java.awt.Dimension(476, 107));
        RootPanel.add(TopPanel);

        BottomPanel.setLayout(new javax.swing.BoxLayout(BottomPanel, javax.swing.BoxLayout.X_AXIS));

        LeftPanel.setMaximumSize(new java.awt.Dimension(13, 168));
        LeftPanel.setMinimumSize(new java.awt.Dimension(13, 168));
        LeftPanel.setPreferredSize(new java.awt.Dimension(13, 168));
        
        BottomPanel.add(LeftPanel);

        LowerBottomPanel.setMaximumSize(new java.awt.Dimension(476, 7));
        LowerBottomPanel.setMinimumSize(new java.awt.Dimension(476, 7));
        LowerBottomPanel.setPreferredSize(new java.awt.Dimension(476, 7));

        CenterPanel.setMaximumSize(new java.awt.Dimension(350, 168));
        CenterPanel.setMinimumSize(new java.awt.Dimension(350, 168));
        CenterPanel.setPreferredSize(new java.awt.Dimension(350, 168));
	  CenterPanel.setLayout(null);
	try
	{ 
if(EncryptedRuleReader.getLocaleString("paymentRespFailureBackgroundImagePath")!=null)
{
 	if(EncryptedRuleReader.getLocaleString("paymentRespFailureBackgroundImagePath").equalsIgnoreCase("")==false)
	{
        final Border bkgrnd = new ImageBackgroundBorder(ImageIO.read(new ByteArrayInputStream(EncryptedRuleReader.getImage(getClass().getResource(EncryptedRuleReader.getLocaleString("paymentRespFailureBackgroundImagePath"))))));
	  if(bkgrnd!=null)
	  {
        Runnable r = new Runnable() {
            public void run() {
			try
			{
                		CenterPanel.setBorder(bkgrnd);
                		CenterPanel.repaint();
			}
			catch(Exception e)
			{

			}
            }
        };
        SwingUtilities.invokeLater(r);
	  }
	}
}
	}
	catch(Exception e)
	{
		e.printStackTrace();
	}
        BottomPanel.add(CenterPanel);
	  if(EncryptedRuleReader.get("paymentBackgroundColor")!=null)
	  {
		if(EncryptedRuleReader.get("paymentBackgroundColor").equalsIgnoreCase("")==false)
		{
			Object[] tmpArray = getStringArraysFromString(EncryptedRuleReader.get("paymentBackgroundColor"));
			getContentPane().setBackground(new java.awt.Color(new Integer((String)tmpArray[0]).intValue(),new Integer((String)tmpArray[1]).intValue(),new Integer((String)tmpArray[2]).intValue()));
			RootPanel.setBackground(new java.awt.Color(new Integer((String)tmpArray[0]).intValue(),new Integer((String)tmpArray[1]).intValue(),new Integer((String)tmpArray[2]).intValue()));
		}
	  }
        RightPanel.setMaximumSize(new java.awt.Dimension(113, 168));
        RightPanel.setMinimumSize(new java.awt.Dimension(113, 168));
        RightPanel.setPreferredSize(new java.awt.Dimension(113, 168));
        BottomPanel.add(RightPanel);

        RootPanel.add(BottomPanel);

        getContentPane().add(RootPanel, java.awt.BorderLayout.CENTER);
        getContentPane().add(LowerBottomPanel, java.awt.BorderLayout.SOUTH);
   	try
	{
	  	  applyComponentOrientation(ComponentOrientation.getOrientation(EncryptedRuleReader.getLocale()));
	}
	catch(Exception e)
	{
		e.printStackTrace();
	} 
        pack();
    }//GEN-END:initComponents
    
    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog
    
    /**
     * @param args the command line arguments
     */
  //  public static void main(String args[]) {
  //      new dlgCustomerBillingResponsePanelFailure(null,new javax.swing.JFrame(), true).show();
  //  }

    private static Object[] getStringArraysFromString(String textArrayString)
    {
        ArrayList aryList = new ArrayList();
        String tempString = "";
        
        while(textArrayString.indexOf(",")!=-1)
        {
            tempString = textArrayString.substring(0,textArrayString.indexOf(","));
            textArrayString = textArrayString.substring(textArrayString.indexOf(",") + 1);
            aryList.add(tempString);
        }
        aryList.add(textArrayString);
        return aryList.toArray();
    }       

    public void paint(Graphics g)
    {
	Graphics2D g2 = (Graphics2D) g;
	g2.setRenderingHint(RenderingHints.KEY_TEXT_ANTIALIASING,RenderingHints.VALUE_TEXT_ANTIALIAS_ON);
	super.paint(g);
    } 
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BottomPanel;
    private com.trinity.ea.forms.payment.PaymentFailedCenterPanel CenterPanel;
    private com.trinity.ea.forms.payment.LeftFillerPanelPaymentFailure LeftPanel;
    private com.trinity.ea.forms.payment.BottomFillerPanelPaymentFailure LowerBottomPanel;
    private com.trinity.ea.forms.payment.PaymentFailureRightPanel RightPanel;
    private javax.swing.JPanel RootPanel;
    private com.trinity.ea.forms.payment.PaymentFailureValidationHeaderPanel TopPanel;

    // End of variables declaration//GEN-END:variables
    
}
