/*
 * EncryptionConfigurationPanel.java
 *
 * Created on April 22, 2004, 4:18 PM
 */

package com.trinity.ea.design.messaging.encrypt;
import com.trinity.ea.design.common.panel.EAPanel;
import com.trinity.ea.design.common.file.ProjectManager;
import com.trinity.ea.design.common.panel.DataContentPanel;
import com.trinity.ea.design.common.util.PasswordGenerator;
import javax.swing.JSpinner;
import javax.swing.SpinnerNumberModel;
import javax.swing.*;
import java.awt.*;

/**
 *
 * @author  aaronsc Trinity Software
 * Copyright ©2003-2004 Trinity Software. All rights reserved.
 */
public class EncryptionConfigurationPanel extends EAPanel {

    private Color backgroundColor = new java.awt.Color(140, 160, 210);   
 
    /** Creates new form EncryptionConfigurationPanel */
    public EncryptionConfigurationPanel() {
        initComponents();
 	setProjectData();       
    }

   public synchronized void getDataUpdate()
   {
        try
        {
		// Messaging Support Password Seed and Password Count Functionality variables
		ProjectManager.putTempNoFileWrite("msgPwdSeed", tfSoftwareTitle1.getText());
		SpinnerNumberModel sm = (SpinnerNumberModel)spinMaxRegistrationAttempts.getModel();
		ProjectManager.putTempNoFileWrite("msgPwdCount", String.valueOf(sm.getNumber().intValue()));
		ProjectManager.saveTempNow();
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
  }   

    public synchronized void setProjectData()
    {
        try
        {
		// Registration Code Serial Number TextField  
            if(ProjectManager.get("msgPwdSeed")!=null)
            {
		    tfSoftwareTitle1.setOpaque(true);
		    tfSoftwareTitle1.setText(ProjectManager.get("msgPwdSeed"));
		    tfSoftwareTitle1.setCaretPosition(0);
            }
            if(ProjectManager.get("msgPwdCount")!=null)
            {
		    spinMaxRegistrationAttempts.setOpaque(true);
   		    spinMaxRegistrationAttempts.setModel(new SpinnerNumberModel(Integer.valueOf(ProjectManager.get("msgPwdCount")),new Integer(1),new Integer(999),new Integer(1)));
		}
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        RegistrationSettingsPanelItem = new javax.swing.JPanel();
        lFiller12 = new javax.swing.JLabel();
        lSoftwareTitle1 = new javax.swing.JLabel();
        lFiller13 = new javax.swing.JLabel();
        tfSoftwareTitle1 = new javax.swing.JTextField();
        lFiller18 = new javax.swing.JLabel();
        btnGenerateEvaluationUnlockCode = new javax.swing.JButton();
        btnGeneratePasswordCount = new javax.swing.JButton();
        lFiller14 = new javax.swing.JLabel();
        ProjectInformationTopPanel4 = new javax.swing.JPanel();
        lFiller15 = new javax.swing.JLabel();
        lSoftwareTitle2 = new javax.swing.JLabel();
        lFiller16 = new javax.swing.JLabel();
        lFiller17 = new javax.swing.JLabel();
        spinMaxRegistrationAttempts = new JSpinner(new SpinnerNumberModel(new Integer(10),new Integer(1),new Integer(1000000),new Integer(1)));

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        setBackground(new java.awt.Color(140, 160, 210));
        RegistrationSettingsPanelItem.setLayout(new javax.swing.BoxLayout(RegistrationSettingsPanelItem, javax.swing.BoxLayout.X_AXIS));

        RegistrationSettingsPanelItem.setBackground(new java.awt.Color(140, 160, 210));
        RegistrationSettingsPanelItem.setMaximumSize(new java.awt.Dimension(2147483647, 30));
        RegistrationSettingsPanelItem.setMinimumSize(new java.awt.Dimension(300, 30));
        RegistrationSettingsPanelItem.setPreferredSize(new java.awt.Dimension(800, 30));
        lFiller12.setBackground(new java.awt.Color(140, 160, 210));
        lFiller12.setText("   ");
        lFiller12.setMaximumSize(new java.awt.Dimension(10, 15));
        lFiller12.setMinimumSize(new java.awt.Dimension(10, 15));
        lFiller12.setPreferredSize(new java.awt.Dimension(10, 15));
        RegistrationSettingsPanelItem.add(lFiller12);

        lSoftwareTitle1.setBackground(new java.awt.Color(140, 160, 210));
        lSoftwareTitle1.setFont(new java.awt.Font("Arial", 0, 12));
        lSoftwareTitle1.setText("Encryption Password Seed:");
        lSoftwareTitle1.setMaximumSize(new java.awt.Dimension(175, 15));
        lSoftwareTitle1.setMinimumSize(new java.awt.Dimension(175, 15));
        lSoftwareTitle1.setPreferredSize(new java.awt.Dimension(175, 15));
        RegistrationSettingsPanelItem.add(lSoftwareTitle1);

        lFiller13.setBackground(new java.awt.Color(140, 160, 210));
        lFiller13.setText("   ");
        lFiller13.setMaximumSize(new java.awt.Dimension(10, 15));
        lFiller13.setMinimumSize(new java.awt.Dimension(10, 15));
        lFiller13.setPreferredSize(new java.awt.Dimension(10, 15));
        //RegistrationSettingsPanelItem.add(lFiller13);

        tfSoftwareTitle1.setFont(new java.awt.Font("Arial", 0, 12));
        tfSoftwareTitle1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tfSoftwareTitle1.setText("<Undefined Serial Number>");
        tfSoftwareTitle1.setMaximumSize(new java.awt.Dimension(200, 20));
        tfSoftwareTitle1.setMinimumSize(new java.awt.Dimension(200, 20));
        tfSoftwareTitle1.setPreferredSize(new java.awt.Dimension(200, 20));
        RegistrationSettingsPanelItem.add(tfSoftwareTitle1);

        lFiller18.setBackground(new java.awt.Color(140, 160, 210));
        lFiller18.setMaximumSize(new java.awt.Dimension(5, 15));
        lFiller18.setMinimumSize(new java.awt.Dimension(5, 15));
        lFiller18.setPreferredSize(new java.awt.Dimension(5, 15));
        RegistrationSettingsPanelItem.add(lFiller18);

        btnGenerateEvaluationUnlockCode.setText("Generate");
        btnGenerateEvaluationUnlockCode.setMnemonic('G');
        btnGenerateEvaluationUnlockCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateEvaluationUnlockCodeActionPerformed(evt);
            }
        });
        RegistrationSettingsPanelItem.add(btnGenerateEvaluationUnlockCode);

        lFiller14.setBackground(new java.awt.Color(140, 160, 210));
        lFiller14.setText("   ");
        lFiller14.setMaximumSize(new java.awt.Dimension(2147483647, 15));
        lFiller14.setMinimumSize(new java.awt.Dimension(15, 15));
        lFiller14.setPreferredSize(new java.awt.Dimension(15, 15));
        RegistrationSettingsPanelItem.add(lFiller14);

        add(RegistrationSettingsPanelItem);

        ProjectInformationTopPanel4.setLayout(new javax.swing.BoxLayout(ProjectInformationTopPanel4, javax.swing.BoxLayout.X_AXIS));

        ProjectInformationTopPanel4.setBackground(new java.awt.Color(140, 160, 210));
        ProjectInformationTopPanel4.setMaximumSize(new java.awt.Dimension(2147483647, 30));
        ProjectInformationTopPanel4.setMinimumSize(new java.awt.Dimension(300, 30));
        ProjectInformationTopPanel4.setPreferredSize(new java.awt.Dimension(800, 30));
        lFiller15.setBackground(new java.awt.Color(140, 160, 210));
        lFiller15.setText("   ");
        lFiller15.setMaximumSize(new java.awt.Dimension(10, 15));
        lFiller15.setMinimumSize(new java.awt.Dimension(10, 15));
        lFiller15.setPreferredSize(new java.awt.Dimension(10, 15));
        ProjectInformationTopPanel4.add(lFiller15);

        lSoftwareTitle2.setBackground(new java.awt.Color(140, 160, 210));
        lSoftwareTitle2.setFont(new java.awt.Font("Arial", 0, 12));
        lSoftwareTitle2.setText("Encryption Password Count:");
        lSoftwareTitle2.setMaximumSize(new java.awt.Dimension(175, 15));
        lSoftwareTitle2.setMinimumSize(new java.awt.Dimension(175, 15));
        lSoftwareTitle2.setPreferredSize(new java.awt.Dimension(175, 15));
        ProjectInformationTopPanel4.add(lSoftwareTitle2);

        lFiller16.setBackground(new java.awt.Color(140, 160, 210));
        lFiller16.setText("   ");
        lFiller16.setMaximumSize(new java.awt.Dimension(300, 15));
        lFiller16.setMinimumSize(new java.awt.Dimension(10, 15));
        lFiller16.setPreferredSize(new java.awt.Dimension(10, 15));

        spinMaxRegistrationAttempts.setMaximumSize(new java.awt.Dimension(40, 20));
        spinMaxRegistrationAttempts.setMinimumSize(new java.awt.Dimension(40, 20));
        spinMaxRegistrationAttempts.setPreferredSize(new java.awt.Dimension(40, 20));
        ProjectInformationTopPanel4.add(spinMaxRegistrationAttempts);

        ProjectInformationTopPanel4.add(lFiller16);

        btnGeneratePasswordCount.setText("Generate");
        btnGeneratePasswordCount.setMnemonic('e');
        btnGeneratePasswordCount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGeneratePasswordCountActionPerformed(evt);
            }
        });
        ProjectInformationTopPanel4.add(btnGeneratePasswordCount);

        lFiller17.setBackground(new java.awt.Color(140, 160, 210));
        lFiller17.setText("   ");
        lFiller17.setMaximumSize(new java.awt.Dimension(2147483647, 15));
        lFiller17.setMinimumSize(new java.awt.Dimension(15, 15));
        lFiller17.setPreferredSize(new java.awt.Dimension(15, 15));
        ProjectInformationTopPanel4.add(lFiller17);

        add(ProjectInformationTopPanel4);

    }//GEN-END:initComponents

    private void btnGenerateEvaluationUnlockCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateEvaluationUnlockCodeActionPerformed
	try
	{
           tfSoftwareTitle1.setText(PasswordGenerator.generate(24));
	}
	catch(Exception e)
	{
		e.printStackTrace();
	}
    }//GEN-LAST:event_btnGenerateEvaluationUnlockCodeActionPerformed
    
     private void btnGeneratePasswordCountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGeneratePasswordCountActionPerformed
	try
	{
	    spinMaxRegistrationAttempts.setModel(new SpinnerNumberModel(new Integer(ProjectManager.getRandomInt(999)),new Integer(1),new Integer(999),new Integer(1)));
	}
	catch(Exception e)
	{
		e.printStackTrace();
	}
    }//GEN-LAST:event_btnGeneratePasswordCountActionPerformed
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ProjectInformationTopPanel4;
    private javax.swing.JPanel RegistrationSettingsPanelItem;
    private javax.swing.JButton btnGenerateEvaluationUnlockCode;
    private javax.swing.JButton btnGeneratePasswordCount;
    private javax.swing.JLabel lFiller12;
    private javax.swing.JLabel lFiller13;
    private javax.swing.JLabel lFiller14;
    private javax.swing.JLabel lFiller15;
    private javax.swing.JLabel lFiller16;
    private javax.swing.JLabel lFiller17;
    private javax.swing.JLabel lFiller18;
    private javax.swing.JLabel lSoftwareTitle1;
    private javax.swing.JLabel lSoftwareTitle2;
    private javax.swing.JTextField tfSoftwareTitle1;
    private javax.swing.JSpinner spinMaxRegistrationAttempts;
    // End of variables declaration//GEN-END:variables

   /* EADesignerRegistrationPanel parentObj = null;
    public void setMasterStatusController(EADesignerRegistrationPanel parentObject)
    {
        parentObj = parentObject;
    }
*/
}
