/*
 * dlgCustomerBillingResponsePanelSuccess.java
 *
 * Created on October 30, 2003, 2:31 AM
 */

package com.trinity.ea.design.payments.preview;
import com.trinity.ea.design.payments.preview.payment.PaymentValidationHeaderPanel;
import com.trinity.ea.design.payments.preview.payment.PaymentSuccessCenterPanel;
import com.trinity.ea.design.payments.preview.payment.PaymentSuccessFooterPanel;
import com.trinity.ea.design.common.file.ProjectManager;
import com.trinity.ea.design.payments.preview.gui.swing.ImageBackgroundBorder;
import javax.swing.border.Border;
import javax.imageio.*;
import java.util.ArrayList;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.util.*;
import java.net.URL;
import java.net.MalformedURLException;

/**
 *
 * @author  aaronsc Trinity Software
 * Copyright ©2003-2005 Trinity Software. All rights reserved.
 */
public class dlgCustomerBillingResponsePanelSuccess extends javax.swing.JDialog {
    private Map respMap = null;      
    /** Creates new form dlgCustomerBillingResponsePanelSuccess */
    public dlgCustomerBillingResponsePanelSuccess(Map responseMap, java.awt.Frame parent, boolean modal) {
        super(parent, modal);
	updateUIExpressionDefines();
        respMap=responseMap;
        initComponents();
        //setSize(528,458);
        setResizable(false);
                // Get the size of the screen
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();

        // Determine the new location of the window
        int w = getSize().width;
        int h = getSize().height;
        int x = (dim.width-w)/2;
        int y = (dim.height-h)/2;

        // Move the window
        setLocation(x, y);
   	try
	{
	  	  //applyComponentOrientation(ComponentOrientation.getOrientation(ProjectManager.getLocale()));
	}
	catch(Exception e)
	{
		e.printStackTrace();
	} 
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        RootPanel = new javax.swing.JPanel();
        PaymentSuccessCenterPanel1 = new com.trinity.ea.design.payments.preview.payment.PaymentSuccessCenterPanel(respMap);
        PaymentValidationHeaderPanel1 = new com.trinity.ea.design.payments.preview.payment.PaymentValidationHeaderPanel();
        PaymentSuccessFooterPanel1 = new com.trinity.ea.design.payments.preview.payment.PaymentSuccessFooterPanel();
	  RootPanel.setLayout(new javax.swing.BoxLayout(RootPanel, javax.swing.BoxLayout.Y_AXIS));
	  PaymentSuccessCenterPanel1.setLayout(null);
        PaymentSuccessCenterPanel1.setPreferredSize(new java.awt.Dimension(519, 294));
        PaymentValidationHeaderPanel1.setPreferredSize(new java.awt.Dimension(519, 102));
        PaymentSuccessFooterPanel1.setPreferredSize(new java.awt.Dimension(519, 42));
	try
	{ 
if(ProjectManager.get("paymentRespSuccessBackgroundImagePath")!=null)
{
 	if(ProjectManager.get("paymentRespSuccessBackgroundImagePath").equalsIgnoreCase("")==false)
	{
	try
	{
        final Border bkgrnd = new ImageBackgroundBorder(ImageIO.read(new URL(ProjectManager.get("paymentRespSuccessBackgroundImagePath"))));
	  if(bkgrnd!=null)
	  {
        Runnable r = new Runnable() {
            public void run() {
                		PaymentSuccessCenterPanel1.setBorder(bkgrnd);
                		PaymentSuccessCenterPanel1.repaint();
            }
        };
        SwingUtilities.invokeLater(r);
	  }
	}
	catch(Exception e)
	{

	}
	}
}
	}
	catch(Exception e)
	{
		e.printStackTrace();
	}


        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
	  if(ProjectManager.get("paymentSuccessResponsePanelTitle")!=null)
	  {
	        setTitle(replaceUIExpressions(ProjectManager.get("paymentSuccessResponsePanelTitle")));
	  }

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

	  if(ProjectManager.get("paymentBackgroundColor")!=null)
	  {
		if(ProjectManager.get("paymentBackgroundColor").equalsIgnoreCase("")==false)
		{
			Object[] tmpArray = getStringArraysFromString(ProjectManager.get("paymentBackgroundColor"));
			getContentPane().setBackground(new java.awt.Color(new Integer((String)tmpArray[0]).intValue(),new Integer((String)tmpArray[1]).intValue(),new Integer((String)tmpArray[2]).intValue()));
			RootPanel.setBackground(new java.awt.Color(new Integer((String)tmpArray[0]).intValue(),new Integer((String)tmpArray[1]).intValue(),new Integer((String)tmpArray[2]).intValue()));
		}
	  }
        RootPanel.add(PaymentValidationHeaderPanel1);
        RootPanel.add(PaymentSuccessCenterPanel1);
        RootPanel.add(PaymentSuccessFooterPanel1);
        getContentPane().add(RootPanel, java.awt.BorderLayout.CENTER);

        pack();
    }//GEN-END:initComponents
    
    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
				try
				{
        				setVisible(false);
        				dispose();
					UIManager.setLookAndFeel("javax.swing.plaf.metal.MetalLookAndFeel");
				}
				catch(Exception e)
				{

				}
    }//GEN-LAST:event_closeDialog

    private static Object[] getStringArraysFromString(String textArrayString)
    {
        ArrayList aryList = new ArrayList();
        String tempString = "";
        
        while(textArrayString.indexOf(",")!=-1)
        {
            tempString = textArrayString.substring(0,textArrayString.indexOf(","));
            textArrayString = textArrayString.substring(textArrayString.indexOf(",") + 1);
            aryList.add(tempString);
        }
        aryList.add(textArrayString);
        return aryList.toArray();
    }    

    public dlgCustomerBillingResponsePanelSuccess setIsSuccessPreview(boolean isSuccessPrev)
    {
	PaymentSuccessFooterPanel1.setIsSuccessPreview(isSuccessPrev);
	return this;
    }

    private String replaceUIExpressions(String UIStringToReplaceExpressions)
    {
        try
        {
            for(int i = 0;i<updateUIExpressions.length;i++)
            {
			if(((String)updateUIExpressions[i]).equalsIgnoreCase("product_version")==false)
			{
                    UIStringToReplaceExpressions = UIStringToReplaceExpressions.replaceAll("(?i)" + (String)updateUIExpressions[i],ProjectManager.get((String)updateUIExpressions[i]));
			}
			else
			{
			  //put replace version string code here.
			  Object[] theVersionArray = getStringArraysFromString(ProjectManager.get((String)updateUIExpressions[i]));
			  int tempInt = 1;
			  String strVersionString = "";
  			  for(int a = 0;a<theVersionArray.length;a++)
			  {
				if(0<a)
				{
					try
					{
						if(Integer.parseInt((String)theVersionArray[a])!=0)
						{
							tempInt = a;
						}
					}
					catch(Exception e)
					{
						//The String likely was not a number and threw an exception
					}
				}
			  }
			  tempInt = tempInt + 1;
  			  for(int a = 0;a<tempInt;a++)
			  {
				if(a!=0)
				{
					strVersionString = strVersionString + "." + (String)theVersionArray[a];
				}
				else
				{
					strVersionString = (String)theVersionArray[a];
				}
			  }
                    UIStringToReplaceExpressions = UIStringToReplaceExpressions.replaceAll("(?i)" + (String)updateUIExpressions[i],strVersionString);
			}
            }
            return UIStringToReplaceExpressions;
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
        return null;
    }

    Object[] updateUIExpressions = new Object[9];
    private void updateUIExpressionDefines()
    {
        try
        {
            ArrayList theExpressionDefinesArrayList = new ArrayList();
            if(ProjectManager.get("product_vendor_name")!=null)
            {
                theExpressionDefinesArrayList.add("product_vendor_name");
            }
            if(ProjectManager.get("product_name")!=null)
            {
                theExpressionDefinesArrayList.add("product_name");
            }
            if(ProjectManager.get("product_version")!=null)
            {
                theExpressionDefinesArrayList.add("product_version");
            }
            if(ProjectManager.get("product_info_url")!=null)
            {
                theExpressionDefinesArrayList.add("product_info_url");
            }
            if(ProjectManager.get("product_url")!=null)
            {
                theExpressionDefinesArrayList.add("product_url");
            }
            if(ProjectManager.get("product_privacy_policy_email")!=null)
            {
                theExpressionDefinesArrayList.add("product_privacy_policy_email");
            }
            if(ProjectManager.get("product_copyright")!=null)
            {
                theExpressionDefinesArrayList.add("product_copyright");
            }     
            if(ProjectManager.get("product_price")!=null)
            {
                theExpressionDefinesArrayList.add("product_price");
            }
            if(ProjectManager.get("product_purchase_support_email")!=null)
            {
                theExpressionDefinesArrayList.add("product_purchase_support_email");
            }
            theExpressionDefinesArrayList.trimToSize();
            updateUIExpressions = theExpressionDefinesArrayList.toArray();
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }   

    public void paint(Graphics g)
    {
	Graphics2D g2 = (Graphics2D) g;
	g2.setRenderingHint(RenderingHints.KEY_TEXT_ANTIALIASING,RenderingHints.VALUE_TEXT_ANTIALIAS_ON);
	super.paint(g);
    } 
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.trinity.ea.design.payments.preview.payment.PaymentSuccessCenterPanel PaymentSuccessCenterPanel1;
    private com.trinity.ea.design.payments.preview.payment.PaymentValidationHeaderPanel PaymentValidationHeaderPanel1;
    private com.trinity.ea.design.payments.preview.payment.PaymentSuccessFooterPanel PaymentSuccessFooterPanel1;
    private javax.swing.JPanel RootPanel;
// End of variables declaration//GEN-END:variables
    
}
