/*
 * ProjectConfigPanel.java
 *
 * Created on December 16, 2003, 4:54 PM
 */

package com.trinity.ea.design.project.config;
import com.trinity.ea.design.common.panel.EAPanel;

/**
 *
 * @author  aaronsc Trinity Software
 * Copyright ©2003-2004 Trinity Software. All rights reserved.
 */
public class ProjectConfigPanel extends EAPanel {
    
    /** Creates new form ProjectConfigPanel */
    public ProjectConfigPanel() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        ProjectConfigCenterPanel = new javax.swing.JPanel();
        ConfigLeftMarginPanel = new javax.swing.JPanel();
        ConfigCenterContentAreaPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ConfigRightMarginPanel = new javax.swing.JPanel();
        ProjectConfigSouthMarginPanel = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        setBackground(new java.awt.Color(140, 160, 210));
        ProjectConfigCenterPanel.setLayout(new java.awt.BorderLayout());

        ProjectConfigCenterPanel.setBackground(new java.awt.Color(140, 160, 210));
        ConfigLeftMarginPanel.setBackground(new java.awt.Color(140, 160, 210));
        ProjectConfigCenterPanel.add(ConfigLeftMarginPanel, java.awt.BorderLayout.WEST);

        ConfigCenterContentAreaPanel.setBackground(new java.awt.Color(140, 160, 210));
        jLabel1.setText("Content for Config panel goes here.");
        ConfigCenterContentAreaPanel.add(jLabel1);

        ProjectConfigCenterPanel.add(ConfigCenterContentAreaPanel, java.awt.BorderLayout.CENTER);

        ConfigRightMarginPanel.setBackground(new java.awt.Color(140, 160, 210));
        ProjectConfigCenterPanel.add(ConfigRightMarginPanel, java.awt.BorderLayout.EAST);

        add(ProjectConfigCenterPanel, java.awt.BorderLayout.CENTER);

        ProjectConfigSouthMarginPanel.setBackground(new java.awt.Color(140, 160, 210));
        ProjectConfigSouthMarginPanel.setMaximumSize(new java.awt.Dimension(32767, 10));
        add(ProjectConfigSouthMarginPanel, java.awt.BorderLayout.SOUTH);

    }//GEN-END:initComponents

  public void getDataUpdate()
  {
	try
	{
		System.out.println("Data Update not implemented in this Panel...");
	}
	catch(Exception e)
	{
		e.printStackTrace();
	}
  }    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ConfigCenterContentAreaPanel;
    private javax.swing.JPanel ConfigLeftMarginPanel;
    private javax.swing.JPanel ConfigRightMarginPanel;
    private javax.swing.JPanel ProjectConfigCenterPanel;
    private javax.swing.JPanel ProjectConfigSouthMarginPanel;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
    
}
