/*
 * PrivacyPolicy.java
 *
 * Created on November 8, 2003, 1:04 AM
 */

package com.trinity.ea.forms;
import com.trinity.ea.rules.reader.EncryptedRuleReader;
import javax.swing.JDialog;
import javax.swing.JPanel;
import javax.swing.JButton;
import javax.swing.JScrollPane;
import javax.swing.JEditorPane;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import java.awt.Font;
import java.awt.Frame;
import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author  aaronsc Trinity Software
 * Copyright �2003 Trinity Software. All rights reserved.
 */
public class PrivacyPolicy extends javax.swing.JDialog {
    
    /** Creates new form PrivacyPolicy */
    public PrivacyPolicy(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
            
        if(EncryptedRuleReader.get("privacyPolicyTitle")!=null)
        {
        	setTitle(EncryptedRuleReader.get("privacyPolicyTitle"));
	  }
      
        //Policy.setText(EncryptedRuleReader.get("privacyPolicy"));
        setSize(491, 383);
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        int w = getSize().width;
        int h = getSize().height;
        int x = (dim.width-w)/2;
        int y = (dim.height-h)/2;
        setLocation(x, y);  
Policy.setCaretPosition(0);

   }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        OKPanel = new javax.swing.JPanel();
        btnOK = new javax.swing.JButton();
        PrivacyPolicyScrollPane = new javax.swing.JScrollPane();
        Policy = new javax.swing.JEditorPane();
		if(EncryptedRuleReader.get("privacyPolicy")!=null)
		{
	  		Policy.setText(EncryptedRuleReader.get("privacyPolicy").replaceAll("\\\\r\\\\n", System.getProperty("line.separator")));         
		} 
        getContentPane().setLayout(null);

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });
setResizable(false);
        btnOK.setFont(new java.awt.Font("Arial", 0, 12));
        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        OKPanel.add(btnOK);

        getContentPane().add(OKPanel);
        OKPanel.setBounds(0, 310, 485, 60);

        Policy.setEditable(false);
        PrivacyPolicyScrollPane.setViewportView(Policy);

        getContentPane().add(PrivacyPolicyScrollPane);
        PrivacyPolicyScrollPane.setBounds(0, 0, 485, 310);

        pack();
    }//GEN-END:initComponents

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
            dispose();
    }//GEN-LAST:event_btnOKActionPerformed
    
    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new PrivacyPolicy(new javax.swing.JFrame(), true).show();
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel OKPanel;
    private javax.swing.JEditorPane Policy;
    private javax.swing.JScrollPane PrivacyPolicyScrollPane;
    private javax.swing.JButton btnOK;
    // End of variables declaration//GEN-END:variables
    
}
