/*
 * X509EncryptionConfigurationPanel.java
 *
 * Created on April 22, 2004, 4:18 PM
 */

package com.trinity.ea.design.autoupdate.encrypt;
import com.trinity.ea.design.common.panel.EAPanel;
import com.trinity.ea.design.common.file.ProjectManager;
import com.trinity.ea.design.common.panel.DataContentPanel;
import com.trinity.ea.design.autoupdate.encrypt.X500EncryptionConfigurationPanel;
import com.trinity.ea.design.autoupdate.encrypt.X509EncryptionConfigurationPanel;
import javax.swing.*;
import java.awt.*;

/**
 *
 * @author  aaronsc Trinity Software
 * Copyright ©2005 Trinity Software. All rights reserved.
 */
public class JarSignerControlPanel extends EAPanel {

    private Color backgroundColor = new java.awt.Color(140, 160, 210);   
 
    /** Creates new form X509EncryptionConfigurationPanel */
    public JarSignerControlPanel() {
        initComponents();
 	setProjectData();       
    }

   public synchronized void getDataUpdate()
   {
        try
        {
                if(rbX500.isSelected()==true)
                {
                    ProjectManager.putTempNoFileWrite("autoUpdateX509CertificateEnabled", "false");
                }
                else
                {
                    ProjectManager.putTempNoFileWrite("autoUpdateX509CertificateEnabled", "true");
                }
		    X500Panel.getDataUpdate();
		    X509Panel.getDataUpdate();
                ProjectManager.saveTempNow();
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
  }   

    public synchronized void setProjectData()
    {
        try
        {
            if(ProjectManager.get("autoUpdateX509CertificateEnabled")!=null)
            {
                if(ProjectManager.get("autoUpdateX509CertificateEnabled").equalsIgnoreCase("true")==true)
                {
                    rbX500.setSelected(false);
                    rbX509.setSelected(true);
                }
                else
                {
                    rbX500.setSelected(true); 
                    rbX509.setSelected(false);
                }
            }
            else
            {
                rbX500.setSelected(true); 
                rbX509.setSelected(false);                
            }
		X500Panel.setProjectData();
		X509Panel.setProjectData();
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        RegistrationSettingsPanelItem1 = new javax.swing.JPanel();
        ContentPanel = new javax.swing.JPanel();
        LeftPanel = new javax.swing.JPanel();
        lFiller20 = new javax.swing.JLabel();
        rbX500 = new javax.swing.JRadioButton();
        lFiller21 = new javax.swing.JLabel();
        rbX509 = new javax.swing.JRadioButton();
        ContentPanelInside = new javax.swing.JPanel();
        X500Panel = new X500EncryptionConfigurationPanel();
        HorizontalRulePanel = new javax.swing.JPanel();
        X509Panel = new X509EncryptionConfigurationPanel();
        ContentPanelInside3 = new javax.swing.JPanel();

        RegistrationSettingsPanelItem1.setLayout(new javax.swing.BoxLayout(RegistrationSettingsPanelItem1, javax.swing.BoxLayout.Y_AXIS));

        RegistrationSettingsPanelItem1.setBackground(new java.awt.Color(140, 160, 210));
        RegistrationSettingsPanelItem1.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        RegistrationSettingsPanelItem1.setMinimumSize(new java.awt.Dimension(300, 30));
        RegistrationSettingsPanelItem1.setPreferredSize(new java.awt.Dimension(800, 30));

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        setBackground(new java.awt.Color(140, 160, 210));
        ContentPanel.setLayout(new javax.swing.BoxLayout(ContentPanel, javax.swing.BoxLayout.X_AXIS));

        ContentPanel.setBackground(new java.awt.Color(140, 160, 210));
        ContentPanel.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        ContentPanel.setMinimumSize(new java.awt.Dimension(300, 30));
        ContentPanel.setPreferredSize(new java.awt.Dimension(800, 30));
        LeftPanel.setLayout(new javax.swing.BoxLayout(LeftPanel, javax.swing.BoxLayout.Y_AXIS));

        LeftPanel.setBackground(new java.awt.Color(140, 160, 210));
        LeftPanel.setMaximumSize(new java.awt.Dimension(25, 2147483647));
        LeftPanel.setMinimumSize(new java.awt.Dimension(25, 30));
        LeftPanel.setPreferredSize(new java.awt.Dimension(25, 30));
        lFiller20.setBackground(new java.awt.Color(140, 160, 210));
        lFiller20.setText("   ");
        lFiller20.setMaximumSize(new java.awt.Dimension(10, 15));
        lFiller20.setMinimumSize(new java.awt.Dimension(10, 16));
        lFiller20.setPreferredSize(new java.awt.Dimension(10, 16));
        LeftPanel.add(lFiller20);

        rbX500.setBackground(new java.awt.Color(140, 160, 210));
        rbX500.setSelected(true);
        rbX500.setMaximumSize(new java.awt.Dimension(21, 119));
        rbX500.setMinimumSize(new java.awt.Dimension(21, 119));
        rbX500.setPreferredSize(new java.awt.Dimension(21, 119));
        rbX500.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        rbX500.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbX500ActionPerformed(evt);
            }
        });

        LeftPanel.add(rbX500);

        lFiller21.setBackground(new java.awt.Color(140, 160, 210));
        lFiller21.setText("   ");
        lFiller21.setMaximumSize(new java.awt.Dimension(10, 15));
        lFiller21.setMinimumSize(new java.awt.Dimension(10, 16));
        lFiller21.setPreferredSize(new java.awt.Dimension(10, 16));
        LeftPanel.add(lFiller21);

        rbX509.setBackground(new java.awt.Color(140, 160, 210));
        rbX509.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbX509ActionPerformed(evt);
            }
        });

        LeftPanel.add(rbX509);

        ContentPanel.add(LeftPanel);

        ContentPanelInside.setLayout(new javax.swing.BoxLayout(ContentPanelInside, javax.swing.BoxLayout.Y_AXIS));

        ContentPanelInside.setBackground(new java.awt.Color(140, 160, 210));
        ContentPanelInside.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        ContentPanelInside.setMinimumSize(new java.awt.Dimension(300, 30));
        ContentPanelInside.setPreferredSize(new java.awt.Dimension(800, 800));
        X500Panel.setLayout(new javax.swing.BoxLayout(X500Panel, javax.swing.BoxLayout.Y_AXIS));

        X500Panel.setBackground(new java.awt.Color(140, 160, 210));
        X500Panel.setMaximumSize(new java.awt.Dimension(2147483647, 134));
        X500Panel.setMinimumSize(new java.awt.Dimension(300, 134));
        X500Panel.setPreferredSize(new java.awt.Dimension(800, 134));
        ContentPanelInside.add(X500Panel);

        HorizontalRulePanel.setBackground(new java.awt.Color(140, 160, 210));
        HorizontalRulePanel.setBorder(new javax.swing.border.EtchedBorder());
        HorizontalRulePanel.setMaximumSize(new java.awt.Dimension(32767, 2));
        HorizontalRulePanel.setMinimumSize(new java.awt.Dimension(10, 2));
        HorizontalRulePanel.setPreferredSize(new java.awt.Dimension(10, 2));
        ContentPanelInside.add(HorizontalRulePanel);

        X509Panel.setLayout(new javax.swing.BoxLayout(X509Panel, javax.swing.BoxLayout.Y_AXIS));

        X509Panel.setBackground(new java.awt.Color(140, 160, 210));
        ContentPanelInside3.setLayout(new javax.swing.BoxLayout(ContentPanelInside3, javax.swing.BoxLayout.Y_AXIS));

        ContentPanelInside3.setBackground(new java.awt.Color(140, 160, 210));
        ContentPanelInside3.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        ContentPanelInside3.setMinimumSize(new java.awt.Dimension(300, 30));
        ContentPanelInside3.setPreferredSize(new java.awt.Dimension(800, 800));
        X509Panel.add(ContentPanelInside3);

        ContentPanelInside.add(X509Panel);

        ContentPanel.add(ContentPanelInside);

        add(ContentPanel);

    }//GEN-END:initComponents

    private void rbX509ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbX509ActionPerformed
        rbX500.setSelected(false);
        rbX509.setSelected(true); 
    }//GEN-LAST:event_rbX509ActionPerformed

    private void rbX500ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbX500ActionPerformed
        rbX500.setSelected(true);
        rbX509.setSelected(false);        
    }//GEN-LAST:event_rbX500ActionPerformed
    
     private void btnGeneratePasswordCountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGeneratePasswordCountActionPerformed

    }//GEN-LAST:event_btnGeneratePasswordCountActionPerformed
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ContentPanel;
    private javax.swing.JPanel ContentPanelInside;
    private javax.swing.JPanel ContentPanelInside3;
    private javax.swing.JPanel HorizontalRulePanel;
    private javax.swing.JPanel LeftPanel;
    private javax.swing.JPanel RegistrationSettingsPanelItem1;
    private X500EncryptionConfigurationPanel X500Panel;
    private X509EncryptionConfigurationPanel X509Panel;
    private javax.swing.JLabel lFiller20;
    private javax.swing.JLabel lFiller21;
    private javax.swing.JRadioButton rbX500;
    private javax.swing.JRadioButton rbX509;
    // End of variables declaration//GEN-END:variables

   /* EADesignerRegistrationPanel parentObj = null;
    public void setMasterStatusController(EADesignerRegistrationPanel parentObject)
    {
        parentObj = parentObject;
    }
*/
}
