/*
 * X509EncryptionConfigurationPanel.java
 *
 * Created on April 22, 2004, 4:18 PM
 */

package com.trinity.ea.design.autoupdate.encrypt;
import com.trinity.ea.design.common.panel.EAPanel;
import com.trinity.ea.design.common.file.ProjectManager;
import com.trinity.ea.design.common.panel.DataContentPanel;
import com.trinity.ea.design.common.X509CertificateChooser.X509CertificateChooser;
import javax.swing.*;
import java.awt.*;

/**
 *
 * @author  aaronsc Trinity Software
 * Copyright ©2005 Trinity Software. All rights reserved.
 */
public class X509EncryptionConfigurationPanel extends EAPanel {

    private Color backgroundColor = new java.awt.Color(140, 160, 210);   
 
    /** Creates new form X509EncryptionConfigurationPanel */
    public X509EncryptionConfigurationPanel() {
        initComponents();
 	setProjectData();       
    }

   public synchronized void getDataUpdate()
   {
        try
        {
		// Auto Update Support Password Seed and Password Count Functionality variables
		ProjectManager.putTempNoFileWrite("autoUpdateX509Certificate", taX509Certificate.getText());
		ProjectManager.saveTempNow();
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
  }   

    public synchronized void setProjectData()
    {
        try
        {
		// Registration Code Serial Number TextField  
            if(ProjectManager.get("autoUpdateX509Certificate")!=null)
            {
		    taX509Certificate.setOpaque(true);
		    taX509Certificate.setText(ProjectManager.get("autoUpdateX509Certificate"));
		    taX509Certificate.setCaretPosition(0);
            }
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        FillerPanel1 = new javax.swing.JPanel();
        X509CertificatePanel = new javax.swing.JPanel();
        lFiller19 = new javax.swing.JLabel();
        taX509CertificateDescription = new javax.swing.JTextArea();
        lFiller22 = new javax.swing.JLabel();
        X500PrincipalPanel1 = new javax.swing.JPanel();
        lFiller21 = new javax.swing.JLabel();
        spX509Cert = new javax.swing.JScrollPane();
        taX509Certificate = new javax.swing.JTextArea();
        lFiller23 = new javax.swing.JLabel();
        FillerPanel = new javax.swing.JPanel();
        RegistrationSettingsPanelItem = new javax.swing.JPanel();
        lFiller12 = new javax.swing.JLabel();
        lFiller18 = new javax.swing.JLabel();
        btnPublicCertificate = new javax.swing.JButton();
        lFiller14 = new javax.swing.JLabel();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        setBackground(new java.awt.Color(140, 160, 210));
        FillerPanel1.setLayout(new javax.swing.BoxLayout(FillerPanel1, javax.swing.BoxLayout.X_AXIS));

        FillerPanel1.setBackground(new java.awt.Color(140, 160, 210));
        FillerPanel1.setMaximumSize(new java.awt.Dimension(2147483647, 10));
        FillerPanel1.setMinimumSize(new java.awt.Dimension(300, 10));
        FillerPanel1.setPreferredSize(new java.awt.Dimension(800, 10));
        add(FillerPanel1);

        X509CertificatePanel.setLayout(new javax.swing.BoxLayout(X509CertificatePanel, javax.swing.BoxLayout.X_AXIS));

        X509CertificatePanel.setBackground(new java.awt.Color(140, 160, 210));
        X509CertificatePanel.setMaximumSize(new java.awt.Dimension(2147483647, 52));
        X509CertificatePanel.setMinimumSize(new java.awt.Dimension(300, 52));
        X509CertificatePanel.setPreferredSize(new java.awt.Dimension(800, 52));
        lFiller19.setBackground(new java.awt.Color(140, 160, 210));
        lFiller19.setText("   ");
        lFiller19.setMaximumSize(new java.awt.Dimension(10, 15));
        lFiller19.setMinimumSize(new java.awt.Dimension(10, 16));
        lFiller19.setPreferredSize(new java.awt.Dimension(10, 16));
        X509CertificatePanel.add(lFiller19);

        taX509CertificateDescription.setBackground(new java.awt.Color(140, 160, 210));
        taX509CertificateDescription.setEditable(false);
        taX509CertificateDescription.setFont(new java.awt.Font("Arial", 0, 12));
        taX509CertificateDescription.setLineWrap(true);
        taX509CertificateDescription.setText("Click the \"Find Jar Signer Certificate...\" button to select a Jar file that was already signed with the digital signature that will be used for automatic software updates, and select the X500 Principal (Subject Distinguished Name), to select the X509 Signer Certificate.");
        taX509CertificateDescription.setWrapStyleWord(true);
        X509CertificatePanel.add(taX509CertificateDescription);

        lFiller22.setBackground(new java.awt.Color(140, 160, 210));
        lFiller22.setText("");
        lFiller22.setMaximumSize(new java.awt.Dimension(15, 15));
        lFiller22.setMinimumSize(new java.awt.Dimension(15, 16));
        lFiller22.setPreferredSize(new java.awt.Dimension(15, 16));
        X509CertificatePanel.add(lFiller22);

        add(X509CertificatePanel);

        X500PrincipalPanel1.setLayout(new javax.swing.BoxLayout(X500PrincipalPanel1, javax.swing.BoxLayout.X_AXIS));

        X500PrincipalPanel1.setBackground(new java.awt.Color(140, 160, 210));
        X500PrincipalPanel1.setMaximumSize(new java.awt.Dimension(2147483647, 90));
        X500PrincipalPanel1.setMinimumSize(new java.awt.Dimension(300, 90));
        X500PrincipalPanel1.setPreferredSize(new java.awt.Dimension(800, 90));
        lFiller21.setBackground(new java.awt.Color(140, 160, 210));
        lFiller21.setText("");
        lFiller21.setMaximumSize(new java.awt.Dimension(10, 15));
        lFiller21.setMinimumSize(new java.awt.Dimension(10, 16));
        lFiller21.setPreferredSize(new java.awt.Dimension(10, 16));
        X500PrincipalPanel1.add(lFiller21);

        spX509Cert.setVerticalScrollBarPolicy(javax.swing.JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);
        taX509Certificate.setFont(new java.awt.Font("Arial", 0, 12));
        taX509Certificate.setLineWrap(true);
        taX509Certificate.setWrapStyleWord(true);
        spX509Cert.setViewportView(taX509Certificate);

        X500PrincipalPanel1.add(spX509Cert);

        lFiller23.setBackground(new java.awt.Color(140, 160, 210));
        lFiller23.setText("   ");
        lFiller23.setMaximumSize(new java.awt.Dimension(15, 15));
        lFiller23.setMinimumSize(new java.awt.Dimension(15, 16));
        lFiller23.setPreferredSize(new java.awt.Dimension(15, 16));
        X500PrincipalPanel1.add(lFiller23);

        add(X500PrincipalPanel1);

        FillerPanel.setLayout(new javax.swing.BoxLayout(FillerPanel, javax.swing.BoxLayout.X_AXIS));

        FillerPanel.setBackground(new java.awt.Color(140, 160, 210));
        FillerPanel.setMaximumSize(new java.awt.Dimension(2147483647, 10));
        FillerPanel.setMinimumSize(new java.awt.Dimension(300, 10));
        FillerPanel.setPreferredSize(new java.awt.Dimension(800, 10));
        add(FillerPanel);

        RegistrationSettingsPanelItem.setLayout(new javax.swing.BoxLayout(RegistrationSettingsPanelItem, javax.swing.BoxLayout.X_AXIS));

        RegistrationSettingsPanelItem.setBackground(new java.awt.Color(140, 160, 210));
        RegistrationSettingsPanelItem.setMaximumSize(new java.awt.Dimension(2147483647, 30));
        RegistrationSettingsPanelItem.setMinimumSize(new java.awt.Dimension(300, 30));
        RegistrationSettingsPanelItem.setPreferredSize(new java.awt.Dimension(800, 30));
        lFiller12.setBackground(new java.awt.Color(140, 160, 210));
        lFiller12.setText("   ");
        lFiller12.setMaximumSize(new java.awt.Dimension(32767, 15));
        lFiller12.setMinimumSize(new java.awt.Dimension(10, 16));
        lFiller12.setPreferredSize(new java.awt.Dimension(10, 16));
        RegistrationSettingsPanelItem.add(lFiller12);

        lFiller18.setBackground(new java.awt.Color(140, 160, 210));
        lFiller18.setMaximumSize(new java.awt.Dimension(5, 15));
        lFiller18.setMinimumSize(new java.awt.Dimension(5, 16));
        lFiller18.setPreferredSize(new java.awt.Dimension(5, 16));
        RegistrationSettingsPanelItem.add(lFiller18);

        btnPublicCertificate.setFont(new java.awt.Font("Arial", 0, 12));
        btnPublicCertificate.setText("Find Jar Signer Certificate...");
        btnPublicCertificate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPublicCertificateActionPerformed(evt);
            }
        });

        RegistrationSettingsPanelItem.add(btnPublicCertificate);

        lFiller14.setBackground(new java.awt.Color(140, 160, 210));
        lFiller14.setText("   ");
        lFiller14.setMaximumSize(new java.awt.Dimension(15, 15));
        lFiller14.setMinimumSize(new java.awt.Dimension(15, 16));
        lFiller14.setPreferredSize(new java.awt.Dimension(15, 16));
        RegistrationSettingsPanelItem.add(lFiller14);

        add(RegistrationSettingsPanelItem);

    }//GEN-END:initComponents

    private void btnPublicCertificateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPublicCertificateActionPerformed
	try
	{
            String theResult = X509CertificateChooser.getX509Certificate(this);
            if(theResult!=null)
            {
                taX509Certificate.setText(theResult);                
            }

	}
	catch(Exception e)
	{
		e.printStackTrace();
	}
    }//GEN-LAST:event_btnPublicCertificateActionPerformed
    
     private void btnGeneratePasswordCountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGeneratePasswordCountActionPerformed

    }//GEN-LAST:event_btnGeneratePasswordCountActionPerformed
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel FillerPanel;
    private javax.swing.JPanel FillerPanel1;
    private javax.swing.JPanel RegistrationSettingsPanelItem;
    private javax.swing.JPanel X500PrincipalPanel1;
    private javax.swing.JPanel X509CertificatePanel;
    private javax.swing.JButton btnPublicCertificate;
    private javax.swing.JLabel lFiller12;
    private javax.swing.JLabel lFiller14;
    private javax.swing.JLabel lFiller18;
    private javax.swing.JLabel lFiller19;
    private javax.swing.JLabel lFiller21;
    private javax.swing.JLabel lFiller22;
    private javax.swing.JLabel lFiller23;
    private javax.swing.JScrollPane spX509Cert;
    private javax.swing.JTextArea taX509Certificate;
    private javax.swing.JTextArea taX509CertificateDescription;
    // End of variables declaration//GEN-END:variables

   /* EADesignerRegistrationPanel parentObj = null;
    public void setMasterStatusController(EADesignerRegistrationPanel parentObject)
    {
        parentObj = parentObject;
    }
*/
}
