/*
 * BaseURLChangePanel.java
 *
 * Created on December 31, 2003, 6:21 PM
 */

package com.trinity.ea.design.messaging.builder;
import com.trinity.ea.design.common.panel.EAPanel;
import com.trinity.ea.design.common.panel.EAMasterControlPanel;
import com.trinity.ea.design.common.panel.EAPropertiesPanel;
import com.trinity.ea.design.common.panel.EAListItem;
import com.trinity.ea.design.common.panel.EAListItemContent;
import com.trinity.ea.design.common.file.ProjectManager;
import java.util.ArrayList;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JPanel;
import javax.swing.ImageIcon;
import javax.swing.Icon;
import javax.swing.BoxLayout;
import java.awt.FlowLayout;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Color;
import java.awt.Font;

/**
 *
 * @author  aaronsc Trinity Software
 * Copyright ©2003-2004 Trinity Software. All rights reserved.
 */
public class BaseURLChangePanel extends EAMasterControlPanel {
    private Color backgroundColor = getBackground();
    private Color borderColor1 = getBackground();
    private Color borderColor2 = getBackground();
    //private Color rowColor = new java.awt.Color(220, 225, 240);
    //private Color rowBorderColor = new java.awt.Color(255, 255, 255);
    //private Color tabColor = new java.awt.Color(255, 255, 255);
    //private Color tabBorderColor = new java.awt.Color(0, 0, 0);
    private Color rowColor = javax.swing.UIManager.getDefaults().getColor("List.background");
    private Color rowBorderColor = javax.swing.UIManager.getDefaults().getColor("List.focusCellBorderColor");
    private Color tabColor = javax.swing.UIManager.getDefaults().getColor("TabbedPane.background");
    private Color tabBorderColor = javax.swing.UIManager.getDefaults().getColor("Button.highlight");
    private Icon theActionRowIcon = new javax.swing.ImageIcon(getClass().getResource("/images/lgpl/stock_insert_url-16.png"));
    private int rowHeight = 25;
    private int defActionLabelWidth = 115;
    private int defActionDataWidth = 260;

    /** Creates new form BaseURLChangePanel */
    public BaseURLChangePanel() {
        initComponents();
	  setProjectData();
	  //theEAProperties.setSelectedIndex(0);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        AutoUpdateContentPanel = new javax.swing.JPanel();
        DynamicHTMLFormInputSettingsPanel1 = new javax.swing.JPanel();
        OptinHTMLFormInputElementsPanelItem18 = new javax.swing.JPanel();
        OptinHTMLFormInputElementsEMailContentPanel13 = new javax.swing.JPanel();
        taOptionsDescription = new javax.swing.JTextArea();
        OptinHTMLFormInputElementsEMailRightFillerPanel13 = new javax.swing.JPanel();
        OptinHTMLFormInputElementsPanelItem14 = new javax.swing.JPanel();
        PaymentMethodsAndMoreGroupPanel = new javax.swing.JPanel();
        PaymentMethodsAndMoreContentPanel = new javax.swing.JPanel();
        PaymentMethodsGroupPanel = new javax.swing.JPanel();
        OptinHTMLFormInputElementsPanelItem15 = new javax.swing.JPanel();
        OptinTitlePanel12 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        OptinHTMLFormInputElementsPanelItem16 = new javax.swing.JPanel();
        OptinHTMLFormInputElementsEMailContentPanel6 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        OptinHTMLFormInputElementsEMailRightFillerPanel6 = new javax.swing.JPanel();
        PaymentTotalVerificationCodeEnabledPanel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel14 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        OptinHTMLFormInputElementsPanelItem20 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        OptinHTMLFormInputElementsPanelItem21 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
	  MiddleFillerPanel = new JPanel();
	  MiddleFillerSpacePanel = new JPanel();
        OptinHTMLFormInputElementsPanelItem22 = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        //setBackground(getBackground());
        //setMinimumSize(new java.awt.Dimension(400, 137));
        //setPreferredSize(new java.awt.Dimension(423, 137));
        setMinimumSize(new java.awt.Dimension(400, 200));
        setPreferredSize(new java.awt.Dimension(423, 200));
//
theEAProperties = new EAPropertiesPanel(getActionsEAListItems(),rowColor, rowBorderColor, backgroundColor, rowHeight);
//
theEAProperties.setMasterControlPanel(this);
//	  
	try
	{
	  //theEAProperties.setTabColor(tabColor);
	  //theEAProperties.setTabBorderColor(tabBorderColor);
	  theEAProperties.setDescriptorPanelWidth(150);
	  theEAProperties.setHeaderText("Message File Download URLs");
	  theEAProperties.setDescriptorText("URL Change Message");
	  theEAProperties.setHeaderTextAndWidth("Message File Download URLs", 220, "", 0, "", 0);
	  theEAProperties.setAddButtonVisible(true);
	  theEAProperties.setEditButtonVisible(true);
	  theEAProperties.setRemoveButtonVisible(true);
	  theEAProperties.setAddButtonText("Add URL");
	  theEAProperties.setEditButtonText("Edit URL");
	  theEAProperties.setRemoveButtonText("Remove URL");
	  theEAProperties.setPreviewButtonVisible(false);
	  theEAProperties.setConfigurationWizardButtonVisible(false);
	  theEAProperties.setSelectedIndex(0);
	  theEAProperties.setDefaultLabelText("Alternate URL ");
	  theEAProperties.setLabelWidth(defActionLabelWidth);
	  theEAProperties.setDataWidth(defActionDataWidth);
	  theEAProperties.setDefaultRowIcon(theActionRowIcon);
	  theEAProperties.setBackgroundColor(backgroundColor);
	  theEAProperties.setTabColor(tabColor);
	  theEAProperties.setTabBorderColor(tabBorderColor);
	  theEAProperties.setParentComponent(this);
	  theEAProperties.setUITextWithStartIndex("Alternate URL ", 0, 1);
	try
	{
	  theEAProperties.setMaxEAListItems(Integer.valueOf(ProjectManager.get("msgMaxBaseURLs")).intValue());
	}
	catch(Exception e)
	{
		e.printStackTrace();
	}
	  EAListItem eaListItemObj = theEAProperties.getSelectedEAListItem();
	  eaListItemObj.setSelectedMode();
	}
	catch(Exception e)
	{
		e.printStackTrace();
	}
        AutoUpdateContentPanel.setLayout(new java.awt.BorderLayout());

        AutoUpdateContentPanel.setBackground(getBackground());
        AutoUpdateContentPanel.setPreferredSize(new java.awt.Dimension(423, 1000));
        DynamicHTMLFormInputSettingsPanel1.setLayout(new java.awt.BorderLayout());

        DynamicHTMLFormInputSettingsPanel1.setBackground(getBackground());
        DynamicHTMLFormInputSettingsPanel1.setMaximumSize(new java.awt.Dimension(0, 400));
        DynamicHTMLFormInputSettingsPanel1.setMinimumSize(new java.awt.Dimension(0, 115));
        DynamicHTMLFormInputSettingsPanel1.setPreferredSize(new java.awt.Dimension(0, 400));
        OptinHTMLFormInputElementsPanelItem18.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        OptinHTMLFormInputElementsPanelItem18.setBackground(getBackground());
        OptinHTMLFormInputElementsPanelItem18.setMaximumSize(new java.awt.Dimension(32767, 33));
        OptinHTMLFormInputElementsEMailContentPanel13.setLayout(new java.awt.BorderLayout());

        OptinHTMLFormInputElementsEMailContentPanel13.setBackground(getBackground());
        OptinHTMLFormInputElementsEMailContentPanel13.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        OptinHTMLFormInputElementsEMailContentPanel13.setPreferredSize(new java.awt.Dimension(550, 240));
        taOptionsDescription.setBackground(getBackground());
        taOptionsDescription.setFont(new java.awt.Font("Arial", 0, 12));
        taOptionsDescription.setLineWrap(true);
        taOptionsDescription.setText("The Messaging settings are defined below.");
        taOptionsDescription.setWrapStyleWord(true);
        OptinHTMLFormInputElementsEMailContentPanel13.add(theEAProperties, java.awt.BorderLayout.CENTER);

        OptinHTMLFormInputElementsPanelItem18.add(OptinHTMLFormInputElementsEMailContentPanel13);

        OptinHTMLFormInputElementsEMailRightFillerPanel13.setLayout(new javax.swing.BoxLayout(OptinHTMLFormInputElementsEMailRightFillerPanel13, javax.swing.BoxLayout.Y_AXIS));

        OptinHTMLFormInputElementsEMailRightFillerPanel13.setBackground(getBackground());
        OptinHTMLFormInputElementsPanelItem18.add(OptinHTMLFormInputElementsEMailRightFillerPanel13);
	  theEAProperties.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        theEAProperties.setPreferredSize(new java.awt.Dimension(423, 275));
        DynamicHTMLFormInputSettingsPanel1.add(theEAProperties, java.awt.BorderLayout.NORTH);

        OptinHTMLFormInputElementsPanelItem14.setLayout(new java.awt.BorderLayout(10, 10));

        OptinHTMLFormInputElementsPanelItem14.setBackground(getBackground());
        OptinHTMLFormInputElementsPanelItem14.setMaximumSize(new java.awt.Dimension(32767, 310));
        OptinHTMLFormInputElementsPanelItem14.setMinimumSize(new java.awt.Dimension(242, 310));
        OptinHTMLFormInputElementsPanelItem14.setPreferredSize(new java.awt.Dimension(497, 310));
        PaymentMethodsAndMoreGroupPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        PaymentMethodsAndMoreGroupPanel.setBackground(getBackground());
        PaymentMethodsAndMoreGroupPanel.setMaximumSize(new java.awt.Dimension(32767, 310));
        PaymentMethodsAndMoreGroupPanel.setMinimumSize(new java.awt.Dimension(242, 310));
        PaymentMethodsAndMoreGroupPanel.setPreferredSize(new java.awt.Dimension(458, 310));
        PaymentMethodsAndMoreContentPanel.setLayout(new javax.swing.BoxLayout(PaymentMethodsAndMoreContentPanel, javax.swing.BoxLayout.X_AXIS));

        PaymentMethodsAndMoreContentPanel.setBackground(getBackground());
        PaymentMethodsAndMoreContentPanel.setBorder(new javax.swing.border.TitledBorder(new javax.swing.border.EtchedBorder(new java.awt.Color(198, 226, 253), new java.awt.Color(96, 110, 145)), "Software Update File Download URLs", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 12)));
        PaymentMethodsAndMoreContentPanel.setMaximumSize(new java.awt.Dimension(32767, 300));
        PaymentMethodsAndMoreContentPanel.setMinimumSize(new java.awt.Dimension(232, 300));
        PaymentMethodsAndMoreContentPanel.setPreferredSize(new java.awt.Dimension(560, 300));
        PaymentMethodsGroupPanel.setLayout(new javax.swing.BoxLayout(PaymentMethodsGroupPanel, javax.swing.BoxLayout.Y_AXIS));

        PaymentMethodsGroupPanel.setBackground(getBackground());
        PaymentMethodsGroupPanel.setMaximumSize(new java.awt.Dimension(32767, 316));
        PaymentMethodsGroupPanel.setMinimumSize(new java.awt.Dimension(332, 286));
        PaymentMethodsGroupPanel.setPreferredSize(new java.awt.Dimension(332, 326));
        OptinHTMLFormInputElementsPanelItem15.setBackground(getBackground());
        OptinHTMLFormInputElementsPanelItem15.setMaximumSize(new java.awt.Dimension(32767, 320));
        OptinTitlePanel12.setBackground(getBackground());
        OptinTitlePanel12.setMaximumSize(new java.awt.Dimension(400, 250));
        OptinTitlePanel12.setMinimumSize(new java.awt.Dimension(210, 180));
        OptinTitlePanel12.setPreferredSize(new java.awt.Dimension(310, 220));
        jScrollPane4.setBackground(getBackground());
        jScrollPane4.setVerticalScrollBarPolicy(javax.swing.JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane4.setMinimumSize(new java.awt.Dimension(200, 180));
        jScrollPane4.setPreferredSize(new java.awt.Dimension(300, 180));
        jList1.setFont(new java.awt.Font("Arial", 1, 12));
        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "http://yourdomain.com/message.eam", "ftp://mydomain.com/messages/" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList1.setMaximumSize(new java.awt.Dimension(102, 60));
        jList1.setMinimumSize(new java.awt.Dimension(102, 60));
        jList1.setPreferredSize(new java.awt.Dimension(102, 60));
        jScrollPane4.setViewportView(jList1);

        OptinTitlePanel12.add(jScrollPane4);

        OptinHTMLFormInputElementsPanelItem15.add(OptinTitlePanel12);

       // PaymentMethodsGroupPanel.add(OptinHTMLFormInputElementsPanelItem15);
//PaymentMethodsGroupPanel.add(theEAProperties);


        OptinHTMLFormInputElementsPanelItem16.setBackground(getBackground());
        OptinHTMLFormInputElementsPanelItem16.setMaximumSize(new java.awt.Dimension(32767, 46));
        OptinHTMLFormInputElementsEMailContentPanel6.setBackground(getBackground());
        OptinHTMLFormInputElementsEMailContentPanel6.setMaximumSize(new java.awt.Dimension(100, 2147483647));
        jButton7.setText("Add URL");
        OptinHTMLFormInputElementsEMailContentPanel6.add(jButton7);

        jButton8.setText("Remove URL");
        OptinHTMLFormInputElementsEMailContentPanel6.add(jButton8);

        OptinHTMLFormInputElementsPanelItem16.add(OptinHTMLFormInputElementsEMailContentPanel6);

        OptinHTMLFormInputElementsEMailRightFillerPanel6.setLayout(new javax.swing.BoxLayout(OptinHTMLFormInputElementsEMailRightFillerPanel6, javax.swing.BoxLayout.Y_AXIS));

        OptinHTMLFormInputElementsEMailRightFillerPanel6.setBackground(getBackground());
        OptinHTMLFormInputElementsPanelItem16.add(OptinHTMLFormInputElementsEMailRightFillerPanel6);

        //PaymentMethodsGroupPanel.add(OptinHTMLFormInputElementsPanelItem16);

        PaymentMethodsAndMoreContentPanel.add(PaymentMethodsGroupPanel);

        PaymentTotalVerificationCodeEnabledPanel.setLayout(new java.awt.BorderLayout());

        PaymentTotalVerificationCodeEnabledPanel.setBackground(getBackground());
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.Y_AXIS));

        jPanel3.setBackground(getBackground());
        jPanel3.setMinimumSize(new java.awt.Dimension(180, 35));
        jPanel3.setPreferredSize(new java.awt.Dimension(180, 35));
        jPanel6.setLayout(new java.awt.BorderLayout());

        jPanel6.setBackground(getBackground());
        jPanel11.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jPanel11.setBackground(getBackground());
        jPanel11.setMaximumSize(new java.awt.Dimension(2147483647, 20));
        jPanel6.add(jPanel11, java.awt.BorderLayout.NORTH);

        jPanel9.setLayout(new java.awt.BorderLayout());

        jPanel9.setBackground(getBackground());
        jPanel9.setMaximumSize(new java.awt.Dimension(2147483647, 40));
        jPanel9.setMinimumSize(new java.awt.Dimension(10, 40));
        jPanel9.setPreferredSize(new java.awt.Dimension(10, 40));
        jPanel12.setLayout(new javax.swing.BoxLayout(jPanel12, javax.swing.BoxLayout.Y_AXIS));

        jPanel12.setBackground(getBackground());
        jPanel12.setMaximumSize(new java.awt.Dimension(2147483647, 20));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        jPanel1.setBackground(getBackground());
        jPanel1.setMaximumSize(new java.awt.Dimension(2147483647, 100));
        jPanel13.setLayout(new java.awt.BorderLayout());

        jPanel13.setBackground(getBackground());
        jPanel13.setMaximumSize(new java.awt.Dimension(2147483647, 40));
        jTextArea1.setBackground(getBackground());
        jTextArea1.setLineWrap(true);
        jTextArea1.setText("The maximum number of URLs to attempt downloading the software message file:");
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setMaximumSize(new java.awt.Dimension(2147483647, 50));
        jTextArea1.setMinimumSize(new java.awt.Dimension(100, 50));
        jTextArea1.setPreferredSize(new java.awt.Dimension(100, 50));
        jPanel13.add(jTextArea1, java.awt.BorderLayout.NORTH);

        jPanel1.add(jPanel13);

        jPanel14.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jPanel14.setBackground(getBackground());
        jPanel14.setMaximumSize(new java.awt.Dimension(2147483647, 30));

        jPanel1.add(jPanel14);

        jPanel15.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jPanel15.setBackground(getBackground());
        jPanel15.setMaximumSize(new java.awt.Dimension(2147483647, 20));

        jPanel1.add(jPanel15);

        jPanel12.add(jPanel1);

        jPanel9.add(jPanel12, java.awt.BorderLayout.CENTER);

        //jPanel6.add(jPanel9, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel6);

        PaymentTotalVerificationCodeEnabledPanel.add(jPanel3, java.awt.BorderLayout.CENTER);

        PaymentMethodsAndMoreContentPanel.add(PaymentTotalVerificationCodeEnabledPanel);

        PaymentMethodsAndMoreGroupPanel.add(PaymentMethodsAndMoreContentPanel);

        //OptinHTMLFormInputElementsPanelItem14.add(PaymentMethodsAndMoreGroupPanel, java.awt.BorderLayout.NORTH);

        jPanel19.setLayout(new java.awt.BorderLayout());

        jPanel19.setBackground(getBackground());
        jPanel19.setMaximumSize(new java.awt.Dimension(32767, 25));
        jPanel19.setMinimumSize(new java.awt.Dimension(275, 25));
        jPanel19.setPreferredSize(new java.awt.Dimension(560, 25));
        OptinHTMLFormInputElementsPanelItem20.setLayout(new javax.swing.BoxLayout(OptinHTMLFormInputElementsPanelItem20, javax.swing.BoxLayout.X_AXIS));

        OptinHTMLFormInputElementsPanelItem20.setBackground(getBackground());
        OptinHTMLFormInputElementsPanelItem20.setBorder(new javax.swing.border.TitledBorder(new javax.swing.border.EtchedBorder(new java.awt.Color(198, 226, 253), new java.awt.Color(96, 110, 145)), "Messaging Options", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 12)));
        OptinHTMLFormInputElementsPanelItem20.setMaximumSize(new java.awt.Dimension(32767, 75));
        OptinHTMLFormInputElementsPanelItem20.setMinimumSize(new java.awt.Dimension(260, 75));
        OptinHTMLFormInputElementsPanelItem20.setPreferredSize(new java.awt.Dimension(1000, 75));
        jPanel5.setBackground(getBackground());
        jPanel5.setMaximumSize(new java.awt.Dimension(10, 10));
        OptinHTMLFormInputElementsPanelItem20.add(jPanel5);

        OptinHTMLFormInputElementsPanelItem21.setLayout(new java.awt.BorderLayout());

        OptinHTMLFormInputElementsPanelItem21.setBackground(getBackground());
        OptinHTMLFormInputElementsPanelItem21.setMaximumSize(new java.awt.Dimension(2147483647, 450));
        OptinHTMLFormInputElementsPanelItem21.setMinimumSize(new java.awt.Dimension(200, 0));
        OptinHTMLFormInputElementsPanelItem21.setPreferredSize(new java.awt.Dimension(500, 75));
        jPanel7.setBackground(getBackground());
        jPanel7.setMaximumSize(new java.awt.Dimension(10, 1));
        jPanel7.setMinimumSize(new java.awt.Dimension(10, 1));
        OptinHTMLFormInputElementsPanelItem21.add(jPanel7, java.awt.BorderLayout.EAST);

        jPanel18.setLayout(new java.awt.BorderLayout());

        jPanel18.setBackground(getBackground());
        jPanel18.setPreferredSize(new java.awt.Dimension(500, 50));
 
        OptinHTMLFormInputElementsPanelItem21.add(jPanel18, java.awt.BorderLayout.SOUTH);

        jPanel2.setBackground(getBackground());
        jPanel2.setMaximumSize(new java.awt.Dimension(10, 10));
        OptinHTMLFormInputElementsPanelItem21.add(jPanel2, java.awt.BorderLayout.EAST);

        OptinHTMLFormInputElementsPanelItem20.add(OptinHTMLFormInputElementsPanelItem21);

        jPanel4.setBackground(getBackground());
        jPanel4.setMaximumSize(new java.awt.Dimension(10, 10));
        OptinHTMLFormInputElementsPanelItem20.add(jPanel4);
////////////////
	  MiddleFillerPanel.setLayout(new javax.swing.BoxLayout(MiddleFillerPanel, javax.swing.BoxLayout.Y_AXIS));
	  MiddleFillerSpacePanel.setBackground(getBackground());
	  MiddleFillerPanel.setBackground(getBackground());
	  MiddleFillerSpacePanel.setMaximumSize(new java.awt.Dimension(32767, 15));
        MiddleFillerSpacePanel.setMinimumSize(new java.awt.Dimension(0, 15));
        MiddleFillerSpacePanel.setPreferredSize(new java.awt.Dimension(1000, 15));

	  MiddleFillerPanel.add(MiddleFillerSpacePanel);
	  //MiddleFillerPanel.add(OptinHTMLFormInputElementsPanelItem20);
        jPanel19.add(MiddleFillerPanel, java.awt.BorderLayout.NORTH);
//////////////////////////
        OptinHTMLFormInputElementsPanelItem22.setLayout(new java.awt.BorderLayout());

        OptinHTMLFormInputElementsPanelItem22.setBackground(getBackground());
        OptinHTMLFormInputElementsPanelItem22.setMaximumSize(new java.awt.Dimension(560, 310));
        OptinHTMLFormInputElementsPanelItem22.setMinimumSize(new java.awt.Dimension(260, 310));
        OptinHTMLFormInputElementsPanelItem22.setPreferredSize(new java.awt.Dimension(560, 310));
      
        jPanel19.add(OptinHTMLFormInputElementsPanelItem22, java.awt.BorderLayout.CENTER);

        OptinHTMLFormInputElementsPanelItem14.add(jPanel19, java.awt.BorderLayout.CENTER);
        DynamicHTMLFormInputSettingsPanel1.add(OptinHTMLFormInputElementsPanelItem14, java.awt.BorderLayout.CENTER);

        AutoUpdateContentPanel.add(DynamicHTMLFormInputSettingsPanel1, java.awt.BorderLayout.CENTER);

        add(AutoUpdateContentPanel, java.awt.BorderLayout.CENTER);

    }//GEN-END:initComponents

public EAListItem[] getEAListItemURLArray()
{
	return getActionsEAListItems();
}

//private String[] strActionsArray = new String[4];
private EAListItem[] getActionsEAListItems()
{
	  EAListItem[] ActionsEAListItemArray = new EAListItem[4];
        try
        {
		ArrayList strArrayList1 = new ArrayList();
		ArrayList eaListItemArrayList1 = new ArrayList();		
            EAListItem eai = new EAListItem(theActionRowIcon,rowColor);
		EAListItemContent msgBaseURL = new EAListItemContent(rowColor, defActionLabelWidth, defActionDataWidth);
		msgBaseURL.setLabelText("Base URL:");
		if(ProjectManager.get("msgBaseURL")!=null)
		{
			msgBaseURL.setInputText(ProjectManager.get("msgBaseURL"));
			//strArrayList1.add("msgBaseURL");
		}
            eai.setRowDataPanel(msgBaseURL);
		// Always call setListItemIsRemovable(false) after the ContentPanel is added, like in setRowDataPanel(...)
		eai.setListItemIsRemovable(false);
		eai.setValueBoxEnabled(false);
		eaListItemArrayList1.add(eai);
//
		try
		{
		int maxURLs = Integer.valueOf(ProjectManager.get("msgMaxBaseURLs")).intValue();
		for(int i = 1;i<maxURLs;i++)
		{
			if(ProjectManager.get("msgAlternateURL" + String.valueOf(i))!=null)
			{
            		EAListItem eai2 = new EAListItem(theActionRowIcon,rowColor);
				EAListItemContent msgAlternateURL1 = new EAListItemContent(rowColor, defActionLabelWidth, defActionDataWidth);
				msgAlternateURL1.setLabelText("Alternate URL " + String.valueOf(i) + ":");
				if(ProjectManager.get("msgAlternateURL" + String.valueOf(i))!=null)
				{
					msgAlternateURL1.setInputText(ProjectManager.get("msgAlternateURL" + String.valueOf(i)));
					//strArrayList1.add("msgAlternateURL" + String.valueOf(i));
				}
            		eai2.setRowDataPanel(msgAlternateURL1);
				// Always call setListItemIsRemovable(false) after the ContentPanel is added, like in setRowDataPanel(...)
				eai2.setListItemIsRemovable(true);
				eai2.setValueBoxEnabled(false);
				eaListItemArrayList1.add(eai2);
			}	
			else
			{
				i=maxURLs;
			}
		}
		}
		catch(Exception e)
		{
			e.printStackTrace();
		}
		eaListItemArrayList1.trimToSize();
		Object[] theEAListItemObjArray = eaListItemArrayList1.toArray();
		ActionsEAListItemArray = new EAListItem[theEAListItemObjArray.length];
		for(int i = 0;i<theEAListItemObjArray.length;i++)
		{
			ActionsEAListItemArray[i] = (EAListItem)theEAListItemObjArray[i];
		}

		return ActionsEAListItemArray;
        }
        catch(Exception e)
        {
          e.printStackTrace();   
        }
	EAListItem[] tempLIArray2 = new EAListItem[0];
	return tempLIArray2;
}
    
    public void setSelectedListItemEvent(int theLastSelectedIndex)
    {
		/*EAListItem eaListItemObj = theEAProperties.getSelectedEAListItem();
		EAListItemContent theContent = eaListItemObj.getRowDataPanel();
		if(theLastSelectedIndex!=-1)
		{
			try
			{
				theEAProperties.getSelectedEAListItem().getRowDataPanel().setInputText(ProjectManager.get(strActionsArray[theLastSelectedIndex]));
			}
			catch(Exception e)
			{
				e.printStackTrace();
			}
		}*/
    }

    public synchronized void setProjectData()
    {
        try
        {

        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }

  public void getDataUpdate()
  {
  }       
    
  public String[] getBaseURLArray()
  {
	try
	{
		EAListItem[] theItems = theEAProperties.getEAListItems();
		if(theItems!=null)
		{
			if(0<theItems.length)
			{
				String[] theBaseURLArray = new String[theItems.length];
				for(int i = 0;i<theItems.length;i++)
				{
						String[] theStrArray = theItems[i].getDataArray();
						if(1<theStrArray.length)
						{
							if(i==0)
							{
								theBaseURLArray[0] = theItems[0].getInputText();
							}
							else
							{
								theBaseURLArray[i] = theStrArray[0];
							}
						}
				}
				return theBaseURLArray;
			}
		}
		return null;
	}
	catch(Exception e)
	{
		e.printStackTrace();
		return null;
	}
  }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AutoUpdateContentPanel;
    private javax.swing.JPanel DynamicHTMLFormInputSettingsPanel1;
    private javax.swing.JPanel OptinHTMLFormInputElementsEMailContentPanel13;
    private javax.swing.JPanel OptinHTMLFormInputElementsEMailContentPanel6;
    private javax.swing.JPanel OptinHTMLFormInputElementsEMailRightFillerPanel13;
    private javax.swing.JPanel OptinHTMLFormInputElementsEMailRightFillerPanel6;
    private javax.swing.JPanel OptinHTMLFormInputElementsPanelItem14;
    private javax.swing.JPanel OptinHTMLFormInputElementsPanelItem15;
    private javax.swing.JPanel OptinHTMLFormInputElementsPanelItem16;
    private javax.swing.JPanel OptinHTMLFormInputElementsPanelItem18;
    private javax.swing.JPanel OptinHTMLFormInputElementsPanelItem20;
    private javax.swing.JPanel OptinHTMLFormInputElementsPanelItem21;
    private javax.swing.JPanel OptinHTMLFormInputElementsPanelItem22;
    private javax.swing.JPanel OptinTitlePanel12;
    private javax.swing.JPanel PaymentMethodsAndMoreContentPanel;
    private javax.swing.JPanel PaymentMethodsAndMoreGroupPanel;
    private javax.swing.JPanel PaymentMethodsGroupPanel;
    private javax.swing.JPanel PaymentTotalVerificationCodeEnabledPanel;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel MiddleFillerPanel;
    private javax.swing.JPanel MiddleFillerSpacePanel;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea taOptionsDescription;
    private EAPropertiesPanel theEAProperties;
    // End of variables declaration//GEN-END:variables
    
}
