/*
 * LanguageChooser.java
 *
 * Created on December 30, 2004, 2:54 PM
 */

package com.trinity.ea.design.messaging.builder;
import com.trinity.ea.design.messaging.builder.SelectedLocalesPanel;
import javax.swing.JFrame;
import javax.swing.JDialog;
import javax.swing.JPanel;
import javax.swing.JButton;
import java.awt.Frame;
import java.awt.BorderLayout;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.WindowConstants;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/** 
 *
 * @author  aaronsc Trinity Software
 * Copyright ©2004 Trinity Software. All rights reserved.
 */
public class LanguageChooser extends javax.swing.JDialog {
    private static SelectedLocalesPanel selectedLocalesPanel = null;     
    private static boolean isOK = false;

    public static String getMessageLocales()
    {
	  return selectedLocalesPanel.getMessageLocales();
    }

    public static String getMessageLocalesNames()
    {
	  return selectedLocalesPanel.getMessageLocalesNames();
    }

    public static String getMessageBuildLocales()
    {
	  return selectedLocalesPanel.getMessageBuildLocales();
    }
    
  public static boolean showLanguageChooserDialog(Frame parent, String title) 
  {
      if(selectedLocalesPanel!=null)
      {}
      else
      {      
        selectedLocalesPanel = new SelectedLocalesPanel(); 
      }
      LanguageChooser dialog = new LanguageChooser(parent, true, title);
      dialog.setVisible(true);
      boolean isOK1 = dialog.isOK;
      dialog.dispose();
      return isOK1;
  }    
 
  public static boolean showLanguageChooserDialog(Frame parent, String title, String defaultLocale, String prjLocales, String prjBuildLocales, String prjLocaleNames)
  {
      if(selectedLocalesPanel!=null)
      {}
      else
      {
        selectedLocalesPanel = new SelectedLocalesPanel(defaultLocale, prjLocales, prjBuildLocales, prjLocaleNames); 
      }
      LanguageChooser dialog = new LanguageChooser(parent, true, title);
      dialog.setVisible(true);
      boolean isOK1 = dialog.isOK;
      dialog.dispose();
      return isOK1;
  }      
  
    /** Creates new form LanguageChooser */
    public LanguageChooser(java.awt.Frame parent, boolean modal, String title) 
    {
        super(parent, modal);
        initComponents();
        setContentPanel(selectedLocalesPanel);
        //setResizable(false);
        setTitle(title);
        // Get the size of the screen
        setSize(414,383);
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        // Determine the new location of the window
        int w = getSize().width;
        int h = getSize().height;
        int x = (dim.width-w)/2;
        int y = (dim.height-h)/2;
 
        // Move the window
        setLocation(x, y);          
    }

  private JPanel TheContentPanelReference = new JPanel();
  private void setContentPanel(JPanel theContentPanel)
  {
    try
    {
	TheContentPanelReference.setVisible(false);
        //ContentPanel.remove(TheContentPanelReference);   
        ContentPanel.removeAll();
        TheContentPanelReference = theContentPanel;
        ContentPanel.add(TheContentPanelReference,java.awt.BorderLayout.CENTER);     
        TheContentPanelReference.setVisible(true);
    }
    catch(Exception e)
    {
        e.printStackTrace();
    }
  }    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        ContentPanel = new javax.swing.JPanel();
        ButtonPanel = new javax.swing.JPanel();
        OKButton = new javax.swing.JButton();
        CancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        ContentPanel.setLayout(new java.awt.BorderLayout());

        getContentPane().add(ContentPanel, java.awt.BorderLayout.CENTER);

        ButtonPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 10));

        OKButton.setFont(new java.awt.Font("Arial", 0, 12));
        OKButton.setMnemonic('O');
        OKButton.setText("OK");
        OKButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKButtonActionPerformed(evt);
            }
        });

        ButtonPanel.add(OKButton);

        CancelButton.setFont(new java.awt.Font("Arial", 0, 12));
        CancelButton.setMnemonic('C');
        CancelButton.setText("Cancel");
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });

        ButtonPanel.add(CancelButton);

        getContentPane().add(ButtonPanel, java.awt.BorderLayout.SOUTH);

        pack();
    }//GEN-END:initComponents

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        isOK = false;
        setVisible(false);
    }//GEN-LAST:event_CancelButtonActionPerformed

    private void OKButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKButtonActionPerformed
        isOK = true;
        setVisible(false);       
    }//GEN-LAST:event_OKButtonActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ButtonPanel;
    private javax.swing.JButton CancelButton;
    private javax.swing.JPanel ContentPanel;
    private javax.swing.JButton OKButton;
    // End of variables declaration//GEN-END:variables
    
}
