/*
 * LanguagePanel.java
 *
 * Created on December 31, 2004, 6:41 PM
 */

package com.trinity.ea.design.messaging.builder;
import javax.swing.JPanel;
import javax.swing.JLabel;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import java.awt.Font;
import java.awt.Dimension;
import javax.swing.BoxLayout;
import java.awt.BorderLayout;
import javax.swing.JScrollPane;

/**
 *
 * @author  aaronsc Trinity Software
 * Copyright ©2004 Trinity Software. All rights reserved.
 */
public class LanguagePanel extends javax.swing.JPanel 
{
    private String langID = "en";
    private String msgTitle = "";
    private String msgBody = "";
    private String OKText = "OK";
    private String OKMnemonic = "O";    
     
    public void setLanguage(String language)
    {
        langID = language;
    }
    
    public String getLanguage()
    {
        return langID;
    }   

    public void setMessage(String msg)
    {
        taMessageBody.setText(msg);
    }
    
    public String getMessage()
    {
	try
	{
            String theText = taMessageBody.getText();
            String theText2 = theText.replaceAll("\r\n", "\\\\r\\\\n");     
            if(theText.equalsIgnoreCase(theText2)==true)
            {
                return theText2.replaceAll("\n", "\\\\r\\\\n");                
            }
            else
            {
                return theText2;
            }
	}
	catch(Exception e)
	{
            e.printStackTrace();
            return taMessageBody.getText();
	}        
    }       
 
    public void setMessageTitle(String title)
    {
        tfMessageTitle.setText(title);
    }
    
    public String getMessageTitle()
    {
        return tfMessageTitle.getText();
    }      
    
    public void setMessageOKText(String okText)
    {
        tfMessageOKButtonText.setText(okText);
    }
    
    public String getMessageOKText()
    {
        return tfMessageOKButtonText.getText();
    }      

    public void setMessageOKMnemonic(String okMnemonic)
    {
        tfMessageOKButtonMnemonic.setText(okMnemonic);
    }
    
    public String getMessageOKMnemonic()
    {
        return tfMessageOKButtonMnemonic.getText();
    }      
    
    /** Creates new form LanguagePanel */
    public LanguagePanel() 
    {
        initComponents();
    }
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        MessageDataPanel = new javax.swing.JPanel();
        MessageTitlePanel = new javax.swing.JPanel();
        Separator13 = new javax.swing.JLabel();
        MessageTitleLabelPanel = new javax.swing.JPanel();
        Separator3 = new javax.swing.JLabel();
        MessageTitleLabel = new javax.swing.JLabel();
        Separator2 = new javax.swing.JLabel();
        MessageTitleTextFieldPanel = new javax.swing.JPanel();
        Separator5 = new javax.swing.JLabel();
        tfMessageTitle = new javax.swing.JTextField();
        Separator4 = new javax.swing.JLabel();
        MessageBodyPanel = new javax.swing.JPanel();
        Separator12 = new javax.swing.JLabel();
        MessageBodyLabelPanel = new javax.swing.JPanel();
        Separator8 = new javax.swing.JLabel();
        MessageBodyLabel = new javax.swing.JLabel();
        Separator9 = new javax.swing.JLabel();
        MessageBodyTextAreaPanel = new javax.swing.JPanel();
        Separator10 = new javax.swing.JLabel();
        scrollPaneMessageBody = new javax.swing.JScrollPane();
        taMessageBody = new javax.swing.JTextArea();
        Separator11 = new javax.swing.JLabel();
        MessageOKButtonPanel = new javax.swing.JPanel();
        Separator14 = new javax.swing.JLabel();
        MessageOKButtonLabelPanel = new javax.swing.JPanel();
        LeftTopPanel = new javax.swing.JPanel();
        Separator6 = new javax.swing.JLabel();
        MessageOKButtonLabel = new javax.swing.JLabel();
        Separator7 = new javax.swing.JLabel();
        CenterTopPanel = new javax.swing.JPanel();
        Separator21 = new javax.swing.JLabel();
        MessageOKButtonMnemonicLabel = new javax.swing.JLabel();
        RightTopPanel = new javax.swing.JPanel();
        MessageTitleTextFieldPanel1 = new javax.swing.JPanel();
        LeftPanel = new javax.swing.JPanel();
        Separator15 = new javax.swing.JLabel();
        tfMessageOKButtonText = new javax.swing.JTextField();
        Separator16 = new javax.swing.JLabel();
        CenterPanel = new javax.swing.JPanel();
        Separator19 = new javax.swing.JLabel();
        tfMessageOKButtonMnemonic = new javax.swing.JTextField();
        Separator20 = new javax.swing.JLabel();
        RightPanel = new javax.swing.JPanel();
        Separator17 = new javax.swing.JLabel();
        Separator18 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        MessageDataPanel.setLayout(new javax.swing.BoxLayout(MessageDataPanel, javax.swing.BoxLayout.Y_AXIS));

        MessageDataPanel.setFont(new java.awt.Font("Arial", 0, 12));
        MessageTitlePanel.setLayout(new javax.swing.BoxLayout(MessageTitlePanel, javax.swing.BoxLayout.Y_AXIS));

        Separator13.setMaximumSize(new java.awt.Dimension(10, 10));
        Separator13.setMinimumSize(new java.awt.Dimension(10, 10));
        Separator13.setPreferredSize(new java.awt.Dimension(10, 10));
        MessageTitlePanel.add(Separator13);

        MessageTitleLabelPanel.setLayout(new javax.swing.BoxLayout(MessageTitleLabelPanel, javax.swing.BoxLayout.X_AXIS));

        Separator3.setMaximumSize(new java.awt.Dimension(10, 10));
        Separator3.setMinimumSize(new java.awt.Dimension(10, 10));
        Separator3.setPreferredSize(new java.awt.Dimension(10, 10));
        MessageTitleLabelPanel.add(Separator3);

        MessageTitleLabel.setDisplayedMnemonic('T');
        MessageTitleLabel.setFont(new java.awt.Font("Arial", 0, 12));
        MessageTitleLabel.setLabelFor(tfMessageTitle);
        MessageTitleLabel.setText("Message Title:");
        MessageTitleLabel.setMaximumSize(new java.awt.Dimension(32767, 15));
        MessageTitleLabel.setPreferredSize(new java.awt.Dimension(1200, 15));
        MessageTitleLabelPanel.add(MessageTitleLabel);

        Separator2.setMaximumSize(new java.awt.Dimension(10, 10));
        Separator2.setMinimumSize(new java.awt.Dimension(10, 10));
        Separator2.setPreferredSize(new java.awt.Dimension(10, 10));
        MessageTitleLabelPanel.add(Separator2);

        MessageTitlePanel.add(MessageTitleLabelPanel);

        MessageTitleTextFieldPanel.setLayout(new javax.swing.BoxLayout(MessageTitleTextFieldPanel, javax.swing.BoxLayout.X_AXIS));

        Separator5.setMaximumSize(new java.awt.Dimension(10, 10));
        Separator5.setMinimumSize(new java.awt.Dimension(10, 10));
        Separator5.setPreferredSize(new java.awt.Dimension(10, 10));
        MessageTitleTextFieldPanel.add(Separator5);

        tfMessageTitle.setFont(new java.awt.Font("Arial", 0, 12));
        tfMessageTitle.setMaximumSize(new java.awt.Dimension(2147483647, 21));
        MessageTitleTextFieldPanel.add(tfMessageTitle);

        Separator4.setMaximumSize(new java.awt.Dimension(10, 10));
        Separator4.setMinimumSize(new java.awt.Dimension(10, 10));
        Separator4.setPreferredSize(new java.awt.Dimension(10, 10));
        MessageTitleTextFieldPanel.add(Separator4);

        MessageTitlePanel.add(MessageTitleTextFieldPanel);

        MessageDataPanel.add(MessageTitlePanel);

        MessageBodyPanel.setLayout(new javax.swing.BoxLayout(MessageBodyPanel, javax.swing.BoxLayout.Y_AXIS));

        Separator12.setMaximumSize(new java.awt.Dimension(10, 5));
        Separator12.setMinimumSize(new java.awt.Dimension(10, 5));
        Separator12.setPreferredSize(new java.awt.Dimension(10, 5));
        MessageBodyPanel.add(Separator12);

        MessageBodyLabelPanel.setLayout(new javax.swing.BoxLayout(MessageBodyLabelPanel, javax.swing.BoxLayout.X_AXIS));

        Separator8.setMaximumSize(new java.awt.Dimension(10, 10));
        Separator8.setMinimumSize(new java.awt.Dimension(10, 10));
        Separator8.setPreferredSize(new java.awt.Dimension(10, 10));
        MessageBodyLabelPanel.add(Separator8);

        MessageBodyLabel.setDisplayedMnemonic('e');
        MessageBodyLabel.setFont(new java.awt.Font("Arial", 0, 12));
        MessageBodyLabel.setLabelFor(taMessageBody);
        MessageBodyLabel.setText("Message Body:");
        MessageBodyLabel.setMaximumSize(new java.awt.Dimension(32767, 15));
        MessageBodyLabel.setPreferredSize(new java.awt.Dimension(1200, 15));
        MessageBodyLabelPanel.add(MessageBodyLabel);

        Separator9.setMaximumSize(new java.awt.Dimension(10, 10));
        Separator9.setMinimumSize(new java.awt.Dimension(10, 10));
        Separator9.setPreferredSize(new java.awt.Dimension(10, 10));
        MessageBodyLabelPanel.add(Separator9);

        MessageBodyPanel.add(MessageBodyLabelPanel);

        MessageBodyTextAreaPanel.setLayout(new javax.swing.BoxLayout(MessageBodyTextAreaPanel, javax.swing.BoxLayout.X_AXIS));

        Separator10.setMaximumSize(new java.awt.Dimension(10, 10));
        Separator10.setMinimumSize(new java.awt.Dimension(10, 10));
        Separator10.setPreferredSize(new java.awt.Dimension(10, 10));
        MessageBodyTextAreaPanel.add(Separator10);

        scrollPaneMessageBody.setMaximumSize(new java.awt.Dimension(32767, 69));
        scrollPaneMessageBody.setMinimumSize(new java.awt.Dimension(23, 69));
        scrollPaneMessageBody.setPreferredSize(new java.awt.Dimension(4, 69));
        taMessageBody.setFont(new java.awt.Font("Arial", 0, 12));
        taMessageBody.setLineWrap(true);
        taMessageBody.setWrapStyleWord(true);
        taMessageBody.setMinimumSize(new java.awt.Dimension(0, 0));
        taMessageBody.setPreferredSize(new java.awt.Dimension(0, 0));
        scrollPaneMessageBody.setViewportView(taMessageBody);

        MessageBodyTextAreaPanel.add(scrollPaneMessageBody);

        Separator11.setMaximumSize(new java.awt.Dimension(10, 10));
        Separator11.setMinimumSize(new java.awt.Dimension(10, 10));
        Separator11.setPreferredSize(new java.awt.Dimension(10, 10));
        MessageBodyTextAreaPanel.add(Separator11);

        MessageBodyPanel.add(MessageBodyTextAreaPanel);

        MessageDataPanel.add(MessageBodyPanel);

        add(MessageDataPanel, java.awt.BorderLayout.NORTH);

        MessageOKButtonPanel.setLayout(new javax.swing.BoxLayout(MessageOKButtonPanel, javax.swing.BoxLayout.Y_AXIS));

        Separator14.setMaximumSize(new java.awt.Dimension(10, 10));
        Separator14.setMinimumSize(new java.awt.Dimension(10, 10));
        Separator14.setPreferredSize(new java.awt.Dimension(10, 10));
        MessageOKButtonPanel.add(Separator14);

        MessageOKButtonLabelPanel.setLayout(new javax.swing.BoxLayout(MessageOKButtonLabelPanel, javax.swing.BoxLayout.X_AXIS));

        LeftTopPanel.setLayout(new javax.swing.BoxLayout(LeftTopPanel, javax.swing.BoxLayout.X_AXIS));

        LeftTopPanel.setMaximumSize(new java.awt.Dimension(150, 15));
        LeftTopPanel.setMinimumSize(new java.awt.Dimension(150, 15));
        LeftTopPanel.setPreferredSize(new java.awt.Dimension(150, 15));
        Separator6.setMaximumSize(new java.awt.Dimension(10, 10));
        Separator6.setMinimumSize(new java.awt.Dimension(10, 10));
        Separator6.setPreferredSize(new java.awt.Dimension(10, 10));
        LeftTopPanel.add(Separator6);

        MessageOKButtonLabel.setDisplayedMnemonic('K');
        MessageOKButtonLabel.setFont(new java.awt.Font("Arial", 0, 12));
        MessageOKButtonLabel.setLabelFor(tfMessageOKButtonText);
        MessageOKButtonLabel.setText("Message OK Button Text:");
        MessageOKButtonLabel.setMaximumSize(new java.awt.Dimension(150, 15));
        MessageOKButtonLabel.setMinimumSize(new java.awt.Dimension(150, 15));
        MessageOKButtonLabel.setPreferredSize(new java.awt.Dimension(150, 15));
        LeftTopPanel.add(MessageOKButtonLabel);

        Separator7.setMaximumSize(new java.awt.Dimension(32767, 10));
        Separator7.setMinimumSize(new java.awt.Dimension(10, 10));
        Separator7.setPreferredSize(new java.awt.Dimension(10, 10));
        LeftTopPanel.add(Separator7);

        MessageOKButtonLabelPanel.add(LeftTopPanel);

        CenterTopPanel.setLayout(new javax.swing.BoxLayout(CenterTopPanel, javax.swing.BoxLayout.X_AXIS));

        CenterTopPanel.setMaximumSize(new java.awt.Dimension(185, 15));
        CenterTopPanel.setMinimumSize(new java.awt.Dimension(0, 15));
        CenterTopPanel.setPreferredSize(new java.awt.Dimension(185, 15));
        Separator21.setMaximumSize(new java.awt.Dimension(32767, 10));
        Separator21.setMinimumSize(new java.awt.Dimension(10, 10));
        Separator21.setPreferredSize(new java.awt.Dimension(10, 10));
        CenterTopPanel.add(Separator21);

        MessageOKButtonMnemonicLabel.setDisplayedMnemonic('n');
        MessageOKButtonMnemonicLabel.setFont(new java.awt.Font("Arial", 0, 12));
        MessageOKButtonMnemonicLabel.setLabelFor(tfMessageOKButtonMnemonic);
        MessageOKButtonMnemonicLabel.setText("Message OK Button Mnemonic:");
        MessageOKButtonMnemonicLabel.setMaximumSize(new java.awt.Dimension(185, 15));
        MessageOKButtonMnemonicLabel.setMinimumSize(new java.awt.Dimension(185, 15));
        MessageOKButtonMnemonicLabel.setPreferredSize(new java.awt.Dimension(185, 15));
        CenterTopPanel.add(MessageOKButtonMnemonicLabel);

        MessageOKButtonLabelPanel.add(CenterTopPanel);

        RightTopPanel.setLayout(new javax.swing.BoxLayout(RightTopPanel, javax.swing.BoxLayout.X_AXIS));

        RightTopPanel.setMaximumSize(new java.awt.Dimension(32767, 0));
        MessageOKButtonLabelPanel.add(RightTopPanel);

        MessageOKButtonPanel.add(MessageOKButtonLabelPanel);

        MessageTitleTextFieldPanel1.setLayout(new javax.swing.BoxLayout(MessageTitleTextFieldPanel1, javax.swing.BoxLayout.X_AXIS));

        LeftPanel.setLayout(new javax.swing.BoxLayout(LeftPanel, javax.swing.BoxLayout.X_AXIS));

        Separator15.setMaximumSize(new java.awt.Dimension(10, 10));
        Separator15.setMinimumSize(new java.awt.Dimension(10, 10));
        Separator15.setPreferredSize(new java.awt.Dimension(10, 10));
        LeftPanel.add(Separator15);

        tfMessageOKButtonText.setFont(new java.awt.Font("Arial", 0, 12));
        tfMessageOKButtonText.setMaximumSize(new java.awt.Dimension(137, 21));
        tfMessageOKButtonText.setPreferredSize(new java.awt.Dimension(137, 21));
        LeftPanel.add(tfMessageOKButtonText);

        Separator16.setMaximumSize(new java.awt.Dimension(10, 10));
        Separator16.setMinimumSize(new java.awt.Dimension(10, 10));
        Separator16.setPreferredSize(new java.awt.Dimension(10, 10));
        LeftPanel.add(Separator16);

        MessageTitleTextFieldPanel1.add(LeftPanel);

        CenterPanel.setLayout(new javax.swing.BoxLayout(CenterPanel, javax.swing.BoxLayout.X_AXIS));

        Separator19.setMaximumSize(new java.awt.Dimension(150, 10));
        Separator19.setMinimumSize(new java.awt.Dimension(10, 10));
        Separator19.setPreferredSize(new java.awt.Dimension(150, 10));
        CenterPanel.add(Separator19);

        tfMessageOKButtonMnemonic.setFont(new java.awt.Font("Arial", 0, 12));
        tfMessageOKButtonMnemonic.setMaximumSize(new java.awt.Dimension(25, 21));
        tfMessageOKButtonMnemonic.setMinimumSize(new java.awt.Dimension(25, 21));
        tfMessageOKButtonMnemonic.setPreferredSize(new java.awt.Dimension(25, 21));
        CenterPanel.add(tfMessageOKButtonMnemonic);

        Separator20.setMaximumSize(new java.awt.Dimension(10, 10));
        Separator20.setMinimumSize(new java.awt.Dimension(10, 10));
        Separator20.setPreferredSize(new java.awt.Dimension(10, 10));
        CenterPanel.add(Separator20);

        MessageTitleTextFieldPanel1.add(CenterPanel);

        RightPanel.setLayout(new javax.swing.BoxLayout(RightPanel, javax.swing.BoxLayout.X_AXIS));

        RightPanel.setMaximumSize(new java.awt.Dimension(32767, 0));
        Separator17.setMaximumSize(new java.awt.Dimension(10, 10));
        Separator17.setMinimumSize(new java.awt.Dimension(10, 10));
        Separator17.setPreferredSize(new java.awt.Dimension(10, 10));
        RightPanel.add(Separator17);

        Separator18.setMaximumSize(new java.awt.Dimension(10, 10));
        Separator18.setMinimumSize(new java.awt.Dimension(10, 10));
        Separator18.setPreferredSize(new java.awt.Dimension(10, 10));
        RightPanel.add(Separator18);

        MessageTitleTextFieldPanel1.add(RightPanel);

        MessageOKButtonPanel.add(MessageTitleTextFieldPanel1);

        add(MessageOKButtonPanel, java.awt.BorderLayout.CENTER);

    }//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CenterPanel;
    private javax.swing.JPanel CenterTopPanel;
    private javax.swing.JPanel LeftPanel;
    private javax.swing.JPanel LeftTopPanel;
    private javax.swing.JLabel MessageBodyLabel;
    private javax.swing.JPanel MessageBodyLabelPanel;
    private javax.swing.JPanel MessageBodyPanel;
    private javax.swing.JPanel MessageBodyTextAreaPanel;
    private javax.swing.JPanel MessageDataPanel;
    private javax.swing.JLabel MessageOKButtonLabel;
    private javax.swing.JPanel MessageOKButtonLabelPanel;
    private javax.swing.JLabel MessageOKButtonMnemonicLabel;
    private javax.swing.JPanel MessageOKButtonPanel;
    private javax.swing.JLabel MessageTitleLabel;
    private javax.swing.JPanel MessageTitleLabelPanel;
    private javax.swing.JPanel MessageTitlePanel;
    private javax.swing.JPanel MessageTitleTextFieldPanel;
    private javax.swing.JPanel MessageTitleTextFieldPanel1;
    private javax.swing.JPanel RightPanel;
    private javax.swing.JPanel RightTopPanel;
    private javax.swing.JLabel Separator10;
    private javax.swing.JLabel Separator11;
    private javax.swing.JLabel Separator12;
    private javax.swing.JLabel Separator13;
    private javax.swing.JLabel Separator14;
    private javax.swing.JLabel Separator15;
    private javax.swing.JLabel Separator16;
    private javax.swing.JLabel Separator17;
    private javax.swing.JLabel Separator18;
    private javax.swing.JLabel Separator19;
    private javax.swing.JLabel Separator2;
    private javax.swing.JLabel Separator20;
    private javax.swing.JLabel Separator21;
    private javax.swing.JLabel Separator3;
    private javax.swing.JLabel Separator4;
    private javax.swing.JLabel Separator5;
    private javax.swing.JLabel Separator6;
    private javax.swing.JLabel Separator7;
    private javax.swing.JLabel Separator8;
    private javax.swing.JLabel Separator9;
    private javax.swing.JScrollPane scrollPaneMessageBody;
    private javax.swing.JTextArea taMessageBody;
    private javax.swing.JTextField tfMessageOKButtonMnemonic;
    private javax.swing.JTextField tfMessageOKButtonText;
    private javax.swing.JTextField tfMessageTitle;
    // End of variables declaration//GEN-END:variables
    
}
