/*
 * MainColorPanel.java
 *
 * Created on October 11, 2004, 3:25 PM
 */

package com.trinity.ea.design.project.lookandfeel.bgimages;
import com.trinity.ea.design.common.panel.EAPanel;
import com.trinity.ea.design.project.lookandfeel.bgimages.PaymentImagesPanel;
import com.trinity.ea.design.project.lookandfeel.bgimages.ErrorImagesPanel;
import com.trinity.ea.design.project.lookandfeel.bgimages.MessagingAutoUpdateImagesPanel;
import javax.swing.*;

/**
 *
 * @author  aaronsc Trinity Software
 * Copyright ©2003-2004 Trinity Software. All rights reserved.
 */
public class BGImagesPanel extends EAPanel {
    
    /** Creates new form MainColorPanel */
    public BGImagesPanel() {
        initComponents();
    }

    public synchronized void getDataUpdate()
    {
	  try
        {
            //ProjectManager.saveTempNow(); 
		paymentsTab.getDataUpdate();
		messagingAutoUpdatesPanel.getDataUpdate();
		errorPanel.getDataUpdate();
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }

    public synchronized void setProjectData()
    {
        try
        {
		paymentsTab.setProjectData();
		paymentsTab.setParentComponent(this);
		messagingAutoUpdatesPanel.setProjectData();
		messagingAutoUpdatesPanel.setParentComponent(this);
		errorPanel.setProjectData();
		errorPanel.setParentComponent(this);
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }   
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        ColorsTabbedPane = new javax.swing.JTabbedPane();
        paymentsTab = new PaymentImagesPanel();
        messagingAutoUpdatesPanel = new MessagingAutoUpdateImagesPanel();
        errorPanel = new ErrorImagesPanel();

        setLayout(new java.awt.BorderLayout());

        setBackground(new java.awt.Color(140, 160, 210));
        ColorsTabbedPane.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        ColorsTabbedPane.setBackground(new java.awt.Color(140, 160, 210));
        //ColorsTabbedPane.setForeground(new java.awt.Color(255, 255, 255));
try
{
	  ((javax.swing.JViewport)ColorsTabbedPane.getComponents()[0]).getView().setBackground(new java.awt.Color(140, 160, 210));
}
catch(Exception e){}         ColorsTabbedPane.setFont(new java.awt.Font("Arial", 0, 12));
        ColorsTabbedPane.addTab("Payment", paymentsTab);

        ColorsTabbedPane.addTab("Messaging/Auto Update", messagingAutoUpdatesPanel);

        ColorsTabbedPane.addTab("Error Dialog", errorPanel);

        ColorsTabbedPane.setTabPlacement(javax.swing.JTabbedPane.TOP);
        add(ColorsTabbedPane, java.awt.BorderLayout.CENTER);

    }//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane ColorsTabbedPane;
    private MessagingAutoUpdateImagesPanel messagingAutoUpdatesPanel;
    private PaymentImagesPanel paymentsTab;
    private ErrorImagesPanel errorPanel;
    // End of variables declaration//GEN-END:variables
    
}
