/*
 * MainTextPanel.java
 *
 * Created on October 11, 2004, 3:25 PM
 */

package com.trinity.ea.design.project.lookandfeel.text;
import com.trinity.ea.design.common.panel.EAPanel;
import com.trinity.ea.design.project.lookandfeel.text.InformationTextPanel;
import com.trinity.ea.design.project.lookandfeel.text.TextPanel;
import javax.swing.*;

/**
 *
 * @author  aaronsc Trinity Software
 * Copyright ©2003-2004 Trinity Software. All rights reserved.
 */
public class MainTextPanel extends EAPanel {
    
    /** Creates new form MainTextPanel */
    public MainTextPanel() {
        initComponents();
    }

    public synchronized void getDataUpdate()
    {
	  try
        {
            //ProjectManager.saveTempNow(); 
		startupTextPanel.getDataUpdate();
		informationTextPanel.getDataUpdate();
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }

    public synchronized void setProjectData()
    {
        try
        {
		startupTextPanel.setProjectData();
		startupTextPanel.setParentComponent(this);
		informationTextPanel.setProjectData();
		informationTextPanel.setParentComponent(this);
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }   
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        ColorsTabbedPane = new javax.swing.JTabbedPane();
        startupTextPanel = new TextPanel();
        informationTextPanel = new InformationTextPanel();
        setLayout(new java.awt.BorderLayout());

        setBackground(new java.awt.Color(140, 160, 210));
        ColorsTabbedPane.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        ColorsTabbedPane.setBackground(new java.awt.Color(140, 160, 210));
        //ColorsTabbedPane.setForeground(new java.awt.Color(255, 255, 255));
try
{
	  ((javax.swing.JViewport)ColorsTabbedPane.getComponents()[0]).getView().setBackground(new java.awt.Color(140, 160, 210));
}
catch(Exception e){} 
       ColorsTabbedPane.setFont(new java.awt.Font("Arial", 0, 12));

        ColorsTabbedPane.addTab("Startup Window", startupTextPanel);

        ColorsTabbedPane.addTab("Information Dialog", informationTextPanel);

        ColorsTabbedPane.setTabPlacement(javax.swing.JTabbedPane.TOP);
        add(ColorsTabbedPane, java.awt.BorderLayout.CENTER);

    }//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane ColorsTabbedPane;
    private InformationTextPanel informationTextPanel;
    private TextPanel startupTextPanel;

    // End of variables declaration//GEN-END:variables
    
}
