/*
 * LanguagePanel.java
 *
 * Created on December 31, 2004, 6:41 PM
 */

package com.trinity.ea.design.autoupdate.builder;
import javax.swing.JPanel;
import javax.swing.JLabel;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import java.awt.Font;
import java.awt.Dimension;
import javax.swing.BoxLayout;
import java.awt.BorderLayout;
import javax.swing.JScrollPane;

/**
 *
 * @author  aaronsc Trinity Software
 * Copyright ©2004 Trinity Software. All rights reserved.
 */
public class LanguagePanel extends javax.swing.JPanel 
{
    private String langID = "en";
    private String msgTitle = "";
    private String msgBody = "";
    private String OKText = "OK";
    private String OKMnemonic = "O";    
     
    public void setLanguage(String language)
    {
        langID = language;
    }
    
    public String getLanguage()
    {
        return langID;
    }   

    public void setMessage(String msg)
    {
        taMessageBody.setText(msg);
    }
    
    public String getMessage()
    {
	try
	{
            String theText = taMessageBody.getText();
            String theText2 = theText.replaceAll("\r\n", "\\\\r\\\\n");     
            if(theText.equalsIgnoreCase(theText2)==true)
            {
                return theText2.replaceAll("\n", "\\\\r\\\\n");                
            }
            else
            {
                return theText2;
            }
	}
	catch(Exception e)
	{
            e.printStackTrace();
            return taMessageBody.getText();
	}        
    }           
 
    public void setMessageTitle(String title)
    {
        tfMessageTitle.setText(title);
    }
    
    public String getMessageTitle()
    {
        return tfMessageTitle.getText();
    }      
    
    public void setMessageOKText(String okText)
    {
        tfMessageOKButtonText.setText(okText);
    }
    
    public String getMessageOKText()
    {
        return tfMessageOKButtonText.getText();
    }      

    public void setMessageOKMnemonic(String okMnemonic)
    {
        tfMessageOKButtonMnemonic.setText(okMnemonic);
    }
    
    public String getMessageOKMnemonic()
    {
        return tfMessageOKButtonMnemonic.getText();
    }      

    public void setMessageSkipText(String skipText)
    {
        tfMessageSkipButtonText.setText(skipText);
    }
    
    public String getMessageSkipText()
    {
        return tfMessageSkipButtonText.getText();
    }     
    
    public void setMessageSkipMnemonic(String skipMnemonic)
    {
        tfMessageSkipButtonMnemonic.setText(skipMnemonic);
    }
    
    public String getMessageSkipMnemonic()
    {
        return tfMessageSkipButtonMnemonic.getText();
    }       

    public void setSupportMessage(String supportmsg)
    {
        taSupportMessage.setText(supportmsg);
    }
    
    public String getSupportMessage()
    {
        return taSupportMessage.getText();
    } 
    
    public void setErrorMessage(String errormsg)
    {
        taErrorMessage.setText(errormsg);
    }
    
    public String getErrorMessage()
    {
        return taErrorMessage.getText();
    }   
    
    /** Creates new form LanguagePanel */
    public LanguagePanel() 
    {
        initComponents();
    }
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        MessageDataPanel = new javax.swing.JPanel();
        MessageTitlePanel = new javax.swing.JPanel();
        Separator13 = new javax.swing.JLabel();
        MessageTitleLabelPanel = new javax.swing.JPanel();
        Separator3 = new javax.swing.JLabel();
        MessageTitleLabel = new javax.swing.JLabel();
        Separator2 = new javax.swing.JLabel();
        MessageTitleTextFieldPanel = new javax.swing.JPanel();
        Separator5 = new javax.swing.JLabel();
        tfMessageTitle = new javax.swing.JTextField();
        Separator4 = new javax.swing.JLabel();
        MessageBodyPanel = new javax.swing.JPanel();
        Separator12 = new javax.swing.JLabel();
        MessageBodyLabelPanel = new javax.swing.JPanel();
        Separator8 = new javax.swing.JLabel();
        MessageBodyLabel = new javax.swing.JLabel();
        Separator9 = new javax.swing.JLabel();
        MessageBodyTextAreaPanel = new javax.swing.JPanel();
        Separator10 = new javax.swing.JLabel();
        scrollPaneMessageBody = new javax.swing.JScrollPane();
        taMessageBody = new javax.swing.JTextArea();
        Separator11 = new javax.swing.JLabel();
        MessageOKButtonPanel = new javax.swing.JPanel();
        Separator14 = new javax.swing.JLabel();
        MessageOKButtonLabelPanel = new javax.swing.JPanel();
        LeftTopPanel = new javax.swing.JPanel();
        Separator6 = new javax.swing.JLabel();
        MessageOKButtonLabel = new javax.swing.JLabel();
        Separator7 = new javax.swing.JLabel();
        CenterTopPanel = new javax.swing.JPanel();
        Separator21 = new javax.swing.JLabel();
        MessageOKButtonMnemonicLabel = new javax.swing.JLabel();
        RightTopPanel = new javax.swing.JPanel();
        MessageTitleTextFieldPanel1 = new javax.swing.JPanel();
        LeftPanel = new javax.swing.JPanel();
        Separator15 = new javax.swing.JLabel();
        tfMessageOKButtonText = new javax.swing.JTextField();
        Separator16 = new javax.swing.JLabel();
        CenterPanel = new javax.swing.JPanel();
        Separator19 = new javax.swing.JLabel();
        tfMessageOKButtonMnemonic = new javax.swing.JTextField();
        Separator20 = new javax.swing.JLabel();
        RightPanel = new javax.swing.JPanel();
        Separator17 = new javax.swing.JLabel();
        Separator18 = new javax.swing.JLabel();
        Separator31 = new javax.swing.JLabel();
        MessageOKButtonLabelPanel1 = new javax.swing.JPanel();
        LeftTopPanel1 = new javax.swing.JPanel();
        Separator28 = new javax.swing.JLabel();
        MessageSkipButtonLabel = new javax.swing.JLabel();
        Separator29 = new javax.swing.JLabel();
        CenterTopPanel1 = new javax.swing.JPanel();
        Separator30 = new javax.swing.JLabel();
        MessageSkipButtonMnemonicLabel = new javax.swing.JLabel();
        RightTopPanel1 = new javax.swing.JPanel();
        MessageTitleTextFieldPanel2 = new javax.swing.JPanel();
        LeftPanel1 = new javax.swing.JPanel();
        Separator22 = new javax.swing.JLabel();
        tfMessageSkipButtonText = new javax.swing.JTextField();
        Separator23 = new javax.swing.JLabel();
        CenterPanel1 = new javax.swing.JPanel();
        Separator24 = new javax.swing.JLabel();
        tfMessageSkipButtonMnemonic = new javax.swing.JTextField();
        Separator25 = new javax.swing.JLabel();
        RightPanel1 = new javax.swing.JPanel();
        Separator26 = new javax.swing.JLabel();
        Separator27 = new javax.swing.JLabel();
        Separator37 = new javax.swing.JLabel();
        BorderSeparator = new javax.swing.JPanel();
        FillerLabel2 = new javax.swing.JLabel();
        BorderSeparator2 = new javax.swing.JPanel();
        FillerLabel3 = new javax.swing.JLabel();
        MessageBodyPanel1 = new javax.swing.JPanel();
        Separator32 = new javax.swing.JLabel();
        MessageBodyLabelPanel1 = new javax.swing.JPanel();
        Separator33 = new javax.swing.JLabel();
        MessageSupportLabel = new javax.swing.JLabel();
        Separator34 = new javax.swing.JLabel();
        MessageBodyTextAreaPanel1 = new javax.swing.JPanel();
        Separator35 = new javax.swing.JLabel();
        scrollPaneMessageBody1 = new javax.swing.JScrollPane();
        taSupportMessage = new javax.swing.JTextArea();
        Separator36 = new javax.swing.JLabel();
        MessageBodyPanel2 = new javax.swing.JPanel();
        Separator38 = new javax.swing.JLabel();
        MessageBodyLabelPanel2 = new javax.swing.JPanel();
        Separator39 = new javax.swing.JLabel();
        MessageBodyLabel2 = new javax.swing.JLabel();
        Separator40 = new javax.swing.JLabel();
        MessageBodyTextAreaPanel2 = new javax.swing.JPanel();
        Separator41 = new javax.swing.JLabel();
        scrollPaneMessageBody2 = new javax.swing.JScrollPane();
        taErrorMessage = new javax.swing.JTextArea();
        Separator42 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        MessageDataPanel.setLayout(new javax.swing.BoxLayout(MessageDataPanel, javax.swing.BoxLayout.Y_AXIS));

        MessageDataPanel.setFont(new java.awt.Font("Arial", 0, 12));
        MessageTitlePanel.setLayout(new javax.swing.BoxLayout(MessageTitlePanel, javax.swing.BoxLayout.Y_AXIS));

        Separator13.setMaximumSize(new java.awt.Dimension(10, 10));
        Separator13.setMinimumSize(new java.awt.Dimension(10, 10));
        Separator13.setPreferredSize(new java.awt.Dimension(10, 10));
        MessageTitlePanel.add(Separator13);

        MessageTitleLabelPanel.setLayout(new javax.swing.BoxLayout(MessageTitleLabelPanel, javax.swing.BoxLayout.X_AXIS));

        Separator3.setMaximumSize(new java.awt.Dimension(10, 10));
        Separator3.setMinimumSize(new java.awt.Dimension(10, 10));
        Separator3.setPreferredSize(new java.awt.Dimension(10, 10));
        MessageTitleLabelPanel.add(Separator3);

        MessageTitleLabel.setDisplayedMnemonic('T');
        MessageTitleLabel.setFont(new java.awt.Font("Arial", 0, 12));
        MessageTitleLabel.setLabelFor(tfMessageTitle);
        MessageTitleLabel.setText("Message Title:");
        MessageTitleLabel.setMaximumSize(new java.awt.Dimension(32767, 15));
        MessageTitleLabel.setPreferredSize(new java.awt.Dimension(1200, 15));
        MessageTitleLabelPanel.add(MessageTitleLabel);

        Separator2.setMaximumSize(new java.awt.Dimension(10, 10));
        Separator2.setMinimumSize(new java.awt.Dimension(10, 10));
        Separator2.setPreferredSize(new java.awt.Dimension(10, 10));
        MessageTitleLabelPanel.add(Separator2);

        MessageTitlePanel.add(MessageTitleLabelPanel);

        MessageTitleTextFieldPanel.setLayout(new javax.swing.BoxLayout(MessageTitleTextFieldPanel, javax.swing.BoxLayout.X_AXIS));

        Separator5.setMaximumSize(new java.awt.Dimension(10, 10));
        Separator5.setMinimumSize(new java.awt.Dimension(10, 10));
        Separator5.setPreferredSize(new java.awt.Dimension(10, 10));
        MessageTitleTextFieldPanel.add(Separator5);

        tfMessageTitle.setFont(new java.awt.Font("Arial", 0, 12));
        tfMessageTitle.setMaximumSize(new java.awt.Dimension(2147483647, 21));
        MessageTitleTextFieldPanel.add(tfMessageTitle);

        Separator4.setMaximumSize(new java.awt.Dimension(10, 10));
        Separator4.setMinimumSize(new java.awt.Dimension(10, 10));
        Separator4.setPreferredSize(new java.awt.Dimension(10, 10));
        MessageTitleTextFieldPanel.add(Separator4);

        MessageTitlePanel.add(MessageTitleTextFieldPanel);

        MessageDataPanel.add(MessageTitlePanel);

        MessageBodyPanel.setLayout(new javax.swing.BoxLayout(MessageBodyPanel, javax.swing.BoxLayout.Y_AXIS));

        Separator12.setMaximumSize(new java.awt.Dimension(10, 5));
        Separator12.setMinimumSize(new java.awt.Dimension(10, 5));
        Separator12.setPreferredSize(new java.awt.Dimension(10, 5));
        MessageBodyPanel.add(Separator12);

        MessageBodyLabelPanel.setLayout(new javax.swing.BoxLayout(MessageBodyLabelPanel, javax.swing.BoxLayout.X_AXIS));

        Separator8.setMaximumSize(new java.awt.Dimension(10, 10));
        Separator8.setMinimumSize(new java.awt.Dimension(10, 10));
        Separator8.setPreferredSize(new java.awt.Dimension(10, 10));
        MessageBodyLabelPanel.add(Separator8);

        MessageBodyLabel.setDisplayedMnemonic('e');
        MessageBodyLabel.setFont(new java.awt.Font("Arial", 0, 12));
        MessageBodyLabel.setLabelFor(taMessageBody);
        MessageBodyLabel.setText("Message Body:");
        MessageBodyLabel.setMaximumSize(new java.awt.Dimension(32767, 15));
        MessageBodyLabel.setPreferredSize(new java.awt.Dimension(1200, 15));
        MessageBodyLabelPanel.add(MessageBodyLabel);

        Separator9.setMaximumSize(new java.awt.Dimension(10, 10));
        Separator9.setMinimumSize(new java.awt.Dimension(10, 10));
        Separator9.setPreferredSize(new java.awt.Dimension(10, 10));
        MessageBodyLabelPanel.add(Separator9);

        MessageBodyPanel.add(MessageBodyLabelPanel);

        MessageBodyTextAreaPanel.setLayout(new javax.swing.BoxLayout(MessageBodyTextAreaPanel, javax.swing.BoxLayout.X_AXIS));

        Separator10.setMaximumSize(new java.awt.Dimension(10, 10));
        Separator10.setMinimumSize(new java.awt.Dimension(10, 10));
        Separator10.setPreferredSize(new java.awt.Dimension(10, 10));
        MessageBodyTextAreaPanel.add(Separator10);

        scrollPaneMessageBody.setMaximumSize(new java.awt.Dimension(32767, 69));
        scrollPaneMessageBody.setMinimumSize(new java.awt.Dimension(23, 69));
        scrollPaneMessageBody.setPreferredSize(new java.awt.Dimension(4, 69));
        taMessageBody.setFont(new java.awt.Font("Arial", 0, 12));
        taMessageBody.setLineWrap(true);
        taMessageBody.setWrapStyleWord(true);
        taMessageBody.setMinimumSize(new java.awt.Dimension(0, 0));
        taMessageBody.setPreferredSize(new java.awt.Dimension(0, 0));
        scrollPaneMessageBody.setViewportView(taMessageBody);

        MessageBodyTextAreaPanel.add(scrollPaneMessageBody);

        Separator11.setMaximumSize(new java.awt.Dimension(10, 10));
        Separator11.setMinimumSize(new java.awt.Dimension(10, 10));
        Separator11.setPreferredSize(new java.awt.Dimension(10, 10));
        MessageBodyTextAreaPanel.add(Separator11);

        MessageBodyPanel.add(MessageBodyTextAreaPanel);

        MessageDataPanel.add(MessageBodyPanel);

        add(MessageDataPanel, java.awt.BorderLayout.NORTH);

        MessageOKButtonPanel.setLayout(new javax.swing.BoxLayout(MessageOKButtonPanel, javax.swing.BoxLayout.Y_AXIS));

        Separator14.setMaximumSize(new java.awt.Dimension(10, 10));
        Separator14.setMinimumSize(new java.awt.Dimension(10, 10));
        Separator14.setPreferredSize(new java.awt.Dimension(10, 10));
        MessageOKButtonPanel.add(Separator14);

        MessageOKButtonLabelPanel.setLayout(new javax.swing.BoxLayout(MessageOKButtonLabelPanel, javax.swing.BoxLayout.X_AXIS));

        LeftTopPanel.setLayout(new javax.swing.BoxLayout(LeftTopPanel, javax.swing.BoxLayout.X_AXIS));

        LeftTopPanel.setMaximumSize(new java.awt.Dimension(156, 15));
        LeftTopPanel.setMinimumSize(new java.awt.Dimension(156, 15));
        LeftTopPanel.setPreferredSize(new java.awt.Dimension(156, 15));
        Separator6.setMaximumSize(new java.awt.Dimension(10, 10));
        Separator6.setMinimumSize(new java.awt.Dimension(10, 10));
        Separator6.setPreferredSize(new java.awt.Dimension(10, 10));
        LeftTopPanel.add(Separator6);

        MessageOKButtonLabel.setDisplayedMnemonic('K');
        MessageOKButtonLabel.setFont(new java.awt.Font("Arial", 0, 12));
        MessageOKButtonLabel.setLabelFor(tfMessageOKButtonText);
        MessageOKButtonLabel.setText("Message OK Button Text:");
        MessageOKButtonLabel.setMaximumSize(new java.awt.Dimension(156, 15));
        MessageOKButtonLabel.setMinimumSize(new java.awt.Dimension(156, 15));
        MessageOKButtonLabel.setPreferredSize(new java.awt.Dimension(156, 15));
        LeftTopPanel.add(MessageOKButtonLabel);

        Separator7.setMaximumSize(new java.awt.Dimension(32767, 10));
        Separator7.setMinimumSize(new java.awt.Dimension(10, 10));
        Separator7.setPreferredSize(new java.awt.Dimension(10, 10));
        LeftTopPanel.add(Separator7);

        MessageOKButtonLabelPanel.add(LeftTopPanel);

        CenterTopPanel.setLayout(new javax.swing.BoxLayout(CenterTopPanel, javax.swing.BoxLayout.X_AXIS));

        CenterTopPanel.setMaximumSize(new java.awt.Dimension(185, 15));
        CenterTopPanel.setMinimumSize(new java.awt.Dimension(0, 15));
        CenterTopPanel.setPreferredSize(new java.awt.Dimension(185, 15));
        Separator21.setMaximumSize(new java.awt.Dimension(32767, 10));
        Separator21.setMinimumSize(new java.awt.Dimension(10, 10));
        Separator21.setPreferredSize(new java.awt.Dimension(10, 10));
        CenterTopPanel.add(Separator21);

        MessageOKButtonMnemonicLabel.setDisplayedMnemonic('n');
        MessageOKButtonMnemonicLabel.setFont(new java.awt.Font("Arial", 0, 12));
        MessageOKButtonMnemonicLabel.setLabelFor(tfMessageOKButtonMnemonic);
        MessageOKButtonMnemonicLabel.setText("Message OK Button Mnemonic:");
        MessageOKButtonMnemonicLabel.setMaximumSize(new java.awt.Dimension(185, 15));
        MessageOKButtonMnemonicLabel.setMinimumSize(new java.awt.Dimension(185, 15));
        MessageOKButtonMnemonicLabel.setPreferredSize(new java.awt.Dimension(185, 15));
        CenterTopPanel.add(MessageOKButtonMnemonicLabel);

        MessageOKButtonLabelPanel.add(CenterTopPanel);

        RightTopPanel.setLayout(new javax.swing.BoxLayout(RightTopPanel, javax.swing.BoxLayout.X_AXIS));

        RightTopPanel.setMaximumSize(new java.awt.Dimension(32767, 0));
        MessageOKButtonLabelPanel.add(RightTopPanel);

        MessageOKButtonPanel.add(MessageOKButtonLabelPanel);

        MessageTitleTextFieldPanel1.setLayout(new javax.swing.BoxLayout(MessageTitleTextFieldPanel1, javax.swing.BoxLayout.X_AXIS));

        LeftPanel.setLayout(new javax.swing.BoxLayout(LeftPanel, javax.swing.BoxLayout.X_AXIS));

        Separator15.setMaximumSize(new java.awt.Dimension(10, 10));
        Separator15.setMinimumSize(new java.awt.Dimension(10, 10));
        Separator15.setPreferredSize(new java.awt.Dimension(10, 10));
        LeftPanel.add(Separator15);

        tfMessageOKButtonText.setFont(new java.awt.Font("Arial", 0, 12));
        tfMessageOKButtonText.setMaximumSize(new java.awt.Dimension(137, 21));
        tfMessageOKButtonText.setPreferredSize(new java.awt.Dimension(137, 21));
        LeftPanel.add(tfMessageOKButtonText);

        Separator16.setMaximumSize(new java.awt.Dimension(10, 10));
        Separator16.setMinimumSize(new java.awt.Dimension(10, 10));
        Separator16.setPreferredSize(new java.awt.Dimension(10, 10));
        LeftPanel.add(Separator16);

        MessageTitleTextFieldPanel1.add(LeftPanel);

        CenterPanel.setLayout(new javax.swing.BoxLayout(CenterPanel, javax.swing.BoxLayout.X_AXIS));

        Separator19.setMaximumSize(new java.awt.Dimension(150, 10));
        Separator19.setMinimumSize(new java.awt.Dimension(10, 10));
        Separator19.setPreferredSize(new java.awt.Dimension(150, 10));
        CenterPanel.add(Separator19);

        tfMessageOKButtonMnemonic.setFont(new java.awt.Font("Arial", 0, 12));
        tfMessageOKButtonMnemonic.setMaximumSize(new java.awt.Dimension(25, 21));
        tfMessageOKButtonMnemonic.setMinimumSize(new java.awt.Dimension(25, 21));
        tfMessageOKButtonMnemonic.setPreferredSize(new java.awt.Dimension(25, 21));
        CenterPanel.add(tfMessageOKButtonMnemonic);

        Separator20.setMaximumSize(new java.awt.Dimension(10, 10));
        Separator20.setMinimumSize(new java.awt.Dimension(10, 10));
        Separator20.setPreferredSize(new java.awt.Dimension(10, 10));
        CenterPanel.add(Separator20);

        MessageTitleTextFieldPanel1.add(CenterPanel);

        RightPanel.setLayout(new javax.swing.BoxLayout(RightPanel, javax.swing.BoxLayout.X_AXIS));

        RightPanel.setMaximumSize(new java.awt.Dimension(32767, 0));
        Separator17.setMaximumSize(new java.awt.Dimension(10, 10));
        Separator17.setMinimumSize(new java.awt.Dimension(10, 10));
        Separator17.setPreferredSize(new java.awt.Dimension(10, 10));
        RightPanel.add(Separator17);

        Separator18.setMaximumSize(new java.awt.Dimension(10, 10));
        Separator18.setMinimumSize(new java.awt.Dimension(10, 10));
        Separator18.setPreferredSize(new java.awt.Dimension(10, 10));
        RightPanel.add(Separator18);

        MessageTitleTextFieldPanel1.add(RightPanel);

        MessageOKButtonPanel.add(MessageTitleTextFieldPanel1);

        Separator31.setMaximumSize(new java.awt.Dimension(10, 5));
        Separator31.setMinimumSize(new java.awt.Dimension(10, 5));
        Separator31.setPreferredSize(new java.awt.Dimension(10, 5));
        MessageOKButtonPanel.add(Separator31);

        MessageOKButtonLabelPanel1.setLayout(new javax.swing.BoxLayout(MessageOKButtonLabelPanel1, javax.swing.BoxLayout.X_AXIS));

        LeftTopPanel1.setLayout(new javax.swing.BoxLayout(LeftTopPanel1, javax.swing.BoxLayout.X_AXIS));

        LeftTopPanel1.setMaximumSize(new java.awt.Dimension(156, 15));
        LeftTopPanel1.setMinimumSize(new java.awt.Dimension(156, 15));
        LeftTopPanel1.setPreferredSize(new java.awt.Dimension(156, 15));
        Separator28.setMaximumSize(new java.awt.Dimension(10, 10));
        Separator28.setMinimumSize(new java.awt.Dimension(10, 10));
        Separator28.setPreferredSize(new java.awt.Dimension(10, 10));
        LeftTopPanel1.add(Separator28);

        MessageSkipButtonLabel.setDisplayedMnemonic('a');
        MessageSkipButtonLabel.setFont(new java.awt.Font("Arial", 0, 12));
        MessageSkipButtonLabel.setLabelFor(tfMessageSkipButtonText);
        MessageSkipButtonLabel.setText("Message Skip Button Text:");
        MessageSkipButtonLabel.setMaximumSize(new java.awt.Dimension(156, 15));
        MessageSkipButtonLabel.setMinimumSize(new java.awt.Dimension(156, 15));
        MessageSkipButtonLabel.setPreferredSize(new java.awt.Dimension(156, 15));
        LeftTopPanel1.add(MessageSkipButtonLabel);

        Separator29.setMaximumSize(new java.awt.Dimension(32767, 10));
        Separator29.setMinimumSize(new java.awt.Dimension(10, 10));
        Separator29.setPreferredSize(new java.awt.Dimension(10, 10));
        LeftTopPanel1.add(Separator29);

        MessageOKButtonLabelPanel1.add(LeftTopPanel1);

        CenterTopPanel1.setLayout(new javax.swing.BoxLayout(CenterTopPanel1, javax.swing.BoxLayout.X_AXIS));

        CenterTopPanel1.setMaximumSize(new java.awt.Dimension(195, 15));
        CenterTopPanel1.setMinimumSize(new java.awt.Dimension(0, 15));
        CenterTopPanel1.setPreferredSize(new java.awt.Dimension(195, 15));
        Separator30.setMaximumSize(new java.awt.Dimension(32767, 10));
        Separator30.setMinimumSize(new java.awt.Dimension(10, 10));
        Separator30.setPreferredSize(new java.awt.Dimension(10, 10));
        CenterTopPanel1.add(Separator30);

        MessageSkipButtonMnemonicLabel.setDisplayedMnemonic('u');
        MessageSkipButtonMnemonicLabel.setFont(new java.awt.Font("Arial", 0, 12));
        MessageSkipButtonMnemonicLabel.setLabelFor(tfMessageSkipButtonMnemonic);
        MessageSkipButtonMnemonicLabel.setText("Message Skip Button Mnemonic:");
        MessageSkipButtonMnemonicLabel.setMaximumSize(new java.awt.Dimension(195, 15));
        MessageSkipButtonMnemonicLabel.setMinimumSize(new java.awt.Dimension(195, 15));
        MessageSkipButtonMnemonicLabel.setPreferredSize(new java.awt.Dimension(195, 15));
        CenterTopPanel1.add(MessageSkipButtonMnemonicLabel);

        MessageOKButtonLabelPanel1.add(CenterTopPanel1);

        RightTopPanel1.setLayout(new javax.swing.BoxLayout(RightTopPanel1, javax.swing.BoxLayout.X_AXIS));

        RightTopPanel1.setMaximumSize(new java.awt.Dimension(32767, 0));
        MessageOKButtonLabelPanel1.add(RightTopPanel1);

        MessageOKButtonPanel.add(MessageOKButtonLabelPanel1);

        MessageTitleTextFieldPanel2.setLayout(new javax.swing.BoxLayout(MessageTitleTextFieldPanel2, javax.swing.BoxLayout.X_AXIS));

        LeftPanel1.setLayout(new javax.swing.BoxLayout(LeftPanel1, javax.swing.BoxLayout.X_AXIS));

        Separator22.setMaximumSize(new java.awt.Dimension(10, 10));
        Separator22.setMinimumSize(new java.awt.Dimension(10, 10));
        Separator22.setPreferredSize(new java.awt.Dimension(10, 10));
        LeftPanel1.add(Separator22);

        tfMessageSkipButtonText.setFont(new java.awt.Font("Arial", 0, 12));
        tfMessageSkipButtonText.setMaximumSize(new java.awt.Dimension(137, 21));
        tfMessageSkipButtonText.setPreferredSize(new java.awt.Dimension(137, 21));
        LeftPanel1.add(tfMessageSkipButtonText);

        Separator23.setMaximumSize(new java.awt.Dimension(10, 10));
        Separator23.setMinimumSize(new java.awt.Dimension(10, 10));
        Separator23.setPreferredSize(new java.awt.Dimension(10, 10));
        LeftPanel1.add(Separator23);

        MessageTitleTextFieldPanel2.add(LeftPanel1);

        CenterPanel1.setLayout(new javax.swing.BoxLayout(CenterPanel1, javax.swing.BoxLayout.X_AXIS));

        Separator24.setMaximumSize(new java.awt.Dimension(150, 10));
        Separator24.setMinimumSize(new java.awt.Dimension(10, 10));
        Separator24.setPreferredSize(new java.awt.Dimension(150, 10));
        CenterPanel1.add(Separator24);

        tfMessageSkipButtonMnemonic.setFont(new java.awt.Font("Arial", 0, 12));
        tfMessageSkipButtonMnemonic.setMaximumSize(new java.awt.Dimension(25, 21));
        tfMessageSkipButtonMnemonic.setMinimumSize(new java.awt.Dimension(25, 21));
        tfMessageSkipButtonMnemonic.setPreferredSize(new java.awt.Dimension(25, 21));
        tfMessageSkipButtonMnemonic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfMessageSkipButtonMnemonicActionPerformed(evt);
            }
        });

        CenterPanel1.add(tfMessageSkipButtonMnemonic);

        Separator25.setMaximumSize(new java.awt.Dimension(10, 10));
        Separator25.setMinimumSize(new java.awt.Dimension(10, 10));
        Separator25.setPreferredSize(new java.awt.Dimension(10, 10));
        CenterPanel1.add(Separator25);

        MessageTitleTextFieldPanel2.add(CenterPanel1);

        RightPanel1.setLayout(new javax.swing.BoxLayout(RightPanel1, javax.swing.BoxLayout.X_AXIS));

        RightPanel1.setMaximumSize(new java.awt.Dimension(32767, 0));
        Separator26.setMaximumSize(new java.awt.Dimension(10, 10));
        Separator26.setMinimumSize(new java.awt.Dimension(10, 10));
        Separator26.setPreferredSize(new java.awt.Dimension(10, 10));
        RightPanel1.add(Separator26);

        Separator27.setMaximumSize(new java.awt.Dimension(10, 10));
        Separator27.setMinimumSize(new java.awt.Dimension(10, 10));
        Separator27.setPreferredSize(new java.awt.Dimension(10, 10));
        RightPanel1.add(Separator27);

        MessageTitleTextFieldPanel2.add(RightPanel1);

        MessageOKButtonPanel.add(MessageTitleTextFieldPanel2);

        Separator37.setMaximumSize(new java.awt.Dimension(10, 5));
        Separator37.setMinimumSize(new java.awt.Dimension(10, 5));
        Separator37.setPreferredSize(new java.awt.Dimension(10, 5));
        MessageOKButtonPanel.add(Separator37);

        BorderSeparator.setLayout(new java.awt.BorderLayout());

        BorderSeparator.setMaximumSize(new java.awt.Dimension(32767, 2));
        BorderSeparator.setMinimumSize(new java.awt.Dimension(10, 2));
        BorderSeparator.setPreferredSize(new java.awt.Dimension(10, 2));
        FillerLabel2.setMaximumSize(new java.awt.Dimension(10, 2));
        FillerLabel2.setMinimumSize(new java.awt.Dimension(10, 2));
        FillerLabel2.setPreferredSize(new java.awt.Dimension(10, 2));
        BorderSeparator.add(FillerLabel2, java.awt.BorderLayout.WEST);

        BorderSeparator2.setBorder(new javax.swing.border.EtchedBorder());
        BorderSeparator2.setMaximumSize(new java.awt.Dimension(32767, 2));
        BorderSeparator2.setMinimumSize(new java.awt.Dimension(10, 2));
        BorderSeparator2.setPreferredSize(new java.awt.Dimension(10, 2));
        BorderSeparator.add(BorderSeparator2, java.awt.BorderLayout.CENTER);

        FillerLabel3.setMaximumSize(new java.awt.Dimension(10, 2));
        FillerLabel3.setMinimumSize(new java.awt.Dimension(10, 2));
        FillerLabel3.setPreferredSize(new java.awt.Dimension(10, 2));
        BorderSeparator.add(FillerLabel3, java.awt.BorderLayout.EAST);

        MessageOKButtonPanel.add(BorderSeparator);

        MessageBodyPanel1.setLayout(new javax.swing.BoxLayout(MessageBodyPanel1, javax.swing.BoxLayout.Y_AXIS));

        Separator32.setMaximumSize(new java.awt.Dimension(10, 5));
        Separator32.setMinimumSize(new java.awt.Dimension(10, 5));
        Separator32.setPreferredSize(new java.awt.Dimension(10, 5));
        MessageBodyPanel1.add(Separator32);

        MessageBodyLabelPanel1.setLayout(new javax.swing.BoxLayout(MessageBodyLabelPanel1, javax.swing.BoxLayout.X_AXIS));

        Separator33.setMaximumSize(new java.awt.Dimension(10, 10));
        Separator33.setMinimumSize(new java.awt.Dimension(10, 10));
        Separator33.setPreferredSize(new java.awt.Dimension(10, 10));
        MessageBodyLabelPanel1.add(Separator33);

        MessageSupportLabel.setDisplayedMnemonic('s');
        MessageSupportLabel.setFont(new java.awt.Font("Arial", 0, 12));
        MessageSupportLabel.setLabelFor(taSupportMessage);
        MessageSupportLabel.setText("Install Issue Customer Support Message:");
        MessageSupportLabel.setMaximumSize(new java.awt.Dimension(32767, 15));
        MessageSupportLabel.setPreferredSize(new java.awt.Dimension(1200, 15));
        MessageBodyLabelPanel1.add(MessageSupportLabel);

        Separator34.setMaximumSize(new java.awt.Dimension(10, 10));
        Separator34.setMinimumSize(new java.awt.Dimension(10, 10));
        Separator34.setPreferredSize(new java.awt.Dimension(10, 10));
        MessageBodyLabelPanel1.add(Separator34);

        MessageBodyPanel1.add(MessageBodyLabelPanel1);

        MessageBodyTextAreaPanel1.setLayout(new javax.swing.BoxLayout(MessageBodyTextAreaPanel1, javax.swing.BoxLayout.X_AXIS));

        Separator35.setMaximumSize(new java.awt.Dimension(10, 10));
        Separator35.setMinimumSize(new java.awt.Dimension(10, 10));
        Separator35.setPreferredSize(new java.awt.Dimension(10, 10));
        MessageBodyTextAreaPanel1.add(Separator35);

        scrollPaneMessageBody1.setHorizontalScrollBarPolicy(javax.swing.JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
        scrollPaneMessageBody1.setVerticalScrollBarPolicy(javax.swing.JScrollPane.VERTICAL_SCROLLBAR_NEVER);
        scrollPaneMessageBody1.setMaximumSize(new java.awt.Dimension(32767, 34));
        scrollPaneMessageBody1.setMinimumSize(new java.awt.Dimension(23, 34));
        scrollPaneMessageBody1.setPreferredSize(new java.awt.Dimension(4, 34));
        taSupportMessage.setFont(new java.awt.Font("Arial", 0, 12));
        taSupportMessage.setLineWrap(true);
        taSupportMessage.setWrapStyleWord(true);
        taSupportMessage.setMinimumSize(new java.awt.Dimension(0, 0));
        taSupportMessage.setPreferredSize(new java.awt.Dimension(0, 0));
        scrollPaneMessageBody1.setViewportView(taSupportMessage);

        MessageBodyTextAreaPanel1.add(scrollPaneMessageBody1);

        Separator36.setMaximumSize(new java.awt.Dimension(10, 10));
        Separator36.setMinimumSize(new java.awt.Dimension(10, 10));
        Separator36.setPreferredSize(new java.awt.Dimension(10, 10));
        MessageBodyTextAreaPanel1.add(Separator36);

        MessageBodyPanel1.add(MessageBodyTextAreaPanel1);

        MessageOKButtonPanel.add(MessageBodyPanel1);

        MessageBodyPanel2.setLayout(new javax.swing.BoxLayout(MessageBodyPanel2, javax.swing.BoxLayout.Y_AXIS));

        Separator38.setMaximumSize(new java.awt.Dimension(10, 5));
        Separator38.setMinimumSize(new java.awt.Dimension(10, 5));
        Separator38.setPreferredSize(new java.awt.Dimension(10, 5));
        MessageBodyPanel2.add(Separator38);

        MessageBodyLabelPanel2.setLayout(new javax.swing.BoxLayout(MessageBodyLabelPanel2, javax.swing.BoxLayout.X_AXIS));

        Separator39.setMaximumSize(new java.awt.Dimension(10, 10));
        Separator39.setMinimumSize(new java.awt.Dimension(10, 10));
        Separator39.setPreferredSize(new java.awt.Dimension(10, 10));
        MessageBodyLabelPanel2.add(Separator39);

        MessageBodyLabel2.setDisplayedMnemonic('r');
        MessageBodyLabel2.setFont(new java.awt.Font("Arial", 0, 12));
        MessageBodyLabel2.setLabelFor(taErrorMessage);
        MessageBodyLabel2.setText("Error Message:");
        MessageBodyLabel2.setMaximumSize(new java.awt.Dimension(32767, 15));
        MessageBodyLabel2.setPreferredSize(new java.awt.Dimension(1200, 15));
        MessageBodyLabelPanel2.add(MessageBodyLabel2);

        Separator40.setMaximumSize(new java.awt.Dimension(10, 10));
        Separator40.setMinimumSize(new java.awt.Dimension(10, 10));
        Separator40.setPreferredSize(new java.awt.Dimension(10, 10));
        MessageBodyLabelPanel2.add(Separator40);

        MessageBodyPanel2.add(MessageBodyLabelPanel2);

        MessageBodyTextAreaPanel2.setLayout(new javax.swing.BoxLayout(MessageBodyTextAreaPanel2, javax.swing.BoxLayout.X_AXIS));

        Separator41.setMaximumSize(new java.awt.Dimension(10, 10));
        Separator41.setMinimumSize(new java.awt.Dimension(10, 10));
        Separator41.setPreferredSize(new java.awt.Dimension(10, 10));
        MessageBodyTextAreaPanel2.add(Separator41);

        scrollPaneMessageBody2.setHorizontalScrollBarPolicy(javax.swing.JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
        scrollPaneMessageBody2.setVerticalScrollBarPolicy(javax.swing.JScrollPane.VERTICAL_SCROLLBAR_NEVER);
        scrollPaneMessageBody2.setMaximumSize(new java.awt.Dimension(32767, 34));
        scrollPaneMessageBody2.setMinimumSize(new java.awt.Dimension(23, 34));
        scrollPaneMessageBody2.setPreferredSize(new java.awt.Dimension(4, 34));
        taErrorMessage.setFont(new java.awt.Font("Arial", 0, 12));
        taErrorMessage.setLineWrap(true);
        taErrorMessage.setWrapStyleWord(true);
        taErrorMessage.setMinimumSize(new java.awt.Dimension(0, 0));
        taErrorMessage.setPreferredSize(new java.awt.Dimension(0, 0));
        scrollPaneMessageBody2.setViewportView(taErrorMessage);

        MessageBodyTextAreaPanel2.add(scrollPaneMessageBody2);

        Separator42.setMaximumSize(new java.awt.Dimension(10, 10));
        Separator42.setMinimumSize(new java.awt.Dimension(10, 10));
        Separator42.setPreferredSize(new java.awt.Dimension(10, 10));
        MessageBodyTextAreaPanel2.add(Separator42);

        MessageBodyPanel2.add(MessageBodyTextAreaPanel2);

        MessageOKButtonPanel.add(MessageBodyPanel2);

        add(MessageOKButtonPanel, java.awt.BorderLayout.CENTER);

    }//GEN-END:initComponents

    private void tfMessageSkipButtonMnemonicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfMessageSkipButtonMnemonicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfMessageSkipButtonMnemonicActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BorderSeparator;
    private javax.swing.JPanel BorderSeparator2;
    private javax.swing.JPanel CenterPanel;
    private javax.swing.JPanel CenterPanel1;
    private javax.swing.JPanel CenterTopPanel;
    private javax.swing.JPanel CenterTopPanel1;
    private javax.swing.JLabel FillerLabel2;
    private javax.swing.JLabel FillerLabel3;
    private javax.swing.JPanel LeftPanel;
    private javax.swing.JPanel LeftPanel1;
    private javax.swing.JPanel LeftTopPanel;
    private javax.swing.JPanel LeftTopPanel1;
    private javax.swing.JLabel MessageBodyLabel;
    private javax.swing.JLabel MessageBodyLabel2;
    private javax.swing.JPanel MessageBodyLabelPanel;
    private javax.swing.JPanel MessageBodyLabelPanel1;
    private javax.swing.JPanel MessageBodyLabelPanel2;
    private javax.swing.JPanel MessageBodyPanel;
    private javax.swing.JPanel MessageBodyPanel1;
    private javax.swing.JPanel MessageBodyPanel2;
    private javax.swing.JPanel MessageBodyTextAreaPanel;
    private javax.swing.JPanel MessageBodyTextAreaPanel1;
    private javax.swing.JPanel MessageBodyTextAreaPanel2;
    private javax.swing.JPanel MessageDataPanel;
    private javax.swing.JLabel MessageOKButtonLabel;
    private javax.swing.JPanel MessageOKButtonLabelPanel;
    private javax.swing.JPanel MessageOKButtonLabelPanel1;
    private javax.swing.JLabel MessageOKButtonMnemonicLabel;
    private javax.swing.JPanel MessageOKButtonPanel;
    private javax.swing.JLabel MessageSkipButtonLabel;
    private javax.swing.JLabel MessageSkipButtonMnemonicLabel;
    private javax.swing.JLabel MessageSupportLabel;
    private javax.swing.JLabel MessageTitleLabel;
    private javax.swing.JPanel MessageTitleLabelPanel;
    private javax.swing.JPanel MessageTitlePanel;
    private javax.swing.JPanel MessageTitleTextFieldPanel;
    private javax.swing.JPanel MessageTitleTextFieldPanel1;
    private javax.swing.JPanel MessageTitleTextFieldPanel2;
    private javax.swing.JPanel RightPanel;
    private javax.swing.JPanel RightPanel1;
    private javax.swing.JPanel RightTopPanel;
    private javax.swing.JPanel RightTopPanel1;
    private javax.swing.JLabel Separator10;
    private javax.swing.JLabel Separator11;
    private javax.swing.JLabel Separator12;
    private javax.swing.JLabel Separator13;
    private javax.swing.JLabel Separator14;
    private javax.swing.JLabel Separator15;
    private javax.swing.JLabel Separator16;
    private javax.swing.JLabel Separator17;
    private javax.swing.JLabel Separator18;
    private javax.swing.JLabel Separator19;
    private javax.swing.JLabel Separator2;
    private javax.swing.JLabel Separator20;
    private javax.swing.JLabel Separator21;
    private javax.swing.JLabel Separator22;
    private javax.swing.JLabel Separator23;
    private javax.swing.JLabel Separator24;
    private javax.swing.JLabel Separator25;
    private javax.swing.JLabel Separator26;
    private javax.swing.JLabel Separator27;
    private javax.swing.JLabel Separator28;
    private javax.swing.JLabel Separator29;
    private javax.swing.JLabel Separator3;
    private javax.swing.JLabel Separator30;
    private javax.swing.JLabel Separator31;
    private javax.swing.JLabel Separator32;
    private javax.swing.JLabel Separator33;
    private javax.swing.JLabel Separator34;
    private javax.swing.JLabel Separator35;
    private javax.swing.JLabel Separator36;
    private javax.swing.JLabel Separator37;
    private javax.swing.JLabel Separator38;
    private javax.swing.JLabel Separator39;
    private javax.swing.JLabel Separator4;
    private javax.swing.JLabel Separator40;
    private javax.swing.JLabel Separator41;
    private javax.swing.JLabel Separator42;
    private javax.swing.JLabel Separator5;
    private javax.swing.JLabel Separator6;
    private javax.swing.JLabel Separator7;
    private javax.swing.JLabel Separator8;
    private javax.swing.JLabel Separator9;
    private javax.swing.JScrollPane scrollPaneMessageBody;
    private javax.swing.JScrollPane scrollPaneMessageBody1;
    private javax.swing.JScrollPane scrollPaneMessageBody2;
    private javax.swing.JTextArea taErrorMessage;
    private javax.swing.JTextArea taMessageBody;
    private javax.swing.JTextArea taSupportMessage;
    private javax.swing.JTextField tfMessageOKButtonMnemonic;
    private javax.swing.JTextField tfMessageOKButtonText;
    private javax.swing.JTextField tfMessageSkipButtonMnemonic;
    private javax.swing.JTextField tfMessageSkipButtonText;
    private javax.swing.JTextField tfMessageTitle;
    // End of variables declaration//GEN-END:variables
    
}
