/*
 * OptinWizard.java
 *
 * Created on March 16, 2004, 11:25 PM
 */

package com.trinity.ea.design.optin.provider;
import com.trinity.ea.design.optin.provider.panels.OptinWizardMainPanel;
import com.trinity.ea.design.optin.EADesignerOptinPanel;
import com.trinity.ea.design.EADesigner;
import com.trinity.ea.design.rules.builder.DesignerRuleBuilder;
import java.io.IOException;
import javax.swing.JFrame;
import javax.swing.JDialog;
import java.awt.Image;
import java.awt.Dimension;
import java.awt.Color;
import java.awt.Insets;
import java.awt.BorderLayout;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.awt.event.WindowAdapter;
import javax.swing.JPanel;
import javax.swing.WindowConstants;

/**
 *
 * @author  aaronsc Trinity Software
 * Copyright ©2004 Trinity Software. All rights reserved.
 */
public class OptinWizard extends javax.swing.JFrame {
    private java.awt.Image TitleBarIcon = null;
    private OptinWizardMainPanel optinWiz;
    public OptinWizard()
    {
	new OptinWizard(0);
    }

    /** Creates new form OptinWizard */
    public OptinWizard(int wizPanel)
{
	  if(wizPanel==0)
	  {
		optinWiz = new OptinWizardMainPanel(0);
	  	optinWiz.setMasterControlPanel(this);
	  }
	  else if(wizPanel==1)
	  {
		optinWiz = new OptinWizardMainPanel(1);
	  	optinWiz.setMasterControlPanel(this);
	  }
        initComponents();
        try
        {
             setTitle(DesignerRuleBuilder.get("eaProductName") + " " + DesignerRuleBuilder.get("eaEditionName"));
        }
        catch(Exception e)
        {
                e.printStackTrace();
        }
	  try
	  {
	  	TitleBarIcon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/lgpl/eaicon16.png"));
		setIconImage(TitleBarIcon);
	  }
	  catch(Exception e)
	  {
		e.printStackTrace();
	  } 

         // Get the size of the screen
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        // Determine the new location of the window
        int w = getSize().width;
        int h = getSize().height;
        int x = (dim.width-w)/2;
        int y = (dim.height-h)/2;

        // Move the window
        setLocation(x, y);
        show();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        ContentPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("EvaluateAnywhere");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        ContentPanel.setLayout(new java.awt.BorderLayout());
        ContentPanel.setMinimumSize(new java.awt.Dimension(450, 350));
        ContentPanel.setPreferredSize(new java.awt.Dimension(450, 350));
	  ContentPanel.add(optinWiz, java.awt.BorderLayout.CENTER);
        getContentPane().add(ContentPanel, java.awt.BorderLayout.NORTH);

        pack();
    }//GEN-END:initComponents
/**/
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
	  setLaunchAdvancedDesigner();
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog
/**/   
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        setVisible(false);
        System.exit(0);
    }//GEN-LAST:event_exitForm
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ContentPanel;
    private javax.swing.ButtonGroup NewOrExistingProjectButtonGroup;
    // End of variables declaration//GEN-END:variables

  private JPanel TheWizardPanelReference = new JPanel();
  private void setWizardPanel(JPanel theWizardPanel)
  {
    try
    {
	  TheWizardPanelReference.setVisible(false);
        ContentPanel.remove(TheWizardPanelReference);        
        TheWizardPanelReference = theWizardPanel;
        ContentPanel.add(TheWizardPanelReference, java.awt.BorderLayout.CENTER);     
        TheWizardPanelReference.setVisible(true);

    }
    catch(Exception e)
    {
        e.printStackTrace();
    }
  }  

	public void setExit()
	{
		setVisible(false);
		dispose();
	}
	
	public void setFinishConfigurationAction()
	{
		((EADesigner)eadopRef.getParentComp()).show();
		eadopRef.setFinishConfigurationAction();
	      setVisible(false);
		dispose();
	}

	public void setLaunchAdvancedDesigner()
	{
		((EADesigner)eadopRef.getParentComp()).show();
	      setVisible(false);
		dispose();
	}

	EADesignerOptinPanel eadopRef = null;
	public void setMasterControlPanel(EADesignerOptinPanel eadop)
	{	
		eadopRef = eadop;
	}

	public void hideDesigner()
	{
	  try
	  {
	 	((EADesigner)eadopRef.getParentComp()).hide();
	  }
	  catch(Exception e)
	  {
		e.printStackTrace();
	  }
	}
}
