/*
 * StartWizardQuestionDialog.java
 *
 * Created on March 20, 2004, 12:32 AM
 */

package com.trinity.ea.design.optin.provider;
import javax.swing.*;
import java.awt.*;
import javax.swing.ImageIcon;

/** 
 *
 * @author  aaronsc Trinity Software
 * Copyright ©2003-2005 Trinity Software. All rights reserved.
 */
public class StartWizardQuestionDialog extends javax.swing.JDialog {
    int retCode = 2;

    private Icon theInfoIcon = new javax.swing.ImageIcon(getClass().getResource("/images/lgpl/filetypes.png"));

    /** Creates new form SaveDialog */
    public StartWizardQuestionDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        // Get the size of the screen
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();

        // Determine the new location of the window
        int w = getSize().width;
        int h = getSize().height;
        int x = (dim.width-w)/2;
        int y = (dim.height-h)/2;
        // Move the window
        setLocation(x, y);  
        setTitle("Restore default build location?");
        show();
    }
    
    public int getMethod()
    {
        return retCode;
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        NorthPanel = new javax.swing.JPanel();
        NorthLeftPanel = new javax.swing.JPanel();
        ImageLabel = new javax.swing.JLabel();
        NorthRightPanel = new javax.swing.JPanel();
        HeaderPanel = new javax.swing.JPanel();
        HeaderLabel = new javax.swing.JLabel();
        DescriptionPanel = new javax.swing.JPanel();
        taDescription = new javax.swing.JTextArea();
        SouthPanel = new javax.swing.JPanel();
        SouthLeftPanel = new javax.swing.JPanel();
        SouthRightPanel = new javax.swing.JPanel();
        CancelButton = new javax.swing.JButton();
        SaveButton = new javax.swing.JButton();

        setTitle("EvaluateAnywhere");
        setModal(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        NorthPanel.setLayout(new java.awt.BorderLayout());

        NorthPanel.setMaximumSize(new java.awt.Dimension(2147483647, 90));
        NorthPanel.setMinimumSize(new java.awt.Dimension(370, 90));
        NorthPanel.setPreferredSize(new java.awt.Dimension(370, 90));
        NorthLeftPanel.setLayout(new java.awt.BorderLayout(20, 0));

        NorthLeftPanel.setMinimumSize(new java.awt.Dimension(80, 50));
        NorthLeftPanel.setPreferredSize(new java.awt.Dimension(80, 50));
        ImageLabel.setBackground(new java.awt.Color(102, 102, 102));
        ImageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ImageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/lgpl/filetypes.png")));
        NorthLeftPanel.add(ImageLabel, java.awt.BorderLayout.CENTER);

        NorthPanel.add(NorthLeftPanel, java.awt.BorderLayout.WEST);

        NorthRightPanel.setLayout(new javax.swing.BoxLayout(NorthRightPanel, javax.swing.BoxLayout.Y_AXIS));

        NorthRightPanel.setMinimumSize(new java.awt.Dimension(300, 40));
        NorthRightPanel.setPreferredSize(new java.awt.Dimension(300, 40));
        HeaderPanel.setLayout(new java.awt.BorderLayout());

        HeaderPanel.setMinimumSize(new java.awt.Dimension(300, 20));
        HeaderPanel.setPreferredSize(new java.awt.Dimension(300, 20));
        HeaderLabel.setBackground(new java.awt.Color(102, 102, 102));
        HeaderLabel.setText("Start the Opt-In feature Configuration Wizard?");
        HeaderLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        HeaderLabel.setMaximumSize(new java.awt.Dimension(300, 20));
        HeaderLabel.setMinimumSize(new java.awt.Dimension(300, 20));
        HeaderLabel.setPreferredSize(new java.awt.Dimension(300, 20));
        HeaderPanel.add(HeaderLabel, java.awt.BorderLayout.CENTER);

        NorthRightPanel.add(HeaderPanel);

        DescriptionPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 15));

        DescriptionPanel.setMinimumSize(new java.awt.Dimension(285, 30));
        DescriptionPanel.setPreferredSize(new java.awt.Dimension(285, 50));
        taDescription.setBackground(new java.awt.Color(204, 204, 204));
        taDescription.setFont(new java.awt.Font("Dialog", 0, 10));
        taDescription.setLineWrap(true);
        taDescription.setText("EvaluateAnywhere has detected the Opt-In feature is not configured yet. Would you like to start the Configuration Wizard?");
        taDescription.setWrapStyleWord(true);
        taDescription.setMaximumSize(new java.awt.Dimension(320, 40));
        taDescription.setMinimumSize(new java.awt.Dimension(275, 40));
        taDescription.setPreferredSize(new java.awt.Dimension(320, 40));
        DescriptionPanel.add(taDescription);

        NorthRightPanel.add(DescriptionPanel);

        NorthPanel.add(NorthRightPanel, java.awt.BorderLayout.CENTER);

        getContentPane().add(NorthPanel, java.awt.BorderLayout.CENTER);

        SouthPanel.setLayout(new javax.swing.BoxLayout(SouthPanel, javax.swing.BoxLayout.X_AXIS));

        SouthLeftPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 10));

        SouthPanel.add(SouthLeftPanel);

        SouthRightPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 10, 10));

        CancelButton.setFont(new java.awt.Font("Arial", 0, 12));
        CancelButton.setMnemonic('N');
        CancelButton.setText("No");
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });

        SouthRightPanel.add(CancelButton);

        SaveButton.setFont(new java.awt.Font("Arial", 0, 12));
        SaveButton.setMnemonic('Y');
        SaveButton.setText("Yes");
        SaveButton.setMaximumSize(new java.awt.Dimension(73, 26));
        SaveButton.setMinimumSize(new java.awt.Dimension(73, 26));
        SaveButton.setPreferredSize(new java.awt.Dimension(73, 26));
        SaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtonActionPerformed(evt);
            }
        });

        SouthRightPanel.add(SaveButton);

        SouthPanel.add(SouthRightPanel);

        getContentPane().add(SouthPanel, java.awt.BorderLayout.SOUTH);

        pack();
    }//GEN-END:initComponents

    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButtonActionPerformed
        retCode=0;
        setVisible(false);
    }//GEN-LAST:event_SaveButtonActionPerformed

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        retCode=2;
        setVisible(false);        
    }//GEN-LAST:event_CancelButtonActionPerformed
    
    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelButton;
    private javax.swing.JPanel DescriptionPanel;
    private javax.swing.JLabel HeaderLabel;
    private javax.swing.JPanel HeaderPanel;
    private javax.swing.JLabel ImageLabel;
    private javax.swing.JPanel NorthLeftPanel;
    private javax.swing.JPanel NorthPanel;
    private javax.swing.JPanel NorthRightPanel;
    private javax.swing.JButton SaveButton;
    private javax.swing.JPanel SouthLeftPanel;
    private javax.swing.JPanel SouthPanel;
    private javax.swing.JPanel SouthRightPanel;
    private javax.swing.JTextArea taDescription;
    // End of variables declaration//GEN-END:variables
    
}
