/*
 * GeneralLookAndFeelPanel.java
 *
 * Created on June 13, 2004, 3:24 PM
 */

package com.trinity.ea.design.project.lookandfeel.general;
import com.trinity.ea.design.common.file.ProjectManager;
import com.trinity.ea.design.common.panel.EAPanel;
import com.trinity.ea.design.project.lookandfeel.preview.actions.StartVerticalButtonBarThemeAction;
import javax.swing.*;
import java.awt.*;

/**
 *
 * @author  aaronsc Trinity Software
 * Copyright ©2003-2004 Trinity Software. All rights reserved.
 */
public class GeneralLookAndFeelPanel extends EAPanel {
    
    /** Creates new form GeneralLookAndFeelPanel */
    public GeneralLookAndFeelPanel() {
        initComponents();
	  setProjectData();
	  //TODO: Add the Horizontal Button Bar Model - set Horizontal Button Bar Disabled until it is included with the product.
 	  HorizontalButtonBarModel.setEnabled(false);
    }
    
    public synchronized void getDataUpdate()
    {
	  try
          {
              if(rbOtherLandF.isSelected()==true)
              {    
                  if(tfLookAndFeelClassName.getText().equalsIgnoreCase("")==true)
                  {
                       ProjectManager.putTempNoFileWrite("LAndFPackage", "javax.swing.plaf.metal.MetalLookAndFeel");
                  }
                  else
                  {
                       ProjectManager.putTempNoFileWrite("LAndFPackage", tfLookAndFeelClassName.getText());
                  }
              }
              else
              {
                  ProjectManager.putTempNoFileWrite("LAndFPackage", "system");
              }
              if(VerticalButtonBarModel.isSelected()==true)
              {
                  ProjectManager.putTempNoFileWrite("project_gui_model", "0");
              }
              else 
              {
                  ProjectManager.putTempNoFileWrite("project_gui_model", "1");          
              }              
              
              ProjectManager.saveTempNow();
          }
          catch(Exception e)
          {
            e.printStackTrace();
          }
    }
    
    public synchronized void setProjectData()
    {
        try
        {
            if(ProjectManager.get("LAndFPackage")!=null)
            {
                if(ProjectManager.get("LAndFPackage").equalsIgnoreCase("system")==true)
                {
                    rbSystemDefault.setSelected(true);
                    rbOtherLandF.setSelected(false);
                    lLandFClassName.setEnabled(false);
                    tfLookAndFeelClassName.setEnabled(false);           
           
                }
                else
                {
                    rbSystemDefault.setSelected(false);
                    rbOtherLandF.setSelected(true);   
                    lLandFClassName.setEnabled(true);
                    tfLookAndFeelClassName.setEnabled(true);   
                    tfLookAndFeelClassName.setText(ProjectManager.get("LAndFPackage"));
                }
            }
            else
            {
                rbSystemDefault.setSelected(true);
                rbOtherLandF.setSelected(false);
                lLandFClassName.setEnabled(false);
                tfLookAndFeelClassName.setEnabled(false);                   
            }
            
            if(ProjectManager.get("project_gui_model")!=null)
            {
                if(ProjectManager.get("project_gui_model").equalsIgnoreCase("0")==true)
                {
                    VerticalButtonBarModel.setSelected(true);
                    HorizontalButtonBarModel.setSelected(false);           
                }
                else if(ProjectManager.get("project_gui_model").equalsIgnoreCase("1")==true)
                {
                    VerticalButtonBarModel.setSelected(false);
                    HorizontalButtonBarModel.setSelected(true);
                }
                else
                {
                    VerticalButtonBarModel.setSelected(true);
                    HorizontalButtonBarModel.setSelected(false);                    
                }
            }
            else
            {
                    VerticalButtonBarModel.setSelected(true);
                    HorizontalButtonBarModel.setSelected(false);                     
            }            
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        UIChoicesPanel = new javax.swing.JPanel();
        UIChoicesTopPanel = new javax.swing.JPanel();
        LeftUIFiller = new javax.swing.JLabel();
        UserInterfaceDescriptionLabel = new javax.swing.JLabel();
        UIChoicesTopPanel1 = new javax.swing.JPanel();
        LeftUIFiller1 = new javax.swing.JLabel();
        SwingUserInterfaceCheckbox = new javax.swing.JCheckBox();
        UIChoicesBottomPanel = new javax.swing.JPanel();
        GUILookAndFeelPanel = new javax.swing.JPanel();
        FillerPanel1 = new javax.swing.JPanel();
        LeftUIFiller5 = new javax.swing.JLabel();
        ImageDescription2 = new javax.swing.JLabel();
        ProjectStartupWindowGUIModelPanel1 = new javax.swing.JPanel();
        LeftUIFiller6 = new javax.swing.JLabel();
        rbSystemDefault = new javax.swing.JRadioButton();
        lFiller32 = new javax.swing.JLabel();
        rbOtherLandF = new javax.swing.JRadioButton();
        lFiller33 = new javax.swing.JLabel();
        lLandFClassName = new javax.swing.JLabel();
        tfLookAndFeelClassName = new javax.swing.JTextField();
        lFiller34 = new javax.swing.JLabel();
        ProjectStartupWindowGUIModelSouthFillerPanel1 = new javax.swing.JPanel();
        StartupWindowGUIModel = new javax.swing.JPanel();
        FillerPanel = new javax.swing.JPanel();
        LeftUIFiller3 = new javax.swing.JLabel();
        ImageDescription1 = new javax.swing.JLabel();
        ProjectStartupWindowGUIModelPanel = new javax.swing.JPanel();
        LeftUIFiller4 = new javax.swing.JLabel();
        VerticalButtonBarModel = new javax.swing.JRadioButton();
        lFiller30 = new javax.swing.JLabel();
        HorizontalButtonBarModel = new javax.swing.JRadioButton();
        lFiller31 = new javax.swing.JLabel();
        ProjectStartupWindowGUIModelSouthFillerPanel = new javax.swing.JPanel();
        PreviewPanel = new javax.swing.JPanel();
        PreviewPanelNorthFiller = new javax.swing.JPanel();
        lPreviewPanelFiller = new javax.swing.JLabel();
        ProjectLocationsCenterPanel4 = new javax.swing.JPanel();
        lFiller200 = new javax.swing.JLabel();
        PreviewButton = new javax.swing.JButton();
        lFiller201 = new javax.swing.JLabel();
        lFiller202 = new javax.swing.JLabel();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        setBackground(new java.awt.Color(140, 160, 210));
        UIChoicesPanel.setLayout(new javax.swing.BoxLayout(UIChoicesPanel, javax.swing.BoxLayout.Y_AXIS));

        UIChoicesPanel.setBackground(new java.awt.Color(140, 160, 210));
        UIChoicesPanel.setBorder(new javax.swing.border.TitledBorder(new javax.swing.border.EtchedBorder(new java.awt.Color(198, 226, 253), new java.awt.Color(96, 110, 145)), "User Interface Modes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12)));
        UIChoicesPanel.setMaximumSize(new java.awt.Dimension(32767, 75));
        UIChoicesPanel.setMinimumSize(new java.awt.Dimension(10, 50));
        UIChoicesPanel.setPreferredSize(new java.awt.Dimension(10, 60));
        UIChoicesTopPanel.setLayout(new javax.swing.BoxLayout(UIChoicesTopPanel, javax.swing.BoxLayout.X_AXIS));

        UIChoicesTopPanel.setBackground(new java.awt.Color(140, 160, 210));
        LeftUIFiller.setMaximumSize(new java.awt.Dimension(10, 10));
        LeftUIFiller.setMinimumSize(new java.awt.Dimension(10, 10));
        LeftUIFiller.setPreferredSize(new java.awt.Dimension(10, 10));
        UIChoicesTopPanel.add(LeftUIFiller);

        UserInterfaceDescriptionLabel.setFont(new java.awt.Font("Arial", 0, 12));
        UserInterfaceDescriptionLabel.setText("Support the following User Interface Modes:");
        UserInterfaceDescriptionLabel.setMaximumSize(new java.awt.Dimension(32767, 15));
        UIChoicesTopPanel.add(UserInterfaceDescriptionLabel);

        UIChoicesPanel.add(UIChoicesTopPanel);

        UIChoicesTopPanel1.setLayout(new javax.swing.BoxLayout(UIChoicesTopPanel1, javax.swing.BoxLayout.X_AXIS));

        UIChoicesTopPanel1.setBackground(new java.awt.Color(140, 160, 210));
        UIChoicesTopPanel1.setMaximumSize(new java.awt.Dimension(32767, 25));
        UIChoicesTopPanel1.setMinimumSize(new java.awt.Dimension(10, 25));
        UIChoicesTopPanel1.setPreferredSize(new java.awt.Dimension(1000, 25));
        LeftUIFiller1.setMaximumSize(new java.awt.Dimension(30, 10));
        LeftUIFiller1.setMinimumSize(new java.awt.Dimension(30, 10));
        LeftUIFiller1.setPreferredSize(new java.awt.Dimension(30, 10));
        UIChoicesTopPanel1.add(LeftUIFiller1);

        SwingUserInterfaceCheckbox.setBackground(new java.awt.Color(140, 160, 210));
        SwingUserInterfaceCheckbox.setFont(new java.awt.Font("Arial", 0, 12));
        SwingUserInterfaceCheckbox.setMnemonic('S');
        SwingUserInterfaceCheckbox.setSelected(true);
        SwingUserInterfaceCheckbox.setText("Swing");
        SwingUserInterfaceCheckbox.setEnabled(false);
        UIChoicesTopPanel1.add(SwingUserInterfaceCheckbox);

        UIChoicesPanel.add(UIChoicesTopPanel1);

        UIChoicesBottomPanel.setBackground(new java.awt.Color(140, 160, 210));
        UIChoicesBottomPanel.setMinimumSize(new java.awt.Dimension(5, 5));
        UIChoicesBottomPanel.setPreferredSize(new java.awt.Dimension(5, 5));
        UIChoicesPanel.add(UIChoicesBottomPanel);

        add(UIChoicesPanel);

        GUILookAndFeelPanel.setLayout(new javax.swing.BoxLayout(GUILookAndFeelPanel, javax.swing.BoxLayout.Y_AXIS));

        GUILookAndFeelPanel.setBackground(new java.awt.Color(140, 160, 210));
        GUILookAndFeelPanel.setBorder(new javax.swing.border.TitledBorder(new javax.swing.border.EtchedBorder(new java.awt.Color(198, 226, 253), new java.awt.Color(96, 110, 145)), "GUI (Graphical User Interface) Look and Feel", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12)));
        GUILookAndFeelPanel.setMaximumSize(new java.awt.Dimension(32767, 75));
        GUILookAndFeelPanel.setMinimumSize(new java.awt.Dimension(10, 50));
        GUILookAndFeelPanel.setPreferredSize(new java.awt.Dimension(10, 60));
        FillerPanel1.setLayout(new javax.swing.BoxLayout(FillerPanel1, javax.swing.BoxLayout.X_AXIS));

        FillerPanel1.setBackground(new java.awt.Color(140, 160, 210));
        LeftUIFiller5.setMaximumSize(new java.awt.Dimension(10, 10));
        LeftUIFiller5.setMinimumSize(new java.awt.Dimension(10, 10));
        LeftUIFiller5.setPreferredSize(new java.awt.Dimension(10, 10));
        FillerPanel1.add(LeftUIFiller5);

        ImageDescription2.setFont(new java.awt.Font("Arial", 0, 12));
        ImageDescription2.setMaximumSize(new java.awt.Dimension(32767, 15));
        FillerPanel1.add(ImageDescription2);

        GUILookAndFeelPanel.add(FillerPanel1);

        ProjectStartupWindowGUIModelPanel1.setLayout(new javax.swing.BoxLayout(ProjectStartupWindowGUIModelPanel1, javax.swing.BoxLayout.X_AXIS));

        ProjectStartupWindowGUIModelPanel1.setBackground(new java.awt.Color(140, 160, 210));
        ProjectStartupWindowGUIModelPanel1.setMaximumSize(new java.awt.Dimension(2147483647, 30));
        ProjectStartupWindowGUIModelPanel1.setMinimumSize(new java.awt.Dimension(600, 30));
        ProjectStartupWindowGUIModelPanel1.setPreferredSize(new java.awt.Dimension(800, 30));
        LeftUIFiller6.setMaximumSize(new java.awt.Dimension(30, 10));
        LeftUIFiller6.setMinimumSize(new java.awt.Dimension(30, 10));
        LeftUIFiller6.setPreferredSize(new java.awt.Dimension(30, 10));
        ProjectStartupWindowGUIModelPanel1.add(LeftUIFiller6);

        rbSystemDefault.setBackground(new java.awt.Color(140, 160, 210));
        rbSystemDefault.setFont(new java.awt.Font("Arial", 0, 12));
        rbSystemDefault.setMnemonic('y');
        rbSystemDefault.setSelected(true);
        rbSystemDefault.setLabel("System Default");
        rbSystemDefault.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbSystemDefaultActionPerformed(evt);
            }
        });

        ProjectStartupWindowGUIModelPanel1.add(rbSystemDefault);
        rbSystemDefault.getAccessibleContext().setAccessibleName("Operating System Default");

        lFiller32.setBackground(new java.awt.Color(140, 160, 210));
        lFiller32.setText("   ");
        lFiller32.setMaximumSize(new java.awt.Dimension(10, 15));
        lFiller32.setMinimumSize(new java.awt.Dimension(10, 16));
        lFiller32.setPreferredSize(new java.awt.Dimension(10, 16));
        ProjectStartupWindowGUIModelPanel1.add(lFiller32);

        rbOtherLandF.setBackground(new java.awt.Color(140, 160, 210));
        rbOtherLandF.setFont(new java.awt.Font("Arial", 0, 12));
        rbOtherLandF.setMnemonic('H');
        rbOtherLandF.setLabel("Other");
        rbOtherLandF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbOtherLandFActionPerformed(evt);
            }
        });

        ProjectStartupWindowGUIModelPanel1.add(rbOtherLandF);

        lFiller33.setBackground(new java.awt.Color(140, 160, 210));
        lFiller33.setText("   ");
        lFiller33.setMaximumSize(new java.awt.Dimension(10, 16));
        lFiller33.setMinimumSize(new java.awt.Dimension(10, 16));
        lFiller33.setPreferredSize(new java.awt.Dimension(10, 16));
        ProjectStartupWindowGUIModelPanel1.add(lFiller33);

        lLandFClassName.setBackground(new java.awt.Color(140, 160, 210));
        lLandFClassName.setFont(new java.awt.Font("Arial", 0, 12));
        lLandFClassName.setText("L&F Class name:");
        lLandFClassName.setMaximumSize(new java.awt.Dimension(110, 16));
        lLandFClassName.setMinimumSize(new java.awt.Dimension(110, 16));
        lLandFClassName.setPreferredSize(new java.awt.Dimension(110, 16));
        lLandFClassName.setEnabled(false);
        ProjectStartupWindowGUIModelPanel1.add(lLandFClassName);

        tfLookAndFeelClassName.setBackground(new java.awt.Color(204, 204, 204));
        tfLookAndFeelClassName.setMaximumSize(new java.awt.Dimension(2147483647, 20));
        tfLookAndFeelClassName.setMinimumSize(new java.awt.Dimension(6, 20));
        tfLookAndFeelClassName.setPreferredSize(new java.awt.Dimension(57, 20));
        tfLookAndFeelClassName.setEnabled(false);
        ProjectStartupWindowGUIModelPanel1.add(tfLookAndFeelClassName);

        lFiller34.setBackground(new java.awt.Color(140, 160, 210));
        lFiller34.setText("   ");
        lFiller34.setMaximumSize(new java.awt.Dimension(32767, 32767));
        lFiller34.setMinimumSize(new java.awt.Dimension(10, 16));
        lFiller34.setPreferredSize(new java.awt.Dimension(10, 16));
        ProjectStartupWindowGUIModelPanel1.add(lFiller34);

        GUILookAndFeelPanel.add(ProjectStartupWindowGUIModelPanel1);

        ProjectStartupWindowGUIModelSouthFillerPanel1.setBackground(new java.awt.Color(140, 160, 210));
        ProjectStartupWindowGUIModelSouthFillerPanel1.setMinimumSize(new java.awt.Dimension(5, 5));
        ProjectStartupWindowGUIModelSouthFillerPanel1.setPreferredSize(new java.awt.Dimension(5, 5));
        GUILookAndFeelPanel.add(ProjectStartupWindowGUIModelSouthFillerPanel1);

        add(GUILookAndFeelPanel);

        StartupWindowGUIModel.setLayout(new javax.swing.BoxLayout(StartupWindowGUIModel, javax.swing.BoxLayout.Y_AXIS));

        StartupWindowGUIModel.setBackground(new java.awt.Color(140, 160, 210));
        StartupWindowGUIModel.setBorder(new javax.swing.border.TitledBorder(new javax.swing.border.EtchedBorder(new java.awt.Color(198, 226, 253), new java.awt.Color(96, 110, 145)), "Startup Window GUI (Graphical User Interface) Model", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12)));
        StartupWindowGUIModel.setMaximumSize(new java.awt.Dimension(32767, 75));
        StartupWindowGUIModel.setMinimumSize(new java.awt.Dimension(10, 50));
        StartupWindowGUIModel.setPreferredSize(new java.awt.Dimension(10, 60));
        FillerPanel.setLayout(new javax.swing.BoxLayout(FillerPanel, javax.swing.BoxLayout.X_AXIS));

        FillerPanel.setBackground(new java.awt.Color(140, 160, 210));
        LeftUIFiller3.setMaximumSize(new java.awt.Dimension(10, 10));
        LeftUIFiller3.setMinimumSize(new java.awt.Dimension(10, 10));
        LeftUIFiller3.setPreferredSize(new java.awt.Dimension(10, 10));
        FillerPanel.add(LeftUIFiller3);

        ImageDescription1.setFont(new java.awt.Font("Arial", 0, 12));
        ImageDescription1.setMaximumSize(new java.awt.Dimension(32767, 15));
        FillerPanel.add(ImageDescription1);

        StartupWindowGUIModel.add(FillerPanel);

        ProjectStartupWindowGUIModelPanel.setLayout(new javax.swing.BoxLayout(ProjectStartupWindowGUIModelPanel, javax.swing.BoxLayout.X_AXIS));

        ProjectStartupWindowGUIModelPanel.setBackground(new java.awt.Color(140, 160, 210));
        ProjectStartupWindowGUIModelPanel.setMaximumSize(new java.awt.Dimension(2147483647, 30));
        ProjectStartupWindowGUIModelPanel.setMinimumSize(new java.awt.Dimension(600, 30));
        ProjectStartupWindowGUIModelPanel.setPreferredSize(new java.awt.Dimension(800, 30));
        LeftUIFiller4.setMaximumSize(new java.awt.Dimension(30, 10));
        LeftUIFiller4.setMinimumSize(new java.awt.Dimension(30, 10));
        LeftUIFiller4.setPreferredSize(new java.awt.Dimension(30, 10));
        ProjectStartupWindowGUIModelPanel.add(LeftUIFiller4);

        VerticalButtonBarModel.setBackground(new java.awt.Color(140, 160, 210));
        VerticalButtonBarModel.setFont(new java.awt.Font("Arial", 0, 12));
        VerticalButtonBarModel.setMnemonic('V');
        VerticalButtonBarModel.setSelected(true);
        VerticalButtonBarModel.setText("Vertical Button Bar Model");
        VerticalButtonBarModel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerticalButtonBarModelActionPerformed(evt);
            }
        });

        ProjectStartupWindowGUIModelPanel.add(VerticalButtonBarModel);

        lFiller30.setBackground(new java.awt.Color(140, 160, 210));
        lFiller30.setText("   ");
        lFiller30.setMaximumSize(new java.awt.Dimension(10, 15));
        lFiller30.setMinimumSize(new java.awt.Dimension(10, 16));
        lFiller30.setPreferredSize(new java.awt.Dimension(10, 16));
        ProjectStartupWindowGUIModelPanel.add(lFiller30);

        HorizontalButtonBarModel.setBackground(new java.awt.Color(140, 160, 210));
        HorizontalButtonBarModel.setFont(new java.awt.Font("Arial", 0, 12));
        HorizontalButtonBarModel.setMnemonic('H');
        HorizontalButtonBarModel.setText("Horizontal Button Bar Model");
        HorizontalButtonBarModel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HorizontalButtonBarModelActionPerformed(evt);
            }
        });

        ProjectStartupWindowGUIModelPanel.add(HorizontalButtonBarModel);

        lFiller31.setBackground(new java.awt.Color(140, 160, 210));
        lFiller31.setText("   ");
        lFiller31.setMaximumSize(new java.awt.Dimension(32767, 32767));
        lFiller31.setMinimumSize(new java.awt.Dimension(10, 16));
        lFiller31.setPreferredSize(new java.awt.Dimension(10, 16));
        ProjectStartupWindowGUIModelPanel.add(lFiller31);

        StartupWindowGUIModel.add(ProjectStartupWindowGUIModelPanel);

        ProjectStartupWindowGUIModelSouthFillerPanel.setBackground(new java.awt.Color(140, 160, 210));
        ProjectStartupWindowGUIModelSouthFillerPanel.setMinimumSize(new java.awt.Dimension(5, 5));
        ProjectStartupWindowGUIModelSouthFillerPanel.setPreferredSize(new java.awt.Dimension(5, 5));
        StartupWindowGUIModel.add(ProjectStartupWindowGUIModelSouthFillerPanel);

        add(StartupWindowGUIModel);
       PreviewPanel.setLayout(new javax.swing.BoxLayout(PreviewPanel, javax.swing.BoxLayout.Y_AXIS));

        PreviewPanel.setBackground(new java.awt.Color(140, 160, 210));
        PreviewPanel.setMaximumSize(new java.awt.Dimension(32767, 50));
        PreviewPanel.setMinimumSize(new java.awt.Dimension(10, 50));
        PreviewPanel.setPreferredSize(new java.awt.Dimension(10, 50));
        PreviewPanelNorthFiller.setLayout(new javax.swing.BoxLayout(PreviewPanelNorthFiller, javax.swing.BoxLayout.X_AXIS));

        PreviewPanelNorthFiller.setBackground(new java.awt.Color(140, 160, 210));
        lPreviewPanelFiller.setMaximumSize(new java.awt.Dimension(10, 10));
        lPreviewPanelFiller.setMinimumSize(new java.awt.Dimension(10, 10));
        lPreviewPanelFiller.setPreferredSize(new java.awt.Dimension(10, 10));
        PreviewPanelNorthFiller.add(lPreviewPanelFiller);

        PreviewPanel.add(PreviewPanelNorthFiller);

        ProjectLocationsCenterPanel4.setLayout(new javax.swing.BoxLayout(ProjectLocationsCenterPanel4, javax.swing.BoxLayout.X_AXIS));

        ProjectLocationsCenterPanel4.setBackground(new java.awt.Color(140, 160, 210));
        ProjectLocationsCenterPanel4.setMaximumSize(new java.awt.Dimension(2147483647, 30));
        ProjectLocationsCenterPanel4.setMinimumSize(new java.awt.Dimension(600, 30));
        ProjectLocationsCenterPanel4.setPreferredSize(new java.awt.Dimension(800, 30));
        lFiller200.setBackground(new java.awt.Color(140, 160, 210));
        lFiller200.setText("   ");
        lFiller200.setMaximumSize(new java.awt.Dimension(32767, 15));
        lFiller200.setMinimumSize(new java.awt.Dimension(15, 16));
        lFiller200.setPreferredSize(new java.awt.Dimension(15, 16));
        ProjectLocationsCenterPanel4.add(lFiller200);

        PreviewButton.setFont(new java.awt.Font("Arial", 0, 12));
        PreviewButton.setLabel("Preview");
        PreviewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PreviewButtonActionPerformed(evt);
            }
        });

        ProjectLocationsCenterPanel4.add(PreviewButton);

        lFiller201.setBackground(new java.awt.Color(140, 160, 210));
        lFiller201.setText("   ");
        lFiller201.setMaximumSize(new java.awt.Dimension(15, 15));
        lFiller201.setMinimumSize(new java.awt.Dimension(15, 16));
        lFiller201.setPreferredSize(new java.awt.Dimension(15, 16));
        ProjectLocationsCenterPanel4.add(lFiller201);

        lFiller202.setBackground(new java.awt.Color(140, 160, 210));
        lFiller202.setText("   ");
        lFiller202.setMaximumSize(new java.awt.Dimension(15, 15));
        lFiller202.setMinimumSize(new java.awt.Dimension(15, 16));
        lFiller202.setPreferredSize(new java.awt.Dimension(15, 16));
        ProjectLocationsCenterPanel4.add(lFiller202);

        PreviewPanel.add(ProjectLocationsCenterPanel4);

        add(PreviewPanel);

    }//GEN-END:initComponents

    private void HorizontalButtonBarModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HorizontalButtonBarModelActionPerformed

	 if(HorizontalButtonBarModel.isSelected()==true)
        {
            VerticalButtonBarModel.setSelected(false);
        }
        else
        {
            VerticalButtonBarModel.setSelected(true);            
        }
    }//GEN-LAST:event_HorizontalButtonBarModelActionPerformed

    private void VerticalButtonBarModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerticalButtonBarModelActionPerformed
      if(HorizontalButtonBarModel.isEnabled()==false)
	{
		VerticalButtonBarModel.setSelected(true);
	}
	else
	{
        if(VerticalButtonBarModel.isSelected()==true)
        {
            HorizontalButtonBarModel.setSelected(false);
        }
        else
        {
            HorizontalButtonBarModel.setSelected(true);            
        }
	}
    }//GEN-LAST:event_VerticalButtonBarModelActionPerformed

    private void rbOtherLandFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbOtherLandFActionPerformed
        if(rbOtherLandF.isSelected()==true)
        {
            rbSystemDefault.setSelected(false);
            lLandFClassName.setEnabled(true);
            tfLookAndFeelClassName.setEnabled(true);
             if(ProjectManager.get("LAndFPackage")!=null)
            {
                if(ProjectManager.get("LAndFPackage").equalsIgnoreCase("")==true)
                {
                     tfLookAndFeelClassName.setText("javax.swing.plaf.metal.MetalLookAndFeel");          
           
                }
                else if(ProjectManager.get("LAndFPackage").equalsIgnoreCase("system")==true)
                {
                    tfLookAndFeelClassName.setText("javax.swing.plaf.metal.MetalLookAndFeel");
                }
            }
            else
            {
                 tfLookAndFeelClassName.setText("javax.swing.plaf.metal.MetalLookAndFeel");                 
            }           
        }
        else
        {
            rbSystemDefault.setSelected(true);  
            lLandFClassName.setEnabled(false);  
            tfLookAndFeelClassName.setEnabled(false);           
        }
    }//GEN-LAST:event_rbOtherLandFActionPerformed

    private void rbSystemDefaultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbSystemDefaultActionPerformed
        if(rbSystemDefault.isSelected()==true)
        {
            rbOtherLandF.setSelected(false);
            lLandFClassName.setEnabled(false);
            tfLookAndFeelClassName.setEnabled(false);           
        }
        else
        {
            rbOtherLandF.setSelected(true);   
            lLandFClassName.setEnabled(true);
            tfLookAndFeelClassName.setEnabled(true);            
        }
    }//GEN-LAST:event_rbSystemDefaultActionPerformed

    private void PreviewButtonActionPerformed(java.awt.event.ActionEvent evt) 
    {
	try
	{
		((EAPanel)getParentComponent()).getDataUpdate();
		new StartVerticalButtonBarThemeAction();	
	}
	catch(Exception e)
	{
		e.printStackTrace();
	}
    }    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel FillerPanel;
    private javax.swing.JPanel FillerPanel1;
    private javax.swing.JPanel GUILookAndFeelPanel;
    private javax.swing.JRadioButton HorizontalButtonBarModel;
    private javax.swing.JLabel ImageDescription1;
    private javax.swing.JLabel ImageDescription2;
    private javax.swing.JLabel LeftUIFiller;
    private javax.swing.JLabel LeftUIFiller1;
    private javax.swing.JLabel LeftUIFiller3;
    private javax.swing.JLabel LeftUIFiller4;
    private javax.swing.JLabel LeftUIFiller5;
    private javax.swing.JLabel LeftUIFiller6;
    private javax.swing.JPanel ProjectStartupWindowGUIModelPanel;
    private javax.swing.JPanel ProjectStartupWindowGUIModelPanel1;
    private javax.swing.JPanel ProjectStartupWindowGUIModelSouthFillerPanel;
    private javax.swing.JPanel ProjectStartupWindowGUIModelSouthFillerPanel1;
    private javax.swing.JPanel StartupWindowGUIModel;
    private javax.swing.JCheckBox SwingUserInterfaceCheckbox;
    private javax.swing.JPanel UIChoicesBottomPanel;
    private javax.swing.JPanel UIChoicesPanel;
    private javax.swing.JPanel UIChoicesTopPanel;
    private javax.swing.JPanel UIChoicesTopPanel1;
    private javax.swing.JLabel UserInterfaceDescriptionLabel;
    private javax.swing.JRadioButton VerticalButtonBarModel;
    private javax.swing.JLabel lFiller30;
    private javax.swing.JLabel lFiller31;
    private javax.swing.JLabel lFiller32;
    private javax.swing.JLabel lFiller33;
    private javax.swing.JLabel lFiller34;
    private javax.swing.JLabel lLandFClassName;
    private javax.swing.JRadioButton rbOtherLandF;
    private javax.swing.JRadioButton rbSystemDefault;
    private javax.swing.JTextField tfLookAndFeelClassName;
    private javax.swing.JButton PreviewButton;
    private javax.swing.JPanel PreviewPanel;
    private javax.swing.JPanel PreviewPanelNorthFiller;
    private javax.swing.JPanel ProjectLocationsCenterPanel4;
    private javax.swing.JLabel lFiller200;
    private javax.swing.JLabel lFiller201;
    private javax.swing.JLabel lFiller202;
    private javax.swing.JLabel lPreviewPanelFiller;
    // End of variables declaration//GEN-END:variables
    
}
