/*
 * RegistrationUIPanel.java
 *
 * Created on December 13, 2003, 1:17 AM
 */

package com.trinity.ea.design.payments.ui;
import com.trinity.ea.design.common.panel.EAPanel;
import javax.swing.*;
import java.awt.*;
import com.trinity.ea.design.common.sidebar.SBTab;
import com.trinity.ea.design.project.EADesignerProjectPanel;
import com.trinity.ea.design.common.sidebar.SBSpacer;
import com.trinity.ea.design.rules.builder.DesignerRuleBuilder;
import java.awt.Font;
import java.util.HashMap;
import java.util.Collections;
import java.util.Map;
import java.util.ArrayList;
import com.trinity.ea.design.common.borderline.ContentAreaHeaderPanel;

/**
 *
 * @author  aaronsc Trinity Software
 * Copyright ©2003-2004 Trinity Software. All rights reserved.
 */
public class PaymentsUIPanel extends EAPanel {
Map sbMap = Collections.synchronizedMap(new HashMap());    
    /** Creates new form EADesignerProjectPanel */
    public PaymentsUIPanel() {
        initComponents();
	  initSidebar();
        setSelectedMenuItem(lConfigurationMenuItem);        
    }

   private EAPanel TheContentPanelReference = new EAPanel();
   private void setContentPanel(EAPanel theContentPanel)
  {
    try
    {
	 getDataUpdate();
       TheContentPanelReference.setVisible(false);
       RegistrationSelectionContentPanel.remove(TheContentPanelReference);        
       TheContentPanelReference = theContentPanel;
       RegistrationSelectionContentPanel.add(TheContentPanelReference);     
       TheContentPanelReference.setVisible(true);

    }
    catch(Exception e)
    {
        System.out.println(e);
    }
  }     

  public void getDataUpdate()
  {
	try
	{
		TheContentPanelReference.getDataUpdate();
	}
	catch(Exception e)
	{
		e.printStackTrace();
	}
  }   
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        RegistrationContentTopPanel = new javax.swing.JPanel();
        RegistrationCentralContentPanel = new javax.swing.JPanel();
        RegistrationContentPanel = new javax.swing.JPanel();
        RegistrationContentPanelItem3 = new javax.swing.JPanel();
        RegistrationSettingsPanelItem2 = new javax.swing.JPanel();
        RegistrationEnabledPanel1 = new javax.swing.JPanel();
        cbRegistrationEnabled = new javax.swing.JCheckBox();
        RegistrationPanelMainContainer1 = new javax.swing.JPanel();
        btnRegistrationFormPreview = new javax.swing.JButton();
        RegistrationSettingsPanelItem8 = new javax.swing.JPanel();
        RegistrationContentPanelItem4 = new javax.swing.JPanel();
        RegistrationSettingsPanelItem1 = new javax.swing.JPanel();
        RegistrationTitlePanel = new javax.swing.JPanel();
        lEvaluationUnlockCode = new javax.swing.JLabel();
	  RegistrationMenuPanelBottomPanel = new javax.swing.JPanel();
        tfEvaluationUnlockCode = new javax.swing.JTextField();
        RegistrationTitleRightPanel = new javax.swing.JPanel();
        btnGenerateEvaluationUnlockCode = new javax.swing.JButton();
        MaxRegistrationAttemptsSettingsPanel = new javax.swing.JPanel();
        MaxRegistrationAttemptsLeftContentPanel = new javax.swing.JPanel();
        lMaxRegistrationAttempts = new javax.swing.JLabel();
        tfMaxRegistrationAttempts = new javax.swing.JTextField();
        MaxRegistrationAttemptsRightFillerPanel = new javax.swing.JPanel();
        RegistrationCentralContentLeftMarginPanel = new javax.swing.JPanel();
        RegistrationCentralContentRightMarginPanel = new javax.swing.JPanel();
        RegistrationContentBottomPanel = new javax.swing.JPanel();
        RegistrationMenuPanel = new javax.swing.JPanel();
        RegistrationMenuButtonPanel = new javax.swing.JPanel();
 	  lConfigurationMenuItem = new SBTab("Configuration",sbTabWidth, sbTabHeight, sbTabLeftMargin, theCurrentMenuColor, theTextMenuColor, arrowIcon, iconTextGap, sbTabTopBorderColor, sbTabBottomBorderColor, sbTabRightInnerBorderColor, sbTabRightOuterBorderColor, sbTabIsOpaque);
        lRegistrationCodeUIMenuItem = new SBTab("Registration Code UI",sbTabWidth, sbTabHeight, sbTabLeftMargin, theCurrentMenuColor, theTextMenuColor, arrowIcon, iconTextGap, sbTabTopBorderColor, sbTabBottomBorderColor, sbTabRightInnerBorderColor, sbTabRightOuterBorderColor, sbTabIsOpaque);
        lRegistrationCodeSuccessUIMenuItem = new SBTab("Registration Code Success UI",sbTabWidth, sbTabHeight, sbTabLeftMargin, theCurrentMenuColor, theTextMenuColor, arrowIcon, iconTextGap, sbTabTopBorderColor, sbTabBottomBorderColor, sbTabRightInnerBorderColor, sbTabRightOuterBorderColor, sbTabIsOpaque);
        lRegistrationCodeFailedUIMenuItem = new SBTab("Registration Code Failed UI",sbTabWidth, sbTabHeight, sbTabLeftMargin, theCurrentMenuColor, theTextMenuColor, arrowIcon, iconTextGap, sbTabTopBorderColor, sbTabBottomBorderColor, sbTabRightInnerBorderColor, sbTabRightOuterBorderColor, sbTabIsOpaque);
        RegistrationMenuButtonPanelTop = new SBTab(null,sbTabWidth, sbTabMenuTopSpaceFiller, sbTabLeftMargin, theCurrentMenuColor, theTextMenuColor, null, iconTextGap, theCurrentMenuColor, sbTabBottomBorderColor, sbTabRightInnerBorderColor, sbTabRightOuterBorderColor, sbTabIsOpaque);
        RegistrationMenuButtonPanelBottom = new SBSpacer(theCurrentMenuColor,sbTabTopBorderColor,theCurrentMenuColor,sbTabRightInnerBorderColor,sbTabRightOuterBorderColor,sbTabIsOpaque);
        RegistrationMenuLeftSpaceFiller = new javax.swing.JPanel();
        RegistrationSelectionContentPanel = new javax.swing.JPanel();
RegistrationMenuContentPanel = new javax.swing.JPanel();
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        setBackground(new java.awt.Color(100, 120, 170));
        RegistrationContentTopPanel.setLayout(new java.awt.BorderLayout());

        RegistrationContentTopPanel.setBackground(new java.awt.Color(100, 120, 170));
        RegistrationContentTopPanel.setMaximumSize(new java.awt.Dimension(2147483647, 150));
        RegistrationContentTopPanel.setPreferredSize(new java.awt.Dimension(620, 150));
        RegistrationCentralContentPanel.setLayout(new java.awt.BorderLayout());

        RegistrationMenuContentPanel.setBackground(new java.awt.Color(100, 120, 170));
        RegistrationMenuContentPanel.setMaximumSize(new java.awt.Dimension(2147483647, 150));
        RegistrationMenuContentPanel.setPreferredSize(new java.awt.Dimension(sbTabWidth, 3000));

        RegistrationCentralContentPanel.setBackground(new java.awt.Color(100, 120, 170));
        RegistrationCentralContentPanel.setMaximumSize(new java.awt.Dimension(2147483647, 110));
        RegistrationCentralContentPanel.setPreferredSize(new java.awt.Dimension(620, 115));
        RegistrationContentPanel.setLayout(new java.awt.BorderLayout());

        RegistrationContentPanel.setBackground(new java.awt.Color(100, 120, 170));
        RegistrationContentPanel.setMaximumSize(new java.awt.Dimension(2147483647, 115));
        RegistrationContentPanel.setMinimumSize(new java.awt.Dimension(448, 0));
        RegistrationContentPanel.setPreferredSize(new java.awt.Dimension(600, 115));
        RegistrationContentPanelItem3.setLayout(new javax.swing.BoxLayout(RegistrationContentPanelItem3, javax.swing.BoxLayout.Y_AXIS));

        RegistrationContentPanelItem3.setBackground(new java.awt.Color(100, 120, 170));
        RegistrationContentPanelItem3.setBorder(new javax.swing.border.TitledBorder(new javax.swing.border.EtchedBorder(new java.awt.Color(140, 171, 240), new java.awt.Color(27, 44, 76)), "Registration Code", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 12)));
        RegistrationSettingsPanelItem2.setLayout(new java.awt.BorderLayout());

        RegistrationSettingsPanelItem2.setBackground(new java.awt.Color(100, 120, 170));
        RegistrationEnabledPanel1.setLayout(new java.awt.BorderLayout(15, 5));

        RegistrationEnabledPanel1.setBackground(new java.awt.Color(100, 120, 170));
        RegistrationEnabledPanel1.setMaximumSize(new java.awt.Dimension(100, 2147483647));
        cbRegistrationEnabled.setBackground(new java.awt.Color(100, 120, 170));
        cbRegistrationEnabled.setFont(new java.awt.Font("Arial", 0, 12));
        cbRegistrationEnabled.setSelected(true);
        cbRegistrationEnabled.setText("Enable Registration Code Support");
        RegistrationEnabledPanel1.add(cbRegistrationEnabled, java.awt.BorderLayout.CENTER);

        RegistrationSettingsPanelItem2.add(RegistrationEnabledPanel1, java.awt.BorderLayout.WEST);

        RegistrationPanelMainContainer1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 15, 0));

        RegistrationPanelMainContainer1.setBackground(new java.awt.Color(100, 120, 170));
        btnRegistrationFormPreview.setFont(new java.awt.Font("Arial", 0, 12));
        btnRegistrationFormPreview.setText("Preview");
        RegistrationPanelMainContainer1.add(btnRegistrationFormPreview);

        RegistrationSettingsPanelItem2.add(RegistrationPanelMainContainer1, java.awt.BorderLayout.CENTER);

        RegistrationContentPanelItem3.add(RegistrationSettingsPanelItem2);

        RegistrationSettingsPanelItem8.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        RegistrationSettingsPanelItem8.setBackground(new java.awt.Color(100, 120, 170));
        RegistrationContentPanelItem3.add(RegistrationSettingsPanelItem8);

        RegistrationContentPanel.add(RegistrationContentPanelItem3, java.awt.BorderLayout.NORTH);

        RegistrationContentPanelItem4.setLayout(new javax.swing.BoxLayout(RegistrationContentPanelItem4, javax.swing.BoxLayout.Y_AXIS));

        RegistrationContentPanelItem4.setBackground(new java.awt.Color(100, 120, 170));
        RegistrationContentPanelItem4.setBorder(new javax.swing.border.TitledBorder(new javax.swing.border.EtchedBorder(new java.awt.Color(140, 171, 240), new java.awt.Color(27, 44, 76)), "Configuration", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 12)));
        RegistrationContentPanelItem4.setMaximumSize(new java.awt.Dimension(1400, 50));
        RegistrationContentPanelItem4.setMinimumSize(new java.awt.Dimension(60, 50));
        RegistrationContentPanelItem4.setPreferredSize(new java.awt.Dimension(600, 50));
        RegistrationSettingsPanelItem1.setLayout(new java.awt.BorderLayout());

        RegistrationSettingsPanelItem1.setBackground(new java.awt.Color(100, 120, 170));
        RegistrationSettingsPanelItem1.setMaximumSize(new java.awt.Dimension(32767, 33));
        RegistrationTitlePanel.setBackground(new java.awt.Color(100, 120, 170));
        RegistrationTitlePanel.setMaximumSize(new java.awt.Dimension(100, 2147483647));
        lEvaluationUnlockCode.setBackground(new java.awt.Color(100, 120, 170));
        lEvaluationUnlockCode.setFont(new java.awt.Font("Arial", 0, 12));
        lEvaluationUnlockCode.setText("Software Evaluation Unlock Code:");
        RegistrationTitlePanel.add(lEvaluationUnlockCode);

        tfEvaluationUnlockCode.setPreferredSize(new java.awt.Dimension(220, 19));
        RegistrationTitlePanel.add(tfEvaluationUnlockCode);

        RegistrationSettingsPanelItem1.add(RegistrationTitlePanel, java.awt.BorderLayout.WEST);

        RegistrationTitleRightPanel.setLayout(new javax.swing.BoxLayout(RegistrationTitleRightPanel, javax.swing.BoxLayout.Y_AXIS));

        RegistrationTitleRightPanel.setBackground(new java.awt.Color(100, 120, 170));
        btnGenerateEvaluationUnlockCode.setText("Generate");
        RegistrationTitleRightPanel.add(btnGenerateEvaluationUnlockCode);

        RegistrationSettingsPanelItem1.add(RegistrationTitleRightPanel, java.awt.BorderLayout.CENTER);

        RegistrationContentPanelItem4.add(RegistrationSettingsPanelItem1);

        MaxRegistrationAttemptsSettingsPanel.setLayout(new java.awt.BorderLayout());

        MaxRegistrationAttemptsSettingsPanel.setBackground(new java.awt.Color(100, 120, 170));
        MaxRegistrationAttemptsSettingsPanel.setMaximumSize(new java.awt.Dimension(32767, 33));
        MaxRegistrationAttemptsLeftContentPanel.setBackground(new java.awt.Color(100, 120, 170));
        MaxRegistrationAttemptsLeftContentPanel.setMaximumSize(new java.awt.Dimension(100, 2147483647));
        lMaxRegistrationAttempts.setBackground(new java.awt.Color(100, 120, 170));
        lMaxRegistrationAttempts.setFont(new java.awt.Font("Arial", 0, 12));
        lMaxRegistrationAttempts.setText("Maximum Registration Attempts to Lockout:");
        MaxRegistrationAttemptsLeftContentPanel.add(lMaxRegistrationAttempts);

        tfMaxRegistrationAttempts.setPreferredSize(new java.awt.Dimension(220, 19));
        MaxRegistrationAttemptsLeftContentPanel.add(tfMaxRegistrationAttempts);

        MaxRegistrationAttemptsSettingsPanel.add(MaxRegistrationAttemptsLeftContentPanel, java.awt.BorderLayout.WEST);

        MaxRegistrationAttemptsRightFillerPanel.setLayout(new javax.swing.BoxLayout(MaxRegistrationAttemptsRightFillerPanel, javax.swing.BoxLayout.Y_AXIS));

        MaxRegistrationAttemptsRightFillerPanel.setBackground(new java.awt.Color(100, 120, 170));
        MaxRegistrationAttemptsSettingsPanel.add(MaxRegistrationAttemptsRightFillerPanel, java.awt.BorderLayout.CENTER);

        RegistrationContentPanelItem4.add(MaxRegistrationAttemptsSettingsPanel);

        RegistrationContentPanel.add(RegistrationContentPanelItem4, java.awt.BorderLayout.CENTER);

        RegistrationCentralContentPanel.add(RegistrationContentPanel, java.awt.BorderLayout.CENTER);

        RegistrationCentralContentLeftMarginPanel.setBackground(new java.awt.Color(100, 120, 170));
        RegistrationCentralContentPanel.add(RegistrationCentralContentLeftMarginPanel, java.awt.BorderLayout.WEST);

        RegistrationCentralContentRightMarginPanel.setBackground(new java.awt.Color(100, 120, 170));
        RegistrationCentralContentPanel.add(RegistrationCentralContentRightMarginPanel, java.awt.BorderLayout.EAST);

        RegistrationContentTopPanel.add(RegistrationCentralContentPanel, java.awt.BorderLayout.CENTER);

        add(RegistrationContentTopPanel);

        RegistrationContentBottomPanel.setLayout(new java.awt.BorderLayout());

        RegistrationContentBottomPanel.setBackground(new java.awt.Color(100, 120, 170));
        RegistrationContentBottomPanel.setMinimumSize(new java.awt.Dimension(180, 10));
        RegistrationContentBottomPanel.setPreferredSize(new java.awt.Dimension(180, 10));
        RegistrationMenuPanel.setLayout(new java.awt.BorderLayout());

        RegistrationMenuPanel.setBackground(new java.awt.Color(100, 120, 170));
        RegistrationMenuPanel.setForeground(new java.awt.Color(255, 255, 255));
        RegistrationMenuPanel.setMaximumSize(new java.awt.Dimension(sbTabWidth, 32767));
        RegistrationMenuPanel.setMinimumSize(new java.awt.Dimension(sbTabWidth, 10));
        RegistrationMenuPanel.setPreferredSize(new java.awt.Dimension(sbTabWidth, 10));
        RegistrationMenuButtonPanel.setLayout(new javax.swing.BoxLayout(RegistrationMenuButtonPanel, javax.swing.BoxLayout.Y_AXIS));

        RegistrationMenuButtonPanel.setBackground(new java.awt.Color(100, 120, 170));
        RegistrationMenuButtonPanel.setForeground(new java.awt.Color(255, 255, 255));
        RegistrationMenuButtonPanel.setMaximumSize(new java.awt.Dimension(sbTabWidth, sbTabGroupHeight));
        RegistrationMenuButtonPanel.setMinimumSize(new java.awt.Dimension(sbTabWidth, sbTabGroupHeight));
        RegistrationMenuButtonPanel.setPreferredSize(new java.awt.Dimension(sbTabWidth, sbTabGroupHeight));

        RegistrationMenuPanelBottomPanel.setLayout(new java.awt.BorderLayout());

        RegistrationMenuPanelBottomPanel.setBackground(new java.awt.Color(39, 63, 109));
        RegistrationMenuPanelBottomPanel.setForeground(new java.awt.Color(255, 255, 255));
        RegistrationMenuPanelBottomPanel.setMaximumSize(new java.awt.Dimension(sbTabWidth, 100));
        RegistrationMenuPanelBottomPanel.setMinimumSize(new java.awt.Dimension(sbTabWidth, 100));
        RegistrationMenuPanelBottomPanel.setPreferredSize(new java.awt.Dimension(sbTabWidth, 100));

	  lConfigurationMenuItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lConfigurationMenuItemMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lConfigurationMenuItemMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lConfigurationMenuItemMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lConfigurationMenuItemMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lConfigurationMenuItemMouseReleased(evt);
            }
        });

        RegistrationMenuButtonPanel.add(lConfigurationMenuItem);


        lRegistrationCodeUIMenuItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lRegistrationCodeUIMenuItemMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lRegistrationCodeUIMenuItemMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lRegistrationCodeUIMenuItemMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lRegistrationCodeUIMenuItemMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lRegistrationCodeUIMenuItemMouseReleased(evt);
            }
        });

        RegistrationMenuButtonPanel.add(lRegistrationCodeUIMenuItem);

        lRegistrationCodeSuccessUIMenuItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lRegistrationCodeSuccessUIMenuItemMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lRegistrationCodeSuccessUIMenuItemMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lRegistrationCodeSuccessUIMenuItemMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lRegistrationCodeSuccessUIMenuItemMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lRegistrationCodeSuccessUIMenuItemMouseReleased(evt);
            }
        });

        RegistrationMenuButtonPanel.add(lRegistrationCodeSuccessUIMenuItem);

        lRegistrationCodeFailedUIMenuItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lRegistrationCodeFailedUIMenuItemMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lRegistrationCodeFailedUIMenuItemMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lRegistrationCodeFailedUIMenuItemMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lRegistrationCodeFailedUIMenuItemMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lRegistrationCodeFailedUIMenuItemMouseReleased(evt);
            }
        });

        RegistrationMenuButtonPanel.add(lRegistrationCodeFailedUIMenuItem);

/**********************/
        RegistrationMenuPanelBottomPanel.add(RegistrationMenuButtonPanel, java.awt.BorderLayout.NORTH);
        RegistrationMenuPanelBottomPanel.add(RegistrationMenuButtonPanelBottom, java.awt.BorderLayout.CENTER);
        RegistrationMenuPanel.add(RegistrationMenuPanelBottomPanel, java.awt.BorderLayout.CENTER);
        RegistrationMenuPanel.add(RegistrationMenuButtonPanelTop, java.awt.BorderLayout.NORTH);
        RegistrationMenuButtonPanelBottom.setBackground(new java.awt.Color(100, 120, 170));
        RegistrationMenuButtonPanelBottom.setForeground(new java.awt.Color(255, 255, 255));
        RegistrationMenuLeftSpaceFiller.setBackground(new java.awt.Color(100, 120, 170));
        RegistrationMenuLeftSpaceFiller.setMinimumSize(new java.awt.Dimension(1, 10));
        RegistrationMenuLeftSpaceFiller.setPreferredSize(new java.awt.Dimension(1, 10));
        RegistrationMenuPanel.add(RegistrationMenuLeftSpaceFiller, java.awt.BorderLayout.WEST);
        RegistrationContentBottomPanel.add(RegistrationMenuPanel, java.awt.BorderLayout.WEST);
/**********************/
        RegistrationSelectionContentPanel.setLayout(new java.awt.BorderLayout());

        RegistrationSelectionContentPanel.setBackground(new java.awt.Color(140, 160, 210));
        RegistrationSelectionContentPanel.setForeground(new java.awt.Color(255, 255, 255));
        RegistrationContentBottomPanel.add(RegistrationSelectionContentPanel, java.awt.BorderLayout.CENTER);

        //add(RegistrationContentBottomPanel);
// add header here
	  contentPanel = new JPanel();
        contentPanel.setLayout(new java.awt.BorderLayout());
        contentPanel.add(RegistrationMenuPanel, java.awt.BorderLayout.WEST);
        contentPanel.add(RegistrationContentBottomPanel, java.awt.BorderLayout.CENTER);
	  contentProjectPanel = new ContentAreaHeaderPanel(contentPanel, sbTabWidth, theCurrentMenuColor, sbTabRightInnerBorderColor,sbTabRightOuterBorderColor,theSelectedMenuColor);
	  add(contentProjectPanel, java.awt.BorderLayout.CENTER);
    }//GEN-END:initComponents

    private void lConfigurationMenuItemMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lConfigurationMenuItemMouseReleased
	 setMouseReleasedMenuLabel(lConfigurationMenuItem);
    }//GEN-LAST:event_lConfigurationMenuItemMouseReleased

    private void lRegistrationCodeFailedUIMenuItemMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lRegistrationCodeFailedUIMenuItemMouseReleased
	 setMouseReleasedMenuLabel(lRegistrationCodeFailedUIMenuItem);
    }//GEN-LAST:event_lRegistrationCodeFailedUIMenuItemMouseReleased

    private void lRegistrationCodeSuccessUIMenuItemMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lRegistrationCodeSuccessUIMenuItemMouseReleased
	 setMouseReleasedMenuLabel(lRegistrationCodeSuccessUIMenuItem);
    }//GEN-LAST:event_lRegistrationCodeSuccessUIMenuItemMouseReleased

    private void lRegistrationCodeUIMenuItemMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lRegistrationCodeUIMenuItemMouseReleased
	 setMouseReleasedMenuLabel(lRegistrationCodeUIMenuItem);
    }//GEN-LAST:event_lRegistrationCodeUIMenuItemMouseReleased

    private void lConfigurationMenuItemMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lConfigurationMenuItemMousePressed
        setMousePressedMenuLabel(lConfigurationMenuItem);
    }//GEN-LAST:event_lConfigurationMenuItemMousePressed

    private void lRegistrationCodeFailedUIMenuItemMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lRegistrationCodeFailedUIMenuItemMousePressed
        setMousePressedMenuLabel(lRegistrationCodeFailedUIMenuItem);
    }//GEN-LAST:event_lRegistrationCodeFailedUIMenuItemMousePressed

    private void lRegistrationCodeSuccessUIMenuItemMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lRegistrationCodeSuccessUIMenuItemMousePressed
        setMousePressedMenuLabel(lRegistrationCodeSuccessUIMenuItem);
    }//GEN-LAST:event_lRegistrationCodeSuccessUIMenuItemMousePressed

    private void lRegistrationCodeUIMenuItemMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lRegistrationCodeUIMenuItemMousePressed
        setMousePressedMenuLabel(lRegistrationCodeUIMenuItem);
    }//GEN-LAST:event_lRegistrationCodeUIMenuItemMousePressed

    private void lConfigurationMenuItemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lConfigurationMenuItemMouseExited
        setMouseExitedMenuLabel(lConfigurationMenuItem);
    }//GEN-LAST:event_lConfigurationMenuItemMouseExited

    private void lRegistrationCodeFailedUIMenuItemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lRegistrationCodeFailedUIMenuItemMouseExited
        setMouseExitedMenuLabel(lRegistrationCodeFailedUIMenuItem);
    }//GEN-LAST:event_lRegistrationCodeFailedUIMenuItemMouseExited

    private void lRegistrationCodeSuccessUIMenuItemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lRegistrationCodeSuccessUIMenuItemMouseExited
        setMouseExitedMenuLabel(lRegistrationCodeSuccessUIMenuItem);
    }//GEN-LAST:event_lRegistrationCodeSuccessUIMenuItemMouseExited

    private void lRegistrationCodeUIMenuItemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lRegistrationCodeUIMenuItemMouseExited
        setMouseExitedMenuLabel(lRegistrationCodeUIMenuItem);
    }//GEN-LAST:event_lRegistrationCodeUIMenuItemMouseExited

    private void lConfigurationMenuItemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lConfigurationMenuItemMouseEntered
        setMouseEnteredMenuLabel(lConfigurationMenuItem);
    }//GEN-LAST:event_lConfigurationMenuItemMouseEntered

    private void lRegistrationCodeFailedUIMenuItemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lRegistrationCodeFailedUIMenuItemMouseEntered
        setMouseEnteredMenuLabel(lRegistrationCodeFailedUIMenuItem);
    }//GEN-LAST:event_lRegistrationCodeFailedUIMenuItemMouseEntered

    private void lRegistrationCodeSuccessUIMenuItemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lRegistrationCodeSuccessUIMenuItemMouseEntered
        setMouseEnteredMenuLabel(lRegistrationCodeSuccessUIMenuItem);
    }//GEN-LAST:event_lRegistrationCodeSuccessUIMenuItemMouseEntered

    private void lRegistrationCodeUIMenuItemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lRegistrationCodeUIMenuItemMouseEntered
        setMouseEnteredMenuLabel(lRegistrationCodeUIMenuItem);
    }//GEN-LAST:event_lRegistrationCodeUIMenuItemMouseEntered

    private void lConfigurationMenuItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lConfigurationMenuItemMouseClicked
 	setSelectedMenuItem(lConfigurationMenuItem);
    }//GEN-LAST:event_lConfigurationMenuItemMouseClicked

    private void lRegistrationCodeFailedUIMenuItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lRegistrationCodeFailedUIMenuItemMouseClicked
 	setSelectedMenuItem(lRegistrationCodeFailedUIMenuItem);
    }//GEN-LAST:event_lRegistrationCodeFailedUIMenuItemMouseClicked

    private void lRegistrationCodeSuccessUIMenuItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lRegistrationCodeSuccessUIMenuItemMouseClicked
 	setSelectedMenuItem(lRegistrationCodeSuccessUIMenuItem);
    }//GEN-LAST:event_lRegistrationCodeSuccessUIMenuItemMouseClicked

    private void lRegistrationCodeUIMenuItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lRegistrationCodeUIMenuItemMouseClicked
 	setSelectedMenuItem(lRegistrationCodeUIMenuItem);
    }//GEN-LAST:event_lRegistrationCodeUIMenuItemMouseClicked

 private Color theCurrentMenuColor = new Color(100, 120, 170);
 private Color theSelectedMenuColor = new Color(140,160,210);
 private Color theTextMenuColor = new Color(255, 255, 255);
 private boolean pressedSelected = false;
 private Icon arrowIcon = new javax.swing.ImageIcon(getClass().getResource("/images/arrow.gif"));
 private Icon arrowSelectedIcon = new javax.swing.ImageIcon(getClass().getResource("/images/arrow_selected.gif"));
 private Icon arrowMouseOverIcon = new javax.swing.ImageIcon(getClass().getResource("/images/arrow_mouseover.gif"));  
 private int iconTextGap = 5;
 private int sbTabMenuTopSpaceFiller = 15;
 private int sbTabLeftMargin = 5;
 private int sbTabWidth = 195;
 private int sbTabHeight = 25;
 private int sbTabGroupHeight = 75;
 private boolean sbTabIsOpaque=true;
 private Color sbTabTopBorderColor = new Color(140, 171, 240);
 private Color sbTabBottomBorderColor = new Color(70, 82, 116);
 private Color sbTabTopSelectedBorderColor = new Color(96, 110, 145);
 private Color sbTabBottomSelectedBorderColor = new Color(198, 226, 253);
 private Color sbTabRightInnerBorderColor = new java.awt.Color(68, 76, 100);
 private Color sbTabRightOuterBorderColor = new java.awt.Color(100, 114, 149);
 private Font sbTabFont = new java.awt.Font("Arial", 1, 12);
 private SBTab TheMenuLabelReference = new SBTab(null,sbTabWidth, sbTabHeight, sbTabLeftMargin, theCurrentMenuColor, theTextMenuColor, arrowIcon, iconTextGap, sbTabTopBorderColor, sbTabBottomBorderColor, sbTabRightInnerBorderColor, sbTabRightOuterBorderColor, sbTabIsOpaque);
 private SBTab thePressedLabelReference = null;
 private SBTab theEnteredLabelReference = null;

 private void setSelectedMenuItem(SBTab theMenuLabel)
  {
    try
    {
        TheMenuLabelReference.setBackgroundColor(theCurrentMenuColor);
	  TheMenuLabelReference.setTheTopBottomBorderColors(sbTabTopBorderColor, sbTabBottomBorderColor, sbTabRightInnerBorderColor, sbTabRightOuterBorderColor);
        TheMenuLabelReference.setTheIcon(arrowIcon);
        theMenuLabel.setBackgroundColor(theSelectedMenuColor);
        theMenuLabel.setTheIcon(arrowSelectedIcon);
	  theMenuLabel.setTheTopBottomBorderColors(sbTabTopSelectedBorderColor, sbTabBottomSelectedBorderColor, theSelectedMenuColor, theSelectedMenuColor);
        TheMenuLabelReference = theMenuLabel;

                        try
                        {
                            setContentPanel((EAPanel)Class.forName(getSidebarComponentID(theMenuLabel.getComponentLocalizationID())).newInstance());
                        }
                        catch(InstantiationException e)
                        {
                            e.printStackTrace();
                        }   
                        catch(IllegalAccessException e)
                        {
                            e.printStackTrace();
                        }                      
                        catch(ClassNotFoundException e)
                        {
                            e.printStackTrace();
                        }   
    }
    catch(Exception e)
    {
	e.printStackTrace();
    }
  }    
 
 boolean isEntered = false;
 private void setMouseEnteredMenuLabel(SBTab theEnteredLabel)
 {
    isEntered = true;
    try
    {
        theEnteredLabelReference = theEnteredLabel;
        if(theEnteredLabel.equals(TheMenuLabelReference)==false)
        {
            theEnteredLabel.setTheIcon(arrowMouseOverIcon);
            if(pressedSelected==true)
            {
                
                TheMenuLabelReference.setForegroundColor(theTextMenuColor);
            }
        }
        else
        {
            if(pressedSelected==true)
            {
                TheMenuLabelReference.setForegroundColor(theSelectedMenuColor);    
            }
        }
    }
    catch(Exception e)
    {
        System.out.println(e);
    }     
 }
 private void setMouseExitedMenuLabel(SBTab theExitedLabel)
 {
    isEntered = false;
    try
    {
        if(theExitedLabel.equals(TheMenuLabelReference)==false)
        {
            theExitedLabel.setTheIcon(arrowIcon);   
        }
        else
        {
            theEnteredLabelReference.setForegroundColor(theTextMenuColor);           
        }
    }
    catch(Exception e)
    {
        System.out.println(e);
    }  
 }

  private void setMousePressedMenuLabel(SBTab thePressedLabel)
 {
    try
    {
        thePressedLabelReference = thePressedLabel;
        if(thePressedLabel.equals(TheMenuLabelReference)==false)
        {
            thePressedLabel.setBackgroundColor(theSelectedMenuColor); 
	  	thePressedLabel.setTheTopBottomBorderColors(sbTabTopSelectedBorderColor, sbTabBottomSelectedBorderColor, theSelectedMenuColor, theSelectedMenuColor);
        }
        else
        {
            pressedSelected=true; 
            thePressedLabel.setForegroundColor(theSelectedMenuColor);
        }
    }
    catch(Exception e)
    {
        System.out.println(e);
    }  
 }
 
  private void setMouseReleasedMenuLabel(SBTab theReleasedLabel)
 {
    try
    {
        pressedSelected = false;
        if(theEnteredLabelReference.equals(thePressedLabelReference)==false || isEntered == false)
        {
            if(thePressedLabelReference.equals(TheMenuLabelReference)==false)
            {
                thePressedLabelReference.setBackgroundColor(theCurrentMenuColor);
		    thePressedLabelReference.setTheTopBottomBorderColors(sbTabTopBorderColor, sbTabBottomBorderColor, sbTabRightInnerBorderColor, sbTabRightOuterBorderColor);
            }
            if(thePressedLabelReference.equals(TheMenuLabelReference)==true)
            {           
                thePressedLabelReference.setForegroundColor(theTextMenuColor);
            }           
        }
        else
        {
            if(thePressedLabelReference.equals(TheMenuLabelReference)==true)
            {           
                thePressedLabelReference.setForegroundColor(theTextMenuColor);
            }
		else
		{
		    try
		    {
 		        TheMenuLabelReference.setBackgroundColor(theCurrentMenuColor);
			  TheMenuLabelReference.setTheTopBottomBorderColors(sbTabTopBorderColor, sbTabBottomBorderColor, sbTabRightInnerBorderColor, sbTabRightOuterBorderColor);
 		        TheMenuLabelReference.setTheIcon(arrowIcon);
 		        thePressedLabelReference.setTheIcon(arrowSelectedIcon);
 		        TheMenuLabelReference = thePressedLabelReference;
                        try
                        {
                            setContentPanel((EAPanel)Class.forName(getSidebarComponentID(theReleasedLabel.getComponentLocalizationID())).newInstance());
                        }
                        catch(InstantiationException e)
                        {
                            e.printStackTrace();
                        }   
                        catch(IllegalAccessException e)
                        {
                            e.printStackTrace();
                        }                      
                        catch(ClassNotFoundException e)
                        {
                            e.printStackTrace();
                        }   
 		    }
		    catch(Exception e)
		    {
		        System.out.println(e);
		    }
		}
        }
        
    }
    catch(Exception e)
    {
        System.out.println(e);
    }  
 } 
    private static synchronized Object[] getStringArraysFromString(String textArrayString)
    {
        ArrayList aryList = new ArrayList();
        String tempString = "";
        try
        {
            while(textArrayString.indexOf(",")!=-1)
            {
                tempString = textArrayString.substring(0,textArrayString.indexOf(","));
                textArrayString = textArrayString.substring(textArrayString.indexOf(",") + 1);
                aryList.add(tempString);
            }
            aryList.add(textArrayString);
            aryList.trimToSize();
        }
        catch(NullPointerException e)
        {
         
        }

        return aryList.toArray();
    }  

private synchronized String getSidebarComponentID(String compRefID)
{
	try
	{
		return (String)sbMap.get(compRefID);
	}
	catch(Exception e)
	{
	e.printStackTrace();
	}
	return "";
}

private synchronized void initSidebar()
{
try
{
	Object[] sbUIStrings = getStringArraysFromString(DesignerRuleBuilder.get("sbRegistrationStrings"));
	Object[] sbUIActions = getStringArraysFromString(DesignerRuleBuilder.get("sbRegistrationActionPanels"));
//sbMap

                    for(int i = 0;i<sbUIStrings.length;i++)
                    {
                        try
				{
					sbMap.put((String)sbUIStrings[i],(String)sbUIActions[i]);
					//LeftMenuButtonPanel.add(new SBTab((String)sbUIStrings[i],sbTabWidth, sbTabHeight, sbTabLeftMargin, theCurrentMenuColor, theTextMenuColor, arrowIcon, iconTextGap, sbTabTopBorderColor, sbTabBottomBorderColor, sbTabRightInnerBorderColor, sbTabRightOuterBorderColor, sbTabIsOpaque));
				}
				catch(Exception e)
				{
					sbMap.put((String)sbUIStrings[i],"");
				} 
                    }
}
catch(Exception e)
{
	e.printStackTrace();
}
}
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MaxRegistrationAttemptsLeftContentPanel;
    private javax.swing.JPanel MaxRegistrationAttemptsRightFillerPanel;
    private javax.swing.JPanel MaxRegistrationAttemptsSettingsPanel;
    private javax.swing.JPanel RegistrationCentralContentLeftMarginPanel;
    private javax.swing.JPanel RegistrationCentralContentPanel;
    private javax.swing.JPanel RegistrationCentralContentRightMarginPanel;
    private javax.swing.JPanel RegistrationContentBottomPanel;
    private javax.swing.JPanel RegistrationContentPanel;
    private javax.swing.JPanel RegistrationContentPanelItem3;
    private javax.swing.JPanel RegistrationContentPanelItem4;
    private javax.swing.JPanel RegistrationContentTopPanel;
    private javax.swing.JPanel RegistrationEnabledPanel1;
    private javax.swing.JPanel RegistrationMenuButtonPanel;
    private SBSpacer RegistrationMenuButtonPanelBottom;
    private SBTab RegistrationMenuButtonPanelTop;
    private javax.swing.JPanel RegistrationMenuContentPanel;
    private javax.swing.JPanel RegistrationMenuLeftSpaceFiller;
    private javax.swing.JPanel RegistrationMenuPanel;
    private javax.swing.JPanel RegistrationPanelMainContainer1;
    private javax.swing.JPanel RegistrationSelectionContentPanel;
    private javax.swing.JPanel RegistrationSettingsPanelItem1;
    private javax.swing.JPanel RegistrationSettingsPanelItem2;
    private javax.swing.JPanel RegistrationSettingsPanelItem8;
    private javax.swing.JPanel RegistrationTitlePanel;
    private javax.swing.JPanel RegistrationTitleRightPanel;
    private javax.swing.JButton btnGenerateEvaluationUnlockCode;
    private javax.swing.JButton btnRegistrationFormPreview;
    private javax.swing.JCheckBox cbRegistrationEnabled;
    private javax.swing.JLabel lEvaluationUnlockCode;
    private javax.swing.JLabel lMaxRegistrationAttempts;
    private SBTab lConfigurationMenuItem;
    private SBTab lRegistrationCodeFailedUIMenuItem;
    private SBTab lRegistrationCodeSuccessUIMenuItem;
    private SBTab lRegistrationCodeUIMenuItem;
    private javax.swing.JTextField tfEvaluationUnlockCode;
    private javax.swing.JTextField tfMaxRegistrationAttempts;
    private javax.swing.JPanel RegistrationMenuPanelBottomPanel;
    private ContentAreaHeaderPanel contentProjectPanel;
    private javax.swing.JPanel contentPanel;
    // End of variables declaration//GEN-END:variables
    
}
