/*
 * MainColorPanel.java
 *
 * Created on October 11, 2004, 3:25 PM
 */

package com.trinity.ea.design.project.lookandfeel.colors;
import com.trinity.ea.design.common.panel.EAPanel;
import com.trinity.ea.design.project.lookandfeel.colors.ColorsPanel;
import com.trinity.ea.design.project.lookandfeel.colors.RefundColorsPanel;
import com.trinity.ea.design.project.lookandfeel.colors.PaymentsColorsPanel;
import com.trinity.ea.design.project.lookandfeel.colors.RegistrationColorsPanel;
import com.trinity.ea.design.project.lookandfeel.colors.OptinColorsPanel;
import com.trinity.ea.design.project.lookandfeel.colors.ErrorColorsPanel;
import com.trinity.ea.design.project.lookandfeel.colors.InformationColorsPanel;
import com.trinity.ea.design.project.lookandfeel.colors.PrivacyColorsPanel;
import com.trinity.ea.design.project.lookandfeel.colors.MessagingAutoUpdateColorsPanel;
import javax.swing.*;
import com.trinity.ea.design.common.colorchooser.JLocalColorChooser;

/**
 *
 * @author  aaronsc Trinity Software
 * Copyright ©2003-2004 Trinity Software. All rights reserved.
 */
public class MainColorPanel extends EAPanel {
    
    /** Creates new form MainColorPanel */
    public MainColorPanel() {
        initComponents();
    }

    public synchronized void getDataUpdate()
    {
	  try
        {
            //ProjectManager.saveTempNow(); 
		startupWindowPanel.getDataUpdate();
		paymentsTab.getDataUpdate();
		//refundPolicyTab.getDataUpdate();
		//registrationPanel.getDataUpdate();
		//optinPanel.getDataUpdate();
		//privacyPolicyPanel.getDataUpdate();
		//messagingAutoUpdatesPanel.getDataUpdate();
		//informationPanel.getDataUpdate();
		//errorPanel.getDataUpdate();
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }

    public synchronized void setProjectData()
    {
        try
        {
		startupWindowPanel.setProjectData();
		startupWindowPanel.setParentComponent(this);
		paymentsTab.setProjectData();
		paymentsTab.setParentComponent(this);
		refundPolicyTab.setProjectData();
		refundPolicyTab.setParentComponent(this);
		registrationPanel.setProjectData();
		registrationPanel.setParentComponent(this);
		optinPanel.setProjectData();
		optinPanel.setParentComponent(this);
		privacyPolicyPanel.setProjectData();
		privacyPolicyPanel.setParentComponent(this);
		messagingAutoUpdatesPanel.setProjectData();
		messagingAutoUpdatesPanel.setParentComponent(this);
		informationPanel.setProjectData();
		informationPanel.setParentComponent(this);
		errorPanel.setProjectData();
		errorPanel.setParentComponent(this);
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }   
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        ColorsTabbedPane = new javax.swing.JTabbedPane();
        startupWindowPanel = new ColorsPanel();
        paymentsTab = new PaymentsColorsPanel();
        refundPolicyTab = new RefundColorsPanel();
        registrationPanel = new RegistrationColorsPanel();
        optinPanel = new OptinColorsPanel();
        privacyPolicyPanel = new PrivacyColorsPanel();
        messagingAutoUpdatesPanel = new MessagingAutoUpdateColorsPanel();
        informationPanel = new InformationColorsPanel();
        errorPanel = new ErrorColorsPanel();

        setLayout(new java.awt.BorderLayout());

        setBackground(new java.awt.Color(140, 160, 210));
        ColorsTabbedPane.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        ColorsTabbedPane.setBackground(new java.awt.Color(140, 160, 210));
        //ColorsTabbedPane.setForeground(new java.awt.Color(255, 255, 255));
try
{
	  ((javax.swing.JViewport)ColorsTabbedPane.getComponents()[0]).getView().setBackground(new java.awt.Color(140, 160, 210));
}
catch(Exception e){}         ColorsTabbedPane.setFont(new java.awt.Font("Arial", 0, 12));
        ColorsTabbedPane.addTab("Startup", startupWindowPanel);

        ColorsTabbedPane.addTab("Payment", paymentsTab);

        ColorsTabbedPane.addTab("Refund Policy", refundPolicyTab);

        ColorsTabbedPane.addTab("Registration", registrationPanel);

        ColorsTabbedPane.addTab("Opt-In", optinPanel);

        ColorsTabbedPane.addTab("Privacy Policy", privacyPolicyPanel);

        ColorsTabbedPane.addTab("Messaging/Auto Update", messagingAutoUpdatesPanel);

        ColorsTabbedPane.addTab("Information Dialog", informationPanel);

        ColorsTabbedPane.addTab("Error Dialog", errorPanel);

        ColorsTabbedPane.setTabPlacement(javax.swing.JTabbedPane.TOP);
        add(ColorsTabbedPane, java.awt.BorderLayout.CENTER);

    }//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane ColorsTabbedPane;
    private MessagingAutoUpdateColorsPanel messagingAutoUpdatesPanel;
    private OptinColorsPanel optinPanel;
    private PaymentsColorsPanel paymentsTab;
    private PrivacyColorsPanel privacyPolicyPanel;
    private RefundColorsPanel refundPolicyTab;
    private RegistrationColorsPanel registrationPanel;
    private InformationColorsPanel informationPanel;
    private ErrorColorsPanel errorPanel;
    private ColorsPanel startupWindowPanel;
    // End of variables declaration//GEN-END:variables
    
}
